### ISSUE TITLE
RailsGirls Tokyo 2nd roundの会計を〆る

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#101]
- [x] 会計Excelを作成 (@kakutani)
- [x] kakutaniの立替ぶんを精算する (@takahashim)
- [x] kuko への立替精算をおわらせる (@kakutani)
- [x] スポンサー企業への請求 #92 (@kakutani)
- [x] レシートを @takahashim に渡す(@kakutani)

**Comment by kakutani** [comment]
〆めました!! railsgir-jp/tokyo-team#61 

@kakutani の精算してほしい額は、190,365 JPYです(振り込めシートに書いときます)

**Comment by kakutani** [comment]
@takahashim まとまったお金が必要になるので、溜まってるやつ精算してもらえると嬉しいです〜。ruby-no-kai.org のgoogle docsにある振り込めシートのやつもまとめてやってもらえるとちょう助かります……。

**Comment by takahashim** [comment]
（振り込めシートはマイドライブからも共有アイテムからも見えないのでした…）
こちら本日振り込んでおきます！

**Comment by kakutani** [comment]
むむむ……設定をミスっているのか……

**Comment by kakutani** [comment]
@takahashim 振り込めシートの共有設定を変えてみました!! (URLはメールしてみました)

**Comment by takahashim** [comment]
振り込みました！
と思ったら２月のmisoca分が入ってなかった…orz

**Comment by kakutani** [comment]
すばやい!! ありがとうございます。確認して @kuko に払ったら完了……!

**Comment by kakutani** [comment]
振込をかくにんしました :heart_decoration:

**Comment by kakutani** [comment]
@kuko に渡ったっぽい!!1

**Comment by kakutani** [comment]
おっと。こちらでは高橋さんにレシートを渡すまでopenだった……。

**Comment by kakutani** [comment]
RubyKaigi 2013のふりかえりのときに、高橋さんにレシートをわたした!!!
