### ISSUE TITLE
るびま編集部向けにサーバを提供する件

### ISSUE THREAD

**Issue by snoozer05** [ruby-no-kai/official#102]
see https://github.com/rubima/rubima/issues/58

**Comment by takahashim** [comment]
こういうのってカードで継続課金だと精算がめんどい＆分かりにくいので、まとめて振り込みできるといいなあと思っております…

**Comment by snoozer05** [comment]
@kakutani #104 でやってるのと同件だと思うので、こっちは閉じておきます。
