### ISSUE TITLE
るびま用の新サーバでsqaleを借りる

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#104]
1年ぶんなら銀行振込に対応してくれるそうなので、それでお願いする。 /cc @hsbt @takkanm

**Comment by takahashim** [comment]
請求書をいただくか、振込先口座＋金額情報をいただくか（←実質請求書と同様の情報）、というところでしょうか

**Comment by hsbt** [comment]
請求書をPDFで送ります! 請求書に記載する情報（担当者、住所、電話番号）を教えてください。

**Comment by takahashim** [comment]
〒151-0066 東京都渋谷区西原2-33-6-104 一般社団法人日本Rubyの会 tel.03-6407-9151 担当高橋です！

**Comment by hsbt** [comment]
ありがとうございます。担当の @pplog から送付させて頂きます。

**Comment by pplog** [comment]
はじめまして、担当の 山本 @pplog です。

請求書PDFをお送りする先のメールアドレスをお教えいただけますでしょうか？

どうぞよろしくお願いいたします！

**Comment by kakutani** [comment]
info at ruby-no-kai dot org 宛でお願いします！

**Comment by pplog** [comment]
@kakutani 承知しました！

**Comment by snoozer05** [comment]
これは done なのかしら??

**Comment by hsbt** [comment]
支払い完了してお試し期間が消えてました!
