### ISSUE TITLE
rubyhiroba.org を日本Rubyの会へ移す

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#106]
まあ、そのうち。

**Comment by snoozer05** [comment]
DNSの設定変更の件の対応が遅れてずいぶん長い間 rubyhiroba.org にアクセス出来ない状況になっていたりした（気がつけたので設定の変更は行い、現状は回復しています）ので、対処したいです...

**Comment by shyouhei** [comment]
これはまだ移せてない。

**Comment by kakutani** [comment]
遅ればせながらRubyの会のアカウントにうつしました！

**Comment by kakutani** [comment]
移動されていることを確認しましたっ。

**Comment by hsbt** [comment]
(@kakutani さんの生存確認だ...!)
