### ISSUE TITLE
RubyKaigi2009 のときに _why を呼ぼうキャンペーンで集めたお金(現金) を高橋さんに渡す or 口座に入れる

### ISSUE THREAD

**Issue by snoozer05** [ruby-no-kai/official#107]
_why 関連のことをするために使いたい。今は島田の手元にあります。

**Comment by takahashim** [comment]
:+1: 
口座に振り込んでもらうのでどうでしょう？

**Comment by snoozer05** [comment]
振り込みました！手数料分差し引いて20,000円振り込んでおりますので、ご確認をお願いします！

**Comment by takahashim** [comment]
こちら振込人が「サッポロルビーカイギシ」になってましたが、これであってます？

**Comment by snoozer05** [comment]
はい！ちょっと振込を簡単にしたくて、いったん札幌Ruby会議実行委員会の口座に入れて、そこ経由で振り込ませていただいたのでした ><

**Comment by takahashim** [comment]
了解です！
