### ISSUE TITLE
おや……PayPalの様子が……

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#109]
> 最近お客さまのアカウントを確認したところ、サービスを引き続きお使いいただくために、お客さまの事業についてさらに詳しい情報が必要となりました。お客さまのアカウントを一刻も早く通常の状態に戻せるよう、ご協力のほどよろしくお願いいたします｡ご不便をおかけしておりますことをお詫びいたします。
> 
> 2013年3月29日: お客さまの事業内容に変更があることが判明いたしました。詳しい情報をご提供ください。
> 
> PayPalにご連絡いただいた際にケースIDをお伝えいただく必要があります: PP-002-272-338-718

![ruby-no-kai-paypal](https://f.cloud.github.com/assets/2160/326993/b8775e0e-9b5c-11e2-9348-8a3f6e780bb4.png)

登記住所変更の影響ですかね? > @takahashim

**Comment by takahashim** [comment]
あー。なんかRubyKaigiで入金が増えたためっぽいです。
RubyKaigi側にも送っておきます。

**Comment by takahashim** [comment]
というわけで、制限は解除されましたが、「定期保留金: アカウントの 10%が 65日間保留されます。」とのことです。要はなんかあった時に入金キャンセルとかチャージバック用にPayPalに金を積んでおけ、とのことぽいです。むむむ。まあ仕方ないか。

というわけで、こちらはいったん閉じておきます！
