### ISSUE TITLE
"[情弱] ruby 会議やるとかやらないとかみんなどこで情報得てるんだろう? http://www.ruby-lang.org/ja/news/ には載らないし... [プログラマ]"

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#111]
前々から知ってた話ではあるのだけれど…… w.r.o の"リニューアル"あたりを契機になんとかしていけるといいな、と思ったことをここに記します。@hsbt にどっかでいろいろ教えてもらおう……。

https://twitter.com/hiroshi3110/status/324405605781626880

**Comment by hsbt** [comment]
events に限らず、日本語の ruby-lang.org のリソースがもの凄く残念なんでどうにかしたいのですが、何処にリソースを求めに行けばいいのやら... という

**Comment by kakutani** [comment]
新生 w.r.o にPRして頑張る流れ……なのかな……。

**Comment by hsbt** [comment]
upcoming events みたいなコンテンツですかね...

**Comment by hsbt** [comment]
pragprog magazine にあるようなのを常設したいのだわ～

**Comment by shyouhei** [comment]
これどうするのー

**Comment by shyouhei** [comment]
このチケットの終了条件は？

**Comment by snoozer05** [comment]
rk14に関してはあとで rko に ja の記事もPRするようにします

**Comment by snoozer05** [comment]
ちゃんとアクションを整理していかないといけなそう

**Comment by shyouhei** [comment]
現状だと、いちおう、https://github.com/ruby/www.ruby-lang.org にPRすればいいところまでは来てはいる。でもそれでOKかというのは悩ましい。

地域Ruby会議とかだったら↑に掲載してもいいのでは

**Comment by shyouhei** [comment]
- regional.rubykaigi.orgの「これから開催される地域Ruby会議」をもう少ししくみ化する?
  - もう確定情報はきちんと掲載されるようになっているので問題ないのでは?

**Comment by kakutani** [comment]
twitterに @rubynokai というのがいるんだけど全然活用できてない。これをもうちょっと意識的に活用するのはどうかなあ #asakusarb

**Comment by snoozer05** [comment]
- どういう情報をだすのか
- 誰がどういうフローで更新する？

**Comment by shyouhei** [comment]
- twitter accountに関してはしまださんとかくたにさんあたりで運用してみて学習する
- 地域Ruby会議とかはruby-listもっと使えばいいんじゃない(うながす)

**Comment by snoozer05** [comment]
- twitter アカウントに関しては、 @snoozer05 @kakutani あたりで運用してみて学習する
- 地域Ruby会議とかは ruby-list 使うように促す

**Comment by kakutani** [comment]
twitterの@rubynokai アカウントは緩く再運用を開始しました

**Comment by shyouhei** [comment]
まずはこれで運用してみる。いったんおわり
