### ISSUE TITLE
RubyHirobaで使うお金の支援

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#113]
- [x] ステッカー (1.34K)
- [x] Tシャツ (56.262K)

**Comment by kakutani** [comment]
@yandod にハンドルしてもらうのがよさそう……。

**Comment by yandod** [comment]
領収書の宛名をどうするかを教えて下さい。

**Comment by kakutani** [comment]
"日本Rubyの会"でお願いします！

**Comment by yandod** [comment]
発送前に振込み情報が来ますが、それは振込をお願いできるということでいいですよね。

**Comment by kakutani** [comment]
いいっすよ info at ruby-no-kai dot org に送ってください

**Comment by kakutani** [comment]
@yandod いただいた振込情報を高橋さんには伝えるのですが、見積書とか請求書みたいなもののファイルを上記のアドレスに送っといてください〜。

**Comment by kakutani** [comment]
「RubyHiroba 2013のステッカー代振込のお願い」というメールをinfoに送りましたので振込おねがいします!! > @takahashim

**Comment by yandod** [comment]
ステッカーのやつを転送しました。Tシャツの方も請求情報がきたら送ります。

**Comment by kakutani** [comment]
Tシャツも来た。「Fwd: 株式会社 Engine Yard 安藤祐介 様■受注明細になります。■」っていうメール。こちらも振込おねがいします > @takahashim

**Comment by takahashim** [comment]
ステッカーの方は振込みました！

**Comment by takahashim** [comment]
Tシャツの方は月曜日に日本Rubyの会名義で振り込みますね

**Comment by takahashim** [comment]
Tシャツの方も振り込みました！（が別の送金業務が長引いて明日の日付で振り込まれる予定です…）
