### ISSUE TITLE
Travis CI GmbHに振り込む

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#114]
海外送金業…

**Comment by kakutani** [comment]
準国際会議、経験業務の幅が広がる…

**Comment by takahashim** [comment]
ゆうちょ銀行の口座を作っておくべきだったか…（2,500円でいけるらしい。三井住友銀行だと6,500円＋α）

**Comment by kakutani** [comment]
こんかいは三井住友でやってしまって、来年に向けてゆうちょ銀行の口座を開設しましょう!!1

**Comment by takahashim** [comment]
こちら振り込みました！（明日の日付で）

**Comment by takahashim** [comment]
ちょっと安心できない感じなのですが、いったん閉じておきますね

**Comment by kakutani** [comment]
> I just want to inform you about the arrival of your remittance.

いつ入金されるの? と来ましたが数日はかかる感じなんですかね??
Fritzにお返事していただけるとよいのかしら(reopenしてみます)

**Comment by takahashim** [comment]
あれ、これって届いた（ことをお知らせしたい）ってことかと思ったんですが、違う？？

**Comment by takahashim** [comment]
（えーごむずかしい…）

**Comment by shyouhei** [comment]
the arrivalであれば「来た」だと思います

**Comment by kakutani** [comment]
うう……ありがとうございます。じゃあdoneだってことですね。とほほ。
