### ISSUE TITLE
railsgirls.jp のドメイン費用を Ruby の会で払って欲しい

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#115]
railsgirls.jp の方から来ました。

http://railsgirls.jp/ というドメインを先日私が個人的に準備したのですが、このドメインの費用を Ruby の会で計上するということは可能でしょうか?

rubykaigi.org とかはどういう管理になっているのでしょうか...

**Comment by kakutani** [comment]
可能です。

rubykaigi.orgのときは、ドメインのownerやらbillingなどを日本Rubyの会の理事に移しました。
すでに @hsbt が払ってしまったぶんについては立替精算とさせてください。
(何らかの支払についての証憑をいただけるとありがたいです)

以上で回答になっていますでしょうか?
具体的な引き継ぎに必要な情報などは、info at rubykaigi dot org 宛にいただけるとありがたいです!
(このissueは、やり忘れがないように状態を管理するためのものという位置づけにしたいです)

RubyKaigi前でバタバタしてて、諸々遅れがちになることもあるとは思いますが
よろしくお願いします!

**Comment by hsbt** [comment]
了解です!!1 お互いにバタバタし終わった後に、こちらの issue はまた再開します。

**Comment by hsbt** [comment]
【再開のお知らせ】

**Comment by kakutani** [comment]
ドメインを日本Rubyの会に移管しましょう!

**Comment by kakutani** [comment]
移管はどうすすめていけば良いんでしたっけ……。

**Comment by hsbt** [comment]
移管先は何処になりますか?

**Comment by kakutani** [comment]
うおお。返信を忘れてました。歴史的な経緯でRubyの会のドメインはvalue-domainで管理しております〜(というので回答になってますか??)

**Comment by hsbt** [comment]
ムームードメイン(自動継続払いがあるので便利!)を使っているので、value-domain に持って行くにはどうすれば〜というところをちょっと調べます。

**Comment by hsbt** [comment]
ほぼ1年経ってしまった...

これ、ドメインの移管はアレなので請求書を発行して費用をいただくという形式は可能でしょうか?

**Comment by takahashim** [comment]
はい、それでも大丈夫です！

**Comment by hsbt** [comment]
色々ありましたが、RailsGirls Japan 口座で何とかすることにします!
