### ISSUE TITLE
監事の名刺がほしい

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#117]
RubyKaigi絡みで卜部さんにも動いてもらうことが増えてきたので、名刺あるとよさそう。
メールアドレスも?

ついでに、
代表理事や理事の皆さんは名刺足りてますか……?
kakutaniのはボチボチ無くなりそうです……。

**Comment by snoozer05** [comment]
しまだ、実はすでに無くなっておりました...

**Comment by takahashim** [comment]
私の名刺はいっぱいあります！

**Comment by kakutani** [comment]
shyouhei@ruby-no-kai.org を?

**Comment by mayuco** [comment]
(いつでも名刺をおつくりできます！)

**Comment by snoozer05** [comment]
えっと、島田、角谷の分の名刺を増やすのと、
卜部さんの名刺を作るというので良いですかね。

@kakutani メールアドレスはもう準備できてるんでしたっけ？

**Comment by kakutani** [comment]
メールアドレスを作るだけ作ってみたつもり( @shyouhei にメールした)

**Comment by snoozer05** [comment]
おお、では仕掛かれるわけですね。
英語表記は
`auditor Shyouhei Urabe`
で大丈夫でしょうか。

**Comment by mayuco** [comment]
卜部さんの名刺データを作成してみました。
いかがでしょうか？

![urabe](https://f.cloud.github.com/assets/52765/846328/c1e3c3ee-f40b-11e2-937a-593e9457d9ab.jpg)

**Comment by snoozer05** [comment]
角谷さんからOKもらったので発注します！

**Comment by snoozer05** [comment]
@takahashim 請求書をつけて名刺をお送りしましたが、届いておりますでしょうか...!! 今月中にお振り込みをいただけると助かります！

**Comment by takahashim** [comment]
すみません、こちら届いてました！
振り込みの方は今週中に何とかします…

**Comment by takahashim** [comment]
こちら振り込みました！
ところで @shyouhei さんにはいつ頃渡せそうですかね…

**Comment by kakutani** [comment]
卜部さんに渡せれば done...

**Comment by snoozer05** [comment]
入金確認しましたー :moneybag:

**Comment by shyouhei** [comment]
受けとりました :+1:
