### ISSUE TITLE
Rubyist MagazineのHotlinks用のICレコーダーについて

### ISSUE THREAD

**Issue by gunjisatoshi** [ruby-no-kai/official#118]
https://github.com/rubima/rubima/issues/174 の件です。

日本Rubyの会の活動のひとつであるRubyist Magazineでは、連載インタビュー記事(Hotlinks)のインタビュー時の録音を、今まで個人持ちのICレコーダーを使用しておりました。

次回よりインタビュアーが変わることもあり、日本Rubyの会様にて公式の備品としてご用意いただけると大変助かります。

お忙しいところ恐縮ですが、ご検討いただきたく、よろしくお願いいたします。

**Comment by kakutani** [comment]
機種を選定してください!!  集音マイクとレコーダー、って感じでしょうか?

**Comment by kakutani** [comment]
(ちなみに「次回より」ってことはもう @ko1 はインタビュワーをやんないってことなんでしょうか? 次回だけじゃなく??)

**Comment by ko1** [comment]
はい、卜部君にバトンタッチ。
ちなみに、私が使っていたのは
 OLYMPUS Voice-Trek DS-50
 http://www.amazon.co.jp/dp/B000KJTP52 
でした。

**Comment by kakutani** [comment]
(ささださんがささださんにインタビューするという最終回の構想が……)

**Comment by gunjisatoshi** [comment]
DS-50の後継だとDS-850とかになるんですかねえ。まあ、オリンパスじゃなくてもいいんですけど。
実際に使う方 ( @shyouhei さん) の意見も聞いてみたいところです。

**Comment by shyouhei** [comment]
む、適当に買っちゃったけど。

**Comment by gunjisatoshi** [comment]
すでに購入されているなら了解です！
(クローズして良いでしょうか)

**Comment by shyouhei** [comment]
次の理事会でcloseしたいです!

(っていつになるのか)

**Comment by kakutani** [comment]
済んでるはず!

**Comment by gunjisatoshi** [comment]
ありがとうございました！
（さて、テープ起こさないと‥‥）
