### ISSUE TITLE
ruby-no-kai.orgのドメイン更新

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#120]
> 　有効期限：2013-08-25(予約：2013-08-25)

急ぎじゃないけど忘れないようにしないと。
毎年の更新は面倒なので、n年でやれるといいなあ。3年とか5年とか。

**Comment by takahashim** [comment]
では5年くらいにしてみましょうか。

**Comment by kakutani** [comment]
3年ぶんで高橋さんが払ってくれた
