### ISSUE TITLE
RailsGirls Sapporo 1stで必要な立替の精算

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#129]
- [x] kuppiが諸々立て替えてくれたぶん
- [x] 粋ラボに発注したお弁当の請求
- [x] kakutaniが現地で精算した、@equal_001 の旅費交通費
- [x] kakutaniの交通宿泊費

振込先は、ruby-no-kai のgoogle appのspreadsheet、振り込めシートに書きました。

振り込めシートの状況が最新の状況を反映していない気がするので、あとでチェックしないといけない……。

**Comment by snoozer05** [comment]
@takahashim えにしテックからのスポンサー料⾦を振り込みましたので、ご確認ください :moneybag:

**Comment by kakutani** [comment]
あとは母のぶんだけ!

**Comment by shyouhei** [comment]
おわったとのこと！
