### ISSUE TITLE
RubyKaigi 2013のissueを0にする

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#134]
"10 open" (8-27-2013)

**Comment by kakutani** [comment]
"8 open" (2013-08-28)

**Comment by kakutani** [comment]
"7 open" (2013-09-11)

**Comment by snoozer05** [comment]
"2 open" (2014-05-08)

**Comment by shyouhei** [comment]
https://github.com/ruby-no-kai/rubykaigi-orgz/issues?q=is%3Aopen+is%3Aissue+milestone%3A2013 0件では?

**Comment by shyouhei** [comment]
おわり。
