### ISSUE TITLE
RubyKaja2013 ノベルティ代金

### ISSUE THREAD

**Issue by hayabusa333** [ruby-no-kai/official#135]
お疲れ様です。RubyKaja2013にてノベルティに使用した金額を共有させていただきます。

RubyKaja2013にて作成したノベルティの代金

ノベルティステッカー：200枚 6,934円
Kaja用ステッカー：20枚 2,418円
Kaja用扇子：20本 54,600円

合計金額：63,952円

扇子は現在、注文中にて領収書がまだ届いておりませんので、届きましたら再び連絡いたします。

**Comment by snoozer05** [comment]
@hayabusa333 これってその後どうなっておりますでしょうか......!!

**Comment by hayabusa333** [comment]
日本Rubyの会様
お疲れ様です。橘田です。

RubyKajaノベルティの代金をお伝えするのが遅くなり申し訳ありません。

一般用ステッカーノベルティ
200枚 = 6,934円
Kaja用ステッカー
20枚 = 2,418円
Kaja用扇子
20本 = 55,650円

合計 65,002円

以上となります。

振込み先と証明書に関しましては本日の夜までに  info@ruby-no-kai.org にお送りいたします。
振込み先をお伝えする場所が別の場所が良いようでしたらお伝えいただければ、そちらに連絡いたします。

以上です、宜しくお願いいたします。

**Comment by kakutani** [comment]
メールがきました!

**Comment by kakutani** [comment]
振り込めシートをupdateして、振り込んでもらう!

**Comment by snoozer05** [comment]
@kakutani ping。これってどんな状況でしょうか

**Comment by snoozer05** [comment]
@takahashim これってもう振込済みですか？

**Comment by takahashim** [comment]
これは振り込んでないですね…。振り込めシートを更新して今週中には振り込んでおきます

**Comment by snoozer05** [comment]
お手数をおかけします ><

**Comment by takahashim** [comment]
さきほど65,002円振り込みました！

**Comment by snoozer05** [comment]
ありがとうございます！
@hayabusa333 お手数をおかけしますが、入金のご確認をお願いできますでしょうか。確認いただけたらこのissueは閉じようと思います。

**Comment by hayabusa333** [comment]
ありがとうございます。
入金の確認ができるのが今週末になるかと思いますので、確認後再びコメントを記載しますので宜しくお願いいたします。

**Comment by snoozer05** [comment]
はい！よろしくおねがいいたします！

**Comment by hayabusa333** [comment]
記載が遅くなりましたが、入金の確認を行いました。
ご対応いただきありがとうございました！

**Comment by snoozer05** [comment]
よかったです！こちらこそ、対応が遅くなってしまい申し訳ありませんでした :bow:
確認ありがとうございました！
