### ISSUE TITLE
RailsGirls Tokyo 3rd の支払・請求・立替

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#137]
請求書が届いたりするので、起票しておきます。
- [x] 惣助弁当の請求書に対する支払 ( @takahashim )
- [x] パーティの代金の請求書が副島シェフから届くので支払ってもらう ( @takahashim)
- [x] @yakitorii のTシャツ立替ぶんを精算 (@kakutani, 振込先を確認する)
- [x] @publichtml のカクヤス代の立替精算
- [x] ステッカーの領収書を @takahashim にわたす → hsbtとやる
- [x] 他、@kakutani が立替たぶんの領収書を @takahashim にわたす → hsbtとやる
- [x] スポンサー向け請求書の発行( @kakutani )
- [x] スポンサーの入金確認( @takahashim )
- [x] hsbtと精算する( @kakutani)

**Comment by kakutani** [comment]
- 惣助の弁当代の振込は、支払期限が10/26(土)なのでメールで @takahashim に振込依頼した。
- 鳥井ちゃんは振込先口座の返信まち。

**Comment by kakutani** [comment]
railsgirls-jp/tokyo-team#77 を済ませました。

**Comment by snoozer05** [comment]
まだっぽい

**Comment by kakutani** [comment]
(まだです…)

**Comment by snoozer05** [comment]
@kakutani @takahashim ping。それぞれの状況いかがでしょうか

**Comment by takahashim** [comment]
misocaで請求しているものについては全て入金確認いたしました！

**Comment by shyouhei** [comment]
@kakutani さんへの清算が終われば終わりぽい

**Comment by shyouhei** [comment]
@kakutani 入金確認したら閉じといてください

**Comment by snoozer05** [comment]
@takahashim これ、角谷さんへの精算は済んでいるということでよいでしょうか...?? であれば閉じてしまいたいです

**Comment by kakutani** [comment]
私の精算が終わっていないかもしれないので、もういっかい確認します。

**Comment by shyouhei** [comment]
6/24 やれるところまでやる。

**Comment by hsbt** [comment]
こちらですが、RailsGirls で集金した分、立替で支払った分を @takahashim さんから RailsGirls の代表口座へ振り込み済みとなっています。ですので、もし @kakutani さんへ立替精算を行う必要があるのであれば、RailsGirls JP から支払う必要がありそうです。

立替が必要かどうかの確認をお願いします。

**Comment by kakutani** [comment]
@hsbt なるほど。一旦全部RG JPに移ってるから、そのほうが良いかもしれないのですね。
えっと、今日はちょっともう脳味噌が電池切れなのですが、

今日までの進捗としては:
- kakutaniが立て替えた(だいぶ前の開催)の振込記録をサルベージした
- 領収書原本一式を発掘した

という状況です。

振込記録の明細と対応するかたちで領収書を整理しようとしたのですが、
集中力が売り切れました。

どっかの Asakusa.rb あたりで同期でいるといいのかなー。
(ただ、7/7はサッポロクラシックの買い出しでした……)

また相談させてくださいませ。

**Comment by hsbt** [comment]
お疲れ様です! もろもろ了解したので、RailsGirls JP の方でも 3rd の振込どうなってるんだっけ、というのを @takahashim さんから頂いたお金の移動にかんする明細記録からサルベージしてみます。

**Comment by kakutani** [comment]
はい!

**Comment by kakutani** [comment]
@hsbt と @kakutani で精算すればよさそう、というところまで辿りついた。どっかの Asakusa.rb で精算しておきます。

**Comment by shyouhei** [comment]
@kakutani これの現状ってどうなってますでしょうか

**Comment by kakutani** [comment]
しばたさんとやりとりする段取りをやらねば……という気持ちになっているところです(進んでない)。

**Comment by shyouhei** [comment]
年内に精算する

**Comment by hsbt** [comment]
RailsGirls 口座の残高が際どくなってきたので、イベントの請求と RailsGirls 口座への移動を頑張ってから...という話を @kakutani としました

**Comment by hsbt** [comment]
@kakutani 会計の残高が回復してきたので立替の精算をそろそろやりたいなあと思っております。金額の詳細をここか何かしらの手段でご連絡ください～。

**Comment by kakutani** [comment]
詳細をつくって連絡します…(向き合うきもちはできつつあります)

**Comment by shyouhei** [comment]
角谷さんが領収書をまとめつつある。進行中。

**Comment by shyouhei** [comment]
現状: 進行中。
next action: 固まったら連絡する

**Comment by shyouhei** [comment]
現状: 領収書はまとまった。
next action: @hsbt とおちあう

**Comment by hsbt** [comment]
金額合計と振込先などを教えていただけると対応できます!

**Comment by shyouhei** [comment]
まだです
next action: 柴田さんに情報を渡す

**Comment by hsbt** [comment]
引き続き待っております

**Comment by shyouhei** [comment]
まだです

現状: じわじわ進んでいる
next action: 柴田さんに情報を渡す

**Comment by hsbt** [comment]
これどうでしょうか...?

そろそろ RG のイベントの開催が本格化しつつあり、収支を計画していく上で払わなければならないけど、いくら払えばいいかわからない=いくら残るのかわからない、という状態になっていて困っています。

期限を決めて、そこまでに判明しない場合は清算不可能として閉じる(いいのだろうか)など、進めたいです。

**Comment by shyouhei** [comment]
@kakutani どうでしょうか。

**Comment by shyouhei** [comment]
現状: @kakutani さんが領収書を発掘した
next action: 来週がんばる

**Comment by takahashim** [comment]
がんばるという話をしばたさんとした。
next action: 領収書をしばたさんに渡す

**Comment by hsbt** [comment]
発掘した領収書を全部もらえれば @hsbt があとはやっておくんで、という話をしました。

**Comment by shyouhei** [comment]
現状: しばたさんがバタバタしている
next action: 近々やる

**Comment by hsbt** [comment]
11/29 の Asakusa.rb でやるぞ、と固い決意を @kakutani としました

**Comment by kakutani** [comment]
@hsbt に領収書と振込先口座を渡しました！

**Comment by hsbt** [comment]
issue 誕生から 3 年を経て振り込みました!!1

**Comment by kakutani** [comment]
ありがとうございます! 入金確認したらclose 🎏 (明日振り込まれてるんじゃないかなー)

**Comment by kakutani** [comment]
> 振込　レイルズ　ガ－ルズ

verified 💰
