### ISSUE TITLE
12/5(木) Ruby開発者会議の軽食の精算

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#138]
> @kakutani @takahashim 5140円でした、美味しく頂きました
> https://twitter.com/_ko1/status/408575370745507841

/cc @ko1 
- [ ] 領収書をもらう
- [ ] ko1さんの口座に振り込む || 現金を渡す?

**Comment by snoozer05** [comment]
領収証は貰いましたか？

**Comment by shyouhei** [comment]
領収書まち

**Comment by snoozer05** [comment]
@shyouhei  領収証の件ってどんな感じなのでしょう...

**Comment by shyouhei** [comment]
@ko1 こちらも領収書お待ちしております。

**Comment by shyouhei** [comment]
続きは #147 で！
