### ISSUE TITLE
るびま用のSqaleの支払い

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#140]
3月中に払わないと、るびまが止まる!!1

**Comment by hsbt** [comment]
ふわっ

**Comment by gunjisatoshi** [comment]
https://github.com/rubima/rubima/issues/263 の件ですね。

すみませんがよろしくお願いします！！１

**Comment by takahashim** [comment]
振り込みました！

**Comment by snoozer05** [comment]
振り込んだとのことなので、閉じちゃいますね...!!
