### ISSUE TITLE
RailsGirls Nagoyaのスポンサー請求業務

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#141]
- [x] @kakutani が請求書を送る
  (つづく)

**Comment by snoozer05** [comment]
@kakutani ping

**Comment by takahashim** [comment]
misocaで請求済みのものに関しては入金確認できました！（全部かどうかは不明ですが）

**Comment by springaki** [comment]
名古屋での請求先としては
- エイチーム様
- heroku様
- スタンドファーム様
- オージス総研様
- IIJ様

で全てのようです。名古屋のオーガナイザーに確認しました。
ご参考まで。

**Comment by snoozer05** [comment]
ありがとうございます！なら全部入金されてそう！
なので、このissueは閉じます :-)
