### ISSUE TITLE
RailsGirls Osaka の会計処理

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#144]
@kakutani hi

https://github.com/railsgirls-jp/osaka-team/issues にある issue の中で Ruby の会が窓口となって請求書や見積書を発行して欲しいというオーダーを頂戴していますが対応可能でしょうか?(実は既に依頼が行っている?)

/cc @snoozer05 @springaki

**Comment by snoozer05** [comment]
@hsbt しまだが代わりに対応しますね。
@springaki https://github.com/railsgirls-jp/osaka-team/issues/15 のことですよね。対応します。お手数をおかけして恐縮ですが、角谷さんに送ったのと同じメールを info@ruby-no-kai.org 宛にも送っていただけますでしょうか？

**Comment by springaki** [comment]
@hsbt @snoozer05 ありがとうございます !!
了解です。メール転送させていただきました。よろしくお願いします。

**Comment by snoozer05** [comment]
@springaki ありがとうございます！
返信しましたので、ご確認下さい！

**Comment by springaki** [comment]
確認しました。 対応ありがとうございます!

**Comment by takkanm** [comment]
@hsbt close にしてよい ?

**Comment by hsbt** [comment]
@springaki 閉じてしまっても大丈夫でしょうか!

**Comment by springaki** [comment]
@takkanm @hsbt 閉じて大丈夫です(私にはcloseする権限ありませんでした)。また請求書業務をお願いするときにはメールでお願いするか新規で Issue作らせてもらいます。

**Comment by hsbt** [comment]
しゅたっ

**Comment by kakutani** [comment]
@springaki 請求は別途issueを切ってもらえると助かります〜

**Comment by springaki** [comment]
@kakutani 了解ですー
