### ISSUE TITLE
るびまの読者プレゼント発送をしたい (yhara さんご提供分)

### ISSUE THREAD

**Issue by sunaot** [ruby-no-kai/official#145]
rubima/rubima#261 のほうから出張してきました。Cc @yhara さん

るびまの読者プレゼントの提供者が今回個人なので、日本 Ruby の会で実費を負担してもらえるとうれしいなという相談です。

おおざっぱに以下の流れになりそうなんですが、誰がどうすると諸々スムーズにいくのかなというところを相談して決めさせてください。
- るびまでの当選発表 <sunaot>
- yhara さんから本の受取
- 当選者 (抽選済) へ連絡して、発送先住所の確認＆発送
- 諸費用の実費を日本 Ruby の会に精算してもらう

**Comment by takahashim** [comment]
Rubyの会の方から来ました。最後に発送者（？）宛に実費を振込か手渡し、という感じでしょうか。

**Comment by sunaot** [comment]
反応ありがとうございます。選択肢としてはこんなところですかね。
- 偶然、松江で発送者にたてるるびま編集者 or 日本 Ruby の会の人がいるので、やってもらう
- sunaot 宛に yhara さんから着払で本を送付いただいて、私が発送などなどする

**Comment by snoozer05** [comment]
@sunaot 関係者がやりやすい方でやってもらえるとよさそう...!!

**Comment by yhara** [comment]
私はどっちでも大丈夫です。(松江にどなたかおられるなら、その人にお願いする方が楽かな？)

**Comment by yhara** [comment]
@sunaot と思ったけど、やっぱり後者のほうがよいかなと思いました。発送先をyutaka.hara.gmail.comまでご連絡いただけますでしょうか。

**Comment by gunjisatoshi** [comment]
@sunaot この件いかがでしょうか？（まずは当選者を決めるところから？）

お忙しいようでしたら本件引き取りますので状況をシェアいただければと思います！

**Comment by sunaot** [comment]
@yhara わーすみません... twitter のほうも見ました。。これから発送先を送ります＆当選者の方へ連絡しておきます。

**Comment by sunaot** [comment]
@gunjisatoshi ありがとうございます。すぐ対応いたします。。

**Comment by snoozer05** [comment]
@sunaot 対応状況っていかがでしょうか。対応が終わっていたら諸費用の精算をいたします。

**Comment by sunaot** [comment]
@snoozer05 ありがとうございます。発送まで終わっております。
精算どのようにすればよろしいでしょうか？

**Comment by snoozer05** [comment]
@sunaot 精算額と振込先について info@ruby-no-kai.org までご連絡くださいませ！

**Comment by sunaot** [comment]
そうそう、これを RubyKaigi でお会いしたときに手渡せればいいかなあと思っていたら当日はたのしくてそんなことをすっかり忘れていたのでした。メールしなければ。

**Comment by takahashim** [comment]
@sunaot これってどうなってましたっけ？

**Comment by sunaot** [comment]
@takahashim これ私がメールしてないですね。すっかり放置ですみません。レシート探すところから始めます。

**Comment by sunaot** [comment]
無事精算していただきました

**Comment by takahashim** [comment]
ただいま精算完了しました！
