### ISSUE TITLE
RubyKaja 2014 の状況について

### ISSUE THREAD

**Issue by snoozer05** [ruby-no-kai/official#148]
RubyKaigi 2014で表彰ならそろそろ...??

**Comment by snoozer05** [comment]
@tyabe ちらっ

**Comment by tyabe** [comment]
@snoozer05 遅くとも今月12日までには募集開始します。
また今回募集開始が遅れてしまったので、個別にお声がけしようとも考えています。

**Comment by snoozer05** [comment]
よろしくお願いします！

**Comment by tyabe** [comment]
こちらこそ。
必要な情報などがあれば共有させていただきたいと思いますので、よろしくお願いします！

**Comment by snoozer05** [comment]
承知いたしました！

**Comment by shyouhei** [comment]
じゃあ続きはkajaのほうで。
