### ISSUE TITLE
RailsGirlsOsakaの精算をお願いします

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#149]
お世話になります。
RailsGirlsOsakaスタッフの Akiです。

皆様の協力のおかげでRailsGirlsOsakaを無事開催する事ができました。
ありがとうございます。

つきましてはRailsGirlsOsakaの精算作業をよろしくお願いします。
- [x] パートナー様へ請求書送付
- [x] パートナー様からの振込確認

**Comment by springaki** [comment]
RailsGirlsOsakaパートナー様 請求先一覧へのリンクは info@ruby-no-kai.org にメールしました !!

**Comment by kakutani** [comment]
はいー

**Comment by snoozer05** [comment]
@kakutani 一覧にあった企業様宛すべての請求書を作成しました。内容をチェックしていただいて問題なければ郵送手続きを進めていただけますでしょうか

**Comment by snoozer05** [comment]
@kakutani ping

**Comment by springaki** [comment]
ping...

**Comment by snoozer05** [comment]
ご迷惑をおかけしています...早急に何とかしますので、今しばらくお待ちください... ><

**Comment by springaki** [comment]
すみません。皆様お忙しいと思いますがよろしくお願いします ><

**Comment by snoozer05** [comment]
今日明日中には送付できるかと思います... ><

**Comment by springaki** [comment]
ありがとうございます !! 今日ピークワンさんからも打診が来たので、そのようにお答えしておきます
(いろいろすみませんー)

**Comment by snoozer05** [comment]
郵送手続きを完了しました！遅くなってしまい、誠に申し訳ありませんでした :bow:
明日明後日には請求書届くかと思います。どうぞよろしくおねがいいたします。

**Comment by springaki** [comment]
こちらこそ急かしてしまってすみません。
ありがとうございます !!

**Comment by takahashim** [comment]
昨日振り込み分までを突き合わせてみました。
こちら一件を除いてそれ以外はお振り込みいただいていたようでした。

**Comment by snoozer05** [comment]
@takahashim 確認ありがとうございます！

**Comment by snoozer05** [comment]
@takahashim いちおう最後の１件も8/5付けで振り込んでいただけるようなご連絡をいただいていたのでした。なので、週明けあたりに再度確認をおねがいいたします :bow:

**Comment by springaki** [comment]
@takahashim @snoozer05 お手数おかけしております :bow:
最後の1件は N社様だと思うのですがN社様内での支払先登録に時間が掛かっているようで、8/5 よりも入金が遅れる可能性があるようです。

**Comment by takahashim** [comment]
すみません、こちら振込確認できてました！

**Comment by snoozer05** [comment]
@springaki @takahashim こちら閉じても大丈夫でしょうか？

**Comment by springaki** [comment]
一応確認なのですが、RailsGirls Osakaに対しての立替精算は未。という認識であってますか？(2重振込してしまいそうなので念のため確認しています)

立替精算はRailsGirlsでできるようになったので、この確認が終われば閉じてもらって大丈夫です。 :bow:

**Comment by springaki** [comment]
すみません。この件振込終わってるようです。(つじたさんに、確認しました)

私は閉じてもらって構いません！

**Comment by snoozer05** [comment]
はい！確認どうもです！
