### ISSUE TITLE
Ruby開発用マシン機材について

### ISSUE THREAD

**Issue by ko1** [ruby-no-kai/official#150]
芝浦工業大学様より、Ruby開発に利用するためのマシンを置く環境を提供して下さることになりました。そのマシンをどっかから持って来れないか探しているのですが（1台は私の私物）、
Rubyの会様から何かしら提供頂くことはできないでしょうか。

用途は、
- テスト
- デバッグ（開発者で共有して、同じ環境上でデバッグ）
- ベンチマーク
- 場所提供元の芝浦工大様の研究に利用（これは場所の利用条件です。研究といっても、本開発環境構築が研究のネタになる予定です）

マシン環境は、例えば：
- MacPro（開発者が共用できる Mac OSX 環境は優先度高い）
- 速い Intel マシン（あるだけ）
- そこそこの Intel マシン（あるだけ）

今のところ、笹田の個人プロジェクトということになる（Ruby-core team の総意などでは無い）ので、公平性などに問題があるかと思います。ただ、もしRubyの会でそういうのを受け入れてくれそうな枠があれば、ご検討頂ければ幸いです。

**Comment by shyouhei** [comment]
まあでも個人的にはrubyの発展に寄与するというたてつけであれば支援したいなーとは思います。
- いつまでに
- なにが
- どれくらい

が決まらないと動けないのでしょうかねえ。たとえば物納が望まれているのか、金銭で良いのか。

**Comment by ko1** [comment]
>  いつまでに

できるだけはやく、

>  なにが

上記に書いた通り（up to you）、

> どれくらい

上記に書いた通り（up to you）、

> が決まらないと動けないのでしょうかねえ。たとえば物納が望まれているのか、金銭で良いのか。

どちらでも（提供者の処理しやすいもの。レンタル、なども可）

かと思います。

**Comment by shyouhei** [comment]
できるだけはやくとなるとRubyKaigiとキャッシュフローの相談になりますねえ。
@takahashim 今度相談させてください

**Comment by hsbt** [comment]
用途として、現在 mrkn が個人で管理している chkbuild の OS X 環境をこのプロジェクト(?)で構築出来れば良いなと思っています。

**Comment by shyouhei** [comment]
@ko1 たとえば、Rubyの会のメーリングリストで「余ってるMacPro持ってる人いませんか」とか（Rubyの会から）聞いてみるというのはNGな感じでしょうか。そうじゃなくて新品が良い？

**Comment by ko1** [comment]
(2014/07/24 18:43), Urabe, Shyouhei wrote:

> @ko1 https://github.com/ko1 たとえば、Rubyの会のメーリングリストで
> 「余ってるMacPro持ってる人いませんか」とか（Rubyの会から）聞いてみるとい
> うのはNGな感じでしょうか。そうじゃなくて新品が良い？

　何の問題もありません。

（個人的には、MacPro はゴミ箱を見てみたい）

## 

// SASADA Koichi at atdot dot net

**Comment by shyouhei** [comment]
とりあえずMLにはメールしてみているところ。

**Comment by shyouhei** [comment]
MLの反応待ち。あればそれ。なければMacProを買う。

**Comment by shyouhei** [comment]
というかんじでどうでしょうか

**Comment by ko1** [comment]
MacPro 以外はどうします？

**Comment by shyouhei** [comment]
mac pro買うのであればごよさんが…
買わないならその分の値段で数台はいけるのでは。

**Comment by ko1** [comment]
今更だけど、告知して募集するなら、私がこれこれの理由でこういうのが欲しい、って言った方が早かったかもね。Mac pro は無いけど、ia32 のマシンなら余ってるのがあるから提供できるわ、って可能性とかもありあそう。というか、今からでも被せて聞いてみますか。

**Comment by ko1** [comment]
ちなみに、pro じゃなくて mini が新型出たら、そっちで十分かもね、と柴田さんと喋ってました。
MacPro って GPU 凄いんですなぁ（使わないけど）。

**Comment by shyouhei** [comment]
これすすめましょう。Mac mini新型出たので、それで。

もとMac Pro想定だったので4コア必要でしょうか？Mac mini2コア2台でもMac Proよりは安いので、Mac mini2台は可だと思います。必要であれば。

**Comment by ko1** [comment]
予算次第って感じでしょうか。
多分、低スペックでもあれば嬉しいし、高スペックでも嬉しい。

複数人でログインする可能性（バグが出たとき、検証のためにログイン）を考えると、他はともかくメモリは多めの方がいいかもしれない。でも、VM とかは立てないだろうから、8GB で良いかな。他は、予算に応じて、CPU を良い奴にする感じで。多分、HDD はそんな大切じゃ無いと、思う（とりあえず ci 的な使い方が主なので、瞬発力はそんなに求められていないのでは無いか）。

元々のベンチマーク環境としては、まだ定点観測のための仕組みを作れていないので、とりあえずテスト・デバッグ環境として。という点で、2台だと、まずはもてあましそう。

**Comment by ko1** [comment]
http://taisy0.com/2014/10/17/39458.html
メモリ増設は後からは出来ないみたいっすね。

**Comment by takahashim** [comment]
そんなに高スペックでなくても良いのであれば、10万円以下なら消耗品扱いになるのでその方が都合良いかなと思いました（別に超えるとムリというわけではないのですが）。

ということだと、2.6GHzのCore i5でメモリ16GBとか？（税別￥94,400）

**Comment by shyouhei** [comment]
じゃあ
- 予算10万円
- メモリ8GB
- CPUそこそこ

という条件でいうと竹コースかなあ

USだと松コースが$999.00で手が届きますねえ。RubyConf現地で買って帰るとか…
http://store.apple.com/us/buy-mac/mac-mini?product=MGEQ2LL/A&step=config

ちなみにCI的に使うのであればCPUよりもディスクに振った方がよいと思うのでSSDのほうが嬉しいですという意味でも松コースが望ましくはある。

**Comment by takahashim** [comment]
円安の昨今では$999は10万円超えるのでは…。
素直に10万円越えにしてRubyの会の固定資産ということにしますか？　PCの場合、償却期間は4年間なので、4年使ったら廃棄、ということにすれば面倒がないんですかねえ。

**Comment by shyouhei** [comment]
4年…2018までこのマシン使うか…

いや、微妙ですね。竹コースにしよう

**Comment by takahashim** [comment]
じゃあこれで購入してよいですか？　送付先はささださんのところがよいですか？＞@ko1

**Comment by shyouhei** [comment]
内容は卜部からはこれ以上ありませんので送付先が決まれば購入でよいと思います！

**Comment by ko1** [comment]
竹コースって何？
今日の開発会議で話題にします。

あと、俺が買って、後で精算と、そっちで買って、こちらに送っていただくでも、どちらでも良いです！
（が、来週引っ越すんで、もうちょっと後にして欲しい）

**Comment by takahashim** [comment]
Mac miniの商品紹介で3つ並んでる奴の真ん中のことではないかと＞竹コース
Core i5 2.6GHz Mac miniです。
http://store.apple.com/jp/buy-mac/mac-mini
メモリは16GBにしておいた方が無難ですか？　それとも8GBで良い？

**Comment by ko1** [comment]
開発会議で検討したところ、一番いい奴で +16GB memory +1TB fusion memory = 126,400 円（税抜き）でどうだろうか、という意見が多いようでした。4年くらいは多分使うだろう、と。
固定資産にすると、色々面倒でしょうか。

**Comment by takahashim** [comment]
なるほどー。であればそれで問題ないです。

**Comment by shyouhei** [comment]
他人のお金だから無責任に言ってません? (笑)
- メモリが16GB必要な理由は? Rubyのコンパイルでそんなにメモリいりませんよ
- ディスクが1TB必要な理由は? Rubyのコンパイルでそんなにディスクいりませんよ

払わないとは言わないので理由が欲しい感がありますね。一番いいやつ！ではおもちゃと同じなので。妥当性がほしいなあ。

**Comment by takahashim** [comment]
ディスクは標準で1TBシリアルATAドライブ、約2万円追加すると256GBのフラッシュか1TBのFusion Driveか（フラッシュとFusion Driveは金額同じ）なので、ある程度速度が欲しいと同金額になっちゃうんですよね…。

**Comment by shyouhei** [comment]
金額同じなら256GB SSDのほうが速そう。

**Comment by ko1** [comment]
メモリは複数人で同時に利用することを考えての値です。
ディスクはログなどが大量に出る可能性があるので、255GB だと不安です。

個人的にはメモリ多め、ディスクはHDDで良い派ですが（手元の ci とかしている Linuxマシンではそれで困っていない。十分なメモリがあれば、page cache に載るからそんなに困らない）、
Mac は i/o 多発するから遅い、という意見がありました（私は真偽を知らない）。
CPU は、それこそ予算があれば速い方がいいよね、というところ。

**Comment by ko1** [comment]
メモリは 16 じゃなくて 8 でもいいかな。HDD は 256 SSD だったら最低でも 512HDD が良いな。

**Comment by shyouhei** [comment]
MacはIO多発より何よりmacminiに搭載されてるHDDがめっちゃ遅いんですよ。3.5インチHDDとか絶対載ってないですから。Linuxマシンとは比較にならないです。

まあ10万円越えちゃうならCPUはけちってもしょうがないのはそうだとおもう。

あとは256GBで不安になるほどの大量のログというのが気になるんだけど、CIのログってどこかのタイミングでS3に移動したりしないんですか?

**Comment by ko1** [comment]
CI のためじゃなくて、開発一般の話です。とにかく dump してデバッグするような場合、溢れる可能性が。

**Comment by shyouhei** [comment]
そういうことであれば特に問題ないと思います。懸念点ないので発注に進んでいただければ。

**Comment by takahashim** [comment]
じゃあささださんが引っ越したら進めるということで！

**Comment by ko1** [comment]
引っ越したんですが、荷物がちょっと大変で作業スペースすら取れない状況で...。

rubyconf で高橋さんに最終的にOKもらって、発注する感じにしますかw

**Comment by ko1** [comment]
@hsbt それとも、柴田さんが発注・セットアップまでやっちゃいます？
（大学に持っていく時、私が受け取る感じで）

私としては、とりあえず clang でコンパイルできる開発マシンが手に入れば何も言うことは無い感じです（Mac OSX 用 clang のキャストの罠にはまることが多く）

**Comment by hsbt** [comment]
@ko1 @takahashim 僕があれこれしてしまって良いということであれば、発注とセットアップしてしまいますが、進めても良いですか?

**Comment by takahashim** [comment]
@hsbt はい、進めてもらえると助かります！
調べてみたら銀行振込にも対応してるみたいなので、支払いはこれでお願いできるとありがたいんですが可能でしょうか？
http://store.apple.com/jp/help/payments

**Comment by hsbt** [comment]
注文前の確認です!

http://gyazo.com/206d58112a071ad4cde213f127aae7d0

真ん中のモデルで CPU: そのまま メモリ: 16GB ドライブ: fusion drive 1TB の合計 114,000 円でよいでしょうか。

**Comment by takahashim** [comment]
私の方は問題ないです！

**Comment by hsbt** [comment]
注文しよう!と思いましたが、銀行振込名義と購入者名義が異なると面倒になりそうなシステムでした。 @takahashim さん(or 中の人どなたか)が購入するか、僕が建て替えて購入するかのどちらかがスムーズに進みそうな気がしますが、どちらがよいでしょうか?

**Comment by takahashim** [comment]
あー、そういうやつなんですね…。
であれば、 @hsbt さんの方で立て替えてもらって、支払い方法はお任せで、領収書を下記フォームから「一般社団法人日本Rubyの会」で発行してもらう、というのは可能でしょうか？
http://www.apple.com/jp/feedback/aos/receipt_request.html

**Comment by hsbt** [comment]
やってみます!

**Comment by hsbt** [comment]
改めて注文と領収書発行をしました!

**Comment by takahashim** [comment]
:+1:

**Comment by hsbt** [comment]
11/17 に Mac mini が到着しました。領収書が到着したら改めてご連絡します。

**Comment by hsbt** [comment]
領収書も到着しました。

@takahashim 何処かの asakusarb でお渡ししますので、よろしくお願いします。

**Comment by ko1** [comment]
ありがとうございます。設置することができました。
ruby-lang のほうに、こんな記事を載せて貰おうと思いますが、よろしいでしょうか。

どうぞよろしくお願いします。

---

= 開発マシン追加のお知らせ

このたび、一般社団法人 日本Rubyの会のご支援によって、Ruby インタプリタの
開発のために、mac mini を導入しました。mac mini の導入によって、Mac OSX
上での問題解決や性能評価に利用する予定です。

導入した mac mini は、 芝浦工業大学 工学部 情報工学科の菅谷研究室（基盤
システムソフトウエア研究室）に設置させて頂いております。

ご支援頂きました一般社団法人 日本Rubyの会、および芝浦工大菅谷研究室には
深く感謝致します。

すでに、Ruby開発には、様々な会社、団体からご支援を頂いております（[参考] 
(https://www.ruby-lang.org/en/about/website/]）。開発用機材など、まだ不
足しておりますので、もしご支援頂ける方がいらっしゃいましたらご連絡下さい。

= Rubyインタプリタ開発者へ

必要な方にはこのマシンにアカウントを作りますので、笹田までご連絡下さい。

**Comment by takahashim** [comment]
はい、問題ないです！
（冒頭で「ご支援」の「ご」はいらないと思いましたが、後のほうでは他団体・法人に係ってるなら揃えてそのままの方が良さそうですかねえ）

**Comment by hsbt** [comment]
振込確認、Web への掲載終わっているので閉じても良いかと思いますー。

**Comment by takahashim** [comment]
@ko1 閉じちゃってよいですか？（私は問題ないです）

**Comment by ko1** [comment]
はい、ありがとうございました。
また、よろしくお願いします。

**Comment by ko1** [comment]
FYI ですが、ここで買った mac mini が起動しなくなりました。4.5 年、お疲れ様でした。

**Comment by takahashim** [comment]
Oh..了解です！

**Comment by hsbt** [comment]
ご報告: この issue で買った mac mini ですが @ko1 さんから回収して @hsbt が軽く見てみましたがセーフブートすらダメっぽい、という状態だったのでパソコンリサイクル制度で本日廃棄処分しました。

**Comment by takahashim** [comment]
ご報告ありがとうございます :pray:
