### ISSUE TITLE
現在の RailsGirls 繰越金額を知りたい

### ISSUE THREAD

**Issue by snoozer05** [ruby-no-kai/official#156]
RailsGirls-JP Organizers 方面から質問をいただきました。
Dropboxにある分だけだと、松江までの記録しかないのですが、収支はどこをあさるといいですかねえ。
@takahashim 決算絡みで、この辺り整理されていたりしませんでしょうか...

**Comment by takahashim** [comment]
Dropboxのfinancialstatements/2013/Rubynokai2013.xlsのピボットテーブルの表で出入りは分かるようになっております。

**Comment by snoozer05** [comment]
確認できました！ありがとうございました！
