### ISSUE TITLE
日本Rubyの会で台湾からの留学生の渡航費用精算事務をお願いしたい件

### ISSUE THREAD

**Issue by snoozer05** [ruby-no-kai/official#157]
相澤さんから以下の依頼をいただきました:

> 背景説明
> ご存知かもしれませんが、今年、RubyConf Twに参加した人たちを中心に、台湾のRuby
> コミュニティーの人を日本のRubyKaigiに招待しようという企画「RubyKaigi2014 Scholar-
> ship Program for RailsGIrls Taipei」を進めており、私が発起人になっています。
> 募集要項はこちらです。
> （中国語版） http://railsgirls.tw/2014/07/28/rubykaigi-scholarship/
> （英語版） https://gist.github.com/ayumin/62ebb6d4b99e2295a49c
> 
> 台湾のコミュニティーリーダーの協力もあり、短い募集期間でありながら、あわせて10名
> の申込を受けました。そして本日、日本と台湾側でミーティングをおこない、3名の方を
> RubyKaigiに招待することにしました。
> 
> 費用負担について
> 今回招待する人たちの渡航費および宿泊費、RubyKaigi参加費は、プログラムの趣旨に賛同
> してくれている人たちからの寄付とHerokuの予算から捻出します。
> ただ、Herokuやその他法人に対しては請求書の発行や、対個人向けに領収書の発行などを行
> う主体として、日本Rubyの会にその事務をお願いしたいとおもっています。
> 
> *この件に関しては、角谷さんに打診してあるのですが、（おそらく）RubyKaigiの準備で忙
> しいためか、回答をいただけていません。
> 実際に手を動かす部分については私が代行できる部分はもちろんやらせていただきますので、
> 請求書や領収書の発行主体として日本Rubyの会にご協力いただけないでしょうか。

すでにRubyKaigi モードなのと決算処理もある中なので帯域がジリ貧ですが、何とかやれる作戦を考えます。。法人への請求業と個人への振込業（領収証の発行はリソース的にきびしい）なら...みたいな感じですすめてみます

**Comment by snoozer05** [comment]
以下のように進行することで調整しました:
1. 協賛企業に対してRubyの会から請求書を発行
2. 協賛者さん（企業、個人）からRubyの会に入金
3. 入金されていることを確認
4. 相澤さんから立替精算明細および精算額を報告いただく（領収証や支払証明もRubyの会に送っていただく）
5. Rubyの会から相澤さんに入金

**Comment by takahashim** [comment]
調整ありがとうございます！

**Comment by snoozer05** [comment]
@takahashim これってどういう状況でしたっけ...??

**Comment by snoozer05** [comment]
@takahashim pingしておきます...!!

**Comment by takahashim** [comment]
これはだいたい終わってるはずです（企業＆個人からは入金してもらった、相澤さんにも入金した、領収書等はデジタルデータなので送ってもらった）。
あとは細かい金額の確認が残っています（←苦手なやつですみません…）

**Comment by snoozer05** [comment]
状況がわかるだけでも大変たすかります！
引き続き確認をよろしくおねがいいたします :bow:

**Comment by shyouhei** [comment]
- 入金等の作業自体は終わっている
- 金額の確認が残件 (★next action)

**Comment by shyouhei** [comment]
決算に向けてそろそろ紙と向き合う。検算。

**Comment by shyouhei** [comment]
#193 が終わればいい

**Comment by takahashim** [comment]
金額確認しました！　問題なかったです。

**Comment by shyouhei** [comment]
おわり!
