### ISSUE TITLE
eBay口座開設

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#158]
PayPalアカウントじゃだめなのか…

**Comment by takahashim** [comment]
提出書類ですが、W-9じゃなくてW-8BENじゃないでしょうか…。
https://www.servicescape.com/help.asp?tab=p&lang=ja&con=2

**Comment by shyouhei** [comment]
W8BENで済むといいですよねえ。米国内の住所がどうしても必要って言われたら無理なので…小切手送ってもらうとかかな…

@takahashim Supplier Registration Page 、だいたい埋めれそうなんですけど、Bank Dataのところがどう書けばいいか no idea です。ちょっと見ていただくことは可能そうでしょうか。

**Comment by takahashim** [comment]
こんな感じですかねえ。

Bank Key: 0009677
SWIFT: SMBCJPJT
Bank Name: SUMITOMO MITSUI BANKING CORPORATION
Bank Branch: MEJIRO BRANCH
Acccount Holder Name: NIHON RUBY NO KAI
Account Number: 6888135
Address: 3-14-1 MEJIRO TOSHIMA-KU TOKYO JAPAN 171-0031

（参考）
- http://www.smbc.co.jp/kojin/otetsuduki/sonota/kaigai/hishimuke.html
- http://ja.wikipedia.org/wiki/%E6%97%A5%E6%9C%AC%E3%81%AE%E9%87%91%E8%9E%8D%E6%A9%9F%E9%96%A2%E3%81%AESWIFT%E3%82%B3%E3%83%BC%E3%83%89%E4%B8%80%E8%A6%A7
- http://sapblog.jugem.jp/?day=20090611
- http://zengin.ajtw.net/dbs5.php?abg=0009&abs=677

**Comment by shyouhei** [comment]
ぐぬー、口座種別を選べと言われる。けどそんなフィールドない…
![screen shot 2014-09-01 at 8 53 29 pm](https://cloud.githubusercontent.com/assets/15377/4107924/bbb2acea-31ce-11e4-9df8-d6bf1b0d6341.png)

入力欄があればOrdinaryまたはSavingsなのだが…

**Comment by shyouhei** [comment]
これは電話しないと解決しないパターンかな...

**Comment by shyouhei** [comment]
だめもとでメールしてみた。向こうはこういうのは電話しないとだいたい反応ないからな…

**Comment by shyouhei** [comment]
現地時間の火曜日で反応なければ現地時間の水曜で電話してみますね…

**Comment by shyouhei** [comment]
へんじない＞＜

**Comment by shyouhei** [comment]
ところでこの携帯電話から国際電話ってどうかけるんだ？

**Comment by shyouhei** [comment]
国際電話の掛け方は分かった

**Comment by shyouhei** [comment]
スクリーンショット確認して折り返しの電話が来ることになってるけどそれ待ってたら永久に練れないので30分ほど待ってから再度かけます

**Comment by shyouhei** [comment]
こちらがおかねをいただく立場なのでわりとがんばる。。。

**Comment by kakutani** [comment]
おうえんしています!!1

**Comment by shyouhei** [comment]
再度電話したので、スクリーンショットを見てくれて、返信をくれるとのことなんだけど、いつ来るかはよくわからない。

**Comment by shyouhei** [comment]
まあeBayくらいの大企業なら電話窓口のオフショアくらい当然やってるよね…

**Comment by shyouhei** [comment]
サポートセンターでは解決できないようなのでとりあえず窓口に電話する修行は終わりのようです

**Comment by shyouhei** [comment]
がこのissueは閉じれない

**Comment by shyouhei** [comment]
とりあえずwebフォームはおかしいようだからメールで必要な情報を送ってくれと言われつつエクセル方眼紙が来たので、埋めて打ち返したところです。

**Comment by kakutani** [comment]
おつかれさまです……先方で代理入力してくれたら…勝利……ッ……

**Comment by shyouhei** [comment]
状況確認中です

**Comment by shyouhei** [comment]
メール来た！

**Comment by shyouhei** [comment]
進んでるけどまだ終わりません(上記のW8BENの話に進むはず)

**Comment by shyouhei** [comment]
とりあえず口座は開けたぽいですね

発注書の単価が間違ってるから「どうなっとるんじゃ？」というメールを送っています。

**Comment by shyouhei** [comment]
ログインできたので口座開設は終わったけど、パスワードはいつものが使えなくて制限がきつかったので `SecureRandom.urlsafe_base64.each_char.map{|i| rand < 0.5 ? i : i.upcase }.join` で作成しました。自分でも暗記できませんのでなにかの方法で共有したいです。。。

![](http://i.gyazo.com/acffc20dc28a9588a0ac1d2f61585a7a.png)

ちなみにログインしてみたら何も特に進行してなかったぽいのでスポンサー費用回収は終わらないです…

**Comment by shyouhei** [comment]
どうなってるの？って聞いてみてます

**Comment by shyouhei** [comment]
発注書来ました。W-8BENは不要ぽい（Asia Pacificはシンガポール国籍の現地法人でとりあつかいの模様）。

official 的な残件はログインパスワードの共有方法のみです。

**Comment by shyouhei** [comment]
閉じますね。ログインパスワードに関しては、そもそもここにログインしなくても請求は送付できる事が明らかになっているので、よくわからんです…
