### ISSUE TITLE
Ruby開発者会議 20140904 への支援について

### ISSUE THREAD

**Issue by ko1** [ruby-no-kai/official#159]
[Ruby開発者会議 20140904](http://cruby.doorkeeper.jp/events/13742) が夜に行なわれるので、ちょっとつまめるように、5,000円くらい、ピザとか援助頂いてもいいでしょうか。
（人数 x 1,000 円くらいを上限）

**Comment by takahashim** [comment]
問題ありません！ :+1:

**Comment by ko1** [comment]
こちら、遅くなりましたが、7人参加で 6,400 円（ピザ）でした。
少しオーバーしてしまいましたが、ご支援賜れば幸いです。

**Comment by takahashim** [comment]
@ko1  了解です！:pizza: 　この前の口座に振り込めばよいですか？

**Comment by ko1** [comment]
はい、よろしくお願いします。

**Comment by snoozer05** [comment]
@takahashim こちらはどういう状況でしょうか

**Comment by takahashim** [comment]
う、これは払ってないみたいでした。すみません :bow:
振り込みます

**Comment by snoozer05** [comment]
@takahashim 振り込み完了済みでしょうか...??

**Comment by snoozer05** [comment]
@takahashim pingしておきます...!!

**Comment by shyouhei** [comment]
完了済みのはずとのことなので確認したらcloseしてください > @takahashim

**Comment by takahashim** [comment]
#172 で振り込みずみです :bow:
