### ISSUE TITLE
「日本Rubyのチュートリアル」を実施する

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#16]
### Rough Timeline
- [x] 2013.03.18: α版(無料)
- [ ] 2013.06.02: β版(無料)
- [ ] 2013.08- 有料でときどき開催したい
### ToDo
- [ ] インセプションデッキを清書してどっかに置く
- [ ] リーンキャンバスを描く

**Comment by kakutani** [comment]
Asakusa.rb で軽く聞いてみたら、「じゃあ英語からですね」って言われた……。まあ英語は他でも習えるしな……

**Comment by kakutani** [comment]
(ここまで具体的な動きなし)

**Comment by kakutani** [comment]
2013年になんかやるぞー。

**Comment by kakutani** [comment]
1/30 に @snoozer05 と札幌でインセプションデッキのラフをつくったので、もうちょっと清書して理事ミーティングでレビューしてもらう。

**Comment by shyouhei** [comment]
3/18の夜?

**Comment by kakutani** [comment]
資料請求したい! http://haa.athuman.com/pr/ruby/

**Comment by kakutani** [comment]
品川で場所を確保できた。

> 3/18（月）18:00-21:00で...20人部屋を予約しております。

**Comment by kakutani** [comment]
@yuumi3 が参観してくれることになった!

**Comment by snoozer05** [comment]
α版は何とか終了しました...!!

**Comment by takahashim** [comment]
そういえば「インセプションデッキを清書してどっかに置く」と「リーンキャンバスを描く」は終わってるんでしたっけ？

**Comment by snoozer05** [comment]
いや、まだなのでした...!!

**Comment by kakutani** [comment]
セグメントを絞って(上のほう狙い)、有料でβ版をやろう。
- Railsのアプリは書けるひと
- 他の言語でプログラムを書ける人

**Comment by kakutani** [comment]
8/8に札幌で話をする。

**Comment by snoozer05** [comment]
難しかったことを整理する

**Comment by snoozer05** [comment]
放置しておくのもあれなので、いったん閉じてしまいたいと思います。
（難しかったことも整理しきれていませんが...）
リベンジの機運が高まったら、開き直すことにしましょう...
