### ISSUE TITLE
RailsGirls 関連の何かを巻き取る

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#161]
RailsGirls Japan(仮称)の方から来ました

今、Rubyの会にお金周りはすべてお願いしていますが、一部を @hsbt @yakitorii @emorima あたりで巻き取れればなあというのを @snoozer05 とぼんやり話していました。
- 全部 RailsGirls でやろうとすると、収支や登記?とかも全部やる必要があるのでそれは大変
- 請求書発行は Ruby の会、資金の出し入れは RailsGirls(これだと口座を分けないとダメ?)
- その他

**Comment by kakutani** [comment]
> 全部 RailsGirls でやろうとすると、収支や登記?とかも全部やる必要があるのでそれは大変

たいへん。

> 請求書発行は Ruby の会、資金の出し入れは RailsGirls(これだと口座を分けないとダメ?)

昔のRubyの会方式(NaClさんやruby-assnに助けてもらってた)がいいんじゃないかなあと。
状況から言いますと、口座は分けたいです(会計士さんから2回指摘された)。
とはいえ、事務手続きは日本Rubyの会で代行します(たいへんだし)。

> その他

開催をまたいで発生する意思決定(年間スポンサーや、繰越金の使う度合い)や
会から「渡す先 is 誰」だと困る(会計的に)。
なので、窓口としての任意団体RGJPカッコカリあったほうがよさそう。

任意団体のつくりかたは、日本Rubyの会の前身をつくった @takahashim が経験者だからお詳しいのでは! ということで相談したい…。

**Comment by takahashim** [comment]
> (これだと口座を分けないとダメ?)

はい。逆に言うと、Rubyの会としては口座さえ分かれていれば良いです。

現在、Rubyの会の会計では、RailsGirlsのお金は「預り金」として計上されています。つまり「一時的に預かってる」状態なので、どこかの口座に戻したいのでした。

Rubyの会の業務としては、RailsGirls *という各イベントの会計事務を担当して行うという形で、各企業からの協賛金を受け取る（振込先口座としてRubyの会の口座を使う）ことは問題ないです。

…というRubyの会側の話はおいておいて、コミュニティとしての一般論を書くと、
- a) 個人で頑張る
- b) 名目として組織を作る（いわゆる任意団体）
- c) 法的実体として組織を作る（NPOとか一般社団法人とか会社とか）

というパターンがあって、c)は大変なのでb)くらいがおすすめという感じです（実はaでも構わない）。

任意団体は会計は小遣い帳的なもので構わない（仕訳は不要、何に使って今いくら残っているかが分かれば良い、現金を使わないようにすれば口座の通帳並でも構わない）、登記はいらないし定款（団体の規約、会則）もつくらなくて良いのですが、口座を作る場合に定款を見せろとかいろいろ言われる可能性はあります。そこは金融機関の窓口の人と相談してみていただければ。
ちなみに任意団体時代のRubyの会は会計があづみさんで、口座の名義は「日本Rubyの会　会計　安積伸弥」になってました。

**Comment by hsbt** [comment]
@publichtml @igaiga @springaki も呼んでおこう

**Comment by springaki** [comment]
呼んでいただきました。

協賛金を受け取っていただく（振込先口座としてRubyの会の口座を使う）ことは問題ないという事は
一旦協賛金を入金していただいた Rubyの会口座から a)個人名義の口座 か b)任意団体名義の口座に振込してもらうという事であってますか？

b) ならそのまま入金してもらってもいい感じですかね。送金業務が発生しなくてRubyの会の負担も減って尚良しな感じなのでしょうか。

RailsGirls で発生している事務処理ってこんな感じですか？
請求書送付とか手伝えるかもです(そういうのは求められてないのでしょうか)。
- 請求書送付
- 入金確認
- 立替金精算
- 証憑類の保管

**Comment by hsbt** [comment]
@springaki 請求書送付そのものは Ruby の会にお願いすることになりそうです(僕らの誰かが Ruby の会の中の人になる、というオプションもある?と全部巻き取れそう)

短期的には、口座を分けて任意団体とすることで
- @kakutani さんや @takahashim さんにお願いしている入金確認、精算業務
- 年間スポンサーというやつの窓口
- 各 RailsGirls 開催のお金周りの窓口

を巻き取れそうだなあという感触です。

**Comment by kakutani** [comment]
> b) ならそのまま入金してもらってもいい感じですかね。送金業務が発生しなくてRubyの会の負担も減って尚良しな感じなのでしょうか。

日本Ruby会議の経験からは、「あっちは任意団体で、こっちは法人口座で」みたいになるので、どちらかに寄せたほうが楽だと思います。で、寄せるなら法人口座じゃないと困る企業さんがいらっしゃるから会の口座のほうがよいと思います。

入金口座のこともありますし、請求書の送付元は日本Rubyの会でよいと思います。
作業の手間は、misocaフォーマットのcsvですぐ終わるので、あんまり大変じゃないです。

開催ごとの立替精算とか事前の支払い(ステッカーとかTシャツとか)を、
巻きとってもらったほうが、機動力は上がると思うし、助かります。

RGJPカッコカリの口座があれば、意思決定から会計までの流れが
スムーズになるんじゃないかな、と思いました。
ネットバンクの口座は、任意団体なら使えるのかな?
(法人のはなんかめんどくさそうにみえました(高橋さんが苦戦してた))

スポンサー窓口のところは巻き取ってもらえると、意思決定含めてスムーズになるので
良さそう(会は事務代行という位置づけ)

**Comment by hsbt** [comment]
@kakutani @takahashim 口座を分けるときに、
- 入金自体は Ruby の会の法人口座
- 集まった分を RailsGirls JP の任意団体口座に移動
  - この資金自体は Ruby の会のものという扱い?
- 口座に入ったあとは RailsGirls JP で決めて使う

という感じだと思うのですが、口座間移動が会計的に問題ないのかをご相談させてください!(そろそろオフラインがいいかも!)

**Comment by hsbt** [comment]
任意団体で 20-30万くらいのお金をやりくりすると税務的に何か問題あるのか、というところが引っかかっております。

**Comment by kakutani** [comment]
移動じたいは問題ない、というのが総会での質疑の結果でした。
なので「預り金をわたす先の口座がほしい」という話の流れでございます!

で、受け取る側の話ですが、RGっていわゆる収益事業じゃないから
そこは課税されないんじゃないかなあ
(そろそろ書きっぷりに気をつけないといけなさそう)。

**Comment by hsbt** [comment]
> なので「預り金をわたす先の口座がほしい」という話の流れでございます!

概ね把握ですぞ〜(続きは Web じゃないところで)

**Comment by takahashim** [comment]
> 任意団体で 20-30万くらいのお金をやりくりすると税務的に何か問題あるのか

一般社団法人でも任意団体でも、課税の義務が発生するのは「34業種の収益事業に該当することを継続的に行うこと」という要件があり、勉強会とかセミナーとかは34業種に含まれないとのことなので、課税されない、という理解です。
（これがたとえば出版業は34業種に含まれるので、継続的に出版を行うと課税対象になるので注意、とのこと）。
- http://www.pref.kanagawa.jp/cnt/f100183/p28234.html#06
- http://hosoka.com/index.php?zinnkakunonaisyadanntou
- http://law.e-gov.go.jp/htmldata/S40/S40SE097.html#1000000000000000000000000000000000000000000000000500000000000000000000000000000

**Comment by springaki** [comment]
> 入金口座のこともありますし、請求書の送付元は日本Rubyの会でよいと思います。
> 作業の手間は、misocaフォーマットのcsvですぐ終わるので、あんまり大変じゃないです。
> 
> 開催ごとの立替精算とか事前の支払い(ステッカーとかTシャツとか)を、
> 巻きとってもらったほうが、機動力は上がると思うし、助かります。

なるほど。
なにが大変で、なには大変じゃないかの理解が進みました。ありがとうございます。口座間移動的なところも気になっていたのですが、大丈夫そうなのですね。

**Comment by hsbt** [comment]
ひとまず口座を巻き取ろうということで https://github.com/railsgirls-jp/railsgirls-jp.github.io/issues/118 で進めることにしました。
