### ISSUE TITLE
RailsGirlsNagoya 2ndのステッカー代金の支払いについて

### ISSUE THREAD

**Issue by yada-ITA** [ruby-no-kai/official#162]
Nagoya Team の@yadaitaです。
@kakutaniさんよりご連絡いただき、コチラにissue作成作成します。

デジタさんへの発注予定です。発注完了後に振込関連情報を
メールにてご連絡しますので、よろしくお願い致します。

**Comment by yada-ITA** [comment]
info宛にメールをお送りしましたので、ご確認お願い致します！

**Comment by takahashim** [comment]
確認しました！
こちら明日中はちょっと厳しそうですが、今週中には振り込んでおきます。

**Comment by yada-ITA** [comment]
はい！よろしくお願いします :star2:

**Comment by takahashim** [comment]
こちら先ほど振り込みましたので、明日には入金されるかと思います。

**Comment by yada-ITA** [comment]
ありがとうございます！

**Comment by yada-ITA** [comment]
10/01にデジタさんより入金確認＆作成開始のメールが入りました！
ありがとうございました！
（ご報告遅れてすみません……）

**Comment by takahashim** [comment]
遅くなってしまいましたがこちら閉じますね。どうもおつかれさまでした！
