### ISSUE TITLE
RailsGirlsTokyo 4th! お弁当代振込み (2014/10/31(金)まで)

### ISSUE THREAD

**Issue by publichtml** [ruby-no-kai/official#163]
RailsGirlsTokyo 4th! のお弁当代の振込みをお願いします。
- 振込金額: 49,000円
- 振込期限: 2014/10/31(金)
- 請求書: @kakutani さんにお渡し済み
  - RailsGirlsTokyo 4th!当日(9/21(日))にお渡ししたpixivのクリアファイルに入っているはずです

よろしくお願いしますm(_ _)m。

**Comment by takahashim** [comment]
@kakutani これって振り込めリストに載ってます？

**Comment by publichtml** [comment]
@takahashim @kakutani 
振込み期限まであと半月となりましたが、進捗いかがでしょうかm(_ _)m

**Comment by takahashim** [comment]
@publichtml 遅くなってしまってすみません、こちらですが直接私(takahashim [at] ruby-no-kai.org)の方まで振込先を教えていただけますか？（金額は49,000円でいいんですよね？　請求書はあとで角谷さんから回収します）

**Comment by publichtml** [comment]
@takahashim すみません、右から左に @kakutani さんに請求書をお渡ししたので振込先は控えていないです＞＜。

たまたま @kakutani さんにお会いしたので、請求書を確認するようお願いしました (どうも他の領収書と一緒くたに渡してしまったので、一通だけ請求書が入ってると思っていなかったようです、すみません)。

確認にお時間かかるようなら業者に振込先など問合せますのでお申し付けいただければm(_ _)m

**Comment by publichtml** [comment]
進展ないようなので、業者に振込先と金額を問い合わせるメールを送りました。返信がもらえたらご連絡します。

**Comment by publichtml** [comment]
@takahashim
お弁当の請求書PDFをメールにて送りました(takahashim [at] ruby-no-kai.org宛です)。
ご確認の上、振込み手続きをお願いいたしますm(_ _)m

**Comment by takahashim** [comment]
振込先の方受け取りました。どうもお手数おかけしました :bow:
来週振り込んでおきます。

**Comment by publichtml** [comment]
こちらこそ、情報が遅くなってすみません。よろしくお願いいたします！

**Comment by takahashim** [comment]
こちら先ほど振り込みました！　入金は明日の日付になるかと思います。

**Comment by publichtml** [comment]
ありがとうございます！いろいろお手数おかけしましたm(_ _)m
