### ISSUE TITLE
RailsGirlsTokyo 4th! 立替精算

### ISSUE THREAD

**Issue by publichtml** [ruby-no-kai/official#164]
今回立て替えたのはスタッフの小田切 ( @publichtml ) のみ、合計 144,135円です。
## 金額 (合計 144,135円)
- カクヤス: 3,266円
- amazon: 6,713円
- ダイソー: 756円
- アフターパーティ: 133,400円
- 合計: 144,135円
- すべて 小田切 ( @publichtml ) が立替
## 領収書お渡し状況 (2014/09/27時点)
- @kakutani さんに RailsGirlsTokyo 4th! 当日(9/21) にお渡し済み
  - カクヤス (3,266円)
  - amazon (6,713円)
- @emorima さん預かりで、次に会った機会に @kakutani さんにお渡しいただく予定
  - ダイソー (756円)
  - アフターパーティ (133,400円)

よろしくお願いしますm(_ _)m。

**Comment by hsbt** [comment]
@emorima アフターパーティーの領収書って今何処に言っているか思い出せますか...

@kakutani @takahashim @snoozer05 @shyouhei こちらの建て替え、金額も大きいので、@publichtml さんへの支払いをお願いしたいのですが、領収書がないと出来ないなどありますか?

**Comment by snoozer05** [comment]
出金伝票を書くなりすればやりようはあると思います。
@takahashim だいじょうぶですよね？？

**Comment by emorima** [comment]
アフターパーティーの領収書は、
takkanm さん 経由で、@kakutani さんへお渡し済です!

**Comment by publichtml** [comment]
領収書状況更新: 
アフターパーティの領収書は @emorima さんが takkanm さん 経由で、@kakutani さんへお渡し済みとのこと。
これで全領収書が @kakutani さんの手に渡ったはず、という状況になります。

**Comment by publichtml** [comment]
(あっ、スレを勘違いして同じ内容を二重書き込みしてしまいましたorz

**Comment by takahashim** [comment]
@snoozer05 @publichtml  Rubyの会から見るとRailsGirlsについては預り金扱いになっているので、まあそんなに細かいことは気にしなくて良いかと思います（入金と出金の金額があってればいいので）。

**Comment by takahashim** [comment]
@publichtml @hsbt  こちらですが、金額がfixしているのであれば明日くらいに振り込みますか？
（それ以降になるとお金の流れが変わる予定）

**Comment by hsbt** [comment]
@takahashim いったん、RailsGirls Japan 口座に現時点でお金の移動が確定したものを頂いて、こちらでアレコレしたいと考えていますが可能でしょうか?

**Comment by publichtml** [comment]
|-`).｡oO( @takahashim @hsbt こちら、急いでいないのでお二人の都合のよいように調整いただければと思います。金額は 144,135円 でfixです )

**Comment by hsbt** [comment]
@publichtml 僕が責任もってお支払いするのでもう少々お待ちください!

**Comment by takahashim** [comment]
@hsbt @publichtml 了解です、では私の方では対応しないようにしておきます :bow:

**Comment by publichtml** [comment]
了解いたしました！
