### ISSUE TITLE
開発会議 DevelopersMeeting20141029Japan へのご支援について

### ISSUE THREAD

**Issue by ko1** [ruby-no-kai/official#166]
例のごとく、開発会議 https://bugs.ruby-lang.org/projects/ruby/wiki/DevelopersMeeting20141029Japan へのご支援をお願い出来ますでしょうか。

**Comment by takahashim** [comment]
はい、こちら問題ないです！

**Comment by ko1** [comment]
連絡が遅くなりましたが、お茶菓子代で、1,496 円でした。
よろしくお願いします。

**Comment by takahashim** [comment]
了解です！
都度払った方がよいですか？　それとも何回分かまとめます？

**Comment by ko1** [comment]
まとめて、が双方楽ではないかと。

**Comment by takahashim** [comment]
了解です。では適当なタイミングで。

**Comment by snoozer05** [comment]
@takahashim こちらまだタイミング待ちでしょうか？

**Comment by snoozer05** [comment]
@takahashim pingしておきます...!!

**Comment by shyouhei** [comment]
これも支払済とのことなので閉じます。
