### ISSUE TITLE
RubyKaja 2014 ノベルティ代金

### ISSUE THREAD

**Issue by tyabe** [ruby-no-kai/official#167]
RubyKaja 2014 のノベルティ送付が完了しました。
後日、領収書と振込先を別途ご連絡します。

ご支援頂きたい金額の内訳は以下の通りです。

| 項目 | 金額 |
| --- | --- |
| 手ぬぐい | 30,888円 |
| レターパック | 6,120円 |
| Tシャツ | 25,056円 |

合計金額：62,064円

なお、手分けして発注したため、
領収書と振込先は @tyabe と @katorie のそれぞれからお知らせします。

**Comment by takahashim** [comment]
@tyabe ご報告ありがとうございます！
@katorie さんからメールのほうもいただきましたが、
- @tyabe さんがTシャツ代25,056円
- @katorie さんが手ぬぐい＋レターパック代で合計37,008円

という立替の分担で正しいでしょうか？

**Comment by tyabe** [comment]
@takahashim はい。おっしゃるとおりです。
わたしの分も今日明日中にはメールでご連絡しますので、よろしくお願いします。

**Comment by takahashim** [comment]
了解です、お待ちしております！

**Comment by katorie** [comment]
@takahashim よろしくお願いいたします！！

**Comment by takahashim** [comment]
@tyabe さんのメールも受け取りました！
週明けにお二人にお振り込みしておきます。

**Comment by tyabe** [comment]
@takahashim ありがとうございます！
よろしくお願いします

**Comment by takahashim** [comment]
@katorie @tyabe そういえばこちらお振り込みしてました！　ご確認ください。

**Comment by katorie** [comment]
@takahashim 確認いたしました！ありがとうございました。

**Comment by tyabe** [comment]
@takahashim 確認しました！ご対応ありがとうございました。
