### ISSUE TITLE
RailsGirls Tokyo 4th のスポンサー費用の請求

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#168]
RailsGirls Tokyo からやってきました。

https://github.com/railsgirls-jp/tokyo-team/issues/121#issuecomment-60878628

RailsGirls のスポンサー費用の請求を該当企業へ行っていただきたいです。スポンサー費用の詳細は
 @emorima が把握しているはず...

/cc @yakitorii

**Comment by snoozer05** [comment]
不安を感じさせてしまい申し訳ないです。今晩遅くになってしまうかもしれませんが、対応しますね。詳細を info@ruby-no-kai.org に送っていただけますでしょうか。

**Comment by emorima** [comment]
メールさせて頂きました!
情報が不足している等ありましたら、ご連絡お願い致します!

**Comment by snoozer05** [comment]
請求書を作成し、郵送が必要な企業様には郵送手続を、原本不要な企業様にはメール配信をそれぞれ行いました。遅くなってしまい申し訳ないです。もし何か不手際などあれば再度ご連絡ください... ><

**Comment by emorima** [comment]
お忙しい中、対応頂きありがとうございました! :star2:

**Comment by hsbt** [comment]
@snoozer05 :bow: いつもありがとうございます。

スポンサー企業からの振込が完了したら issue 閉じますので、入金確認までよろしくお願いします。

**Comment by hsbt** [comment]
どうなっているのかな...

**Comment by snoozer05** [comment]
入金確認は高橋さんじゃないとできないのでした。 @takahashim どうなってますでしょうか

**Comment by hsbt** [comment]
@snoozer05 反応ありがとうございます。Nagoya 2nd, Kyoto 2nd も支出の精算が終わってないような気がするので issue などの状況をまとめたほうが良ければご連絡ください。

**Comment by springaki** [comment]
> @snoozer05 反応ありがとうございます。Nagoya 2nd, Kyoto 2nd も支出の精算が終わってないような気がするので issue などの状況をまとめたほうが良ければご連絡ください。

@hsbt さんのおっしゃるとおり Kyoto 2nd の立替清算も終わってないので、新規 issueでお願いしようとしていました。まとめた方がよさそうでしたら、それに準じますー。清算お願いが遅くなっていて申し訳ありません...

**Comment by takahashim** [comment]
こちらすみません、入金はすべて確認できました！
どうもお手数をおかけしました :bow:

**Comment by snoozer05** [comment]
入金まで終わっているので閉じてしまいます
