### ISSUE TITLE
RailsGirls Nagoya 2nd のスポンサー費用の請求

### ISSUE THREAD

**Issue by yada-ITA** [ruby-no-kai/official#169]
RailsGirls Nagoya teamの@yadaitaです。

@kakutaniさんには、数日前にFacebookのメッセージにて直接ご連絡しましたが、
こちらにも念のため書き込みしておきます。

（Tokyo 4thでも、
https://github.com/railsgirls-jp/tokyo-team/issues/121
https://github.com/ruby-no-kai/official/issues/168
の書き込みがあった事もあり、ちょっと心配になりました……）

RailsGirls Nagoya 2ndについても、スポンサー様への請求業務をお願いしたいです。
詳細情報については、info@ruby-no-kai.org にお送りすればよろしいでしょうか？

**Comment by snoozer05** [comment]
> 詳細情報については、info@ruby-no-kai.org にお送りすればよろしいでしょうか？

はい。お手数をおかけしますが、おねがいいたします m(_ _)m

**Comment by yada-ITA** [comment]
先程、メールをお送りしました！
よろしくお願い致します。

また不足情報等ありましたらご連絡をお願いします。

**Comment by snoozer05** [comment]
すべての請求書を作成して郵送手続を行いました。
週明けには届くかと思いますので、ご確認の程どうぞよろしくお願いいたします。
何かありましたらご連絡くださいませ

**Comment by yada-ITA** [comment]
ご対応ありがとうございます！ :smiley: 

請求書は週明けに確認したいと思います！

**Comment by yada-ITA** [comment]
取り急ぎの速報ですが、今日時点では、まだ弊社宛の請求書は届いていない模様です…。

ということで、届いたらこちらにご報告する、ということで、いったん今週中は様子を見てみますー。

**Comment by snoozer05** [comment]
`2014年11月10日 17時07分31秒  請求書が [発送] されました` となっております。住所も間違っていないと思いますので、もう少し待ってみていただけますでしょうか...

**Comment by yamadashizuka** [comment]
(@yada-ITA さんがRuby World Conferenceに出かけてしまったので、留守番中の@yamadashizuka ですー)
発送されたということで了解です！ ありがとうございますー。じーっと待っておきますです、じーっと……

**Comment by yamadashizuka** [comment]
留守番の @yamadashizuka です。
弊社宛のもの、届きましたっ！ ありがとうございました！

**Comment by yada-ITA** [comment]
ただいまRWC休憩はいりました〜

@yamadashizuka さん、連絡ありがとうございます！ :smile_cat: 
@snoozer05 さん、お手数おかけしました！ :smiley:

**Comment by springaki** [comment]
よかった  :star:

**Comment by takahashim** [comment]
遅くなりましてすみません、こちら全て入金確認いたしました！
