### ISSUE TITLE
松江Ruby会議06 へのご支援について

### ISSUE THREAD

**Issue by yoshiokaCB** [ruby-no-kai/official#170]
Matsue.rb の @yoshiokaCB と申します。
先日メーリングリストでご相談させていただきましたが、東京よりゲストを招いて講演をしてもらうことが正式に決定しました。
つきましては交通費と宿泊費のご支援をお願いいたします。
#### 費用詳細

交通費：￥30,980-
宿泊費：￥10,600-
合計：￥41,580-

何卒よろしくお願いいたします。

**Comment by yoshiokaCB** [comment]
関連して一点質問をさせてください。
宿泊場先、飛行機などをWebで予約したため、PDFで領収書をお渡しする形になるかと思います。
問題はないでしょうか？

**Comment by snoozer05** [comment]
@takahashim 上記問題ないでしょうか

**Comment by takahashim** [comment]
はい、PDFで問題ありません！

**Comment by yoshiokaCB** [comment]
早速のご返事ありがとうございます！
それでは上記内容で進めさせていただきます。
引き続きよろしくお願いいたします。

**Comment by yoshiokaCB** [comment]
おかげさまで先日無事に松江Ruby会議06を開催することができました。
ありがとうございます。
開催報告のレポートは後日お送りさせていただきます。

それで、請求書の処理をさせていただきたいと思いますが、請求書の添付と振込先はどのような連絡手段を用いてお送りしたらよいでしょうか？
よろしくお願い致します。

**Comment by takahashim** [comment]
開催おつかれさまでした！
PDFと振込先口座情報については info [at] ruby-no-kai.org 宛にお送り下さい。

**Comment by yoshiokaCB** [comment]
承知しました。
今日中に送らせていただきます。

**Comment by takahashim** [comment]
受け取りました！　先ほどお振込したのでご確認下さい。

**Comment by yoshiokaCB** [comment]
ありがとうございます。
昨日からバタバタしておりまだ確認出来ておりません。
明日中には確認したいと思います。
お待たせして申し訳ありませんが、もうしばらくお待ちください。

**Comment by takahashim** [comment]
@yoshiokaCB こちらの方は別に急ぎではないので年内でも年明けでも大丈夫です！　お手すきのときにどうぞ。

**Comment by yoshiokaCB** [comment]
@takahashim 
確認しました。ありがとうございました！

**Comment by takahashim** [comment]
こちらご確認ありがとうございました！
issueは閉じておきますね。
