### ISSUE TITLE
ruby-no-kai.orgのGitHub Pages対応

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#171]
これって今月中にやらないといけないんでしたっけ。
cf. https://github.com/blog/1917-github-pages-legacy-ip-deprecation

**Comment by takahashim** [comment]
再度アナウンスが来てたので。

DNSって @kakutani さんしか変更できないんでしょうか…。

**Comment by shyouhei** [comment]
これは困りましたね

**Comment by takahashim** [comment]
よく見たらruby-no-kai.orgの方はvalue-domainがname serverになってました！
というわけでこっちだけでも変更してみます。
rubyhiroba.orgの方はかくたにさんが持ってる模様。

**Comment by takahashim** [comment]
value-domainのruby-no-kai.orgの設定変更して反映待ちです。

**Comment by takahashim** [comment]
`dig ruby-no-kai.org` の結果が、

```
;; ANSWER SECTION:
ruby-no-kai.org.    1200    IN  A   192.30.252.153
ruby-no-kai.org.    1200    IN  A   192.30.252.154
```

になっているので、ruby-no-kai.orgの方は変更されたはず。

**Comment by hsbt** [comment]
:ok_woman: セフセフ...
