### ISSUE TITLE
 開発会議 DevelopersMeeting20141126Japan へのご支援について

### ISSUE THREAD

**Issue by ko1** [ruby-no-kai/official#172]
例のごとく、
https://bugs.ruby-lang.org/projects/ruby/wiki/DevelopersMeeting20141126Japan
にご支援いただけませんでしょうか。

**Comment by takahashim** [comment]
はい、問題ないです！
というか次の12/xxも問題ないですよ

**Comment by ko1** [comment]
ありがとうございます！
移行は、確認じゃ無くて、「これでお願いします」と ticket たてることにします！

**Comment by ko1** [comment]
というわけで、今回は 1,923円 でした。

**Comment by snoozer05** [comment]
@takahashim こちら処理済みでしょうか？

**Comment by takahashim** [comment]
@snoozer05 ここまでたまっているみたいです。
@ko1 今年に入ってDevelopersMeetingはまだ開催されてない＆予定もまだない、のでしょうか？

**Comment by ko1** [comment]
On 2015/03/17 14:43, Masayoshi Takahashi wrote:

> @ko1 https://github.com/ko1 今年に入ってDevelopersMeetingはまだ開催さ
> れてない＆予定もまだない、のでしょうか？

4月にやろうかと思っております。

## 

// SASADA Koichi at atdot dot net

**Comment by takahashim** [comment]
@ko1 了解です、ではこれまでの分（#159 と #166）をまとめて振り込んでおきます :bow:

**Comment by ko1** [comment]
On 2015/03/17 15:24, Masayoshi Takahashi wrote:

> @ko1 https://github.com/ko1 了解です、ではこれまでの分をまとめて振り込
> んでおきます :bow:

ありがとうございます。よろしくお願いします。

## 

// SASADA Koichi at atdot dot net

**Comment by takahashim** [comment]
@ko1 こちら計9,819円振り込みました！

**Comment by snoozer05** [comment]
@takahashim これはもう閉じても大丈夫なんでしたっけ？それとも領収証の受け渡しが必要でしょうか？

**Comment by snoozer05** [comment]
@takahashim pingしておきます...!!

**Comment by takahashim** [comment]
領収書もらいました！
