### ISSUE TITLE
RailsGirls Kyoto 2nd のスポンサー協賛金の請求

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#173]
RailsGirls Kyoto teamのAkiです。

皆様の協力のおかげでRailsGirls Kyoto 2ndを無事開催する事ができました。
ありがとうございます。

つきましてはスポンサー協賛金の請求作業をよろしくお願いします。
RailsGirlsKyoto 2nd パートナー様 請求先一覧は別途 info@ruby-no-kai.org に送付させていただきます。

**Comment by springaki** [comment]
請求先一覧 へのリンクを info@ruby-no-kai.org に送付させていただきました !!

**Comment by snoozer05** [comment]
すべての請求書について、郵送手続かんりょういたしました。
今週中にはそれぞれの企業様に届くかと思います。

**Comment by springaki** [comment]
素早い ! いつもありがとうございます :smiley_cat:

**Comment by hsbt** [comment]
:bow:

**Comment by springaki** [comment]
請求書送付先企業からのフィードバックです。

> 弊社経理上の処理ですが、寄付行為（消費税無）で対応したいので次回からご協力いただけませんでしょうか。

とのこと。
協賛金表示額 + 消費税での請求書になっているようです。これは慣習的にどちらが一般的なのかはわかりませんが、無税の額で請求するのは可能なのでしょうか。
今回は請求額どおりにお振込みいただけるとの事なので大丈夫なのですが、次回請求時に備えてみなさんのご意見など伺えれば幸いですー。

**Comment by takahashim** [comment]
フィードバックありがとうございます！

ええと、まず「寄付行為」（寄附行為）という用語は法律用語としてはふつうの寄付とは違う特殊な意味なので、要するに寄附金のことだと判断します。

寄附金については、消費税法基本通達第2節5－2－14では消費税の課税対象にならないことになっているのですが、一方で広告宣伝効果がある場合は「寄附金」ではなく「広告宣伝費」として扱うことになるようです。

例えば「基本的に表には法人名を出さないで、お金だけもらう」という扱いの場合は広告効果がないので、広告宣伝費ではなく寄附金として受け取るというのもありうると思いますが、全部がぜんぶそう扱うのも現実的ではない（広告宣伝効果を期待する法人が多そう）でしょうし、いちいち区別すると事務処理が面倒になりそうなのですが、どうするのがいいんでしょうね…。

（それと念のためですが、Rubyの会のような普通の一般社団法人（公益認定されていない一般社団法人）に対しては、企業が寄附しても所得控除の対象にはなりませんし、法人税の損金算入限度額も特に有利になりません。）

**Comment by springaki** [comment]
おぉ。なるほど。
実際に区別して発行するのは現実的じゃないなぁとは感じていたので、どうなるのが両者都合がいいんだろうとお伺いしてみました。(実際には今までの企業様からは何も言われていないわけで...)

実質は寄附金ではなく(企業が寄附しても所得控除の対象にはならないの意味で)、広告宣伝費の一貫としてお取り扱いいただくようにお願いしてみようかなと思います。

ありがとうございました !! :bow:

**Comment by snoozer05** [comment]
@takahashim 入金確認が終わりましたらここに追記をおねがいいたします :bow:

**Comment by snoozer05** [comment]
@takahashim 入金確認状況いかがでしょうか

**Comment by snoozer05** [comment]
@takahashim pingしておきます...!!

**Comment by takahashim** [comment]
遅くなってすみません、こちら入金完了しました！

**Comment by snoozer05** [comment]
確認ありがとうございました！
