### ISSUE TITLE
RailsGirls Shiojiri へのコーチ派遣の補助をおねがいしたい

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#174]
@kakutani @takahashim @snoozer05 @shyouhei 

http://railsgirls.com/shiojiri のオーガナイザーの方より、開催にあたって RailsGirls のコーチ経験者数名の派遣要請が RailsGirls のコミュニティへ届きました。

現在、有志がお手伝いに行くという意思表明をされていますが、このような開催地からの要請があった際に交通費の補助があると自助努力だけではなく、継続的な RailsGirls 開催が可能になると思います。

本来であれば、RailsGirls Japan(仮)でスポンサー費用のプール金や何かしらの資金集めで補助すべきと思いますが、まだ実体のない団体のため実現できません。そこで、「Rubyの利用者の支援」を目的としている、日本Rubyの会に「RailsGirls Shiojiri へのコーチ派遣の交通費補助」をお願いしたいです。

いかがでしょうか。

**Comment by takahashim** [comment]
@hsbt この件について、Rubyの会が補助するとか以前の話として、RailsGirlsのお金として預かっているものがまだRubyの会の口座にそれなりの金額分残っているわけですが、それを使ったりしますか？

あと、個人的な意見としては、Rubyの会が特定のRailsGirls 〇〇 NN(th)に対してお金を出すというのは、公平な是非の判断が難しそうなのであんまり良い形ではなさそうだなあと思っています。それよりは、RailsGirls Japan(仮)の発足支援的な形でまとめて支出して、あとは何にどう使うかはRailsGirls Japan(仮)の中で検討して適切に振り分けてもらう、というのが良いかなあと思いました（定期的に支援できるかどうかはまたちょっと微妙な感じではあります）。

**Comment by hsbt** [comment]
> Rubyの会が特定のRailsGirls 〇〇 NN(th)に対してお金を出すというのは、公平な是非の判断が難しそうなのであんまり良い形ではなさそうだなあ

はい、そう思います。

> RailsGirlsのお金として預かっているものがまだRubyの会の口座にそれなりの金額分残っているわけですが、それを使ったりしますか？

可能であれば、この方向で考えたいので、残額を個人的にご連絡していただくことは可能でしょうか? よろしくお願いします!

**Comment by takahashim** [comment]
去年のRubyの会の会計として〆た時点の計算を元にした情報を柴田さんにメールしておきましたー

**Comment by hsbt** [comment]
https://github.com/railsgirls-jp/railsgirls-jp.github.io/issues/118 で口座開設を進めているので、完了したら預り金を受け取って、残金とにらめっこしつつ、RailsGirls サイドで決める。

**Comment by publichtml** [comment]
@takahashim @hsbt 

RailsGirls預かり金の額についてですが、実は #164 のRailsGirlsTokyo 4th! の立替精算(14万4,135円)がまだ処理いただけておりません。今の残額は恐らくこれを含んだものになっているかと思います。

ただ、領収書が昨年9月に他の方にお預けした以降行方知れずになってしまっているかと思います…。
立て替えた本人的にはもう諦めてるので精算不能で決着しても構わないのですが、それでRubyの会の決算やRailsGirls口座への資金移動に際し何か不都合ありそうでしょうか＾＾；；；

**Comment by hsbt** [comment]
@publichtml がーん。この金額はさすがにちゃんとしないといけない気がします...

**Comment by hsbt** [comment]
資金移動あれこれは @hsbt 個人としてはちゃんとお支払いするという思いがあります。続きは https://github.com/ruby-no-kai/official/issues/164 で。

**Comment by publichtml** [comment]
ご面倒をおかけしてすみません…orz

**Comment by takahashim** [comment]
@publichtml う、支払い損ねているものがあったらごめんなさい。
ちなみに先日 @hsbt さんの方に伝えた金額はRubyの会の期末である昨年7月末時点のもので、それ以降の入出金は（ご指摘の分も）含まれてなかったりします。

**Comment by hsbt** [comment]
@takahashim はい! 先日頂戴したリストには Tokyo 4th, Kyoto 2nd は含まれていないことを確認しています。

**Comment by publichtml** [comment]
oh...7月時点の金額でお話してたのですね、失礼いたしましたm(_ _)m

**Comment by snoozer05** [comment]
@hsbt これはもう閉じてしまっても大丈夫でしょうか

**Comment by hsbt** [comment]
RailsGirls で巻き取ることにしたので大丈夫です!
