### ISSUE TITLE
神奈川Ruby会議01 へのご支援について

### ISSUE THREAD

**Issue by hamakn** [ruby-no-kai/official#175]
神奈川Ruby会議 http://regional.rubykaigi.org/kana01/ 会計の川口@hamaknと申します。
神奈川Ruby会議で遠方からお招きしたゲストスピーカーへの交通費と宿泊費のご支援をお願いいたします。

費用詳細

ゲスト1
交通費: ¥11,640-
宿泊費: ¥8,880-
ゲスト2
交通費: ¥29,380-
宿泊費: ¥5,600-

合計: ¥55,500-

また、領収書は上記のうち3件は原本、もう1件はPDFがあるのですが、
どのようにお送りすれば良いでしょうか。
郵送、スキャンして電子データを送信のどちらも可能なのでご指定ください。

以上よろしくお願いいたします。

**Comment by takahashim** [comment]
開催おつかれさまでした！

さて領収書ですが、紙のものは、

```
〒151-0066 東京都渋谷区西原2丁目33-6-104 一般社団法人日本Rubyの会　高橋
```

宛にお送りください。電子のものは `info [at] ruby-no-kai.org` 宛のメールに添付ください。

**Comment by hamakn** [comment]
対応ありがとうございます。

電子のものはたった今送信しました。
紙のものは明日送付したいと思います。

**Comment by takahashim** [comment]
PDFの方は受領しました！
来週振り込んでおきます。

**Comment by hamakn** [comment]
紙の方、明日（3days ago）送付、と書きながら、本日投函しました。
よろしくお願いいたします。

**Comment by takahashim** [comment]
領収書受領しました！
来週になってしまうかもしれませんが振り込んでおきます。少々お待ちください。

**Comment by na74** [comment]
2/4に振り込まれていました。確認が遅くなってすみません。
ご対応ありがとうございました。

**Comment by hamakn** [comment]
2/4に振り込まれていました。確認が遅くなってすみません。
ご対応ありがとうございました。

**Comment by takahashim** [comment]
@hamakn  そういえばこちらで報告してなくて失礼しました :bow:　こちらこそありがとうございました！

**Comment by snoozer05** [comment]
こちら閉じてしまいます〜
