### ISSUE TITLE
RailsGirls Shiojiri のスポンサー協賛金の請求

### ISSUE THREAD

**Issue by cobachie** [ruby-no-kai/official#176]
Rails Girls Shiojiri Teamの小林（cobachie)です。

みなさまにいろいろご協力 & ご助言いただいたおかげで、
はじめてのRails Girls Shiojiriを無事開催することができました。
本当にありがとうございました。

つきましては、パートナー様への請求処理をお願いいたします。
RailsGirlsShiojiri1st パートナー様 請求先一覧は、
別途 info@ruby-no-kai.org に送付させていただきましたので、
ご確認をお願いいたします。

**Comment by snoozer05** [comment]
承知いたしました！

**Comment by snoozer05** [comment]
請求書を作成し、それぞれ郵送手続をいたしました。
今週中にはパートナー様のところに届くと思います！

**Comment by cobachie** [comment]
早速のご対応、ありがとうございます！

**Comment by snoozer05** [comment]
@takahashim 入金確認が終わりましたらここに追記をおねがいいたします :bow:

**Comment by snoozer05** [comment]
@takahashim こちらも入金確認状況を教えていただけると助かります...!!

**Comment by snoozer05** [comment]
@takahashim pingしておきます...!!

**Comment by takahashim** [comment]
こちら先月終わり頃の状況ではまだ未入金のものが残ってました。
あとで今月分の確認もしてみます :bow:

**Comment by snoozer05** [comment]
お手数をおかけしますが、よろしくお願いします :bow:

**Comment by takahashim** [comment]
こちら入金確認できました！

**Comment by cobachie** [comment]
お忙しいところいろいろご対応いただきまして、ありがとうございました！:bow:

**Comment by hsbt** [comment]
@takahashim 

続きの依頼となりますが、RailsGirls Japan 口座への振込もお願いします :bow:

**Comment by takahashim** [comment]
@hsbt こちら承りました！

**Comment by takahashim** [comment]
こちら振り込みました :bow:

**Comment by hsbt** [comment]
振込確認しました! ありがとうございます。

**Comment by shyouhei** [comment]
これはおわり。
