### ISSUE TITLE
るびま合宿へのご支援のお願い

### ISSUE THREAD

**Issue by ko1** [ruby-no-kai/official#177]
Rubyist Magazine（るびま）は、今度50号を迎えます。
現在、るびまのシステムにはいくつか問題があり、これを集まって解決する合宿ができないか計画しています。

そのために、場所の用意、遠方から集まる交通費、食事代など、Ruby の会様のほうでご支援頂けると助かりますが、いかがでしょうか。具体的な計画はまだなのですが、何なら出来る、出来ない、この目的ならいくらまでなら出せる、などアドバイス頂ければ幸いです。

ご検討頂ければ幸いです。

**Comment by takahashim** [comment]
遅くなってすみません、資金的な面でも何かしら支援できると思います！　が、ちょっとまだざっくりしてるので何ともいえないかも。
人数は10〜20人くらいでしょうか。食事代くらいは大丈夫そうですが、それよりも遠方の人が多いと交通費が大きそうですかね。
それと場所について、どこか安い施設のあてはありますか？

**Comment by snoozer05** [comment]
@ko1こちら、このあとどのように進めたら良いですかねえ

**Comment by ko1** [comment]
@gunjisatoshi どないしませう。

**Comment by gunjisatoshi** [comment]
ありがとうございます！
まずはるびま編集者側でコスト等を詰めてみてから、あらためてご相談させていただきます！

**Comment by gunjisatoshi** [comment]
@takahashim https://github.com/rubima/rubima/issues/337 にて話をしたところ、合宿はやめて半日の会議になりそうです。日程は5/31、場所は丸の内です。

お昼ごはん代とお茶菓子代、交通費のご支援がいただけると嬉しいですが、金額的な上限とかありますでしょうか（参加表明はいただいていないので例えばの話ですが、関西とかハワイとかからの交通費は出ますかねえ）

**Comment by takahashim** [comment]
毎年ハワイからの交通費をと言われると微妙そうですが、長らく貢献されてる方なので1回くらいは来ていただいて（招待で）もいいんじゃないでしょうか :smiley: 
関西の方もるびま編集部的に来て欲しい方であれば問題ないかと。

**Comment by gunjisatoshi** [comment]
@takahashim ご回答ありがとうございます！
（まだ参加者が確定していないので、あらためてご相談させてください！）

**Comment by gunjisatoshi** [comment]
@takahasim 今のところ参加者は 4 ～ 5 人、ほとんど東京近郊、遠方（関西方面）からの参加者 1 名の可能性あり、といったところです。見込まれる金額としては、関西からだと新幹線代がかかるので往復で 3 万円弱、プラスして昼食人数分、お茶菓子代くらいでしょうか。

費用のご支援にあたりまして、注意点等（予算的な上限、交通費や昼食等どこまでご支援いただけるか、領収書の必要有無、領収書の宛名等）ございましたらご教授ください。

**Comment by takahashim** [comment]
予算的な上限は10万円/年くらいという感じなので、その人数なら普通に交通費＋昼食代は出せるかと。
領収書は交通費はあれば出して欲しい(MAY)でレシートでも可、宛名は一般社団法人日本Rubyの会にしていただければ。

**Comment by gunjisatoshi** [comment]
@takahashim ありがとうございます。予算＆宛名の件承知しました！

**Comment by ko1** [comment]
お弁当、レシートだけでも大丈夫でしょうか。
一部、お昼を買ってこられた方がおりまして、どうしようかと。

**Comment by takahashim** [comment]
@ko1 大丈夫です！

**Comment by ko1** [comment]
ありがとう御座います。

お弁当代
- お弁当代: 2,916 + 900 = 3816 円 (5 人)
- 飲物代: 521 円
- お茶菓子代: 1,125 円

合計: 5,462 円になりました。

あと、@SugHimsi san の交通費代が、領収書が無いとのことでした。
これはどうなんだろう。

**Comment by takahashim** [comment]
どうもおつかれさまでした！
交通費については明細が分かれば領収書なしでも構わないかと。
あと立替は @ko1 さんですか？

**Comment by SugHimsi** [comment]
お金については何もしないで帰りました。有意義な日を過ごしましたので何卒お気遣いなく。

**Comment by ko1** [comment]
> 合計: 5,462 円になりました。

については、笹田が立て替え、領収書・レシートを持っております。

**Comment by shyouhei** [comment]
next action
- ささださんから領収書をもらう。

**Comment by shyouhei** [comment]
動きなし

@ko1 領収書ください。

**Comment by ko1** [comment]
どうやって渡せばいいでしょう。
あと、これって振り込まれたんだっけ。

**Comment by takahashim** [comment]
@ko1  近々に会う機会があればそのタイミングで渡していただければいいんですが、なさそうだったら郵送していただいた方がよいかもです。
振込は今日しておきます！

**Comment by shyouhei** [comment]
@ko1 ご確認ください。大丈夫そうならcloseしてください。

**Comment by shyouhei** [comment]
@ko1 ご確認ください。大丈夫そうならcloseしてください。

**Comment by shyouhei** [comment]
@ko1 ご確認ください。大丈夫そうならcloseしてください。

**Comment by ko1** [comment]
確認が大変遅くなってすみません。
確認しました。

**Comment by takahashim** [comment]
確認ありがとうございました！
