### ISSUE TITLE
DevelopersMeeting20150408Japan ご支援のお願い

### ISSUE THREAD

**Issue by ko1** [ruby-no-kai/official#179]
https://github.com/ruby-no-kai/official/wiki/RubyDevelopersMeetingSupportGuideline
に基づいて、本日の会議についてもご支援頂きたく、よろしくお願いします。
https://bugs.ruby-lang.org/projects/ruby/wiki/DevelopersMeeting20150408Japan

**Comment by takahashim** [comment]
:+1: 了解です！

**Comment by ko1** [comment]
1,196 円でした。
笹田が領収書を持っております。

**Comment by takahashim** [comment]
こちらの領収書は明日回収予定です

**Comment by takahashim** [comment]
領収書受け取りました

**Comment by shyouhei** [comment]
振り込みがまだ(★next action)

**Comment by shyouhei** [comment]
振り込みがまだ(★next action)

**Comment by shyouhei** [comment]
振り込みがまだ(★next action)

**Comment by takahashim** [comment]
こちら #177 と合わせて振り込みました！

**Comment by shyouhei** [comment]
@ko1 ご確認ください。大丈夫そうならcloseしてください。

**Comment by shyouhei** [comment]
@ko1 ご確認ください。大丈夫そうならcloseしてください。

**Comment by ko1** [comment]
きっと大丈夫だと信じて閉じます。ありがとうございました。
