### ISSUE TITLE
RailsGirls Kyoto 3rd のスポンサー協賛金の請求

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#180]
RailsGirls Kyoto teamのAkiです。

皆様の協力のおかげでRailsGirls Kyoto 3rdを無事開催する事ができました。
ありがとうございます。

つきましてはスポンサー協賛金の請求作業をよろしくお願いします。
RailsGirlsKyoto 3rd パートナー様 請求先一覧は別途 info@ruby-no-kai.org に送付させていただきます。
- [x] 日本Rubyの会から請求書郵送していただく
- [x] 日本Rubyの会口座への入金を確認していただく

**Comment by takahashim** [comment]
こちらお返事遅くなってすみません、メールの方受領しております。請求作業は連休中に行っておきます :bow:

**Comment by springaki** [comment]
お手数お掛けしますが、よろしくお願いいたします :bow:

**Comment by snoozer05** [comment]
こちら、いただいた内容にしたがって請求書を作成しまして郵送手続を行いました。
遅くなってしまい申し訳ありませんでした... :bow:

**Comment by springaki** [comment]
ありがとうございます !! :smile:

**Comment by shyouhei** [comment]
@takahashim Rubyの会口座に入金されてくるのを確認する

**Comment by shyouhei** [comment]
まだ確認できてない

**Comment by shyouhei** [comment]
「入金は確認できてるはず」とのこと by @takahashim 

確認できてたらcloseしてください

**Comment by takahashim** [comment]
確認が遅くなりました、こちら振り込みを確認いたしました！

**Comment by springaki** [comment]
ありがとうございました !!

**Comment by hsbt** [comment]
@takahashim こちら、RailsGirls JP の口座への振り込みはどうしましょう?

他のイベント(Kobe, Tokyo)のぶんが集まった時点で行って頂いてもよいのですが、近々 Kyoto 4th が開催されるので、二回分貯めこむ前に移動していただけると、混乱しなくてよさそうかな～と思っています!

**Comment by takahashim** [comment]
@hsbt  確かにそうかも。では先にお振り込みしておきます！

**Comment by takahashim** [comment]
@hsbt こちら振り込みました！
