### ISSUE TITLE
RailsGirls等のイベント主催者間がリアルの場で情報共有できる機会を作りたい

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#181]
RailsGirlsなど、地域Ruby会議以外にもRubyに関連する各地域の活動があるので、そういった活動をされている主催者間で危機管理等の情報共有ができる機会を作るとよいのではないか。

**Comment by shyouhei** [comment]
next action:
- とりあえず @hsbt @emorima あたりと #asaskusarb で一回もんでみる by @kakutani さん
- RailsGrilsと地域Ruby会議 _以外_ をどこまで巻き込むかは要fix

**Comment by hsbt** [comment]
了解しました. よろしくお願いします。

**Comment by kakutani** [comment]
こちらこそよろしくお願いします！

**Comment by shyouhei** [comment]
- 話はした。
- next action:
  - 具体的にどうということは決まってない
  - けど、できるといいねというところまでは共有できている
  - 引き続き実現に向けてもむ

**Comment by emorima** [comment]
亀レスですみません。

了解しました。
現時点では、 @kakutani さん、 @hsbt さんと、asakusarb で都度ご相談させて頂いてます！

**Comment by shyouhei** [comment]
next action: 引き続き実現に向けてもむ

何か起きてから動き出すのでは遅いので、進めたい。

**Comment by hsbt** [comment]
問題意識をまだ共有できてない(と個人的には思っている)のですが、イベント主催者の大枠(RailsGirls, 地域 Ruby 会議のみ?)で、各々が持っているトラブル事例であるとか、事前・事後対応を話し合って、未来に向けてはいい感じにしていく、という取り組みであってますか?

**Comment by shyouhei** [comment]
まあ問題意識しかないというか、具体的な課題があるわけではないとのこと。

@kakutani @hsbt 二人で問題意識を共有していただければ。

**Comment by hsbt** [comment]
はいー、もうすこし詰めたいと思います。

**Comment by hsbt** [comment]
@kakutani と話したこと
- RailsGirls 関係者で集まって何かを話し合う、という機会がある分にはいいけど、集まって何を話そう、どういう形式にすると良いか、というところまでは詰め切れていない
- RailsGirls のイベントが変な感じで開催されたり、流れていく、というのは防ぎたい(商用利用など)
- @emorima を始めとする RailsGirls Japan メンバーがローカルオーガナイザーと話し合いの場を数回設けているので、その交通費などを支援していただけるのであればありがたい
  - 例: 塩尻に出向いて、イベントやコーチの説明、Kyoto の支援に準備で出向くなど

という感じです!

**Comment by kakutani** [comment]
まとめありがとうございます!

> 交通費などを支援していただけるのであればありがたい
> 例: 塩尻に出向いて、イベントやコーチの説明、Kyoto の支援に準備で出向くなど

それぞれの開催そのものについてはRGの開催協賛のおかねを充てていくのでいいんだけど、
そんなに潤沢な状況でもない。なので上記のような
「**これから** 開催しようとしている都市のオーガナイザーたちのサポート」を
日本Rubyの会でやれるといいかなあと思いました。

> RailsGirls のイベントが変な感じで開催されたり、流れていく、というのは防ぎたい(商用利用など)

ここらへんは、 @hsbt や @emorima といった手練や過去のオーガナイザー(けっこう人数はふえてきた!)がパトロールして、声かけをしていくっていうので地道にやってくしかないよねえ、という話になりました。それでも事故はやってくるかもしれないけれど、railsgirls.jpっぽい人たちの間ではこのあたりの問題意識の認識はそろってると思います。

**Comment by kakutani** [comment]
RubyWorld Conf 2015の1Fおまえらスペースで @springaki ともちょっと話はできたし、何か起きそうになったらお互い連絡相談はできるふんいきは醸成されてきたかなーと思うので、一旦閉じます。

今後なんか具体的な話がでたら、またissueを立てます。
交通費の支援については、別途理事ミーティングで相談します!

**Comment by kakutani** [comment]
開催の事前のご説明交通費支援は、つぎの機会があったら一度支援をやってみましょう、という話になりました! > @hsbt

**Comment by hsbt** [comment]
了解しましたー、 RailsGirls オーガナイザーズで共有します。

**Comment by springaki** [comment]
またなにかありそうなら情報連携しましょう〜。 今後ともよろしくお願いします !
