### ISSUE TITLE
rubykaigi.infoを更新する

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#183]
7月に切れるので、その前に。

**Comment by takahashim** [comment]
1年延長しました。

**Comment by takahashim** [comment]
1年たったので。
あと、http://tokyo10.rubykaigi.info が死んでるようです。直さないと。

**Comment by shyouhei** [comment]
現状: 
- ドメインが切れそう
- tokyo10の向先があやしい

**Comment by shyouhei** [comment]
next action:
- ドメイン更新する
- tokyo10がどこに収容されているか確認して対応

**Comment by takahashim** [comment]
1年延長しました 💵

**Comment by takahashim** [comment]
tokyo10の件は #227 で対応することにして、こちらは閉じておきます。

**Comment by takahashim** [comment]
と思ったら入金しただけで更新されてなかった…。
