### ISSUE TITLE
esa代金を払う

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#184]
esaを使うことにしたので、とりあえずesa代を払わないと。

とりあえず @bash0C7 さんのところに請求行ってる可能性? まきとるなどする。

**Comment by kakutani** [comment]
ラップトップが無かったので自信がなかったのですが、戻って確認してみたら
https://rubykaigi.esa.io/ は私がスクワッティングしてました。/cc @amatsuda

たぶん前のrubykaigiのときにesaのことを教えてもらって作るだけ作ったのかも…

> Status Code:402 Payment Required

となってますが、メンバーは私だけだったなので課金額は1,000JPY。

**Comment by amatsuda** [comment]
おお。なるほど！

**Comment by amatsuda** [comment]
> おー、やったーー！！ありがとうございます！rubykaigi .esa.io は請求期間を過ぎてしまって今利用停止状態になってしまってるんですが、rubykaigi 使っていただけるなら無償提供しようと思ってたので、請求情報をリセットして使えるようにしてみますー！

トノコト。

**Comment by amatsuda** [comment]
「ロハで使えないものか」とかこっちからは(まだ)ひとことも言ってないですよ？

**Comment by kakutani** [comment]
おー、すごい。運用をはじめるにあたってなんか操作しないといけないことがあればご指示くださいませ /cc @bash0C7

**Comment by amatsuda** [comment]
> 使えるようになったと思いますのでご確認ください。ひとまず、チームの凍結をリセットして、2020-02-29まで無料期間 という感じにしてあります！

**Comment by kakutani** [comment]
続きは rubykaigi の運営のほうでやればよさそう。

**Comment by bash0C7** [comment]
> 運用をはじめるにあたってなんか操作しないといけないことがあればご指示くださいませ 

はい、おまちください！ (( ⁰⊖⁰)/)
まとめます
