### ISSUE TITLE
herokuからの課金に備える

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#185]
必要なものは課金上等だと思うので、そうしたアプリのownerをRubyの会としてまとめるのがいいかな、と思ってます。
- [x] info at ruby-no-kai dot org のアドレスでherokuのアカウントを作りました(info アカウント)。
- [x] Rubyの会で面倒をみるアプリに info アカウントをcollaboratorとして追加しました。
- [x] Rubyの会で面倒をみるアプリのownerをinfoアカウントへtransferする
- [x] infoアカウントにクレジットカード情報を登録する

**Comment by kakutani** [comment]
> Rubyの会で面倒をみるアプリに info アカウントをcollaboratorとして追加しました。

kakutaniのherokuダッシュボードを見て、それっぽいのを追加した。漏れが無いかが少し心配。

**Comment by shyouhei** [comment]
- どこまでherokuでやるの
- 「高いのでherokuやめるか」みたいな話になりそうな状況がきてからおもむろに相談すればいいのでは
- sqale とか?

**Comment by shyouhei** [comment]
- cfpappはよせてある
- egoidoを寄せるかは要相談 ( @darashi 個人的にはどうしてます?)

---
- るびまはsqualeなので関係ない
- rubykaigiは
  - 去年のはgithub pages
  - 一昨年以降はHerokuかも? -> rko_routerでわかる
    - https://github.com/ruby-no-kai/rko-router/blob/master/config/nginx.conf.erb#L180-L190
    - でも課金するほどだろうか?

**Comment by darashi** [comment]
> egoidoを寄せるかは要相談 ( @darashi 個人的にはどうしてます?)

個人的には、 Heroku でそのまま有料プランにするか、別の用途で使っている VPS に相乗りにするか、どっちかにしようかなーと思っているところです。

> 去年のはgithub pages

去年のも heroku です。

**Comment by kakutani** [comment]
@darashi ありがとうございます! 過去のrk.orgはHobbyでもいいかなー。rubykaigi用のegoidoは課金を辞さない構えでいってみようと思います!

**Comment by darashi** [comment]
まとめると以下のとおりです:

| Year | Placement |
| --- | --- |
| http://rubykaigi.org/2006 | jp.rubyist.net (redirect by linode) |
| http://rubykaigi.org/2007 | jp.rubyist.net (redirect by linode) |
| http://rubykaigi.org/2008 | jp.rubyist.net (redirect by linode) |
| http://rubykaigi.org/2009 | linode |
| http://rubykaigi.org/2010 | linode |
| http://rubykaigi.org/2011 | linode |
| http://rubykaigi.org/2012 | N/A but "404" page served by linode |
| http://rubykaigi.org/2013 | heroku |
| http://rubykaigi.org/2014 | heroku |
| http://rubykaigi.org/2015 | heroku |

**Comment by shyouhei** [comment]
rko/2013 が「Your Heroku app rubykaigi2013 on free dynos needs to recharge」だったので @kakutani さんにrechargeしてもらった事件があった。

でもrko/2013に関してはtransfarは終わってそう。

しばらくはメールが来たら反応する運用でよいのではないか

**Comment by shyouhei** [comment]
とりあえずはメールがきたらrechargeであまり困ってない。このままかな?

**Comment by shyouhei** [comment]
@kakutani さんの立替精算という運用になった。
