### ISSUE TITLE
るびま 50 号プレゼント企画の送料を支援していただきたい

### ISSUE THREAD

**Issue by takkanm** [ruby-no-kai/official#186]
残作業を記録します -- kakutani
- [x] 振り込めシートに記録(@kakutani)
- [x] 領収書を @takahashim にわたす(@kakutani)
- [x] ふりこみ(@takahashim)

以下、originalのdesc:

---

るびまのほうから来ました。

50 号で EffectiveRuby を 3 冊プレゼントする企画があり、
その発送をわたし (takkanm) が担当することになっております。

レターパックにて送付予定で、最大で 1530 円かかる見込みです。
こちらの料金を日本 Ruby の会で支援していただくことはできますでしょうか ?

**Comment by takahashim** [comment]
はい、問題ないです！

**Comment by takkanm** [comment]
ありがとうございます !!
発送後、領収書をどなたかにお渡しでよいでしょうか ?

**Comment by takahashim** [comment]
@takkanm はい、そんな感じでお願いします

**Comment by takkanm** [comment]
金額は 1,080 円でした。

本日、@kakutani さんに領収書を渡し、清算していただきました。

**Comment by shyouhei** [comment]
振り込んでいるはずとのことです。 @kakutani ご確認ください
