### ISSUE TITLE
関西Ruby会議06 の協賛金のために銀行口座を利用させていただきたい

### ISSUE THREAD

**Issue by cuzic** [ruby-no-kai/official#187]
Ruby 関西の cuzic です。

関西Ruby会議06 でスポンサーを募っています。
スポンサーで手を挙げてくれる会社があるのですが、
協賛金を受け取るときの事務手続きの関係で
銀行口座がないと難しそうです。

一旦、日本Rubyの会の銀行口座に振り込んでいただく
形で協賛金を受け取りたいのですが、可能でしょうか？

ご検討よろしくお願いいたします。

**Comment by kakutani** [comment]
> 一旦、日本Rubyの会の銀行口座に振り込んでいただく
> 形で協賛金を受け取りたいのですが、可能でしょうか？

はい、可能です。

受発注や請求は関西Ruby会議06の運営チームにお任せでよいのでしょうか。
それとも日本Rubyの会側でおこなうほうがよいでしょうか。

**Comment by cuzic** [comment]
受発注や請求についても、日本 Ruby の会にお願いしたいと考えております。

お手間とらせてすいませんが、よろしくお願いいたします。

具体的な進め方、手順など教えてください。

**Comment by kakutani** [comment]
> 受発注や請求についても、日本 Ruby の会にお願いしたいと考えております。

なるほどー。先方の担当者をはじめ、詳細な情報のやりとりも発生するので、
現在状況を info at ruby-no-kai dot org 宛にメールで教えていただけますでしょうか。
- 何社あって、
- 先方の担当はどなたで、
- 状況はどこまで進行していて、
- 関西Ruby会議06の運営チームのどこ宛にやりとりを同報すればいいのか

とかそんな感じで。
定型のフォーマットみたいなのが用意できてなくて申し訳ないです。

**Comment by shyouhei** [comment]
これまで
- 請求書発行済。

next action
- 入金を待つ
- 関西Ruby会議の人たちにお金を渡す

**Comment by shyouhei** [comment]
上記の通りでまだ入金待ちです。

**Comment by takahashim** [comment]
こちらほぼ確認できたのですが、一件微妙なのがあったので一応ちゃんと確認しておきます…。
あと関西Ruby会議の口座も教えてもらったので、こちらも後ほど振り込みます。

**Comment by takahashim** [comment]
こちら入金を確認して、こちらからの入金も済ませました！

**Comment by shyouhei** [comment]
おわったはず
@cuzic ご確認ください。問題なければcloseしてください。

**Comment by shyouhei** [comment]
消費税分の請求額の差分について質問があったので、それは返事がしてあります

**Comment by cuzic** [comment]
すばやい ご対応ありがとうございましたっ！
