### ISSUE TITLE
www.ruby-lang.org をどうにかしないといけない(どうしよう……)

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#19]
問題がcomplexなので一撃でどうにかなる、ってものでもないんだけど、まずは課題の共有から。
- Ruby 2.0 リリースに向けてなんとかしたいね (1.9.3リリースお祝いの会での話題)
-  2011.08のPeter Cooper 提案ってどうなったんだっけ…… http://www.rubyinside.com/official-ruby-site-not-so-good-5248.html
- サイト運営について、なにがどうなってるのかよく見えない……vit-core さん……どうなってるんや……
- (英語で乗り込んでいってまとめていかないといけないから大変かもね)
- 現状のRubyアソシエーションでなんとかするにはちょっと問題の粒度が大きすぎる ( RWC2011での会談)
  - かといって日本Rubyの会も丸ごと受けることはできないんだけど……
- リリースのタイミングと、サイトの更新の同期がとれてなくてめんどい (1.9.3リリースお祝いの会での話題)
- 日本語より英語のほうが情報が充実していて哀しい( @takahashim がn年前に言ってた)

(別件だけど、redmine.ruby-lang.org は Asakusa.rb が面倒をみるということになっている)

**Comment by takahashim** [comment]
以前話題になってたリニューアル案は↓これでしたっけ？
https://github.com/postmodern/www.ruby-lang.org

**Comment by snoozer05** [comment]
この issue はどうしましょう。
@hsbt さんは Rubyの会とは関係なく動いてくれているように見えているので、どう置いておくのかが気になりました。
今後は @hsbt さんから、アクションするためにこんな支援をしてもらえると嬉しいんだけどみたいな相談ベースで issue を切っていくとかでも良いのですかねぃ

**Comment by hsbt** [comment]
"a year ago": hi

スネークしたところ、 ruby/www-ruby-lang.org で vit-core チームが作業中です。彼らの方でまだ残っている作業(リンク漏れとか諸々)をせっせとこなしている途中です。こちら(というか @hsbt) のボールとしては、neon.ruby-lang.org を @shugo さんから使って良いよと言われたので neon の上で vit-core の作業したものを見えるようにしようという状態。

残っている問題
- ステージングというかプレビューどうするんの
- デプロイ戦略(github から持って来て～)
- github pages の方が楽でいいんじゃね?
- 本格移行いつやんの

というところです。

**Comment by kakutani** [comment]
このissue、@hsbt のスネーク報告スレとして活用してもらってよいのでしょうか? (報告ありがたし)

**Comment by kakutani** [comment]
https://github.com/ruby/www.ruby-lang.org/issues をみんな☆つけて応援しよう!
