### ISSUE TITLE
RailsGirls Osaka 2nd の清算について

### ISSUE THREAD

**Issue by satomicchy** [ruby-no-kai/official#190]
RailsGirls Osaka 2ndのつじたです。
おかげさまで、RailsGirls Osaka 2ndを無事開催することができました。
ありがとうございました。

スポンサー様請求先一覧と立て替え分の領収書をスキャンしたものを、 info@ruby-no-kai.org へ送付いたします。
いつもお手数をおかけしますが、ご確認の上、ご請求とお振込のほど、よろしくお願いいたします。

**Comment by snoozer05** [comment]
おつかれさまです！

メール間違いなく受領いたしました。
請求手続など順次処理して参りますので、お待ちくださいませ。
どうぞよろしくお願いします。

**Comment by hsbt** [comment]
@satomicchy 

Ruby の会がスポンサーに請求 -> Ruby の会が RailsGirls JP 口座に請求して集まったスポンサー代金を振込 -> RailsGirls JP が立替金を立替した人に振込

という流れで事務処理したいと思いますので、 @hsbt と @springaki さんにも明細のメールの転送を転送をお願いします :bow:

**Comment by kakutani** [comment]
精算用に使うメーリングリストは別のを用意したほうがスムーズっぽい感じですね。
railsgirls.jpにそれっぽいのを作って、ruby-no-kai の理事がjoinするのが情報共有は楽かなあ。WDYT?

**Comment by hsbt** [comment]
> 精算用に使うメーリングリストは別のを用意したほうがスムーズっぽい感じですね。

良さそう感あります!

**Comment by snoozer05** [comment]
GitHub 様以外については請求書の発行/送付手続を完了いたしました。

@takahashim GitHub 様への請求ならびに立て替え精算業については、ご対応をお願いできますでしょうか :bow:

**Comment by satomicchy** [comment]
みなさまありがとうございます！
清算用ML、Fukuoka#1には間に合いそうですか？
どなたがどうつながってるかわからないので、来週のMTGでそれとなくフォローしておきます。

@hsbt さん
お返事遅くなってすみません。 @springaki さんのメルアドはわかるのですが、@hsbt さんのメルアドがわからないので、FBかtwitterか何かで教えていただけないでしょうか。よろしくお願いいたします。

**Comment by hsbt** [comment]
@satomicchy shibata.hiroshi@gmail.com でお願いします!

ML は今週準備します!

**Comment by satomicchy** [comment]
@hsbt ありがとうございます！

**Comment by kakutani** [comment]
リストのメンテの手間を思うと:

> Ruby の会がスポンサーに請求 -> Ruby の会が RailsGirls JP 口座に請求して集まったスポンサー代金を振込 -> RailsGirls JP が立替金を立替した人に振込
- RailsGirls JPの口座を見てるひとたち
- 日本Rubyの会の理事

のgroupをRails Gilrs groupのappに作って「誰でも投稿可」にする(仮に seisan@railsgirls.jp みたいなの)。

各開催の人たちは、請求作業などの依頼時には seisan@railsgirls.jp にメールする。
そのとき、開催準備用にMLなどを使っているのであればそこにもccする。

作業の進捗はGH issuesで管理する。

という感じでどうかなあと思いました。
(info@ruby-no-kai.org に投げてたメールの投げ先を変更するだけでよさそう)

**Comment by takahashim** [comment]
先ほどアルメディア・ネットワークさんの担当者の方から島田さん宛にお電話をいただいて、振込期日を教えてくれということでしたが、特に指定はないので御社の通常のフローでお振込くださいとお返事しておきました。とりいそぎ。

**Comment by hsbt** [comment]
@satomicchy 遅くなりましたが、 railsgirlsjp-invoice@googlegroups.com を作成していました! 福岡方面にも共有済みです。あと、メール添付の領収書も届いていました。こちらは報告となります!

この辺、誰もがMLに投げれば会計周りは安心できるという状態にしていこうと思うので、引き続きご意見などお待ちしています!

**Comment by satomicchy** [comment]
@hsbt ご連絡ありがとうございます！
柴田さんやAkiさんの手間が省けるように、会計に必要な項目の定形フォームやイベント主催側のチェックリストなどあればいいかもしれませんね。
こちらこそ、引きつづきよろしくお願いいたします。

**Comment by shyouhei** [comment]
それはそれとしてOsaka 2ndの精算状況
- Githubへの請求がまだ
- それ以外は請求済み、入金待ち

**Comment by hsbt** [comment]
github のは RailsGirls JP でスポンサードしてもらったのとは別件なのか同一なのかが気になります...

**Comment by satomicchy** [comment]
githubのCiaraさんとやり取りしたのは2015/6/11が最後で、スポンサード申し込みもRailsGirls Osakaという名目でした。その後こちらには特に連絡はありません。

**Comment by takahashim** [comment]
@hsbt @satomicchy 遅くなりましたがとりあえずメールを送ってみました。別件とごっちゃになってそうなときはご相談させてください…

**Comment by springaki** [comment]
@satomicchy さんに 立替えてもらっていた費用は 7/24 に @satomicchy さんからご連絡いただいた口座に振込済みです (RailsGirls JP プール金から立替)。
以上、連絡まで。

**Comment by shyouhei** [comment]
現状: 請求書はすべて発送済み。
- [ ] 入金を確認する必要がある( @takahashim :TODO:)

**Comment by takahashim** [comment]
7月末時点ではまだ未入金のものがありました。もうちょっとお待ちください :bow:

**Comment by satomicchy** [comment]
すみません、Yahoo!大阪支社から、Osaka#2の会場警備の請求書届いてないでしょうか？
7月中旬に手続きしたそうなんですが。。。

**Comment by takahashim** [comment]
@satomicchy う、なんか見たことあるような気もしますが、これってこちらで支払うものですか？

**Comment by satomicchy** [comment]
@takahashim はい、そうなんです、お支払いしていただくものなんです。精算報告でお伝えしてなくてすみません。
請求書が届いたら分かるかなと、無精してしまいました。。。

**Comment by hsbt** [comment]
いったん、 @springaki (と @hsbt) の方で支払いだけ済ませてしまった方が Yahoo! さんにご迷惑をおかけしない感じな気がしますが、どうでしょう?

**Comment by takahashim** [comment]
@hsbt 金額と振込先がわかるならそれでも構いませんです

**Comment by takahashim** [comment]
@hsbt @satomicchy あ、いや、領収書の束から発見できました！　領収書と間違えていたようです。どうもすみませんでした…。

（請求書関連はいま会計事務所さんのところに送付済みだったのでしたがこちらは手元にあったのでした）

前言撤回ですが私の方で明日振り込んでおきますね。

**Comment by hsbt** [comment]
:bow: 振り込みお願いします!

メモ: Osaka 2nd の入金時に振り込み分を差し引くのを忘れないこと

**Comment by takahashim** [comment]
@hsbt @satomicchy  先ほど振り込みました :bow:

**Comment by satomicchy** [comment]
@hsbt @takahashim ありがとうございます！
お手間をおかけしましたm(_ _)m

**Comment by takahashim** [comment]
@satomicchy いえいえ、申し訳ございませんでしたとお伝えいただければ…。

**Comment by shyouhei** [comment]
現状
- こちらから払うものに関しては払った
- 入金待ちに関しては未入金のものがある

next action
- 未入金のものにかんして、さすがにそろそろ先方に確認

**Comment by satomicchy** [comment]
ご心配をおかけします。m(_ _)m
メールかprivateの何かで連絡いただければフォローします。

**Comment by shyouhei** [comment]
githubから振り込まれたと思しきものが振り込まれていた。
あと入金が確認できてない企業がまだある。

next action: 先方に確認する。

**Comment by hsbt** [comment]
> githubから振り込まれたと思しきものが振り込まれていた。

:octocat:

**Comment by shyouhei** [comment]
現状: 入金の確認が残ってる。
next action: 確認が取れれば閉じて良い。

**Comment by hsbt** [comment]
@takahashim こちら、Yahoo!JP さんへの会場代を引いたスポンサー費用の預り金の移動をお願いできますでしょうか? 年明けでもいいので早い内に2015年までの分の会計を締めたいなあと思ってます。

**Comment by shyouhei** [comment]
現状: 入金の確認はできた
next action: RG口座に振り込む

**Comment by takahashim** [comment]
こちらお待たせしてしまっております…
misocaで請求したもの＋githubに請求したものーYahoo!JPに振り込んだ分、でいいですよね。

**Comment by shyouhei** [comment]
next action: 確定金額をメールする

**Comment by hsbt** [comment]
> misocaで請求したもの＋githubに請求したものーYahoo!JPに振り込んだ分

はい、僕もそのつもりです。よろしくお願いします :bow:

**Comment by shyouhei** [comment]
現状: 振り込んだはず
@hsbt ご確認ください。

**Comment by shyouhei** [comment]
おっと、確認済みとのこと。お騒がせしました。
