### ISSUE TITLE
休眠一般法人になっていたりしていないか

### ISSUE THREAD

**Issue by snoozer05** [ruby-no-kai/official#191]
LOCALの小岩さんからの情報共有で、最後の登記から５年を経過している一般社団法人又は一般財団法人は、「まだ事業を廃止していない」旨の届出又は登記（役員変更等の登記）の申請をしない限りみなし解散とみなされるので気をつけてください、というものがありました。
http://www.moj.go.jp/MINJI/minji06_00082.html

@takahashim こちらの対応、私たちの方って大丈夫そうでしょうか...??

**Comment by takahashim** [comment]
おお…知見だ。法人住民税払っててもNGなのか。
まあでもRubyの会は最後の登記（事務所移転）をしてからまだ5年たってないので大丈夫そうです！

**Comment by hsbt** [comment]
知見だ...

**Comment by snoozer05** [comment]
@takahashim よかったです！何か近づくとそれとないお知らせが登記先住所に送られてくるので、その際はご対応をよろしくお願いします！
