### ISSUE TITLE
RailsGirls メーリングリストへのお誘い

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#192]
https://github.com/ruby-no-kai/official/issues/190 で提案があった、RailsGirls イベントの会計回りのやりとりを RailsGirls 関係者(@hsbt と @springaki 、Rubyの会理事)とで行うためのメーリングリストを作りました。

railsgirlsjp-invoice@googlegroups.com

Ruby の会の追加対象のアドレスを教えてください :bow:

**Comment by kakutani** [comment]
info at ruby-no-kai dot org を追加していただければとおもいます!
(投稿が誰での可能、になっているのであればとう前提ですが…)

いかがでしょう。

**Comment by hsbt** [comment]
info at ruby-no-kai dot org を登録してみました!

**Comment by kakutani** [comment]
gmailからこんにちはメールを出してみました。届いてますかねえ @takahashim @snoozer05

**Comment by hsbt** [comment]
"グループをグループには登録できません" とのことです!

**Comment by kakutani** [comment]
@hsbt お手数をおかけします……
- snoozer05 at ruby-no-kai dot org
- takahashim at ruby-no-kai dot org
- kakutani at ruby-no-kai dot org

でお願いします!

**Comment by hsbt** [comment]
招待しました...!

**Comment by kakutani** [comment]
招待されました!

**Comment by hsbt** [comment]
それでは今後はこちらで請求情報をやりとりしたり、オーガナイザーから連絡を受け取るって感じにしていこうと思います!

**Comment by springaki** [comment]
:+1:
