### ISSUE TITLE
決算する 2014年度

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#193]
cf #182 

そろそろ向き合う

**Comment by shyouhei** [comment]
関係しそうなチケット
- #177 
- #188 
- #187 
- #186 
- #179 
- #157 
- #180
- #189 
- #178 
- #190

**Comment by shyouhei** [comment]
決算できるはずのタイミングではある

**Comment by shyouhei** [comment]
TODO
今年は消費税の申告が必要になったのが新しい
8月中に帳簿をまとめる必要がある

**Comment by shyouhei** [comment]
#146

**Comment by takahashim** [comment]
とりあえず帳簿はまとめて会計事務所さんに投げました…。

**Comment by takahashim** [comment]
決算出ました。いろいろあったけどちょっとだけ黒字、というところです。
