### ISSUE TITLE
松江Ruby会議07 へのご支援について

### ISSUE THREAD

**Issue by yoshiokaCB** [ruby-no-kai/official#194]
お世話になります。Matsue.rb の @yoshiokaCB と申します。
先日FBのグループでお話しましたが、松江Ruby会議07の詳細が決まってきました。
http://matsue.rubyist.net/matrk07/
（後日pullリクは送らせていただきます。）

そこで、遠方からお招きするゲストスピーカーへの交通費と宿泊費のご支援をお願いいたします。
まだ概算ですが、費用は大まかに以下の考えております。
#### 費用詳細

交通費：￥41,786-
宿泊費：￥11,016-（前乗りが必要なため2泊分計上）
合計：￥52,802-

詳細が決まり次第、随時ご相談させていただければと思います。
金額に問題等ありましたらご指摘いただけると幸いです。

何卒よろしくお願いいたします。

**Comment by takahashim** [comment]
@yoshiokaCB はい、問題ないかと思います！

**Comment by yoshiokaCB** [comment]
@takahashim さん
早速のお返事ありがとうございます。
それではこのまま、調整を進めたいと思います。また詳細が決まりましたらご相談させていただきます！

**Comment by yoshiokaCB** [comment]
金額が正式に決定しましたので、お知らせいたします。

```
交通費：42,000円
宿泊費：10,368円
合計：52,368円
```

そして、いよいよ今週末開催予定です！
終わりましたら、領収書をお送りしたいと思いますので、お手数ですが送り先をお教えください。
引き続きよろしくお願いいたします！！

**Comment by takahashim** [comment]
@yoshiokaCB 領収書の方は以下にお送りいただけるとありがたいです。

〒151-0066 東京都渋谷区西原2-33-6
一般社団法人日本Rubyの会　高橋征義

それでは開催頑張ってください！ :pray:

**Comment by shyouhei** [comment]
無事開催された。
領収書待ち。

**Comment by yoshiokaCB** [comment]
報告が遅くなって申し訳ありませんでした！
おかげさまで無事に「松江Ruby会議07」を開催することができました。

今週末に領収書を送る予定ですので、もう少しお待ちください。
送りましたらまたご連絡させていただきます！

**Comment by yoshiokaCB** [comment]
@takahashim さん
遅くなりましたが、昨日領収書をお送りしましたので、明日あたりにはそちらに届くかと思いますので、ご確認をお願いいたします。
また、振込先については書類を同封しておりますので、そちらをご確認いただければと思います。
よろしくお願いいたしますm(_ _)m

**Comment by takahashim** [comment]
送付ありがとうございます、こちら領収書が届いたので振り込みました！　ご確認ください。

**Comment by yoshiokaCB** [comment]
@takahashim さん
遅くなりましたが入金確認しました！
ありがとうございました！！

**Comment by takahashim** [comment]
@yoshiokaCB 確認ありがとうございます！
