### ISSUE TITLE
RailsGirls Fukuokaのスポンサー協賛金の請求をお願いします

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#196]
お世話になります。RailsGirls方面の Aki です。

RailsGirls Fukuoaka のスポンサー協賛金の請求をお願いします。
請求先一覧は railsgirlsjp-invoice@googlegroups.com 宛の  "subject:【rgfukuoka】会計報告" に添付されております。

よろしくお願いします :bow: 
- [x] 請求書郵送
- [x] 入金確認
- [x] RGへの入金

**Comment by snoozer05** [comment]
請求書発行は今晩対応いたしますね。お待ちいただいて申し訳ありません m(_ _)m

**Comment by snoozer05** [comment]
請求書郵送について対応いたしました。
@takahashim 入金確認をよろしくお願いいたします

**Comment by springaki** [comment]
@snoozer05 ありがとうございます !

**Comment by shyouhei** [comment]
入金待ちです

**Comment by shyouhei** [comment]
引き続き入金待ち

**Comment by shyouhei** [comment]
~~引き続き入金待ち~~

入金されていた。

next action: なし

**Comment by shyouhei** [comment]
next action: Rails Girlsに入金する。

**Comment by hsbt** [comment]
口座がかつかつになってきたので入金よろしくおねがいします...! :bow:

**Comment by springaki** [comment]
よろしくお願いします! :bow:

**Comment by takahashim** [comment]
@hsbt @springaki お待たせしてすみません、こちら12/1に振り込みます！ :bank:

**Comment by springaki** [comment]
@takahashim ありがとうございます !  :smile:

**Comment by takahashim** [comment]
@springaki @hsbt 先ほど振り込みました!

**Comment by springaki** [comment]
@takahashim ありがとうございます !! @hsbt に確認してもらいますー。(ネットバンクでは明細見られなかったので通帳記入で確認...)

**Comment by shyouhei** [comment]
@hsbt 確認したら閉じてくださいー

**Comment by hsbt** [comment]
通帳記入確認しました!(僕は閉じることができないようです!)

**Comment by springaki** [comment]
@hsbt ありがとうございます。閉じます。
