### ISSUE TITLE
RailsGirls Kobe 1stのスポンサー協賛金の請求をお願いします

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#198]
お世話になります。RailsGirls-jp の Aki です。

RailsGirls Kobe 1st のスポンサー協賛金の請求をお願いします。
請求先一覧は railsgirlsjp-invoice@googlegroups.com 宛の "subject: Rails Girls Kobe 1st 会計について" に添付されております。

1社のみ書面送付より先行してPDFを発行して欲しいとの依頼がありました。メール文中にも記載してありますが、対応可能でしょうか？

お手数おかけしますが、よろしくお願いします :bow:
- [x] スポンサー協賛各社への請求書郵送
- [x] 日本Rubyの会への入金確認
- [x] RailsGirls への入金

**Comment by takahashim** [comment]
@springaki お返事遅くなりました。請求の件やってみます。

**Comment by springaki** [comment]
@takahashim 急なお願いで申し訳ありません。よろしくお願いします !

**Comment by takahashim** [comment]
こちら一通り郵送いたしました！

**Comment by springaki** [comment]
ありがとうございます !

**Comment by shyouhei** [comment]
請求済み、入金待ち。

**Comment by shyouhei** [comment]
引き続き入金待ち。

**Comment by shyouhei** [comment]
現状: たしか入金が確認できているはず
next action: RGの口座に移動する

**Comment by takahashim** [comment]
こちら明日付けで振り込みました。

**Comment by springaki** [comment]
@takahashim ありがとうございます !

@hsbt 確認お願いします

**Comment by shyouhei** [comment]
柴田さん確認待ち
@hsbt 確認できたら閉じてください

**Comment by hsbt** [comment]
12/22 付けで振り込み確認しました!

(issue 閉じることができないので、railsgirls team など作成していただけたらもう少しハンドリングしやすくなりそうです)

**Comment by springaki** [comment]
@hsbt 確認ありがとうございます。
起票者なので閉じまーす
