### ISSUE TITLE
Rubyist Hotlinks テープ起こしのアウトソース費用ご支援のお願い

### ISSUE THREAD

**Issue by gunjisatoshi** [ruby-no-kai/official#199]
郡司＠るびま編集部です。

現在 Rubyist Hotlinks のテープ起こしを外部の業者等にアウトソースすることを考えております。 https://github.com/rubima/rubima/issues/349

つきましてはアウトソースの費用についてご支援いただけるかどうか、ご支援いただける場合は費用の上限などについてご教授いただきたく、よろしくお願いいたします。

**Comment by takahashim** [comment]
特に上限とかはないので（強いて言えばるびま全体で数万円/年くらいなら問題ないかと）、試しに1回やってみていただければと思います！　それで結果の品質も合わせて考えてみればいいんじゃないでしょうか。

**Comment by miyohide** [comment]
@takahashim  @gunjisatoshi 文字起こし担当の miyohide です。調整ありがとうございます。とりあえずやってみます。まずは見積りを取ってみます。回答が来るのが月曜日以降のようです。

業者については、 ITmedia さんの記事（ http://www.itmedia.co.jp/bizid/articles/1005/12/news027.html ）で評価が高かった東京反訳さん（ http://www.8089.co.jp/ ）を利用しようかと思います。

**Comment by kakutani** [comment]
今後につながる実験になるといいなとおもいます! 段取りよろしくおねがいします! @miyohide   :raised_hands:

**Comment by miyohide** [comment]
@takahashim @gunjisatoshi @kakutani 見積りを頂けました。31,298円（税込み）となります。納品予定日は本日発注で10/9（金）。一部、雑音が多いため、聞き取り不明点が複数箇所出るとのことでした。

特に問題なければ、発注をお願いしようと思っています。よろしいでしょうか？

**Comment by takahashim** [comment]
はい、お願いいたします！ :+1:

**Comment by miyohide** [comment]
@takahashim 早速のご連絡ありがとうございます。発注処理を済ませました。10/9（金）に完了予定とのことです。出来上がりましたらまたご連絡します。

**Comment by shyouhei** [comment]
next action: 費用についてどのように精算するかを決める。普通に請求書払いで処理できるならかなりありがたいが。。。？

**Comment by miyohide** [comment]
問い合わせてみました。

費用についてですが、納品後に請求書が郵送されるそうです。今のところ、私の住所に送付されることになります。
http://www.8089.co.jp/guide/howto#collapse5

請求書の宛名・宛先は変更可能とのことなので、都合がよいものをお知らせいただけますでしょうか？ >  @takahashim ？
http://www.8089.co.jp/faq/grant2

**Comment by takahashim** [comment]
@miyohide  請求書の送付先は、

〒151-0066 東京都渋谷区西原2-33-6-104
一般社団法人日本Rubyの会　高橋征義

宛にしていただければ！

**Comment by miyohide** [comment]
@takahashim ありがとうございます。早速依頼しました。

**Comment by miyohide** [comment]
東京反訳さんより文字起こしデータを頂きました。ちょっと見た感じ、再度聞き直して書き起こしが必要な部分はありますが、全部書き起こされていることから精神的にちょっと楽になりました。

@takahashim 請求書が近いうちに届くかと思います。お手数おかけしますが、ご対応よろしくお願いします。
@gunjisatoshi データをメールで送付させていただきました。ご確認をお願いします。

**Comment by takahashim** [comment]
@miyohide こちら請求書をいただいたので振り込んでおきました！

**Comment by miyohide** [comment]
@takahashim 振り込みありがとうございます。ご支援いただいたことから、一気に文字起こしが進みそうです。再度聞き直して清書する必要はあるものの、すでにできているものがあるというのはかなり心強いです。

詳細な結果報告はまたのちほど致します。

**Comment by shyouhei** [comment]
お金のやりとりは終わり。

next action: 実際の編集作業

**Comment by shyouhei** [comment]
費用周りは終わったので閉じる
