### ISSUE TITLE
今更だがRailsConfに取材に行く

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#201]
- [x] 実施する
- [ ] 精算する

**Comment by amatsuda** [comment]
毎年行ってますが何かお手伝いできますか？

**Comment by kakutani** [comment]
まさに、毎年参加されている松田さんの2次情報で暮らしているので、今さらだけどどんな感じなのか自分たちで見にいってみてもいいかなー。ほんと今さらだけど。という話をしていたのでした!

**Comment by shyouhei** [comment]
http://rubycentral.org/railsconf

> Next spring, join us in Kansas City, MO for RailsConf 2016 from May 4-6. We'll have more information available about the conference in the coming months!

**Comment by shyouhei** [comment]
- まあ行くのはいいのでは。
- next action: 飛行機をとったりする

**Comment by shyouhei** [comment]
2月くらい? に飛行機とる

**Comment by shyouhei** [comment]
現状:まだ買ってない
next actoin: @kakutani いそいで買う

**Comment by amatsuda** [comment]
ホントに行くんスか、これ？

今年はDHHも来ないし(内部情報)、例年に増してつまんなそうな予感でいっぱいなんで、無理してゴールデンウィーク中にカンザス・シティくんだりまで行かなくても良いと思いますよ……。
まぁ承知の上で、それでも何か収穫があると思われるのであればこれ以上は止めませんが。

**Comment by shyouhei** [comment]
現状:まだ買ってない
next actoin: クレカ待ち。

まあ行くことは行く。

**Comment by shyouhei** [comment]
現状: 買った。$900でした。
next action: 実施する。

**Comment by shyouhei** [comment]
現状: 開催された。
next action: 精算する

**Comment by shyouhei** [comment]
next action: 精算する

**Comment by shyouhei** [comment]
next action: 精算する

**Comment by shyouhei** [comment]
next action: 精算する

**Comment by takahashim** [comment]
next action: 精算の項目を特定する

**Comment by shyouhei** [comment]
現状: 金額はわかったが証憑がサルベージできてない
next action: 証憑を見つける。

**Comment by shyouhei** [comment]
現状: 金額はわかったが証憑がサルベージできてない
next action: 証憑を見つける。

**Comment by shyouhei** [comment]
これを取材した後どう生かすか? がopen problemかもしれない

**Comment by kakutani** [comment]
証憑一式を例のDropboxの receipts/2016/railsconf2016 っていうフォルダの下に置きました!
README.txtに合計金額も書いてあります。 @takahashim

**Comment by kakutani** [comment]
> これを取材した後どう生かすか? がopen problemかもしれない

#248 の参考になると思ってます!

**Comment by shyouhei** [comment]
現状: 振り込み済み。
next action: 角谷さんが確認したら閉じる

**Comment by kakutani** [comment]
確認したら気になった点があったので、info at ruby-no-kai.org にメールしましたー。

**Comment by kakutani** [comment]
確認とれましたっ。

**Comment by takahashim** [comment]
どうもお手数おかけしました…！
