### ISSUE TITLE
もう10月ですが2015年ですね。

### ISSUE THREAD

**Issue by amatsuda** [ruby-no-kai/official#202]
<img width="1155" alt="ruby-no-kai_2014" src="https://cloud.githubusercontent.com/assets/11493/10201700/4a2bf210-67e8-11e5-877b-f068fddae786.png">

動的に表示を変えてるのかと思いきや半自動だったようで。一度サイトを出し直したほうが良いかもです。

**Comment by kakutani** [comment]
ご指摘ありがとうございます! 出しなおしてみました。
空コミットを`gh-pages`にpushしてみたんですが、他にいい方法あるのかな…。

**Comment by shyouhei** [comment]
@amatsuda 確認できたら閉じちゃってください(今見る感じだと平気層だけど)

**Comment by amatsuda** [comment]
:ok_hand:
