### ISSUE TITLE
RailsGirls Tokyo 5th のスポンサー費用の請求

### ISSUE THREAD

**Issue by youchan** [ruby-no-kai/official#203]
遅くなってしまってもうしわけありません。

スポンサーの請求先の情報などまとめましたので、別途メールいたします。

よろしくおねがいします。
- [x] 請求書送付
- [x] 入金確認
- [x] RG口座に移動

**Comment by takahashim** [comment]
@youchan 先日メールした原本送付不要のスポンサーさんに対する対応ですが、どうすればよいですか？

**Comment by takahashim** [comment]
あっと、書き忘れましたが要原本送付なスポンサーさんにはすでに送付しております。

**Comment by youchan** [comment]
#168 にあるように
原本送付不要のスポンサーさんの場合はメールで振込先を送るという対応でよいと思います。

**Comment by takahashim** [comment]
お、前回がそういうフローだったんですね。気づかなくて失礼しました。
では後ほどメールしておきます！

**Comment by youchan** [comment]
こちらこそ返事おそくなってすいませんでした。

**Comment by shyouhei** [comment]
next action: 請求する。

**Comment by hsbt** [comment]
こちら、到着をお待ちしています!!1

**Comment by hsbt** [comment]
@takahashim 
https://github.com/ruby-no-kai/official/issues/203#issuecomment-146075152 によると発送済みとのことですが、「GMOペパボ」に発送済みか確認していただいてよいでしょうか...

**Comment by takahashim** [comment]
@hsbt すみません、確認しておきます…

**Comment by takahashim** [comment]
@hsbt @youchan すみません、こちらてっきりお送りしていたつもりだったのですが、確認した所請求書を作成したところで止まっていて発送になっていませんでした。申し訳ないです。

**Comment by takahashim** [comment]
郵送処理のものについては、18日に処理が受理され、20日の夕方に発送されたとのことでした。
おそらく週明けに到着すると思うので、今しばらくお待ち下さい :bow:

**Comment by hsbt** [comment]
到着して社内の支払い稟議を進めています!

**Comment by shyouhei** [comment]
現状: 請求済み、入金待ち
next action: 入金確認とRG口座に移動

**Comment by takahashim** [comment]
@hsbt こちらですが、とりいそぎRG口座の方に移動しました。ご確認ください

**Comment by shyouhei** [comment]
現状: まだ入金待ちだがそろそろ来ててもいい頃
next action: 確認する

**Comment by youchan** [comment]
> 表題の件について、ご請求書を手配いただくにあたり宛先と送付先のご連絡が済んでいなかったようです。
> 申し訳ございません。
> 日が経ってしまいましたが、昨年9月のPayPal様協賛につき下記にて請求書をご手配いただきたく、宜しくお願いいたします。
> PDFの添付でも結構です。
> 
> ・請求先を弊社（株式会社シーキューブ・プランニング）でお願いいたします。
> ・請求項目はイベント名とPayPal協賛費と明記ください。
> ・協賛費は2万(税別)と伺っていますが間違いありませんでしょうか？
> ・郵送いただく場合は、下記にてお願いいたします。
> 150-0013
> 渋谷区恵比寿1-21-8　セラ51ビル　8階
> 株式会社シーキューブ・プランニング
> 03-6409-6581

という連絡が来ています。
PayPalの請求は株式会社シーキューブ・プランニングにおねがいします。というのを言われていたのですが、それをこちらに伝えわすれてしまったようです。
お願いできますでしょうか。

**Comment by youchan** [comment]
↑ @takahashim @hsbt よろしくおねがいします。

**Comment by hsbt** [comment]
これは @kakutani のちからも借りないとダメかもですね...お願いします!

**Comment by takahashim** [comment]
@youchan @hsbt む、こちら確認しておきます

**Comment by hsbt** [comment]
paypal さん以外の振り込み確認済みです

**Comment by youchan** [comment]
請求書をメールにて株式会社シーキューブ・プランニングに送付いたしました。

**Comment by takahashim** [comment]
@youchan メールも確認しました、ありがとうございます！

**Comment by shyouhei** [comment]
現状: シーキューブプランニングさんからの入金が確認できた
next action: RGの口座に移動する

**Comment by hsbt** [comment]
@takahashim お待ちしております :bow:

**Comment by takahashim** [comment]
@hsbt この件ですが、12/21に振り込んだもののような気がしてきたのですが、これ合ってますか？

**Comment by hsbt** [comment]
高橋さんにお会いした時に確認。もともと PayPal さんからのスポンサー資金は https://github.com/ruby-no-kai/official/issues/203#issuecomment-166273726 で事前に移動してもらう総額に含まれていたので、シーキューブプランニングさんから振り込まれた分は改めて RG の口座に振り込む必要はないことを確認しました。

@shyouhei @takahashim というわけで、東京 5th の会計は無事締まったのでクローズでお願いします。

**Comment by shyouhei** [comment]
無事しまっていた
