### ISSUE TITLE
Fwd: RubyKaigi 2015 チケット差額の返金について

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#206]
rubykaigiの話だけど、定例理事ミーティングというチェックポイントがあるのでこっちにもfileしときます:
- [x] infoに転送した口座への振り込み( @takahashim )
- [x] 先方へ連絡( @kakutani)

**Comment by takahashim** [comment]
こちら了解です！

**Comment by takahashim** [comment]
振り込みました！

**Comment by kakutani** [comment]
先方からackもらいました
