### ISSUE TITLE
CI のための mac mini ご支援について

### ISSUE THREAD

**Issue by ko1** [ruby-no-kai/official#207]
#150 の続きですが、OS X El Capitan‎ が出たので、CI に追加したいけど、

今動いている Yosemite も、しばらく続けたいので、新しく買って貰えないでしょうか。

柴田さんがセットアップ・管理
笹田が芝浦工大にまた持っていって設置

という流れを考えています。
ご検討頂ければ幸いです。
マシンの見積もり等は @hsbt にお任せ。
- [x] マシンを買う
- [x] 請求書が来る
- [x] 請求書に従って柴田さんに支払う
- [x] 安川さんに見積書を送付
- [x] 同請求書
- [x] 振り込まれてくるのを待つ

**Comment by takahashim** [comment]
@ko1 了解です。話を進めてみます。
時期としては年内くらいですか？　それとも今年のリリースが終わって年明けくらい？

**Comment by hsbt** [comment]
昨年のやつ: https://github.com/ruby-no-kai/official/issues/150#issuecomment-61947522 同じ構成で 130,800 円と円安辛い(去年は  114,000 円)

@takahashim El Capitan での動作検証が個人のマシンベースになっているので、 2.3.0 リリース前に用意できると嬉しい、という状況です。

**Comment by takahashim** [comment]
@hsbt 購入の流れは前回と同じく@hsbt さんで立替購入→領収書のコピーを送ってもらう→送金→あとで領収書の原本をいただく、で良いでしょうか？

**Comment by hsbt** [comment]
@takahashim はい! 問題ありません

**Comment by takahashim** [comment]
お待たせしてしまってすみません、こちら進めていただければ。
去年と同様の構成で130,800円でよいですか？

**Comment by hsbt** [comment]
はい、130800 円となります!

**Comment by takahashim** [comment]
了解です、それで購入の方を進めてください！

**Comment by hsbt** [comment]
消費税込みで 141,264 円でした... :bow:

**Comment by takahashim** [comment]
:ok_woman:

**Comment by hsbt** [comment]
11/24 に注文しました! 到着、セットアップ後にまた連絡します。

**Comment by hsbt** [comment]
11/29 に商品到着しました。これからセットアップを開始して12月中旬を目処に稼働予定です。請求書は別途発行しているので、どこかのタイミングでお渡しします!

**Comment by shyouhei** [comment]
現状: 柴田さん方面の請求書対応はおわり
next action: 安川さん方面にすすむ

**Comment by takahashim** [comment]
こちら請求完了しました
