### ISSUE TITLE
RailsGilrs Matsue 2ndの協賛費用の請求

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#209]
- [x] 請求する(@kakutani)
- [x] 16年1末の入金期日になってるので、入金確認(@takahashim)
- [x] RG口座にうつす(@takahashim)
- [ ] 移った金額の確認(@hsbt)

…で、閉じれるのかな

---

「(送付)RGM2nd スポンサーの請求一覧」っていうメールを @AyakoMakihara が railsgirlsjp-invoice at googlegroups.com に投稿してくれているので、請求する必要がある。
- 請求日: 11/14(土)
- 翌月末: 12/31(土)

**Comment by AyakoMakihara** [comment]
RGM2nd請求書発行のお手続き状況、いかがでしょうか？

**Comment by shyouhei** [comment]
おっと。
現状: 請求できてない
next action: 請求する

**Comment by kakutani** [comment]
やりますー。ちょっとお時間ください。

**Comment by kakutani** [comment]
12/7には請求できるように進めていくつもりでおります。
月が替わってしまったので(ｽﾐﾏｾﾝ...)、入金期日は1月末に設定しておこうと思います。

**Comment by AyakoMakihara** [comment]
お忙しい所、ありがとうございます！入金期日１末で、OKです。

**Comment by kakutani** [comment]
昨日、完了までやれませんでした…

**Comment by AyakoMakihara** [comment]
そうですか :crying_cat_face: 完了次第、ご連絡ください。スポンサー様へのお礼は終わっていますが、請求が遅くなりそうなら、再度連絡したいと思っています。

**Comment by AyakoMakihara** [comment]
@kakutani 状況いかがでしょうか？スポンサー企業様からクレームのメールが私宛に届いてます。どのように返答したらよろしいでしょうか。いつ頃に請求書発行予定でしょうか？

**Comment by AyakoMakihara** [comment]
スポンサー様へ請求書発送予定と振り込み期日の変更を連絡したいので、発送予定日（確定）を教えて下さい。よろしくお願いします。

**Comment by kakutani** [comment]
@AyakoMakihara 原本郵送不要の企業さんには12/21(月)に送付します。郵送希望の企業さんには25日(金)までには到着すると思います(連絡担当者さま宛にpdfは21日に送ります)。進捗ありしだいまた報告します。

申し訳ないです。

**Comment by AyakoMakihara** [comment]
@kakutani 上記期日で全スポンサー様へ連絡致します。入金期日１末でお願いします。

**Comment by kakutani** [comment]
- 原本不要の企業さま: PDFをメールで送信しました
- 原本郵送希望の企業さま: 郵送手続きをおこないました(& PDFでのメール送信もおこないました)

各社さまとも入金期日は2016/01/29を指定しています。
遅くなってしまって申し訳ありませんでした。

**Comment by AyakoMakihara** [comment]
ありがとうございます。安心致しました！

**Comment by shyouhei** [comment]
現状: 請求書発行済み、入金待ち
next action: 入金されてくるのを待つ

**Comment by takahashim** [comment]
こちら全件入金されていることを確認しました。

**Comment by shyouhei** [comment]
現状: RGの口座にうつした
next action: @hsbt 確認してくださいー

**Comment by AyakoMakihara** [comment]
入金のご連絡ありがとうございました :hamster: 安心しました。

**Comment by shyouhei** [comment]
現状: 確認待ち

**Comment by shyouhei** [comment]
確認されていた。
