### ISSUE TITLE
TokyuRuby 会議 10 の開催

### ISSUE THREAD

**Issue by yucao24hours** [ruby-no-kai/official#210]
こんにちは。Tokyu.rb の 加藤由佳 と申します。

第 10 回目となる TokyuRuby 会議の開催を
以下の要領にて計画しております。
日程のみ決まっており、役割等はこれから決める予定です。
おおよそこれまでの TokyuRuby 会議と同規模のものを予定していますが、
取り急ぎ日程を確保致したく、連絡させていただきます。

名称：TokyuRuby 会議 10
開催日：2016/05/29(日) 
会場：未定
参加費：未定
配信：なし
定員: 未定
実行委員長：加藤  由佳
実行副委員長：未定
実行委員：
　小川　伸一郎
　沢田　正
　五十嵐　邦明
　大場　光一郎
　小椋　隆史
　影山　勝彦
　三浦　美咲樹
　三浦　わか菜

**Comment by snoozer05** [comment]
連絡ありがとうございます！
https://github.com/ruby-no-kai/official/wiki/Upcomingregionalrubykaigi に記載しておきました！

**Comment by takahashim** [comment]
こちらも開催おつかれさまでした！

**Comment by shyouhei** [comment]
@yucao24hours これ残件何かありますでしょうか。なければ閉じていただけると。おつかれさまでした

**Comment by shyouhei** [comment]
@yucao24hours 閉じちゃいますねー
