### ISSUE TITLE
Rails Girls Kyoto 4thのスポンサー協賛金の請求をお願いします

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#211]
お世話になります。RailsGirls-JP の Aki です。

おかげ様で Rails Girls Kyoto 4th も無事開催できました。ご協力ありがとうございます。

今回もスポンサー協賛金の請求をお願いします。
請求先一覧は railsgirlsjp-invoice@googlegroups.com 宛の "subject: Rails Girls Kyoto 4th パートナー企業様請求のお願い" に添付されております (全部で 5社です)。

お手数おかけしますが、よろしくお願いします !
- [x] スポンサー協賛各社への請求書郵送・PDF送付
- [x] 日本Rubyの会への入金確認
- [x] 日本Rubyの会から RailsGirls-JP への入金

**Comment by shyouhei** [comment]
next action: 請求書送付

**Comment by springaki** [comment]
お忙しい中大変申し訳ありません。こちらもスポンサー様からいつ請求書がくるのか問い合わせがありました。請求書の発送はいつ頃になりそうでしょうか？

**Comment by shyouhei** [comment]
漏れてそう…

next action: 請求書送付する

**Comment by kakutani** [comment]
漏れてました。やります

**Comment by springaki** [comment]
お忙しい中大変申し訳ありません。
本日、スポンサー様から「RailsGirlsKyoto4thの請求書がまだ届かない。どうなっているのか。最悪 3月中には処理したいので早く送って欲しい」と言われました。

請求書発行はいつ頃になりそうでしょうか？

**Comment by takahashim** [comment]
@springaki うう、申し訳ないです。週末確認して、来週には出せるよう作業します

**Comment by springaki** [comment]
@takahashim 了解です。先方にはその旨(来週中にはと)伝えさせていただきますね。
申し訳ありませんが、よろしくお願いします。 :bow:

**Comment by takahashim** [comment]
（請求書が発行されていないのを確認、新しく請求書を4通起こしました。後で再度確認して、問題なければ送付します。）

**Comment by takahashim** [comment]
こちら郵送が必要ないものについてはメールで送付しました。郵送するものは明日発送される予定です。お待たせしてしまってすみませんでした。

**Comment by springaki** [comment]
とんでもありません ! お手数おかけして申し訳ありません。ありがとうございました !!

**Comment by springaki** [comment]
@takahashim 大変申し訳ありません。確認なのですが、請求書(紙・PDF合わせて)は5社に送っていただけましたでしょうか？最初に4社のシートをお送りして1社追加があったので訂正メールを送らせていただいたのですが、いかがでしょうか？ (全部で5社が正解です)

**Comment by takahashim** [comment]
なんと。上記のとおり4社ですね…

**Comment by takahashim** [comment]
確認します

**Comment by takahashim** [comment]
@springaki 確認しました。やはり一件漏れてました。申し訳ないです…。
残りの1件の方も発送処理します。

**Comment by takahashim** [comment]
こちら発送処理しました。

**Comment by springaki** [comment]
@takahashim おぉ...やはり :sweat_drops:  ありがとうございます !! :smile:

**Comment by shyouhei** [comment]
現状: 請求済み
nextaction: 入金待ち

**Comment by hsbt** [comment]
@takahashim 3/11 にご相談しましたが、京都の総額を Ruby の会から仮払いという形で RailsGirls の口座への移動をお願いします :bow:

**Comment by takahashim** [comment]
@hsbt お待たせしてすみません、こちら今週中にはお振り込みしておきます :bow:

**Comment by hsbt** [comment]
@takahashim RailsGirls 口座に振り込まれているのを確認しました!

**Comment by springaki** [comment]
@takahashim @hsbt ありがとうございます !!

**Comment by shyouhei** [comment]
現状: 終わっているもの
- 請求
- 仮払い金の振り込み

待っているもの
- 協賛企業からの振り込み

**Comment by shyouhei** [comment]
現状: 振込待ち
next action: 確認して終わり

**Comment by shyouhei** [comment]
現状: ゆめみ様からの振込みがまだ
next action: 振込待ち

**Comment by springaki** [comment]
この件、ゆめみさんに確認したところ、「Misocaからのメールを見落としていました。今見ようとしたら URL期限切れで内容を確認できないので、再発行お願いできませんか？」との事でした。
お手数おかけしますが、お願いできますでしょうか？

**Comment by takahashim** [comment]
@springaki こちら対応します。直接担当者の方に添付で送りますね。しばしお待ちを。

**Comment by springaki** [comment]
@takahashim ありがとうございます ! よろしくお願いします。

**Comment by takahashim** [comment]
@springaki こちらお送りしました！

**Comment by springaki** [comment]
@takahashim ありがとうございました 😊

**Comment by takahashim** [comment]
こちら振り込んでいただいた模様です。というわけで完了しました。
どうもありがとうございました。

**Comment by springaki** [comment]
みなさま、ありがとうございました ! 🎉
