### ISSUE TITLE
地域Ruby会議のShout issueをどのタイミングで閉じるべきか

### ISSUE THREAD

**Issue by snoozer05** [ruby-no-kai/official#212]

**Comment by snoozer05** [comment]
基本は開催が終わって事後処理とかも終わったら閉じることにしましょう。
というのをWikiに書いたら、このissueは閉じます。

**Comment by shyouhei** [comment]
next action: wiki書く

**Comment by shyouhei** [comment]
まだやってないのでwiki書く

**Comment by shyouhei** [comment]
まだやってないのでwiki書く

**Comment by shyouhei** [comment]
まだやってないのでwiki書く

**Comment by shyouhei** [comment]
まだやってないのでwiki書く

**Comment by shyouhei** [comment]
まだやってないのでwiki書く

**Comment by kakutani** [comment]
いまやったのでwikiに書いた!

https://github.com/ruby-no-kai/official/wiki/Regionalrubykaigi
