### ISSUE TITLE
RailsGirls オーガナイザー ランチミーティング＠RubyKaigi 2015 へのお弁当提供について

### ISSUE THREAD

**Issue by publichtml** [ruby-no-kai/official#213]
RubyKaigi 2015 Team かつRailsGirlsに以前絡んでいた小田切です。

RubyKaigi 2015 にてRailsGirls オーガナイザーのふりかえりを行おうという企画が上がっています。

しかし今年の会場には会議室的な場所を提供するゆとりがなく、お弁当を手配して発表を行うホールの片隅で昼休みにランチミーティングはどうかというプランが出ています。

つきましては、お弁当代をご支援いただきたいのですが、可能でしょうか？
個数は今わかっている時点で4人分(スタッフ弁当をもらえるKaigiスタッフとの重複抜いております)、どこまで行っても1桁に納まると思います。

なお、ご支援いただける場合は、RubyKaigiのスタッフ弁当の個数増加にて対応する予定です。
請求書はRubyKaigi 2015とRailsGirls分に分けて発行していただけるよう、業者に掛け合います。

**Comment by kakutani** [comment]
ふだんは全国に散り散りなorganizersが集まる機会はなかなかないので、支援したいです。

> 請求書はRubyKaigi 2015とRailsGirls分に分けて発行していただけるよう、業者に掛け合います。

ここはうまいこと分けてもらえるといいなと思います。

OT: そーいえば今年は地域Ruby会議会議はむつかしいかなあ。

**Comment by publichtml** [comment]
こちら、明後日12/9(水)のお昼には業者に追加をかけたいのですが、お弁当代ご支援の可否いかがでしょうか。
お弁当が必要な人数は4人のようなので、費用は五千円前後となりそうです。

( こういう件は @takahashim さん辺りお呼すればいいのでしょうか…^^;;;？

**Comment by takahashim** [comment]
@publichtml たぶん角谷さんは可否についてはOKな上で請求書について分けてほしい、というお返事をしたつもりではないかと…。

**Comment by publichtml** [comment]
お、そういうことでしたか、失礼しましたorz (援護射撃なのだと勘違いしてました＞＜)。

ありがとうございます、手配させていただきます！

**Comment by kakutani** [comment]
不明瞭な返信しちゃってすみませんでした…。手配よろしくお願いします！

**Comment by publichtml** [comment]
こちら手配いたしました！請求書も分けていただけるそうです。

お弁当4個、4,390円です。
請求書はRubyKaigiスタッフ弁当の請求書とともに、別の紙で日本Rubyの会の住所に郵送されます。
- お店: 駒春(くるめし弁当経由) http://www.kurumesi-bentou.com/komaharu/
- 請求書締め日: 12月末
- 振込期限: 2016/1/31(日)
- 金額: 4,390円

請求書届きましたら振込よろしくお願いしますm(_ _)m

**Comment by hsbt** [comment]
ご支援ありがとうございました。以下のように有意義な会議ができました。

https://gist.github.com/hsbt/20ef65d42d1874e892b9

**Comment by takahashim** [comment]
@hsbt それはよかったです！

**Comment by takahashim** [comment]
こちら請求書が届きましたので、明日振り込む予定です。

**Comment by takahashim** [comment]
駒春振り込みました

**Comment by publichtml** [comment]
ご支援ありがとうございます！

やるべきことは全て終わったようなのでクローズしてしまいます。
