### ISSUE TITLE
RubyKaigi下見第一回精算

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#215]
- [x] 下見実施
- 金額の確定
  - [x] 旅費 卜部立替え払い
  - [x] 宿泊費 松田さんが払った
  - [x] 会議費 角谷さんが払った
- 領収書を高橋さんに渡す
  - [x] @shyouhei
  - [x] @amatsuda
  - [x] @kakutani 
- [x] 振り込む

**Comment by takahashim** [comment]
（ちなみに会議費は「会議に際して社内又は通常会議を行う場所において通常供与される昼食の程度を超えない飲食物等の接待に要する費用」ということになってるそうで、その範囲を超えると交際費になります…）

**Comment by shyouhei** [comment]
現状:実施待ち

**Comment by shyouhei** [comment]
実施済みです

**Comment by shyouhei** [comment]
現状: @shyouhei @amatsuda に振込済
next action: @kakutani むけに振込む

**Comment by shyouhei** [comment]
next action: @kakutani むけに振込む

**Comment by shyouhei** [comment]
角谷さんの金額をサルベージする必要がある
next action: @kakutani 金額サルベージして振り込めに書く

**Comment by shyouhei** [comment]
現状: 角谷さんの金額をサルベージする必要がある
next action: @kakutani 金額サルベージして振り込めに書く

**Comment by shyouhei** [comment]
現状: 角谷さんの金額をサルベージする必要がある
next action: @kakutani 金額サルベージして振り込めに書く

**Comment by takahashim** [comment]
next action: 金額サルベージして振り込めに書く

**Comment by shyouhei** [comment]
next action: 金額サルベージして振り込めに書く

**Comment by shyouhei** [comment]
現状: 振り込めページが更新されそう
next action: 振り込む

**Comment by kakutani** [comment]
金額を書きましたっ

**Comment by takahashim** [comment]
@kakutani 振り込んでおきました！
