### ISSUE TITLE
弁護士さんに相談する

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#216]
そろそろ法務が発生するかもの雲行きなので、まずはご相談から

**Comment by shyouhei** [comment]
- 初回 3月7日 17:00- より
- 参加予定 @shyouhei @takahashim

**Comment by takahashim** [comment]
相談してきました。
- 景品表示法にはちゃんと向き合った方が良さそう（チケットの金額と配布物の金額をバランスさせなければならない）
- イベントに行動規範などを設けることは、要するに申し込みの際の契約事項の一種として扱うのが良さそう（できればチェックボックスとかを入れて明示的に合意の手続きを踏ませるとか、準拠法も触れておくとか）

**Comment by shyouhei** [comment]
当日メモです

景表法のやつ
- 景品にあたるかどうか、という点がある。景品だった場合：
- 価格規制がある
  - 取引価格に対する割合
  - 取扱い価格が千円未満の場合は200円
- 以前に問い合わせたとき、取引価格は一番安いものであるという回答が監督官庁からあったことがある。
- 景品に相当するのであれば総付け景品
- 「顧客を誘因する手段」かどうかはなんともいえない
  - だが感覚としては真っ白とは言いづらい
- スポンサーノベルティは営業の一環として、という整理になるのではないか、広告の扱い
- スポンサーのものはこちらは無関係だと主張できるように分かるようにしておいた方がいいか
- 4条違反だとちょく罰則ではなく官庁から指摘されるのがワンクッションある
- 監督官庁は消費者庁

行動規範の話
- 海外のものだからダメということはない
- 契約なのでお互いに合意してあればOK
- 返金しないことに関しても普通のサービスでもある話
- ただし消費者契約法というものがある
- 免責されるための規程はある
- やるのであれば申し込み時点で利用規約に合意させておくべき
- オプトイン方式のほうがおすすめ。
- 準拠法が日本法になっていることは要確認
- 行動規範というか著作権、知財の取扱いなどは明確にしておいたほうがいいかも

**Comment by shyouhei** [comment]
相談したので閉じる。
