### ISSUE TITLE
るびまサーバ更新

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#217]
cf. https://github.com/rubima/rubima/issues/392

**Comment by miyohide** [comment]
@takahashim 振込先、振込金額は以下になります。ご対応よろしくお願いします。

【Sqale】2016年04月01日～2017年03月31日　¥11,280
合計：11,280円

【お振込先】
三菱東京ＵＦＪ銀行( 0 0 0 5 ) 渋谷支店( 1 3 5 )
普通　3 5 0 1 6 1 1
カ）ペーパーボーイアンドコー

【ご入金締切日】2016年3月31日（木）

**Comment by takahashim** [comment]
@miyohide 対応ありがとうございます！！　振り込んでおきます。

**Comment by takahashim** [comment]
こちら振り込み済みです

**Comment by shyouhei** [comment]
振り込み済みなのでこちらは閉じる
