### ISSUE TITLE
linode撤退

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#218]
いまlinode上にあるリソース(昔のサイトとか)をlinodeからはがす

はがしてどうする
- Heroku?
- Github Pages?

----
動的な必要もないかと思うので、GitHub Pagesに置く方向で。

TODO:

* [x] rubykaigi.org/2009 - /2011 をサルベージする
* [x] GitHub Pagesか何かで新しいサーバを用意する
* [x] rubykaigi.orgにlinodeじゃない新しいホスト名のFQDNを用意してそこをGitHub Pagesに向ける
* [x] rko-routerを書き換えてlinode.rubykaigi.orgから新しいサーバに向き先を変える

**Comment by shyouhei** [comment]
現状: 撤退できてない
next action: とりあえずlinodeに何があるんだっけ? をリストする

**Comment by shyouhei** [comment]
現状: 撤退できてない。

DNSとかrko-routerとかもはがしたので、基本的に過去rubykaigi(09-11)でしか使ってないはずではある。

**Comment by shyouhei** [comment]
現状: 撤退できてない。

next action: 過去rubykaigi(09-11)のサイトをwgetする。素直に`wget --mirror`でやろうとしてもなぜかうまくいかなない。

**Comment by shyouhei** [comment]
現状: 撤退できてない。

next action: 過去rubykaigi(09-11)のサイトをwgetする。とりあえずwgetしてみよう。

**Comment by shyouhei** [comment]
現状: 撤退できてない。動きなし

next action: 過去rubykaigi(09-11)のサイトをwgetする。とりあえずwgetしてみよう。

**Comment by shyouhei** [comment]
現状: 撤退できてない。動きなし

**Comment by takahashim** [comment]
現状: 撤退できてない。wgetを素朴に使うだけではNG

**Comment by shyouhei** [comment]
現状: 撤退できてない。動きなし。

放置しているとまた課金されてしまう。

**Comment by shyouhei** [comment]
現状: 撤退できてない。動きなし。

次回課金は春頃との情報

**Comment by shyouhei** [comment]
現状: 撤退できてない。動きなし。

#255 とも関連してくる気がしてきた。

**Comment by shyouhei** [comment]
現状: 撤退できてない。動きなし。
なんか、次回の課金は不可避の気がしてきた

**Comment by kakutani** [comment]
「プランをもっと安いのにしてもいいかも」

**Comment by takahashim** [comment]
linodeのプラン https://www.linode.com/pricing
これの「Linode 2GB」だと$10/月=$120/年になるので半額以下にはなりそう（年間プランはもうない？？）。

やり方としては、管理画面からResizeで Linode 2048 にすればよいはず。
https://www.linode.com/docs/migrate-to-linode/disk-images/resizing-a-linode

**Comment by shyouhei** [comment]
現状: プランは変えちゃっていいのでは。宣言とかいる?
next action: いきなりプラン変えてしまう

**Comment by takahashim** [comment]
プラン変更を試してみたところ、Tokyo1のサーバはプランが変えられない&Tokyo2で動かすのは大変そうなので、わりと厳しい感じです…

**Comment by takahashim** [comment]
静的HTMLにするべくサルベージしてみました。
https://github.com/ruby-no-kai/rubykaigi-static

**Comment by takahashim** [comment]
あとは https://github.com/ruby-no-kai/rubykaigi の public以下を持ってくればだいたい補完できそうな気がします。

**Comment by shyouhei** [comment]
現状: 動き始めた
next action: 勢いで今月なんとかなりそう

**Comment by takahashim** [comment]
とりあえず http://2009-2011.rubykaigi.org/2009/ 等で動かすようにしました

**Comment by takahashim** [comment]
こちら今晩移行作業をしてみます https://github.com/ruby-no-kai/rko-router/pull/30

**Comment by takahashim** [comment]
rko-router変更しました。
もうlinodeにはアクセスが行かないはずなので、linodeはshutdownしておきます。

**Comment by takahashim** [comment]
linodeのインスタンスを削除しました。このissueは閉じておきます
