### ISSUE TITLE
ruby-lang.orgのen/にはあるけどja/にはないコンテンツをどんどん訳していく活動がひつよう

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#219]
aboutとか。

**Comment by takahashim** [comment]
cf. https://github.com/ruby/www.ruby-lang.org/issues/577

**Comment by shyouhei** [comment]
aboutは拡充されつつある(?)

それ以外をどうするか

**Comment by shyouhei** [comment]
- 英語と日本語とそれ以外を基本的に同期させたい。
- researchはべつに訳さないでもいいのでは(研究者は英語読めるやろ)
- booksは日本語書籍によさげなるといいなあ

**Comment by shyouhei** [comment]
@stomar's opinion about this: https://github.com/ruby/www.ruby-lang.org/pull/1339#issuecomment-203930245

**Comment by shyouhei** [comment]
next action:
- しまださんがキリがよくなったらpull requestしてもらう
- 右側のnavigationのところをいろいろ足す

**Comment by shyouhei** [comment]
現状: しまださんがだいぶんがんばってくれたので、だいぶ拡充された
next action: ?

**Comment by shyouhei** [comment]
しまださんありがとうということで一旦閉じる。
