### ISSUE TITLE
Rubyの入門用資料(日本語) を収集したり公開していく必要（→ tryrubyのマージの件）

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#220]
いまだと日本語資料はQiitaとかSlideShareとかに散在している。。。
しかも古い。

**Comment by hsbt** [comment]
#219 にも関連しますが https://github.com/ruby/www.ruby-lang.org/issues/1182 という tryruby を www.ruby-lang.org/en/tryruby みたいに公開してはどうか、という案が来ていまして、個人的には賛成で進めたいと思っています。

そこで https://github.com/easydatawarehousing/TryRuby の翻訳を何処かで進められると、RailsGirls やその他いろいろな媒体で日本語で irb とチュートリアルを試してみようというにはちょうど良いコンテンツになるのではないか、と思っています。

誰が何をする、というのはないのですが共有でした。

**Comment by takahashim** [comment]
@hsbt おお、しかし多言語化はたいへんなのでは…と思ったら、すでにI18N/L10Nの仕組みがあるんですね！　素晴らしいです。

**Comment by takahashim** [comment]
なんか、日本語資料室プロジェクトみたいなを作ればいいんですかね。あるいは部活動みたいなやつとか。

**Comment by shyouhei** [comment]
- tryrubyの翻訳はよさそう! やりたい。
- 翻訳合宿とか?

**Comment by shyouhei** [comment]
next action: 担当をアサインしたい。

**Comment by shyouhei** [comment]
現状: 動けていない

**Comment by shyouhei** [comment]
rubykaigiでこういう話をちょっとしてみるとか。

**Comment by hsbt** [comment]
tryruby の進捗共有ですが、 https://github.com/ruby-no-kai/official/issues/220#issuecomment-205261827 の tryruby を html ビルドしようと思ったところ全く動かないぞこれ...という状況でした。

**Comment by takahashim** [comment]
tryruby、とりあえずいくつか訳してみています https://github.com/takahashim/TryRuby/commit/1db7706ba245c6593ac47baa8b7bead2cfe7792b

**Comment by shyouhei** [comment]
引き続きtryrubyをやっていく

**Comment by snoozer05** [comment]
easydatawarehousing/TryRuby ですが、 https://github.com/easydatawarehousing/TryRuby/pull/13 でビルドできるようになっているはず...という状況です。
あとは翻訳作業を手伝いたいので、 ruby-no-kai に folk したものにブランチを生やして作業していくようにするのがいいですかねい。

**Comment by shyouhei** [comment]
next action: 高橋さんのレポジトリをkaiにtransfer する

**Comment by shyouhei** [comment]
https://github.com/ruby-no-kai/TryRuby

**Comment by snoozer05** [comment]
ひとまず https://github.com/orgs/ruby-no-kai/teams/translation-team を作って @takahashim と@snoozer05 を足して ruby-no-kai/TryRuby の owner にしました。

**Comment by hsbt** [comment]
ありがとうございます...! これを www.ruby-lang.org/en/tryruby に生やすのは僕が再開します.

**Comment by snoozer05** [comment]
@takahashim TryRubyですが、後を引き継いで訳し終わったものを https://github.com/easydatawarehousing/TryRuby/pull/14 でPRしました

**Comment by shyouhei** [comment]
@hsbt tryrubyのほうはマージされたようです！

**Comment by hsbt** [comment]
www.r-l.o に持っていけるように何かを進めます...!

**Comment by shyouhei** [comment]
現状: tryrubyをrloに持ってこれないかという動き
next action: 見守る

**Comment by shyouhei** [comment]
現状: 見守っている

閉じていい?

**Comment by takahashim** [comment]
続きは https://github.com/ruby/www.ruby-lang.org/issues/1182 で進行中、ということで。
