### ISSUE TITLE
川崎Ruby会議01の開催

### ISSUE THREAD

**Issue by chezou** [ruby-no-kai/official#221]
こんにちは、kawasaki.rbの有賀です。

kawasaki.rb主催の地域Ruby会議、川崎Ruby会議01を下記の要領で実施の計画をしています。
つきましては、日程を確保させていただければと思います。
- 名称：川崎Ruby会議01
- 開催日：2016/08/20(土) 
- 会場：ミューザ川崎セントラルタワー NTT-ATプレゼンルーム
- 参加費：なし
- 配信：なし
- 定員: 100名程度
- 実行委員長：有賀康顕
- 実行委員：
  - 会場担当：長住直樹
  - るびま班：
    - 徳田農
    - 松久保敬人
    - 近藤悠太郎

**Comment by snoozer05** [comment]
:sunglasses: 

> つきましては、日程を確保させていただければと思います。

https://github.com/ruby-no-kai/official/wiki/Upcomingregionalrubykaigi を編集しておいていただけますでしょうかー。サイトの準備などが整いましたら、ruby-no-kai/regional.rubykaigi.org にPRいただければと思います！

参考: https://github.com/ruby-no-kai/official/wiki/Regionalrubykaigi#%E9%96%8B%E5%82%AC%E3%81%8C%E6%B1%BA%E5%AE%9A%E3%81%97%E3%81%9F%E3%82%89 

何か不明点などがあれば適宜つっついてくださいませ :-)

**Comment by chezou** [comment]
了解です！ Upcomingregionalrubykaigi のupdateしましたー :smile_cat:

**Comment by shyouhei** [comment]
現状:実施までは静観。
next action: actionが必要そうなら相談してください

**Comment by shyouhei** [comment]
現状:実施までは静観。
next action: actionが必要そうなら相談してください

**Comment by chezou** [comment]
remindありがとうございます。色々ありましたが、予定通り実行できそうです :)

**Comment by chezou** [comment]
無事実施しました 
http://regional.rubykaigi.org/kwsk01

**Comment by shyouhei** [comment]
@chezou 無事でよかったです！残務とか特になければこのチケットは閉じてしまってください。

**Comment by chezou** [comment]
残りるびまだけなので、ここはcloseしますね
