### ISSUE TITLE
Herokuアカウントください

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#223]
いろいろなアカウント情報をまきとりというか共有してほしいので
- Herokuのアカウント
- CloudFlareのアカウント

などをどこかでシェアしてほしいです。

**Comment by takahashim** [comment]
@shyouhei CloudFlareのアカウント情報はDropboxの方に置いてあります。

**Comment by shyouhei** [comment]
じゃあそこにHerokuの情報などもまとめていく感じですかねえ。

**Comment by takahashim** [comment]
そんな感じかでよいかと思います。

**Comment by takahashim** [comment]
アカウント情報はそれでよいとして、どのサービスを使ってるかの情報は見えるところにまとめておいた方がよいかもですね…。

**Comment by shyouhei** [comment]
とりあえずアカウントは集約されつつあるのでclose
