### ISSUE TITLE
githubのruby-no-kaiのowner/team

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#224]
誰が持ってるか誰も整理してなくて非常に不穏に感じるので整理すべき。

**Comment by shyouhei** [comment]
基本方針としては
- 社員が持ってる必要はある
- 他は必要に応じて付与したりはがしたりする

**Comment by takahashim** [comment]
とりあえず、以下のTeamは削除してしまってもよさそうです（古いレポジトリの管理者じゃないコミット権限用チーム）。
- RubyKaigi2014 Volunteers
- RubyKaigi2014 Translators
- RubyKaigi2014 Speakers
- RubyKaigi2014 LT Speakers
- RubyKaigi2014 gihyojp Reporters
- rubykaigi2013 volunteers
- RubyKaigi2013 Speakers
- RubyKaigi2013 rubima-reporters

以下もチームは不要そう。
- Regional RubyKaigi Man
- luadns

以下は公開してよさそう。
- kaigi_subscreen core team

**Comment by kakutani** [comment]
@takahashim 不要そう! || よさそう!!

**Comment by takahashim** [comment]
とりあえずluadnsとRegional RubyKaigi Manは削除しますね

**Comment by takahashim** [comment]
- RubyKaigi2014 Volunteers
- RubyKaigi2014 Translators
- RubyKaigi2014 Speakers
- RubyKaigi2014 LT Speakers
- RubyKaigi2014 gihyojp Reporters
- rubykaigi2013 volunteers
- RubyKaigi2013 Speakers
- RubyKaigi2013 rubima-reporters

は削除しました。kaigi_subscreen core teamも公開済みです。

**Comment by shyouhei** [comment]
- ruby-no-kai/regional_rubykaigi は、いらなそう
- rubyhirobaは…?

**Comment by shyouhei** [comment]
すぐにできる整理はしたので一旦閉じる
