### ISSUE TITLE
privateレポジトリを整理する

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#225]
終わったイベント用サイトのレポジトリとかはpublicにしてしまってもいいのではないかと思いました。

**Comment by shyouhei** [comment]
- 整理し始めるのは良いことではありそうなのでtwo_carton_foxesなど公開に向けて動き始める
- とはいえprivateレポジトリはゼロにはできないだろう。

**Comment by kakutani** [comment]
:octocat: 📝 
https://github.com/blog/2164-introducing-unlimited-private-repositories

```
For a paid organization on GitHub.com what kind of users will be charged?

You must purchase a seat for each user in your GitHub.com organization. 
These users fill a seat:

* Organization members and owners
* Pending invitations
* Outside collaborators with access to 1 or more private repositories

These users do not fill a seat:

* Outside collaborators with access to only public repositories
* Billing managers
```

ポイントは、

> Outside collaborators with access to 1 or more private repositories

ってことだな…。

**Comment by shyouhei** [comment]
teamの整理にともない整理がすすんでいる

**Comment by shyouhei** [comment]
取り急ぎで整理できそうなものは整理済みの気がした

next action: rubyhirobaをどうするか

**Comment by hsbt** [comment]
rubyhiroba 内容を確認します。

**Comment by hsbt** [comment]
おおむね public にしてもよいのではないか、と思いましたが issue だけセンシティブな内容が含まれると思いました。 git clone してサイトは保存、今のリポジトリ削除、public にしてサイトを push でいかがでしょう?

@bash0C7 と @kwappa これでどうでしょうかー

**Comment by kwappa** [comment]
異存ございません！

**Comment by shyouhei** [comment]
next action: こしばさんの反応を待つ

**Comment by shyouhei** [comment]
two carton foxes はどうしたものか

**Comment by shyouhei** [comment]
現状: @bash0C7 待ち

**Comment by bash0C7** [comment]
お返事遅れてすいません。異存ないです。

**Comment by takahashim** [comment]
next action: hirobaについて、git clone してサイトは保存、今のリポジトリ削除、public にしてサイトを push する

**Comment by shyouhei** [comment]
現状: 動きなし
next action: hirobaについて、git clone してサイトは保存、今のリポジトリ削除、public にしてサイトを push する

**Comment by shyouhei** [comment]
- 「今のレポジトリを削除」がちょっと怖い
- まあ大丈夫のはずというコンセンサスになったので、消す

**Comment by shyouhei** [comment]
現状: 動きなし
next action: hirobaについて、git clone してサイトは保存、今のリポジトリ削除、public にしてサイトを push する

**Comment by shyouhei** [comment]
現状: 動きなし
next action: hirobaについて、git clone してサイトは保存、今のリポジトリ削除、public にしてサイトを push する

**Comment by snoozer05** [comment]
やりました
