### ISSUE TITLE
Rubyの会の機材の貸し出しについて

### ISSUE THREAD

**Issue by snoozer05** [ruby-no-kai/official#228]
主にRubyKaigiに使われているRubyの会の機材(電源タップ、LANケーブル等)ですが、地域Ruby会議などにも貸し出せますよ、ということをどこかに書いた気がするのですが、見当たりませんでした...

こちらについて上記の認識であってましたっけ...?? @takahashim @kakutani 
その場合、地域Ruby会議以外(たとえばRailsGirlsとか)についても issue で相談してもらえれば貸し出してよいと思うのですが、どこに書いておくといいですかねえ。

@ko1 さんが東京11でタップを購入してしまった（借りれるなら借りたかった）という事象がありましたので、もう少し周知できているといいかなあと思っております。

**Comment by takahashim** [comment]
@snoozer05 なんとなく、貸出は問題ないけど本格的に始めると機材の管理が大変そうなのをどうしたものか（何か仕組みを作る必要がありそう）…というところで止まっていたような。

**Comment by takahashim** [comment]
あと、機材じゃないけどRubyKaigi 2015で使ったものの残りがこしばさんのところにあったはず（文具等の消耗品っぽいもの）

**Comment by snoozer05** [comment]
@takahashim なるほど。仕組みということだとRAさんに管理をお願いしてプロトコルが定められるとよさそうですね。今週金曜日に RA の理事会があるそうで、それまでに感触がわかっているとよさそうとのことでしたので、やってもらう方向で聞いてもらうといいですかね cc @ko1

**Comment by ko1** [comment]
聞いてみます。
（無理だよ！　って言われたらすみません）

**Comment by kakutani** [comment]
👀  (特に気のきいたことを思いつかなかったので、読んでますのお知らせまで…)

**Comment by ko1** [comment]
RA 理事会にて提案しました。
（cc/ RA 事務局長 @shugo san）
- どれくらいの量か（備品の規模）
- どれくらいの頻度か

がわかれば検討できる、ということです。
以降、RA 事務局の方とあわせて検討頂ければと思うのですが、この ticket が適当でしょうか。

**Comment by shyouhei** [comment]
- 頻度は過去の実績からいうとmaxでも年数回レベル、minでは年一回(the RubyKaigiで必ず使う)。
- 備品の規模？ @darashi が把握してるんでしょうか。。。

**Comment by snoozer05** [comment]
https://github.com/ruby-no-kai/rubykaigi-orgz/wiki/ruby-no-kai-equipments

**Comment by takahashim** [comment]
https://github.com/ruby-no-kai/official/wiki/ruby-no-kai-equipments にコピーしました

**Comment by shyouhei** [comment]
@ko1 上記のような規模のようです

**Comment by shyouhei** [comment]
rubykaigiが終わって落ち着いた後で考えた方が混乱が少なそう

**Comment by shyouhei** [comment]
現状: rubykaigiが終わった
next action: @ko1 どうでしょう

**Comment by ko1** [comment]
#229 の話とはちがうんだっけ。

**Comment by shyouhei** [comment]
#229 は「どこで管理するか」という話で、 #228 は「それを貸し出すかどうか」という理解でいます。

RAのほうで一体的に考えていただけるのであればそれでもかまわないかと。

**Comment by ko1** [comment]
Ruby の会か、RA かってことになるだろうから、私が判断するものじゃないかと思います。実際問題、RA がそれが出来るかどうか、ってところじゃないでしょうか。

**Comment by shyouhei** [comment]
現状: RAを見守っている

**Comment by shyouhei** [comment]
現状: RAを見守っている

**Comment by ko1** [comment]
RA 的には、量的・負荷的に可能なら、と言うことになると思います。#229 で続きでしょうか。

**Comment by shyouhei** [comment]
こちらは閉じますね。
