### ISSUE TITLE
Rubyの会の機材管理について

### ISSUE THREAD

**Issue by snoozer05** [ruby-no-kai/official#229]
@ko1 さんから以下のような提案をいただきました:

> 管理コスト、もし問題になるようでしたら、RA のほうで引き取れるか相談しましょうか。
> コストとしては、おそらく
>  (a) 在庫の管理
>  (b) リクエストの管理（スケジューリング）
>  (c) 発送、引き取り業務
> になると思うのですが、もし負担になっているようでしたら、RA には
> 専任の事務の方がいらっしゃるので、そちらにお任せしてもいいかも
> しれません。（ただし、機動性は落ちる）

現状備品を保管しているえにしテック側はそこまではコストだと思っているわけではないですが、RubyKaigiのみなさんが上記のほうがやりやすいなどあれば、上記に移行してもよいかもしれません。どうしましょうねえ。

**Comment by ko1** [comment]
> 現状備品を保管しているえにしテック側はそこまではコストだと思っているわけではないですが、RubyKaigiのみなさんが上記のほうがやりやすいなどあれば、上記に移行してもよいかもしれません。どうしましょうねえ。

やりやすさは、多分えにしテックさんが管理しているほうが、やりやすいと思いますよ。
#228 のように、手を広げ出すとしんどそう、と思います。

**Comment by shyouhei** [comment]
このチケットは管理コストの話をする、という感じでしょうか。

**Comment by shyouhei** [comment]
- 都度買ったほうが管理コストより安いこともあるのでは

next action: まずは一覧というか、都度買うのはもったいないような機材があるかを見る

**Comment by ko1** [comment]
はい、お願いします。
@shugo san, 適当にコメント頂ければ。

**Comment by shyouhei** [comment]
現状: ご意見募集中です
@shugo どうでしょう

**Comment by shyouhei** [comment]
現状: @shugo どうでしょう

**Comment by shugo** [comment]
@ko1 さんに保管すべき機材の量と発送業務の頻度の情報をお願いしていたと思うのですが、その後進展はあったでしょうか。

**Comment by shyouhei** [comment]
@shugo https://github.com/ruby-no-kai/official/issues/228#issuecomment-226450429 ここからの議論では

- 頻度は年数回
- 一覧はhttps://github.com/ruby-no-kai/official/wiki/ruby-no-kai-equipments

というかんじでした！

**Comment by ko1** [comment]
ざっくり、段ボール何個分、みたいな話ってありますでしょうか。

**Comment by darashi** [comment]
ヒシコンテナ O-51L が 5 個分あります。
http://www.hishicon.com/container/kikaku-o/o-51l_huta.html

内容量としては、ぎっちり詰めなおせば4個に納まるかもしれないというくらいです。

**Comment by ko1** [comment]
ありがとうございます。
@shugo san、という感じだそうなので、ご検討いただけますか。

**Comment by shugo** [comment]
@ko1 了解しました

**Comment by shugo** [comment]
RAの事務所だとスペース的に保管が難しそうなので、お引き受けするとしたらNaClのオフィス
での保管を検討することになりそうですが、RAの事務局スタッフがNaClのオフィスに自由に
出入りできるわけではないので、ちょっとオペレーションを検討させてください。

その他、以下の点の確認をお願いします。

* 貸出希望の受け付けはRubyの会でされた上で、貸出の意思決定後に発送依頼がRA事務局
  に来るというイメージで合っているでしょうか。
* 機材の員数管理と送付だけで問題ないでしょうか（気になっているのは故障リスクです）。

**Comment by darashi** [comment]
内容物には今となってはあまり使わないようなものも色々とあるとは思いますので、中身を精査して本当に必要なものだけを残し、量を減らすということはできそうです。たとえば、ものすごく長い有線LANケーブルや、大量の WiFi AP なども不要かもしれません。

**Comment by shyouhei** [comment]
どうしようかなというかんじ。

**Comment by shyouhei** [comment]
@shugo ご質問についてですが、

> - 貸出希望の受け付けはRubyの会でされた上で、貸出の意思決定後に発送依頼がRA事務局
に来るというイメージで合っているでしょうか。

はい。

> - 機材の員数管理と送付だけで問題ないでしょうか（気になっているのは故障リスクです）。

問題ないです。壊れるのはもともとRubyの会でハンドリングしていても壊れるものですし。

**Comment by shyouhei** [comment]
現状: 動きなし

**Comment by shugo** [comment]
地域Ruby会議向けの貸出（#228）のためということであれば、貸出対象の機材を絞っていただいて
RAの事務所に置けそうな分量であればこちらで管理するということにしてはどうでしょうか。

**Comment by shugo** [comment]
その後の調整で、コンテナ4個程度であればスペースを空けられそうという話になりましたので、お知らせしておきます。

**Comment by shyouhei** [comment]
現状: しまったRAでこの話するのわすれた
next action:

方向性としてはRAで管理をお願いする方向にしたいですね。

- いまコンテナ5個分あるやつをどうするか
- RubyKaigi本体ではもう使わないであろう機材もあるけどRegionalでは便利に使えるというものもあるだろう
- rubyじゃないカンファレンスで貸し出すかどうか? (技術書典?)

**Comment by shyouhei** [comment]
現状: 送るものが決まりさえすれば送付することはわりとすぐ可能
next action:

- コンテナ4個分に減らす
- RAに内容と送付する旨を申し送り

**Comment by snoozer05** [comment]
TODO: 内容を精査してコンテナ４個分に減らして、RAに内容と送る旨を伝える @snoozer05

**Comment by snoozer05** [comment]
@darashi と話はしたので、あとはリストを作って、RAさんに連絡する。引き続き

**Comment by snoozer05** [comment]
忘れずやる

**Comment by snoozer05** [comment]
今年のRubyKaigiで多少増えるかもしれない

**Comment by shyouhei** [comment]
現状: 動きなし
next action: あとはリストを作って、RAさんに連絡する。

**Comment by darashi** [comment]
📝 https://github.com/ruby-no-kai/official/wiki/ruby-no-kai-equipments に現状のリスト

**Comment by shyouhei** [comment]
現状: RubyKaigiで送付するものがありそう

**Comment by shyouhei** [comment]
関連 #286

**Comment by shyouhei** [comment]
next action: じゃあ一旦RubyKaigiに備品は集約しましょう

**Comment by shyouhei** [comment]
@sorah Rubyの会の機材がいつまでに届いて欲しいかとか送付先住所とかコメントしといてください。

**Comment by sorah** [comment]
先に量を把握したいです。1〜2箱にまとまっている感じ?

送付先は https://info.cookpad.com/corporate/about + インフラ部 @sorah + 03-6368-1008 で。
9/13 までには欲しいです。

**Comment by snoozer05** [comment]
@sorah 機材のリストは https://github.com/ruby-no-kai/official/wiki/ruby-no-kai-equipments 、量はコンテナ４箱分といった感じです！

**Comment by sorah** [comment]
コンテナ……。置き場所あるかな…。
おてすきのときに写真がほしい。

**Comment by snoozer05** [comment]
@sorah ものはこちら http://www.hishicon.com/container/kikaku-o/o-51l_huta.html になりますー

**Comment by sorah** [comment]
ちょっと他の荷物の具合を見てから回答します。

**Comment by sorah** [comment]
コンテナ4つだとだいぶ(全部使わないわりに)邪魔かもしれない…電源ケーブルとLANケーブルだけシュッと選別できたりしないですよね…?

**Comment by shyouhei** [comment]
(このスレッドはRubyKaigiそのものの話題ではないものが混じっているためちょっと話が混乱している)

@darashi ご面倒ですが、二箇所に送付してもらうことって可能でしょうか。電源ケーブルとLANケーブルの箱だけ先に東京、残りはあとで広島という感じです。

**Comment by sorah** [comment]
スレッド移したい (rubykaigi2017 repoで探して混乱したりしてる)

**Comment by darashi** [comment]
@shyouhei はい、大丈夫です！

実際に荷物を詰めてみないとわかりませんが、電源ケーブルとLANケーブルだけでも全て入れると2箱はあるような気がします。明日時間がとれたら見てみます。

それから、広島国際会議場に送る際の詳細をお知らせいただけますでしょうか。
適当に調べてたたき台を用意しました。問題があればご指摘ください。

〒070-0811
広島市中区中島町1番5号 平和記念公園内
広島国際会議場気付 RubyKaigi2017 9月17日-20日利用
082-242-7777

気になっている点:

* 利用期間は「9月17日-20日」としてみましたが会期前日を含めて「9月16日-20日」のほうがよいでしょうか？
* 配達日時の指定はどうしましょうか？
  * 日付は会期前日(9月16日)着がよいでしょうか？
  * 時刻はヤマトで送るつもりなので「午前中」「14時〜16時」「16時〜18時」「18時から20時
「19時〜21時」「指定なし」からお選びください。
* 元払/着払は、会場への送付なのでおそらく元払&後日精算がいいですよね。

以上よろしくお願いします！

**Comment by darashi** [comment]
つめなおしてみました。

LANケーブルと電源タップ類をまとめてコンテナ2個分になりました。

残りの荷物はコンテナ1個分です(ぎっしりつめたら3個に収まりました)。
これらに加えて都合2個の空コンテナができました。空のコンテナも広島に送ってしまってよいでしょうか？

まとめると

1. LANケーブル・電源タップ→東京
2. LANケーブル・電源タップ→東京
3. 残りの全て→広島
4. 空コンテナ→広島？
5. 空コンテナ→広島？

という状況です。

ちなみに今年は私も参加者として広島に伺う予定ですので、もしよろしければ、これを気に不要な機材を処分するなどのお手伝いもできるかと思います。

**Comment by darashi** [comment]
@shyouhei @sorah 問題なければ東京行きの2箱はもう発送してしまってよいでしょうか？9/8(金)には発送の作業ができそうで、そうすると9/10(日)には東京に到着する見込みです。
＃実質受け取りは次の営業日の9/11(月)になるでしょうか

**Comment by snoozer05** [comment]
@shyouhei @sorah 東京宛については明日発送できるとこちらとしては諸々楽なのですが、手配してしまっていいですか...??

**Comment by sorah** [comment]
おっけいです https://github.com/ruby-no-kai/official/issues/229#issuecomment-324630006

**Comment by shyouhei** [comment]
@darashi @snoozer05 じゃあ明日発送でおねがいします！

**Comment by darashi** [comment]
東京宛のコンテナ2箱を発送しました。ヤマト 745-8176-1564 です。3,472円でした。

**Comment by darashi** [comment]
@shyouhei @sorah 広島宛はできれば 9/13(水) に発送したいので、会場側の受け入れプロトコルをご確認いただければ幸いです。

あと、手元が狂って東京宛の送り状に私の自宅住所が載ってしまいました。お手数をおかけして申し訳ないのですが、適当に破棄していただけるとありがたいです。すみません。次は気をつけます。

**Comment by sorah** [comment]
@darashi コンテナ2コ受け取りました。住所破棄了解です〜

**Comment by shyouhei** [comment]
@darashi 

〒 730-0811
広島県広島市中区中島町1-5
広島国際会議場
RubyKaigi 2017
☎︎ 082-242-7777

9月17日の17時から21時必着でお願いします

**Comment by darashi** [comment]
@sorah @shyouhei 諸々ありがとうございます。残りは明日発送の予定です。

**Comment by darashi** [comment]
広島宛のコンテナも発送しました。2,484円、ヤマト3308-1765-5324です。

**Comment by takahashim** [comment]
ありがとうございます！！

**Comment by takahashim** [comment]
これですが、RubyKaigi 2017に送りつけてもらったものを @darashi さんに見てもらいながら整理した結果、かなりの程度は古い and/or 使わなさそうということで処分する方向になりました…。

**Comment by shyouhei** [comment]
現状: Rubyの会の機材は一旦えにしテックからはなくなった
next action: とりあえずこのチケットは終了してもいいかなあ。えにしテック以外の場所から機材を集める必要がある

**Comment by sorah** [comment]
電源系の機材のコンテナが 2 つクックパッドにあります。着払い発送対応可能なので指示もらえたらいい感じにやります。

**Comment by takahashim** [comment]
@sorah 着払いでRubyの会までお送りいただければ…！

〒151-0066　東京都渋谷区西原2丁目33-6
一般社団法人日本Rubyの会　高橋征義

**Comment by sorah** [comment]
来週まるっと日本いないので、10月中旬くらいに…!

**Comment by takahashim** [comment]
まだ送ってもらってない。

next action: 回収してトランクに送る

**Comment by sorah** [comment]
あっ、いろいろあって送りそびれていた…すいません来月くらいになります…。

**Comment by takahashim** [comment]
@sorah 了解です、来月なら上旬くらいだとありがたいです！

**Comment by sorah** [comment]
他の荷物の整理とかどたばたしたまま長めの出張にでちゃったので、はやくて13日発送とかになるとおもいます…!

**Comment by takahashim** [comment]
@sorah おっとそうなんですね、であればむしろ22日以降に着くように配送していただけるとありがたいです…！（今度はこちらが不在にしているため）

**Comment by sorah** [comment]
あーじゃあRubyConfのあとにしよう。

**Comment by shyouhei** [comment]
現状: @sorah が送付してくれたら終わり
next action: どうでしょうか :><:

**Comment by sorah** [comment]
ナイスリマインド…。水曜か木曜中に送ります。日時指定あれば言ってください。

**Comment by takahashim** [comment]
@sorah お、すみません、日時指定は特にないです。来週とかなら（火曜の夜以外は）誰かはいる予定です。

**Comment by sorah** [comment]
どたばたしてるなか発送したので通知遅れちゃいましたが今日明日で届くと思います。

**Comment by takahashim** [comment]
@sorah 荷物受け取れました！　ありがとうございます！

しかしでかすぎてうちに入らない…（中身だけは移した）

**Comment by takahashim** [comment]
こちら倉庫に発送しました

**Comment by snoozer05** [comment]
おつかれさまです！

**Comment by shyouhei** [comment]
だいたいおわり。他の個別案件は個別にチケットを切る
