### ISSUE TITLE
名誉会員の件

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#23]
これは理事会でちゃんとやる

**Comment by kakutani** [comment]
第1回理事会で承認されたので、議事録は掲載するタイミングあたりでまつもとさんにお知らせする。

**Comment by kakutani** [comment]
see also: #43

**Comment by shyouhei** [comment]
まつもとさんに連絡してclosedにする

Todo: 名誉会員をリストアップするばしょがない

**Comment by kakutani** [comment]
http://ruby-no-kai.org/aboutus.html に載せればよさそう。

**Comment by snoozer05** [comment]
PRしました: https://github.com/ruby-no-kai/official/pull/69

**Comment by takahashim** [comment]
ありがとうございます！
