### ISSUE TITLE
Heroku Team機能をつかうかどうか検討する

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#230]
https://blog.heroku.com/archives/2016/6/9/heroku-teams

なんだかんだでお世話になっているし、
どれがどうなってんだっけ…の整理がてら導入してもいいかも(課金アイテム)

> Pricing and Use
> 
> Every Heroku user can create up to five teams. All teams are free for up to five members, and larger teams are just $10/month. Each Team can have up to 25 members.
> For larger Teams with additional governance, compliance, and authentication needs, there's seamless transition for any Team to a new or existing Heroku Enterprise instance.

現在はパスワード使いまわし共用アカウントをownerにして
適宜collaboratorに作業する人を追加している。

**Comment by kakutani** [comment]
記事を読んだだけなので、ちょっと試してみて考える。

**Comment by shyouhei** [comment]
@kakutani さんが試してみる

**Comment by shyouhei** [comment]
@kakutani さんが試してみる

**Comment by shyouhei** [comment]
@kakutani さんが試してみる

**Comment by takahashim** [comment]
今のところ困っていないので、困った時 or 試してみたくなった時に試してみることになりました
