### ISSUE TITLE
RubyKaigi 向けに観光案内のリポジトリを用意したい

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#233]
ふわっとしたアイデアなのですが、RubyConf Taiwan/RailsPacific, RedDotRubyConf で来訪者向けに観光ガイド(地球の歩き方っぽいやつ)を用意していて大変便利でした。
- https://github.com/rubytaiwan/taipei
- https://github.com/rubysg/singapore

上記のようなイメージです。RubyKaigi でも似たような情報を集めるリポジトリを作るのは如何でしょう?

**Comment by hsbt** [comment]
(最初の投稿を途中で投稿してしまったので更新しています)

**Comment by shyouhei** [comment]
- よいとおもいます
- どう進めましょう
- できれば音頭とってくれる人がいるといいな
- レポジトリ名だけ決まったらとりあえず空のレポジトリを作成するのはできます

**Comment by takahashim** [comment]
レポジトリ名、「welcome-to-kyoto」で作ってみますね

**Comment by hsbt** [comment]
おねがいします...! 英語力に不安もあるので、日本語書いて翻訳、直接英語などいろいろありますが、音頭は取っていこうと思います。

**Comment by takahashim** [comment]
@hsbt https://github.com/ruby-no-kai/welcome-to-kyoto を作りました！

**Comment by hsbt** [comment]
リポジトリ作成いただいたので、続きはリポジトリで頑張ります!
