### ISSUE TITLE
RailsGirls Osaka 3rd のスポンサー請求

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#234]
@takahashim 6/18-19 に開催された http://railsgirls.com/osaka のスポンサー(一覧は別途ご連絡します)へのスポンサー費用の請求(9万円)をお願いします。

また、以前に相談した通り、スポンサー資金の総額分の RG 口座への立替え払いもお願いします 🙇 
- [x] 請求する
- [x] 入金確認する
- [x] 資金移動する

**Comment by shyouhei** [comment]
現状: 請求書作成中
next: 粛々と送付する

**Comment by shyouhei** [comment]
現状: 請求は送付済みのはず? @takahashim 要確認
next action: 確認する

**Comment by shyouhei** [comment]
現状: 請求書送付済、入金確認済
next action: なし
