### ISSUE TITLE
永和システムマネジメントからの RG スポンサーの申し出の対応

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#235]
永和システムマネジメント様より、 RG 全体の年間スポンサーとして 12 万円(Tokyo 2万円、年間10万円)を拠出したいとの申し出を受けたため、 7月末までを期日とした 12 万円の請求書を発行していただきたいです。発行先住所は別途ご連絡します。

発行に合わせて 12 万円の資金移動もお願いします...!
- [x] 請求する
- [x] 入金確認する
- [x] 資金移動する

**Comment by shyouhei** [comment]
現状: 粛々と作業中

**Comment by takahashim** [comment]
@hsbt  こちら #234 と合わせて資金移動しました！　ご確認ください

**Comment by hsbt** [comment]
@takahashim こちら、請求書の発行も完了ということで良いですよね?(チェックボックスありますが確認)

**Comment by takahashim** [comment]
@hsbt ええと、まだmisocaで発送済みになってないのもありますが、受付はされた模様なのでじきに発送されるはずです

**Comment by hsbt** [comment]
了解しましたー。永和さんにご連絡します。

**Comment by hsbt** [comment]
@takahashim 

永和さんに確認したところ、到着して手続きを進めたとのことでした。入金確認ののち、 close をお願いします.

**Comment by shyouhei** [comment]
現状: まだかも? 入金待ち
next action: まつ

**Comment by shyouhei** [comment]
現状: 入金確認がまだ
next action: 確認して閉じる

**Comment by takahashim** [comment]
現状: 入金確認がまだ
next action: 確認して閉じる

**Comment by takahashim** [comment]
こちら入金確認しました！
