### ISSUE TITLE
日本Rubyの会総会

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#236]
- [x] いつやる?
  - 10月までのどこか(年度が終わってから3ヶ月以内)で実施
- [x] オフラインでやる?

**Comment by shyouhei** [comment]
- どこかの会場を借りると良いのでは

**Comment by shyouhei** [comment]
- そろそろ日程調整する

**Comment by kakutani** [comment]
調整さん的なやつをつくります

**Comment by kakutani** [comment]
https://chouseisan.com/s?h=33d2f418335343158878ab60213839e7

個人を特定できる情報ばかりですが作りました!

**Comment by takahashim** [comment]
こちらも無事開催できました！　ありがとうございました。
