### ISSUE TITLE
RailsGirls Tokyo 6th スポンサーへの請求と資金移動依頼

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#237]
無事、先週 RailsGirls Tokyo 6th を終えることができたので、スポンサー企業への請求と資金の移動をお願いします。

請求先は 8 社、請求額合計は 18 万円です。高橋さんに共有している Google Docs フォルダにある "RGT6 スポンサーお申し込みフォーム（回答）" に詳細が記載されているのでご対応お願いします 🙇

**Comment by hsbt** [comment]
@takahashim メンション入れ忘れました...

**Comment by takahashim** [comment]
@hsbt spreadsheet確認しました。請求先が異なる会社さんと、宛名が「のちほど連絡します。」になっている会社さんについて確認していただきたく…！

**Comment by takahashim** [comment]
- [x] RG口座への振り込み
- [x] 請求書発行
- [x] 入金確認

**Comment by hsbt** [comment]
請求先、宛名のそれぞれ確認中です!

**Comment by hsbt** [comment]
@takahashim 請求先が異なる会社さんは invoice 用の ML に届いている情報(請求先の名前もシートのものではなく、メールの内容にする必要がありそうです)、「のちほど連絡します。」の会社さんについては更新しました。

これでお願いします...!

**Comment by takahashim** [comment]
@hsbt 前者の方、メールにある「協賛内容」ってどう書くのがよいでしょうか？
そして後者の方は一瞬変更された後に戻っちゃってるようですが、要は会社名そのままでよいでしょうか…？

**Comment by hsbt** [comment]
協賛内容は以下でお願いします。

```
 * イベントで提供する飲食費の支援
 * イベントで使用する文具の購入費支援
```

> 後者の方は一瞬変更された後に戻っちゃってるようですが、要は会社名そのままでよいでしょうか…？

🙇 はい、会社名そのままでお願いします...!

**Comment by shyouhei** [comment]
現状: いろいろの問題はクリアされた
next action: 送付する

**Comment by hsbt** [comment]
@takahashim Rails 技術者検定様から請求書が届いてないという連絡をもらったのですが、送付済みか確認していただけないでしょうか...! 弊社には届いて処理を終えているので送付漏れか何かかなと思います。

**Comment by takahashim** [comment]
@hsbt 確認したところ、8/18の午前1時にメールでお送りしているようでした。

**Comment by hsbt** [comment]
伝えておきます!(伝書バト)

**Comment by shyouhei** [comment]
現状: 請求書発行済
next action: Rails 技術者検定様に届いているか未確認だが、届いているなら入金待ち。

**Comment by hsbt** [comment]
Rails 技術者検定様に再確認したところ spam フォルダに分類されていたものの、届いていたそうです。

**Comment by takahashim** [comment]
よかったです！（あんまり良くないけど）

**Comment by takahashim** [comment]
next action: 入金を確認する

**Comment by shyouhei** [comment]
現状: 入金確認済み
