### ISSUE TITLE
今年の渡航費支援について

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#238]
- 学生を支援するのはどうか
- 企業のスポンサーをつのれそう
- しかしRubyConfは日程的にタイトなので
- 台湾かシンガポールでどうですかね

**Comment by shyouhei** [comment]
- 学生をどう募るか
  - 募集要項が必要
- 企業をどう募るか
  - どちらかというと後でもよさそう

**Comment by shyouhei** [comment]
rubykaigiのチラシ置き場にチラシまくのはどうでしょう

**Comment by shyouhei** [comment]
現状: しまったrubykaigiで動くの忘れてた
next action: 学生募集のそれっぽい文章を作る

**Comment by kakutani** [comment]
それっぽい文面をつくるのやってみます

**Comment by shyouhei** [comment]
今年は終了してしまった
next action: 来年がんばる。ターゲット?

- フィリピン
- シンガポール
- 他?

**Comment by shyouhei** [comment]
現状: oh…

- シンガポールは良さそう
- RailsConfでもいい
- Eurukoもいい

まとめ:
- 今年はやりましょう

next action:
- 文章を書く @kakutani 
- どこにアナウンスするか?
    - るびま
    - Qiitaとか?

**Comment by kakutani** [comment]
reddotrubyconfのCFPが開いていた: https://cfp.reddotrubyconf.com/

> Paper must be submitted before 2017-03-15 23:59:59 UTC.

今月中には支援の文面についてpublishできるようにしたい(気持ちを表明)

**Comment by shyouhei** [comment]
かくたにさんがreddotのCFPが閉まるまでに文面を出す

**Comment by kakutani** [comment]
書いてみました:

https://gist.github.com/kakutani/e71b6fa0f40e779c33c83cb6b92ce89f

http://rubyconferences.org/ に載っているすべて、というよりはRubyの会が支援して…という意味合いを踏まえて:

* RubyKaigiのことをアピってきてほしい
* 戻ってきたら日本のRubyistにフィードバックしてほしい

という思いを混ぜてみました。なので支援対象も、定着してる感じのいくらか国際色のある地域RubyConfとしてみました(railsconf,reddot,euruko)。台湾あたりが今年もやるなら追加かなーと。

ruby-assnのRubyConf渡航費支援にならって、旅費の支援にしてあります:
http://www.ruby.or.jp/ja/news/20160810.html
(CFPに落ちちゃった人はチケットは自腹で買ってください、という感じ)。

応募フォームはこれから作りますが、まずは文面を確認してもらえるとうれしいです > @takahashim @snoozer05 @shyouhei

**Comment by kakutani** [comment]
> 応募フォームはこれから作りますが

フォームをつくりました。gistの文中にリンクがあります

**Comment by shyouhei** [comment]
よいのでは

**Comment by takahashim** [comment]
旅費の精算、後日精算じゃ厳しい場合にはご相談くださいでもよいかと思いました。

あと「参加渡航費支援対象カンファレンス」も、載ってない場合はご相談くださいでもよいかと思います。ある程度国際色のあるものであれば、マイナーなイベントに行ってきてアピールしたりレポートしてくれたりするのはありがたいですし。

**Comment by takahashim** [comment]
もう一つ、一部離島地域にお住まいの方も、日頃からいろいろ苦労されてると思うので普通にお支払いしてあげたいです。（「相場よりも著しく高額な参加渡航費となる場合〜」があるので、変な支払いはこれで防げると思う）

それ以外は良いかと思います！！ 🙆

**Comment by kakutani** [comment]
指摘内容を反映させて、
https://github.com/ruby-no-kai/official/wiki/RegionalRubyConfTravelGrant2017
に公開しましたっ。

**Comment by amatsuda** [comment]
Wikinameが不適切だと思います。
国境を超える話なのに敢えて"regional"(= 地方の、田舎の)という言葉が使われていると、単に「日本国外のRubyカンファレンス」ではなく、Ruby出づる処の国である先進国日本からRuby未開の地に下向してやる的な含意を強く感じます。
ニュートラルに「日本国外のRubyカンファレンス」と言いたいなら"Overseas"ぐらいでしょうか。

**Comment by kakutani** [comment]
> ニュートラルに「日本国外のRubyカンファレンス」と言いたいなら"Overseas"ぐらいでしょうか。

なるほど…っ(変えときます)

**Comment by kakutani** [comment]
_(変えました)_

**Comment by shyouhei** [comment]
現状: 公開された
next action: 広報?

このissueは一旦閉じる

**Comment by kakutani** [comment]
⏩  #267
