### ISSUE TITLE
Wiki の次の東京Ruby会議

### ISSUE THREAD

**Issue by znz** [ruby-no-kai/official#239]
[次の東京Ruby会議](https://github.com/ruby-no-kai/official/wiki/Upcomingregionalrubykaigi#%E6%AC%A1%E3%81%AE%E6%9D%B1%E4%BA%ACruby%E4%BC%9A%E8%AD%B0)に

> もし開催されるとしたら、カウントは「 東京Ruby会議11 」でお願いします。

と書いてありますが、11のままで良いのでしょうか?

**Comment by takahashim** [comment]
確かに変えたほうが良さそうですね。文面修正してみます

**Comment by takahashim** [comment]
修正してみました。

**Comment by znz** [comment]
確認しました。
修正ありがとうございます。
