### ISSUE TITLE
RubyEventCheckをjp.rubyist.net -> github/wiki に誘導する

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#24]
https://twitter.com/#!/higaki/status/141486797443178496

**Comment by sunaot** [comment]
https://github.com/ruby-no-kai/official/wiki/RubyEventCheck
こちらまでお願いします！　るびまは最新だけ書きかえようかなぁ

**Comment by kakutani** [comment]
http://jp.rubyist.net/?RubyEventCheck 誘導するようにしました
