### ISSUE TITLE
RubyKaigi 会場へ備品を送付してほしい

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#240]
@springaki wrote:

> @shyouhei 日本Rubyの会から以下のものを送っていただきたいです ! (PCは @asonas さんが持ってるらしいので敢えてココには書きません。)
> 
> | プラグ形状 | 分類 | 差し込み口数 | 長さ | 色 | 数量 | 備考 |
> | --- | --- | --- | --- | --- | --- | --- |
> | 3pin | タップ | 6 | 5m | 白 | 2 | 抜止め有, AOAM65N-MG |
> | 3pin | タップ | 6 | 2m | 白 | 6 | 抜止め有, Arvel TA4362L, 電源側ピンに3Pアダプタ装着済み |
> 
> | 種別 | 個数 |
> | --- | --- |
> | Mini DisplayPort -> アナログ VGA | 2 |

**Comment by shyouhei** [comment]
@darashi @snoozer05 対応可能そうでしょうか。送付先住所は以下のような感じです。

> 送付先・受取時間帯-----------
> 〒606-0001京都市左京区岩倉大鷺町422番地
> 国立京都国際会館 157号室 RubyKaigi宛
> 9/7 午後 〜 9/10 午前まで受取可能
> ※発払いにて発送ください。配達業者の指定は特にありません。

**Comment by darashi** [comment]
承知しました。今週金曜日(9/2)には在庫を確認してまたご連絡します。

**Comment by darashi** [comment]
上記、在庫をすべて確認できました。

ヤマトだと一週間先まで配送日を指定できるので今日中に発送の手配をしてしまおうと思います。

配送時間はいつに指定するのがよいでしょうか？「9/7 午後 〜 9/10 午前まで受取可能」という条件にあう一番早い便ということで「9/7 12:00-14:00」(午後零時) で送ってしまいますね。問題がありそうならなるべく早めにお知らせください。

＃これを予め伺っておけばよかったですね。すみません。今日発送できないようであれば、私の都合で月曜日の発送になってしまいます。札幌→京都は中一日かかるようなので、月曜発送だとマージンが0日になってしまいます。ということで、本件の返信をいただけなかった場合でも今日中に送ってしまおうと思います。いずれにせよ伝票番号はお伝えしますので、不都合があるようでしたら配達時間を調整していただけると助かります。

**Comment by darashi** [comment]
![img_8741](https://cloud.githubusercontent.com/assets/2363/18192461/5f14e9bc-710f-11e6-8389-fb1ec533dc72.JPG)

発送予定の物品は以上のとおりです。

**Comment by darashi** [comment]
元払いで発送しました (送料は @darashi が立替)。伝票の情報は public じゃない経路のほうがよさそうなので、ひとまず日本Rubyの会の窓口のメールアドレス宛にお送りしておきました。

**Comment by springaki** [comment]
@darashi さん、ありがとうございます。

> 9/7 12:00-14:00」(午後零時)

で大丈夫でした。助かります ! 
取り急ぎ御礼まで。

**Comment by springaki** [comment]
@darashi 
すみません。お借りした電源タップを1個紛失しました。
( @kakutani さんとは情報共有しています )

電源タップ 7個
"Mini DisplayPort -> アナログ VGA" 2個

を発送しましたので到着後ご確認いただけますでしょうか。
大変申し訳ありませんがよろしくお願いします。

**Comment by darashi** [comment]
了解しました。こちら、不在通知が入っていてまだ受け取れてはおりませんが、受け取れたらまたご連絡します。

**Comment by shyouhei** [comment]
現状: 受け取っていただいた、が、着払い。
next action: 費用精算に進む

**Comment by darashi** [comment]
遅くなりましたが、さきほど内容物を確認しました。近日中に精算の手続きをしますのでよろしくお願いします。

**Comment by takahashim** [comment]
next action: 精算する

**Comment by shyouhei** [comment]
現状: 精算済み
