### ISSUE TITLE
松江Ruby会議08 開催

### ISSUE THREAD

**Issue by yoshiokaCB** [ruby-no-kai/official#241]
お世話になります。Matsue.rb の @yoshiokaCB と申します。
第8回目となる 松江Ruby会議の開催を以下の要領にて計画しております。

名称：松江Ruby会議08
開催日：2016/12/17(土) 
会場：松江テルサ 4F 大会議室
参加費：なし
配信：あり（URL未定）
定員: 100名程度
実行委員長：吉岡 隆行
るびまのレポート記事担当：橋下 将
会計 : 杉原 健司
サイト： http://matsue.rubyist.net/matrk08/ （準備中）

そこで、ご相談なのですが、遠方からお招きするゲストスピーカーへの交通費と宿泊費のご支援をお願いいたします。
まだ概算ですが、費用は以下ように考えております。
### 費用詳細

交通費：￥38,880-
宿泊費：￥15,536-（前乗りが必要なため2泊分計上）
合計：￥54,416-

詳細が決まり次第、随時ご相談させていただければと思います。
何か問題がありましたらご指摘いただけると幸いです。

何卒よろしくお願いいたします。

**Comment by takahashim** [comment]
費用の件了解です！　どうぞよろしくお願いいたします。

**Comment by shyouhei** [comment]
今後の流れ
- [x] 開催する
- [x] 費用が確定する
- [ ] 清算する

**Comment by shyouhei** [comment]
現状: 見守っている
next action: 開催を見守る

**Comment by takahashim** [comment]
開催おつかれさまでした！　費用の方は上に書かれている金額で確定でしょうか？

**Comment by yoshiokaCB** [comment]
@takahashim 
報告遅くなり申し訳ありませんでした。
おかげさまで無事に開催することができました！
開催報告のレポートは後日お送りさせていただきます。
本当にありがとうございました。

さて、以下、確定した金額です。

### 金額
```
宿泊費：¥11,390-
交通費：¥36,480-
合計：¥4,7870-
```

### 2点確認事項です。

1. 領収書をお送りしたいと思いますが、以下の宛先でよろしいでしょうか？

```
〒151-0066 東京都渋谷区西原2-33-6
一般社団法人日本Rubyの会　高橋征義様
```

2. また、振込先をお伝えするのと、領収書の電子データをお送りしたいと思いますが、送り先は以下のメールでよろしいでしょうか？
（交通費は昇竜所は電子データのみとなります。）

```
 info [at] ruby-no-kai.org
```

以上、よろしくお願いいたします。

**Comment by takahashim** [comment]
@yoshiokaCB はい、２点ともそれでOKです！
また金額については費用が下がったのですね。それでは47,870円で対応いたします。

**Comment by yoshiokaCB** [comment]
@takahashim 
先ほど、領収書と振込先をメールにて高橋様宛（日本Rubyの会）にお送りしました。
領収書の原本は明日、明後日を目処に発送予定です。
取り急ぎ、ご報告でしたm(_ _)m

**Comment by takahashim** [comment]
@yoshiokaCB メール受領いたしました！

**Comment by yoshiokaCB** [comment]
@takahashim 
昨日、領収書を郵便にてお送りしました。
届きましたらご検収をお願い致します。

**Comment by takahashim** [comment]
ありがとうございます！

**Comment by shyouhei** [comment]
現状: 領収書の受領を確認。振り込み済み。
next action: @yoshiokaCB 振り込まれているかご確認ください、大丈夫そうならチケット閉じてしまっていただいてOKです

**Comment by yoshiokaCB** [comment]
@shyouhei 
手続きありがとうございます。
入金確認しますので少々お待ちください。

**Comment by yoshiokaCB** [comment]
@takahashim @shyouhei 
入金確認できました。
色々とご協力頂き感謝です！
本当にありがとうございましたm(_ _)m

**Comment by takahashim** [comment]
@yoshiokaCB いえいえ、こちらこそありがとうございました！
