### ISSUE TITLE
TokyuRuby 会議 11 の開催

### ISSUE THREAD

**Issue by igaiga** [ruby-no-kai/official#242]
こんにちは。Tokyu.rb の 五十嵐邦明 と申します。

第 11 回目となる TokyuRuby 会議の開催を
以下の要領にて計画しております。
日程のみ決まっており、役割等はこれから決める予定です。
おおよそこれまでの TokyuRuby 会議と同規模のものを予定していますが、
取り急ぎ日程を確保致したく、連絡させていただきます。

名称：TokyuRuby 会議 11
開催日：2017年7月29日(土)
会場：株式会社VOYAGE GROUP
参加費：無料
配信：なし
定員: 未定
実行委員長：五十嵐　邦明
実行副委員長：河野　誠
　加藤　由佳
　小椋　隆史
　大場　光一郎
　影山　勝彦
　三浦　美咲樹
　多田　あき

https://tokyurubykaigi.github.io/tokyu11/

**Comment by kakutani** [comment]
@igaiga お知らせありがとうございます。 https://github.com/ruby-no-kai/official/wiki/Upcomingregionalrubykaigi で日程を晒しておきました。引き続きよろしくお願いいたします。

**Comment by shyouhei** [comment]
現状: 見守っている
next action: next actionが発生するまで見守る

**Comment by shyouhei** [comment]
現状: 見守ってるけどそろそろ動きがあってもいいかも?
next action: @igaiga とりあえずそろそろ会場くらいは決めていきたい時期じゃないでしょうか?

**Comment by igaiga** [comment]
@shyouhei 会場決まってましたので編集、更新しました。
ただいまのステータスとしてはリージョナルのページ作成中で、GW前後くらいで公開予定です。
見守り業ありがとうございます。m(_ _)m

**Comment by kakutani** [comment]
@igaiga 地域Ruby会議の今後の開催予定は https://github.com/ruby-no-kai/official/wiki/RubyEventCheck にマージしたので、そちらの情報も更新しておいていただけるとありがたいです…!

**Comment by igaiga** [comment]
@kakutani 承知しました！
ページできたらリンク貼っておきますね。

**Comment by igaiga** [comment]
@kakutani ページ公開したので開催予定ページも更新しました。
https://tokyurubykaigi.github.io/tokyu11/

**Comment by shyouhei** [comment]
現状: 見守っている
next action: next actionが発生するまで見守る

**Comment by shyouhei** [comment]
現状: 見守っている
next action: next actionが発生するまで見守る

**Comment by igaiga** [comment]
一般参加者募集開始しました。
発表者情報などタイムスケジュールも公開しました。
https://tokyurubykaigi.github.io/tokyu11/

**Comment by shyouhei** [comment]
現状: いよいよ来週となりました
next action: 終わったら報告してください

**Comment by igaiga** [comment]
こちら、昨日無事に開催しました。見守り業ありがとうございました。
るびま記事、追って対応します。

**Comment by shyouhei** [comment]
るびまのほうはるびまで。こちらのチケットは終わり。おつかれさまでした
