### ISSUE TITLE
大江戸Ruby会議06 開催

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#243]
地域 Rubyist 集団の Asakusa.rb のメンバーが中心となって開催する大江戸Ruby会議の5回目を開催します。以下が開催概要です。
- 名称: 大江戸Ruby会議06
- 日時: 2017年3/20(月) 9:00-17:00
- 場所: 御茶ノ水ソラシティカンファレンスセンター
- テーマ等: 検討中
- オーガナイザー & スタッフ: Asakusa.rb メンバー

なお、 @takahashim さんには事前に相談しましたが、会場費用の支払いを事前に行う必要があるため、立て替えを日本Rubyの会にご支援いただきたいです。

**Comment by takahashim** [comment]
支払いの方は必要なタイミングでお声がけください💰

**Comment by takahashim** [comment]
next action: いつ頃事前の支払いが発生するかを確認する

**Comment by hsbt** [comment]
1ヶ月前には支払いとのことなので 2017/2 月下旬を目処にお願いします。

**Comment by koic** [comment]
前回が[大江戸RubyKaigi05](http://regional.rubykaigi.org/oedo05)だったため、こちらのナンバリングは大江戸RubyKaigi06だと思ったのですがいかがでしょうか？

[これから開催される予定の地域Ruby会議](https://github.com/ruby-no-kai/official/wiki/Upcomingregionalrubykaigi)では06になっておりました。

**Comment by hsbt** [comment]
あっ、確かに 06 です。なんてこった...

**Comment by koic** [comment]
ご確認ありがとうございました 🙏

**Comment by shyouhei** [comment]
現状: 支払いサイトは確認した
next action:

- [x] 金額が確定する
- [x] 支払う
- [x] 開催される
- [ ] 精算される
    - スポンサーフィーが振り込まれたらasakusaの口座にスライドさせる

**Comment by hsbt** [comment]
@takahashim 金額が確定し、請求書がソラシティーの担当の方から送付されたので、支払いをお願いしてよいでしょうか? まずは請求書を @kakutani @shyouhei を cc でメールにて共有しますー。

**Comment by takahashim** [comment]
@hsbt 了解です、金額は問題ないです！（今週は帯域の方が厳しいです…が、今月末とかでも大丈夫ぽいのは確認いたしました）

**Comment by hsbt** [comment]
@takahashim よろしくお願いします! 振込日が判明したら共有をお願いします...! 🙇

**Comment by shyouhei** [comment]
現状: 会場費は振り込んだ
next action: rubyの会としてのアクションは当面なし。開催後に精算が発生する。

**Comment by kakutani** [comment]
スポンサーシップの提案をいただいたので、請求・入金確認・振込業務がある(備忘のために記録します)

**Comment by hsbt** [comment]
無事開催できました。立て替えていただいた会場費のうち、Cookpad さんのスポンサード 324,000 円を差し引いた金額を後ほど振り込みまーす。

**Comment by hsbt** [comment]
@takahashim こちら振込できる状態になったので、Ruby の会の口座情報を何かしらの手段で共有いただけないでしょうか? 🙏

**Comment by takahashim** [comment]
@hsbt ジャパンネット銀行　すずめ支店（店番号002）　普通口座　2978372　シャ）ニホンルビーノカイ　です！

**Comment by hsbt** [comment]
本日振り込みましたのでご確認ください!(確認終えたらクローズもお願いします)

**Comment by takahashim** [comment]
@hsbt 振り込まれてました！ありがとうございます！
