### ISSUE TITLE
基本的なコーディング規約をまとめたい

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#244]
Rubyのプロジェクトを始めるにあたりRubyのコーディング規約を調べたけれど良くわからない（信頼性高そうなところとしてRubyアソシエーションのサイトを見たら「Rubyの正式なコーディング規約はありません。」( http://www.ruby.or.jp/ja/tech/development/ruby/050_coding_rule.html )と書いてあり、参考の規約がいくつか載っているけれどもどれを選べばいいのかも良くわからない）ので困った、という話を聞きました。

どれか一つに決めようとすると戦争になりそうですが、そうは言ってもそこそこ汎用的な指針があった方がよさそうです。
複数の規約をベースにして最大公約数的なものを用意したりするのはどうでしょうか…？
## 書かないこと
- 1行の文字数の上限
- メソッドのカッコの省略可否
- 文字列リテラルの`"`と`'`の使い分け
- `%`記法の区切り文字
## 書きたいこと
- クラス名はCamelCaseにする
- メソッド名はsnake_caseにする
- ifのあとのthenは省略する
- 1クラスは原則1ファイルに書く（例外あり）
- ファイル名はクラス名を小文字にしたものにする。ただし大文字と小文字の境界に「_」を挟む（挟まない場合もある）
## 迷うもの
- ブロックの`do`〜`end`と`{`〜`}`の使い分け
- インデントのスペース(と文字数)/タブ

**Comment by takahashim** [comment]
今どきだと参考になりそうなのは以下でしょうか
- https://shugo.net/ruby-codeconv/codeconv.html
- https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md (original: https://github.com/bbatsov/ruby-style-guide )
- https://github.com/cookpad/styleguide/blob/master/ruby.ja.md
- https://github.com/styleguide/ruby
- https://github.com/airbnb/ruby

**Comment by hsbt** [comment]
> 文字列リテラルの"と'の使い分け

これ、どちらにしてもパフォーマンスへの影響はないから `"` 使うに統一するというのが増えてきてる印象です(rails など、個人的には賛成なので rake も採用した)

see. https://www.viget.com/articles/just-use-double-quoted-ruby-strings

**Comment by takahashim** [comment]
文字列リテラルについてはbbatsovのは選択式 https://github.com/bbatsov/ruby-style-guide#strings ,クックパッドは規定はないけど空文字列は「`''`」決め打ち https://github.com/cookpad/styleguide/blob/master/ruby.ja.md#strings 、airbnbは規定はないけど両方を併用、…という感じなので、現時点で「`"`〜`"`」が一般的とは言い切れないようです。とはいえ、もう少し時間が立つと変わってくるのかも。

**Comment by kakutani** [comment]
http://blog-ja.sideci.com/entry/2016/10/03/171816

> MeowCopは、コーディングスタイルに関するルールなど、プロジェクトごとに変わってくるルールを無効化します。 また、バグに繋がるようなコードやパフォーマンス上の問題など、スタイルに関するルール以外は有効になっています。

...という話を最近みました。

昔むかし、まつもとさんに聞いたら"好きにしたらいいよ"的なことを言われた思いで…(RAの見解がそれかな、と思ったり)

"意見はいろいろあるけど、まずはこういうのはどう？"みたいなのはあってもよさそうだけど、選択肢が増えて混乱するだけになるんですかねえ。

**Comment by hsbt** [comment]
> 現時点で「"〜"」が一般的とは言い切れないようです。

揺れているので、書かないことに入れた方が良いとは思いますが、こういうのって、contribute するときに「直さないと受け入れないよ」というのを省くために入れるものだと(@hsbt は)思っているので、影響力(=利用者数)が大きいであろう Rails/Rake に揃えておくと面倒じゃなくなるんじゃないか、という考えでのコメントでした。

なので最近は緩く「Rails の .rubocop.yml に従っておけ」派です。

**Comment by takahashim** [comment]
MeowCopはちょっと見てみましたが、どちらかというと主戦場は`Style/*`のうちの一部（ `Style/MethodName` とか `Style/MultilineIfThen` とか）なのでここを落とされるとあまり意味がなくって、一方で `Metrics/*` とか `Performance/*` とかはローカルルールで必要な分だけ使っていただければ…という気持ちなのです。

> "意見はいろいろあるけど、まずはこういうのはどう？"みたいなのはあってもよさそうだけど、選択肢が増えて混乱するだけになるんですかねえ。

他言語は知ってるけどRubyは初心者、という人に対して「選択肢が増える（けれどもどういう基準で判断するべきかの情報はない）」のはあまりよろしくなさそうでした。

**Comment by takahashim** [comment]
> なので最近は緩く「Rails の .rubocop.yml に従っておけ」派です。

確かにこれは手堅そう。特にRailsやその周辺ツールを使うんだったらこうするべきですよねえ。

今回はPerlやCやJavaなどを使ってツールを作っていたけど最近はRubyが便利らしいのでRuby使ってみますか、くらいの人とかがメソッド名を大文字で始めたりしないようにしたい、というのが動機です。とはいえ、まずは `bundle gem hogehoge` を実行して…という雰囲気でもなさそうで（最初の説明が大変そう）、１ファイルのスクリプトから始めつつライブラリに切り出して…みたいな流れを想定しているのですが、その時でもまずは規約があった方が便利かなと思ったのでした。

それともminimalな.rubycop.ymlを用意しておいて、最初にrubocop実行環境くらいは作らせるくらいの方が手っ取り早いのかな…。

**Comment by takahashim** [comment]
next action: 認定試験でこの手の問題をどう扱っているか聞いてみる

**Comment by shyouhei** [comment]
現状: とくに聞いてみてない
next action: 誰に聞けばいいんだっけ

**Comment by shyouhei** [comment]
現状: 動きなし

とりあえず一旦閉じますかね。また動きそうになったら開く
