### ISSUE TITLE
名古屋Ruby会議03 開催

### ISSUE THREAD

**Issue by eitoball** [ruby-no-kai/official#245]
Ruby東海の かたぎり です。

名古屋Ruby会議03の開催を以下の要領にて計画しております。
日程・場所が決まっていますが、詳細は今後（できれば、今年中）決めていきます。
宜しくお願いします。

名称：名古屋Ruby会議03
開催日：2017年2月11日(土) 
会場：[大須演芸場](http://www.osuengei.nagoya)
参加費：1,000 から 1,500 円程度を予定しています。
配信：なし
定員：100名程度
実行委員長(仮)：かたぎり えいと (@eitoball）
会計：TBA
レポート：TBA
サイト：TBA

1から2名ほど、遠方からお招きするゲストスピーカーへの交通費と宿泊費のご支援について、詳細が決まり次第、ご相談させて下さい。

**Comment by kakutani** [comment]
> 1から2名ほど、遠方からお招きするゲストスピーカーへの交通費と宿泊費のご支援について、詳細が決まり次第、ご相談させて下さい

承知しました~

**Comment by takahashim** [comment]
next action: 費用について連絡を待つ

**Comment by shyouhei** [comment]
現状: 動きを見守る(日程的にタイトになってきた気が…) @eitoball 
next action:

- [x] 金額の確定
- [x] 振込み
- [x] 開催

**Comment by eitoball** [comment]
ありがとうございます。準備しますー :fire:

**Comment by eitoball** [comment]
遅くなりましたが、支援頂きたい費用の概算についてですが、以下になります。

### ゲストスピーカーへの交通費と宿泊費

* 交通費: 15,780 * 2 + 11,090 * 2 = ￥53,740-
* 宿泊費: 6,000 + 6,000 = ￥12,000-

幸いにも、予定以上にスポンサー様に支援頂けそうなので、参加者数によっては、上記より金額が少なくなる可能性があります。

以上、ご検討よろしくお願いします。

**Comment by shyouhei** [comment]
現状: 開催を待つ
next action: @eitoball 会場費など支払いあると思いますがキャッシュフローは後日精算で大丈夫でしょうか。事前に振り込みが必要ならおしらせください。

あとスポンサー費用ってRubyの会から請求する形だと理解しています( #254 )が請求が先のほうがよいスポンサー様があるようでしたら、先に情報いただけると対応可能ですが、どんなもんでしょう。

**Comment by eitoball** [comment]
@shyouhei ありがとうございます。会場費については、支払いは完了してます。ですので、後日精算（ #251 ）で大丈夫です。スポンサー様への費用の請求も、会議後で大丈夫です。

**Comment by eitoball** [comment]
ゲストスピーカー様の費用ですが、 https://github.com/ruby-no-kai/official/issues/245#issuecomment-271061172 の金額でも、大丈夫でしょうか？

**Comment by shyouhei** [comment]
@eitoball ありがとうございます、支払済とのことで安心しました。金額は概算としては問題ないですので、確定したらおしらせください。

**Comment by eitoball** [comment]
昨日、大きな問題なく、終了しました。ありがとうございます。今後、スポンサー様への費用や参加費（ #251　）の請求などでお手数かけますが、宜しくお願いします。

この issue は、開催が終了したので、 close します。

**Comment by kakutani** [comment]
お疲れさまでした！ たのしく交流できてた会議だったと思います！

カンファレンスは終わりましたが、後処理は残っているので、このまま続行でよいとおもいまーす。

**Comment by snoozer05** [comment]
@eitoball るびまレポートの方も忘れずよろしくお願いします

**Comment by shyouhei** [comment]
このissueの残件はないので閉じる。

**Comment by eitoball** [comment]
> るびまレポートの方も忘れずよろしくお願いします

はい！
