### ISSUE TITLE
RailsGirls Nagoya 3rd のスポンサー費用請求

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#246]
10/28 開催の http://railsgirls.com/nagoya のスポンサー費用の請求をお願いしたいです。

@takahashim 別途ご連絡しますが、一部の企業様から 11/04 までに請求書を欲しいと要望されているので、ご対応をお願いしたいです!

-----
- [x] 請求する
- [x] 精算する
- [ ] 入金確認する

**Comment by takahashim** [comment]
@hsbt  こちら郵送処理しました! 明日発送の予定です。

**Comment by shyouhei** [comment]
現状: 先に請求書が欲しいところの請求書は郵送した
next action: 残りをやらねばだが、請求先を確認する必要がある @hsbt

**Comment by takahashim** [comment]
こちら対応しました

**Comment by takahashim** [comment]
@hsbt これとKobe 2ndのってまとめて口座に振り込んでもよいですか？

**Comment by hsbt** [comment]
@takahashim お願いします!

**Comment by takahashim** [comment]
@hsbt 振り込みました！

**Comment by shyouhei** [comment]
現状: 振り込み済み。入金確認待ち
next action: @hsbt ご確認ください

**Comment by hsbt** [comment]
12/2 に振り込まれているのを確認しました!

**Comment by shyouhei** [comment]
現状: 入金が確認された
