### ISSUE TITLE
関西Ruby会議2017の開催

### ISSUE THREAD

**Issue by ogom** [ruby-no-kai/official#247]
Ruby関西の おごもり (@ogom) です。

関西Ruby会議の開催を計画しております。
日程と開場が決まっており、役割などはこれから決める予定です。
（役割が決定したので更新しました。）

* 名称: 関西Ruby会議2017
* 開催日: 2017年5月27日(土)
* 会場: 大阪産業創造館 4F イベントホール
* 参加費: なし
* 配信: 未定
* 定員: 200名程度
* 実行委員長: おごもり (@ogom)
* るびまのレポート記事担当: くさかべ (@t-kusakabe)
* 会計担当: まつもと (@urimaro)
* サイト: https://rubykansai.github.io/kansai2017/

ご相談なのですが、遠方からのゲストスピーカーの費用の支援をお願いできますでしょうか。
費用は概算ですが、東京を想定して交通費(¥40,000)が宿泊費(¥20,000)の予定です。

どうぞよろしくお願いいたします。

**Comment by kakutani** [comment]
支援はもちろんできます。詳細は追ってで問題ありません！

**Comment by ogom** [comment]
ありがとうございます。よろしくお願いいたします。

**Comment by shyouhei** [comment]
現状: 費用確定を見守る
next action:

- [x] 支援金額が確定する
- [x] 振り込む
- [x] 開催される

**Comment by shyouhei** [comment]
@ogom そのごいかがでしょうか。そろそろお金が動く時期の気がしてきました。

**Comment by ogom** [comment]
@shyouhei スポンサーは1月から募集をしています。2月末であるていどの目処がたつ予定です。

ティザーサイトやCFP募集ページも準備が進んでいます。
https://github.com/rubykansai/kansai2017

**Comment by kakutani** [comment]
順調ですか〜?

**Comment by ogom** [comment]
@kakutani まだまだ準備の序盤ですが順調です。

**Comment by kakutani** [comment]
よかったです :ok_woman: 困りごとなどございましたらカジュアルにご相談くださいませ。

**Comment by kakutani** [comment]
@ogom どこに報告するのがいいかわかんなかったのでこちらで…。CFP募集開始おつかれさまです!

https://rubykansai.doorkeeper.jp/events/57723

> 2016年は京都でRuby会議が開催されて大盛況でした

2013以降、rubykaigi.org でやってるルビーカイギの表記は **RubyKaigi** でお願いします。日本語名称はありません(2011までと2013以降で正式名称が異なっている)。
可能であれば修正いただけると助かります(参加者が混同するのは構わないけれど、運営側としては揃えてもらえるとうれしいです)。

いっぽう、地域Ruby会議プログラムは大きなレギュレーション変更もなく2008年から連綿と続いており、こちらは正式名称は日本語を混ぜるなら「どこそこRuby会議」、ぜんぶ英語で表記するなら「Where RubyKaigi」というかたちになっております。こちらはご参考まで(関西Ruby会議2017, Kansai RubyKaigi 2017)。

**Comment by ogom** [comment]
@kakutani 連絡ありがとうございます。修正の対応は完了しております。
次回にCFP募集のメールを送信するときに、RubyKaigi に誤表記があったことを記載します。

運営側として認識不足で申し訳ございません。今後もフォローをお願いいたします。

**Comment by kakutani** [comment]
> RubyKaigi に誤表記があったことを記載します

そこまでやらなくても大丈夫です!!(シレっとdk.jpのページが直ってればOK!)

**Comment by ogom** [comment]
承知しました。（シレッとDoorkeeperは直っています）

**Comment by kakutani** [comment]
@ogom しつこくすみません、むしろ「開催概要」の表に主催者を明記したほうがよいと思いました。Ruby関西なのでしょうか。表形式になっていると、明示的に載っていないのが気になりました。

**Comment by ogom** [comment]
@kakutani さっそくのフォローありがとうございます。dk.jpのページに主催をRuby関西で明記しました。

**Comment by ogom** [comment]
@shyouhei ご支援の金額ですが、¥60,000 をお願い致します。

会計の担当は 松本(@urimaro) さんです。
Ruby関西の口座がありますので、また連絡いたします。

(現時点で2社からスポンサーの申し出があり、会場費は対応の目処がつきました。)

**Comment by shyouhei** [comment]
現状: @ogom から口座情報が来るのを待っている
next action: まつ

**Comment by urimaro** [comment]
@shyouhei 
会計担当の松本です。
連絡が遅くなってしまい、申し訳ありません。
口座情報は以下のとおりです。

項目 | 情報
--- | ---
銀行名 | りそな銀行 (銀行コード: 0010)
支店名 | 京阪京橋支店 (店番: 109)
科目 | 普通
口座番号 | 0209782
口座名義 | ルビーカンサイ (Ruby関西)

よろしくお願いいたします 🙇

**Comment by takahashim** [comment]
@urimaro 振り込み処理しておきました！
明日には入金されると思います。ご確認ください。

**Comment by urimaro** [comment]
@takahashim 
ありがとうございます。
時間がなくて確認できなかったので、明日確認いたします。

任意団体として口座作ったんですが、個人口座より面倒なことが多くて…😢
<ダイレクトの申し込みなど

**Comment by urimaro** [comment]
@takahashim 
振り込まれていることを確認いたしました。
お忙しい中、ありがとうございました 🙇

**Comment by shyouhei** [comment]
現状: 見守っている
next action: 大詰めのようですが頑張って下さい。些細なことでも、これまでどおりお気軽にご相談いただければ。

**Comment by urimaro** [comment]
@takahashim 
いただいた金額の請求書をお送りした方がよろしいでしょうか？ 🤔

**Comment by shyouhei** [comment]
現状: 見守っている
next action: @urimaro 請求書なくて大丈夫です。何事もなく開催されることをお祈りしています。

**Comment by ogom** [comment]
関西Ruby会議2017が開催されました。そして安全に閉会することができました。会計処理やレポートも順調に進みそうです。ご支援ありがとうございました。

レポートの Issue はこちらです。
https://github.com/rubima/rubima/issues/430

**Comment by shyouhei** [comment]
このチケットは終わっていいのだろうか

なにかあったらreopenします
