### ISSUE TITLE
1 day 5 para 的なイベントをやるとよいのでは

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#248]
Beyond bootcamp的なやつ?

next action: 高橋さんが思いをdumpする

**Comment by shyouhei** [comment]
やるとしたら

- 会場はなんかあるんじゃない
- 名前はない

**Comment by takahashim** [comment]
（この前長文を書きかけたのに誤ってブラウザを閉じてしまってふっとんだので再度気力が溜まったらdumpします…）

**Comment by kakutani** [comment]
まってます 👀

**Comment by takahashim** [comment]
## 気持ち

* 新しい登壇者・スタッフ・参加者を増やしたい
    * 積極的に（コストをかけて）宣伝するかはさておき、興味ある人が気軽に参加できるようにしたい
* それには間口を広げる必要がありそう
* RubyConf 2016はその辺を意識して、新しいspeakerを増やそうとしているように感じた
* また、Rubyに直接関係ないトピックでも気にせずspeakerにしていた
    * そこまで見習う必要があるかどうかは別だけど
* RubyKaigiは「すごいイベント」というブランディングを狙ってる気がしている
    * それはそれで活かしたい
    * その手前のやつがほしい
    * 「いつかはKaigiやその他の世界的イベントで発表したい」という人の通過点になるのがベスト

## コンセプト

* 気軽に参加できる
    * スタッフとしても登壇者としても
* 登壇者を増やすため、セッション数は多めにできるようにする
* 運営はしんどくなくする
    * たぶん1日にすればよいのでは…？
    * その代わりトラック数を増やす
    * トラック数増える分はスタッフ増やす・ゆるくすればなんとかなるのでは
* 参加費もそんなに高くなくする(〜5,000円くらい？ 無料でもいいし有料でも構わない)
* Rubyに直接関係ないセッションもOKにする
* その代わり、間接的でもいいからRubyを使ってたりRubyに関わってたりするものにする
* OKなセッションな例:
    * 「Rubyプロダクト開発で使ってるチーム開発ツール」
    * 「Webアプリの監視の仕方(たまたまRails)」
    * 「RubyistのためのRust入門」
    * 「OpenCVの使い方」(サンプルコードがRuby)
    * 「和音の基礎」(サンプルコードがRuby)
    * 「開発者向け英語の勉強方法」（Rubyプロダクトのレポジトリを例にする）
* BoF・アンカンファレンス的なものもあってもよさそう

**Comment by takahashim** [comment]
↑まずはこんな感じで…

**Comment by hsbt** [comment]
開催する側に回りたい気持ちがあります。名前、RubyHiroba はどうかなあ。

**Comment by takahashim** [comment]
名前についてはちょっと保留というか、もう少し考えてみるということで。

**Comment by shyouhei** [comment]
現状: 周辺事情が固まりつつあるのでそろそろ動けるかもしらぬ…
next action:
- [x] 名前を決める
- [ ] 会場を探す
- こえかけをする
    - [ ] スポンサー
    - [x] 運営コアメンバー

**Comment by kakutani** [comment]
以下、書きかけの国内Rubyカンファレンスのフランチャイズの見立て(独自研究)

### RubyKaigi 2013以降

世界でいちばんすごいRubyのカンファレンス

### 地域Ruby会議

RubyKaigiで拾えないニーズに応えたいと思って2008年に始まったやつで、続くやつは地域のRubyコミュニティが運営にたずさわっている、というのが実証されている(2017年)。

#### “東京Ruby会議”

これはちょっと「特殊」。コミュニティが、というよりは「実行委員長のやりたいかたちのカンファレンスをやる」という実態になってる(これはこれで毎回趣があるので「次にやりたい誰か」のために置いておきたい)。

### RubyHiroba

RubyKaigiの参加者の皆さんがリラックスして交流できる場所として用意しようとしたが時代が追いついておらず、2回やって2回ともCode of Conductに関連するインシデントが発生。
このフランチャイズは歴史的教訓としたい(意見)。

### RubyWorld Conference

松江の、島根の、Rubyはよいものなのですよ、というのを共有する時間。しーまね しまねしまね しまね生まれの しまね しまねっこ

### RUBY BUSINESS USERS CONFERENCE

Rubyをビジネスに活用するが人々集うコミュニティーイベントです。ソフトウェア開発者やビジネス管理者、ユーザーとの交流を通じ、Rubyの活用方法の発見や新たなビジネスを創出できる場を提供します。

http://www.rubybusiness-conf.org/

行ったことないので2/23に視察にいく。

**Comment by amatsuda** [comment]
完全にオフトピで申し訳ないんですが、 http://www.rubybusiness-conf.org/#rbu-keynote-speakers の下の方の「講演者」が"Keynote speakers"になってるのは"Speakers"の間違いなんじゃないかなぁ。
と思うんだけど、誰に言えばいいのかわからん…。

**Comment by kakutani** [comment]
> 誰に言えばいいのかわからん…。

same here.

**Comment by amatsuda** [comment]
とりあえず修吾さんに通報しました(GHのコメント欄にスレッド機能欲しくなるな)。

**Comment by shyouhei** [comment]
@hsbt 柴田さんも呼んでとりあえず各位の思いをdumpしあうのが良いのではという話をしています

**Comment by kakutani** [comment]
@hsbt やりましょー。 @takahashim の都合もあえばぜひ。

**Comment by kakutani** [comment]
### いまのきぶん

* 東京Ruby会議12: 悪くないとおもいはじめているが、「実行委員長」どうするのがいいかな、というのが気になっている。
* RubyHiroba: rebootさせる…????? それもやっぱり悪くないかもしれない。
* 別のなまえ: これでやれるならチ〜フオ〜ガナイザ〜やりたい

↑これは、「日本Rubyの会」が主催するなら(すでにRubyKaigiをやっている団体が別のRubyカンファレンスのフランチャイズをやるなら)という前提でした。

**Comment by kakutani** [comment]
(連絡をとって、Asakusa.rbで @hsbt と話をしましょっかーという流れになった)

**Comment by hsbt** [comment]
@kakutani とランデブーしてコンセプトと、こういう名前でどうか、という一発目の話し合いをゆるーくしました。

**Comment by kakutani** [comment]
名前をかんがえるうえでのフォース:

* RubyKaigiとは異なるものであること明確にしたい("Kaigi"を安易に使わない)
* Rubyのカンファレンスだけど「Ruby Conference」ではない(諸外国のRegional RubyConfとの混同を避ける)
* 他のIT系イベント使われているsuffix,prefixは避けたい(kakutaniの好み; Yet Another, Matsuri, Gatheringなど)
* 名前にRubyistを入れるとスコープが狭くなる気がするから、入れるのはRubyのほうがいい(@takahashim発言要旨)

**Comment by shyouhei** [comment]
それってrubyconferences.orgには掲載しない方向ってことですよね

**Comment by kakutani** [comment]
> それってrubyconferences.orgには掲載しない方向ってことですよね

はい。まずは国内のIT系カンファレンスっぽい感じでいいんじゃないかなーと思ってます。

念頭に置いてる感じはRubyKaigi 2006かせいぜい2008、スピーカー/参加者に日本人っぽくない人がいたとしても大江戸Ruby会議ぐらいのイメージ(わかってて来てくれる人は歓迎)。

**Comment by takahashim** [comment]
Rubyistと言われても良く分からない、あるいは自分はRubyまだまだ詳しくないからRubyistじゃないのでは…という方が気持ちよく参加できるイベントにした方がよいかな？という気持ちでした＜フォース

**Comment by shyouhei** [comment]
next action: 名前を決めたい。どんなに遅くても6月くらいまで

**Comment by kakutani** [comment]
2つ3つ持っていったけど @takahashim からは「んー」という反応だった。視点を変えて考えてみよう…。

決まるまでissueには書かないほうがいいかなとおもうので(闇鍋会場)、
(ゆるぼ: このスレを見ている人で思いついた名前があったら、kakutaniまでタレ込みください)

**Comment by kakutani** [comment]
> どんなに遅くても6月くらいまで

RubyKaigi 2017の後だけど直後ではなく11月を外して、その次のRubyKaigiの直前すぎないタイミングとなると
開催時期の最初のターゲットは12月の前半か18年初頭かなあ、という見立てからの「6月」という数字でした。

**Comment by kakutani** [comment]
その後:
* 名前が決まりました ⚡️ 
* 小さなチームで始めてみます: organizers - @kakutani, @hsbt 💪 
* 2018年陽春開催予定(場所、日程は調整中) 👀 

RubyKaigi 2017の足音も聞こえつつある今日この頃なので、
当面はRubyKaigiに注力することになると思います。

具体的な進展あれば別途issueにて相談します。というわけでこのissueは一旦閉じます。
