### ISSUE TITLE
[Nagoya03] スピーカー募集・問い合わせ用のメールアドレス

### ISSUE THREAD

**Issue by eitoball** [ruby-no-kai/official#250]
`nagoya03@rubykaigi.org` のようなメールアドレスを作成して、指定するメールアドレスに転送して頂くことは可能でしょうか？可能であれば、以下の2アドレスをお願いします。1つだけの場合は、`eitoball` の方をお願いします。

  * `eitoball+nagoya03` _at_ `gmail.com`
  * `dominion525+nagoya03` _at_ `gmail.com`

不可能の場合、良い方法を教えて頂けると助かります。

**Comment by takahashim** [comment]
@eitoball とりあえずruby-no-kai.orgのドメインにグループを作ってみたのですが、そこに登録するアドレスとしてはどうも`+`は使えないようでした…。(ちなみにGoogle Appsを使ってます)

**Comment by eitoball** [comment]
では、

* `eitoball` _at_ `gmail.com`

2つ以上登録できるなら、

* `dominion525` _at_ `gmail.com`

でお願いいたします。

**Comment by takahashim** [comment]
あっと、これってよく見たら`@rubykaigi.org`の方なんですね（ruby-no-kai.orgかと思ってました…）。
これって作れますか？＞ @kakutani さん？

**Comment by kakutani** [comment]
@takahashim はい、やれます(そしていまからやります)

**Comment by kakutani** [comment]
nagoya03 at rubykaigi.org のメーリングリストを作成しました…が、
実態はGoogle Apps(名前これでいいんだっけ)のグループでして、
これは拡張メールアドレスでの追加ができないのでした。

なので、おふたりとも拡張部分ナシのgmail.comのアドレスで追加してあります。
不都合あればお知らせくださいませ。 @eitoball @Dominion525

**Comment by eitoball** [comment]
メール届きました。ありがとうございます。

**Comment by eitoball** [comment]
閉じます
