### ISSUE TITLE
[Nagoya03] Paypal ビジネスアカウントについて

### ISSUE THREAD

**Issue by eitoball** [ruby-no-kai/official#251]
名古屋Ruby会議03 では、Doorkeeper を使って、参加者を募集しようとしています。参加費も集めたいと考えています。Paypal のビジネスアカウントが必要らしいのですが、日本Rubyの会が、アカウントを持っているなら、お借りすることは可能でしょうか？

**Comment by takahashim** [comment]
むむ、これはどうすればいいですかね…？

* Rubyの会のdoorkeeper使う
* Rubyの会のpaypalアカウントを別のdoorkeeperアカウントで使ってもらう

どっちかはいけると思います。

**Comment by takahashim** [comment]
doorkeeperでのオペレーションを考えると後者が便利でしょうか？

**Comment by eitoball** [comment]
すみません。情報が不足していました。Doorkeeper アカウントを持っていますので、Paypal アカウントだけお借りできればと思っています。

**Comment by hsbt** [comment]
railsgirls-jp では、payment アカウントを各地の doorkeeper の管理者(支払い?)アカウントとして普通に使う分には各地におまかせという形にしてますー。

**Comment by takahashim** [comment]
では、

* 名古屋03用のDoorkeeperにRubyの会のpaypalアカウントを登録してもらう
* Doorkeeperの参加募集を締め切った段階でRubyの会から集金した金額を名古屋03の口座に送金
* 名古屋03開催

みたいな流れでキャッシュフロー的には問題ないでしょうか。

**Comment by eitoball** [comment]
こちらの件、如何でしょうか？お忙しい中、お手数かけ、申し訳ありませんが、お返事よろしくお願いいたします。

**Comment by takahashim** [comment]
@eitoball う、「問題ないでしょうか」は名古屋03の準備をされてる方々の方で問題ないかどうか（要はお金が入るのがDoorkeeper参加募集終了後になるけれどそれで困らないか）というつもりだったのでした…

**Comment by eitoball** [comment]
😭 すみません…理解力が不足していました。募集終了後で問題ありません。よろしくお願いします。

**Comment by takahashim** [comment]
nagoya03 [at] rubykaigi.org の方にお送りしました！

**Comment by eitoball** [comment]
メールを確認しました。ありがとうございます。:bow:

> Doorkeeperの参加募集を締め切った段階でRubyの会から集金した金額を名古屋03の口座に送金

こちらは、その時になりましたら、別途、issue を作成します。
