### ISSUE TITLE
Cookpad さんへ RailsGirls 年間スポンサーの請求書を発行してほしい

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#252]
@takahashim 別途メールにてご連絡している件について請求書 PDF の発行をお願いします... 🙇 

* 金額は 15 万円
* 請求先は Tokyo 5th (http://railsgirls.com/tokyo-2015-09-12) で発行した際の cookpad さんの請求先でお願いします
* 12/19 までに欲しいとのことなので早めに作成をお願いします 🙏

**Comment by takahashim** [comment]
@hsbt どうもTokyo 5thのときのspreadsheetが見えなくなっているような…とりあえず請求書は作ります

**Comment by hsbt** [comment]
oh... 調べてわからなかったら聞いちゃいます!

**Comment by takahashim** [comment]
こちらとりあえずPDFで発行して確認待ち。

**Comment by shyouhei** [comment]
現状: PDF送ったら、それで通っちゃったので、入金済み
next action: なし?

**Comment by hsbt** [comment]
あ、next action: は RailsGirls JP の口座に資金を移動する、です!

@takahashim そこまで含めて完了でしょうか?

**Comment by takahashim** [comment]
@hsbt あれ、RGJPには12/28に入金したような‥と思ったら、これは別のやつだったんですね。たいへん失礼しました… 🙇 
こちらの年間スポンサーの分も先ほど入金しました。ご確認ください。

**Comment by hsbt** [comment]
確認しました! ありがとうございます。
