### ISSUE TITLE
RailsGirls Kyoto 6th のスポンサー費用請求

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#253]
11/26 開催の http://railsgirls.com/kyoto のスポンサー費用の請求をお願いしたいです。
(請求先はメールで共有させていただきました)

- [x] 請求する
- [x] 精算する
- [x] 入金確認する

**Comment by takahashim** [comment]
@springaki 対応しました！　RG口座への入金は明日になる予定です

**Comment by springaki** [comment]
@takahashim 了解です。いつもありがとうございます !!

**Comment by shyouhei** [comment]
現状: 精算済み、請求済み、入金待ち
next action: 入金を待つ

**Comment by shyouhei** [comment]
現状: 入金待ち
next: もうちょっと待つ

**Comment by springaki** [comment]
3分の2 が初めての企業様なので、手違いで原本待たれていたりするのでしょうか。うーん...気になる...

**Comment by shyouhei** [comment]
現状: 入金待ち。misocaは送信済みになってる模様
next: さすがに確認したほうがよさそうな気がしてきた…

**Comment by takahashim** [comment]
RGのMLの方に投げておきました。

**Comment by springaki** [comment]
先方に問い合わせ中ですー

**Comment by springaki** [comment]
先方で対応漏れがあったようで、これから手続き開始してもらいます。
早くても4月7日 入金とのこと。

**Comment by takahashim** [comment]
こちら入金確認いたしました！！

**Comment by springaki** [comment]
ありがとうございました ! 😊
