### ISSUE TITLE
[Nagoya03][質問]名古屋Ruby会議03 のスポンサー費用の請求について

### ISSUE THREAD

**Issue by eitoball** [ruby-no-kai/official#254]
表題の件ですが、RailsGirls と同様に 日本Rubyの会で請求して頂けますでしょうか？

**Comment by takahashim** [comment]
@eitoball はい、請求書を出すのに必要な情報をいただければそれで対応いたします！

**Comment by eitoball** [comment]
ありがとうございます。会議終了後にメールでお伝えして、issue を作成するようにします。
