### ISSUE TITLE
ruby-no-kai.orgのSSL化

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#255]
なんとなくあらゆるサイトのSSL化をした方がよさそうという雰囲気を感じています。
こちらのDNSもcloudflareに持っていくといいんでしょうか。

**Comment by kakutani** [comment]
> こちらのDNSもcloudflareに持っていくといいんでしょうか。

なるほど、それでやれるならそれでよさそう。

**Comment by kakutani** [comment]
rk.orgではありませんが、regionalのほうで、大江戸06でregional.rk.orgからgh-pagersで作ったページ(https)にproxy_passしようとすると期待と異なる動作をする、という問題にでくわしました。

**Comment by takahashim** [comment]
@kakutani お、それって無事に解決しました？

**Comment by kakutani** [comment]
@takahashim まだです! cloudflareのアクセス情報ってdropboxにあるんでしたっけ…

**Comment by takahashim** [comment]
はい、ありますよ

**Comment by kakutani** [comment]
時間つくって見てみます!

**Comment by shyouhei** [comment]
現状: とりあえず緊急の案件はないが方向性としては進めていく
next action: かくたにさんから大江戸06の知見をシェアしてもらう

**Comment by kakutani** [comment]
rubykaigi.orgとregional.rubykaigi.orgについては ruby-no-kai/rko-router#23 に現状をまとめました。

ruby-no-kai.orgはgh-pagesだけなので証明書を用意すればなんとかなるのでは、と思えてきました。
(cloudflareで面倒みてくれそう)

**Comment by shyouhei** [comment]
現状: 動きなし
next action: 急ぎではないけど、必要になる前に練習しておきたい思いはある

**Comment by shyouhei** [comment]
現状: 動きなし
next action: ruby-no-kai/rko-router#23 を注視していく

**Comment by shyouhei** [comment]
現状: 動きなし
next action: ruby-no-kai/rko-router#23 を注視していく

**Comment by shyouhei** [comment]
現状: 動きなし
next action: ruby-no-kai/rko-router#23 を注視していく

**Comment by shyouhei** [comment]
現状: 動きなし
next action: ruby-no-kai/rko-router#23 を注視していく

**Comment by shyouhei** [comment]
現状: 動きなし
next action: ruby-no-kai/rko-router#23 を注視していく

**Comment by takahashim** [comment]
next action: ruby-no-kai/rko-router#23 を注視していく

**Comment by kakutani** [comment]
次回までになんか進捗させます

**Comment by shyouhei** [comment]
next action: ruby-no-kai/rko-router#23 を注視していく

**Comment by shyouhei** [comment]
現状:RubyKaigiに向けて動き出さないとな
next action: ruby-no-kai/rko-router#23 を注視していく

**Comment by shyouhei** [comment]
現状: 動きなし
next action: ruby-no-kai/rko-router#23 を注視していく

**Comment by takahashim** [comment]
next action: タイミングを見てえいやっとやってみる

**Comment by springaki** [comment]
@snoozer05 さんがやってくれた。https://ruby-no-kai.org/

**Comment by snoozer05** [comment]
regional.rubykaigi.org がまだ

**Comment by snoozer05** [comment]
どこかで時間を作って状況の整理からやる必要がある。

**Comment by springaki** [comment]
ref. https://github.com/ruby-no-kai/rko-router/issues/23

**Comment by springaki** [comment]
現状: 動きなし
next action: 順次やっていく

**Comment by springaki** [comment]
現状: 動きなし
next action: 確認しつつ順次やっていく

ref. ruby-no-kai/rko-router#23

**Comment by kakutani** [comment]
一旦このissueとしては完了な気がする。個別になんかでれば個別でやればいいのかなあ。
