### ISSUE TITLE
[Nagoya03][質問]名古屋Ruby会議03 のスポンサー費用の見積もりについて

### ISSUE THREAD

**Issue by eitoball** [ruby-no-kai/official#256]
名古屋Ruby会議03に協賛して下さる企業様から、決済手続きのため、見積書の提出を依頼されています。こちらで見積書を作成して提出しても構いませんでしょうか？それとも、日本Rubyの会の方で提出する方がよいのでしょうか？スポンサー費用の請求が日本Rubyの会からになるため（ #254 ）聞いています。

**Comment by kakutani** [comment]
やりやすいほうでいいかなあと思ってます:

* 名古屋03側で作る: 先方に送ったものを info at ruby-no-kai.org にもccしてください
* 日本Rubyの会側で作る: 宛先, 金額など必要そうな情報を info at ruby-no-kai.org に送ってください

どちらでも対応できます!

**Comment by eitoball** [comment]
> 名古屋03側で作る: 先方に送ったものを info at ruby-no-kai.org にもccしてください

でやります。ありがとうございます。
