### ISSUE TITLE
OedoRubyKaigi06 のスポンサー請求依頼

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#257]
https://github.com/ruby-no-kai/official/issues/243#issuecomment-278482452 にコメントがありますが、大江戸 Ruby 会議 06 に協賛いただける企業がありますので、請求書の発行をお願いしたいです。発行に関する詳細内容は別途 @takahashim に送ります。

**Comment by hsbt** [comment]
と思ったんですが、クックパッドさんなので、RG などで請求している内容で 300,000 JPY な請求書の作成をお願いできますでしょうか。

今後は

 * PDF を作成してもらって、@hsbt (実際には @amatsuda かな)からクックパッドへ
 * 振込は Ruby の会へ
 * 会場費として立て替えていただいている金額からスポンサー費用を相殺

という感じにして、残金を Asakusa.rb から支払いというように進めていきたいです。

@takahashim 

いかがでしょうかー

**Comment by takahashim** [comment]
🙆 了解です！

**Comment by shyouhei** [comment]
現状：準備はできた
next action: PDFをなげる

**Comment by shyouhei** [comment]
現状: PDFは送付したような
next action: 請求が通っているか確認する。

**Comment by shyouhei** [comment]
現状: 請求した
next action: 入金待ち

**Comment by shyouhei** [comment]
現状: 入金が確認できた

ありがとうございました
