### ISSUE TITLE
名古屋Ruby会議03残務 スピーカー旅費宿泊費の精算

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#258]
参照 #245

**Comment by takahashim** [comment]
@eitoball こちらの金額ですが、
https://github.com/ruby-no-kai/official/issues/245#issuecomment-271061172
の概算通りでよいですか？　また振込先についても #259 と同じでよいでしょうか？

**Comment by eitoball** [comment]
@takahashim 

旅費・宿泊費は、大丈夫になりました。ご報告が遅れて申し訳ありません。

**Comment by shyouhei** [comment]
@eitoball これは振り込み不要でしょうか、このチケット閉じてしまっていいですか?

**Comment by eitoball** [comment]
@shyouhei  不要です。閉じて下さい。よろしくお願いします。

**Comment by snoozer05** [comment]
閉じますー
