### ISSUE TITLE
名古屋Ruby会議03残務: 参加費の精算

### ISSUE THREAD

**Issue by snoozer05** [ruby-no-kai/official#259]
ref #245

**Comment by eitoball** [comment]
こちらから、金額と振り込みの口座を info _at_ の方へ送ります。

**Comment by eitoball** [comment]
「[名古屋Ruby会議03] 参加費の精算」という件名で、メールを info __at__ の方へ送りました。よろしくお願いします。

**Comment by takahashim** [comment]
@eitoball お待たせしました、こちら先ほどお振り込みいたしました。

**Comment by shyouhei** [comment]
現状: 振り込まれているはず
next action: @eitoball ご確認ください。問題なければチケット閉じましょう

**Comment by eitoball** [comment]
> ご確認ください。問題なければチケット閉じましょう

確認しました。問題ありません。

**Comment by snoozer05** [comment]
閉じます
