### ISSUE TITLE
名古屋Ruby会議03残務 スポンサー請求

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#260]
参照: #245 #254 #256 

* [x] 請求する
* [x] 入金確認する
* [ ] 精算する

**Comment by shyouhei** [comment]
これ結局どうなってるんでしょう…

@eitoball ちょっと状況整理しませんか

**Comment by eitoball** [comment]
> ちょっと状況整理しませんか

@shyouhei ありがとうございます。info _at_ の方へ、詳細をメールさせて頂きます。

**Comment by eitoball** [comment]
「[名古屋Ruby会議03] 協賛費用の請求のお願い」という件名で、請求をお願いしたい会社様の情報をCSVファイルで添付して、info __at__ の方へ送付しました。よろしくお願いします。

**Comment by eitoball** [comment]
CSVファイルを添付したメールは届きましたでしょうか？CSVファイルに不足はないでしょうか？宜しくご確認下さい。後、2月末までには会社様に届けたいなぁという気持ちです。お忙しい中、申し訳ありませんが、宜しくお願いします。

**Comment by takahashim** [comment]
@eitoball お返事遅くてすみません、こちらは昨日misocaに突っ込んでおいたので、今週中には確認してメールでお送りする予定です…と思ってたんですが、1社は早めに送った方がよいですね。メールします。

**Comment by eitoball** [comment]
@takahashim 請求書の送付ありがとうございます。最初にCSVファイルに誤りがありました。申し訳ありません。訂正して頂きたい内容を info __at__ rubykaigi.org の方へ送りましたので、お手数ですが、再度、発行して下さい。よろしくお願いします。

**Comment by eitoball** [comment]
修正された請求書をメールにて受け取りました。ありがとうございました。

質問があります。消費税と振込手数料に関してですが、今回、発行して頂いた請求書は、本編のRubykaigiと同じでしょうか？よろしくお願いします。

**Comment by takahashim** [comment]
@eitoball なんか途中で切れちゃってるようですが…消費税についてはRubyの会は課税事業者なので、地域Ruby会議に関しても請求書は消費税は別に記載しています。振込手数料も別扱いですね。

**Comment by eitoball** [comment]
> 消費税についてはRubyの会は課税事業者なので、地域Ruby会議に関しても請求書は消費税は別に記載しています。振込手数料も別扱いですね。

回答ありがとうございます！

> なんか途中で切れちゃってるようですが…

（消したつもりでしたが、消えていませんでした…）

**Comment by takahashim** [comment]
@eitoball こちらメールした通りで明日28日に請求書出そうと思うのですが良いでしょうか…？

**Comment by eitoball** [comment]
@takahashim メール確認させて頂きました。メールの内容通りでお願いします。

**Comment by takahashim** [comment]
@eitoball こちら一通りお送りいたしましたっ

**Comment by takahashim** [comment]
@eitoball こちらの振り込みも #259 と同じ口座でよいですか？

**Comment by hsbt** [comment]
GMO ペパボ 届きましたので処理進めます(届いたという報告)

**Comment by eitoball** [comment]
@takahashim 

> こちらの振り込みも #259 と同じ口座でよいですか？

同じ口座でお願いします。

**Comment by shyouhei** [comment]
現状: 請求書送付済、入金待ち
next action: まつ

**Comment by takahashim** [comment]
精算の方、週明けに口座に入金されるよう指示を出しておきました

**Comment by eitoball** [comment]
入金を確認しました！ありがとうございます。

**Comment by shyouhei** [comment]
終わっていた
