### ISSUE TITLE
RubyKaigi下見第一回精算 #2017

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#261]
- [x] 下見実施
- 金額の確定
  - 旅費
      - [x] 卜部立替え払い
      - [x] 松田さん立替え払い
      - [x] 角谷さん立替え払い
  - [x] 宿泊費 松田さんが払った
  - [x] 会議費 角谷さんが払った
- 領収書を高橋さんに渡す
  - [x] @shyouhei
  - [x] @amatsuda
  - [x] @kakutani 
- [x] 振り込む

**Comment by shyouhei** [comment]
現状: 領収書が渡った人もいる
next action: よろしくおねがいします

**Comment by shyouhei** [comment]
現状: まつださんのやつ以外は振込み済み
next action: まつださんのやつを精算

**Comment by amatsuda** [comment]
あー、そうだー。新幹線の領収書をたぶん紛失したっぽいです。どうしよう。
あと、宿の立替分もまだだったのでした。すいません。

**Comment by takahashim** [comment]
@amatsuda 交通費は領収書なければ伝票を起こすので、金額とかだけでもesaに書いておいてください！

**Comment by shyouhei** [comment]
現状: 動きなし
next action: @amatsuda よろしくお願いします。

**Comment by shyouhei** [comment]
現状: 旅費は払った。宿泊費がまだ
next action: よろしくおねがいします。

**Comment by shyouhei** [comment]
現状: 宿泊費がまだ
next action: 現状確認する。領収書がどこまで到達しているか?

**Comment by takahashim** [comment]
next action: 宿泊費を精算すれば終わるはず

**Comment by takahashim** [comment]
領収書受領しました！
