### ISSUE TITLE
RubyKaigi下見第一回精算 #2018

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#262]
- [x] 下見実施
- 金額の確定
  - 旅費
      - [x] 卜部
      - [x] 松田さん
      - [x] 角谷さん
  - [x] 会議費
- 領収書を高橋さんに渡す
  - [x] @shyouhei
  - [x] @amatsuda
  - [x] @kakutani 
- [x] 振り込む

**Comment by shyouhei** [comment]
現状: 領収書が渡った人もいる
next action: よろしくおねがいします

**Comment by shyouhei** [comment]
現状: まつださんのやつ以外は振込み済み
next action: まつださんのやつを精算

**Comment by shyouhei** [comment]
現状: 動きなし
next action: よろしくおねがいします。

**Comment by shyouhei** [comment]
現状: 動きなし
next action: よろしくおねがいします。

**Comment by takahashim** [comment]
next action: 宿泊費を確認する

**Comment by shyouhei** [comment]
現状: この下見は日帰りだった。ので宿泊費はない。
next action: 交通費を払う

**Comment by shyouhei** [comment]
現状: 動きなし
next action: 交通費を払う

**Comment by shyouhei** [comment]
現状: まだだった
next action: 交通費を払う

**Comment by takahashim** [comment]
支払いました！
