### ISSUE TITLE
RailsGirls Matsue 3rd のスポンサー費用請求 

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#264]
3/3 開催の RailsGirls Matsue 3rd のスポンサー費用の請求をお願いしたいです。

@takahashim メールにて共有しましたが、一部の企業様から 3/31 までに請求書を欲しいと要望されているので、対応をお願いしたいです。よろしくお願いします !

- [x] 請求する
- [x] 精算する
- [x] 入金確認する

**Comment by takahashim** [comment]
@springaki こちら了解です！
ちなみに３月末を入金期限にしたいところは早めに送りますが、請求書に書かれるお支払期限は4月に統一してもよいですか？

**Comment by springaki** [comment]
@takahashim ありがとうございます。確かに入金期限を短く設定する意味はあまりなさそうですね(年度末に入金してもらえばいいだけ)。
確認します !  ( > @AyakoMakihara さん)

**Comment by AyakoMakihara** [comment]
@takahashim ご対応、ありがとうございます。また、年度内支払をご希望の会社様へもご配慮いただき、助かります。お支払期限は４月に統一で大丈夫です :smile: よろしくお願いします！

**Comment by takahashim** [comment]
@springaki @AyakoMakihara ありがとうございます、では郵送の企業さまには先ほど郵送指示しましたので、明日発送される予定です。（メール送付の企業さまは後で送ります）

**Comment by AyakoMakihara** [comment]
@takahashim 早々に対応頂き、安心しました！ありがとうございます 🐰

**Comment by springaki** [comment]
@takahashim ありがとうございます 😊

**Comment by takahashim** [comment]
こちらメールの方も一通り請求しました。

**Comment by AyakoMakihara** [comment]
@takahashim スポンサー様への請求書発行連絡を行いました :smile_cat: ありがとうございます！

**Comment by shyouhei** [comment]
現状: 請求書送付済、入金待ち
next action: まつ

**Comment by shyouhei** [comment]
現状: 請求書送付済、入金待ち
next action: 引き続き待つ

**Comment by shyouhei** [comment]
現状: 請求書送付済、入金待ち
next action: そろそろ入金されてきててもいい頃? 要確認

**Comment by shyouhei** [comment]
現状: たぶん来てるんじゃないかな、要確認
next action: 確認する

**Comment by shyouhei** [comment]
現状: きてない…
next action: 督促へと

**Comment by AyakoMakihara** [comment]
@shyouhei 大変ご迷惑をおかけしております。どこの会社かわかりましたら、私からも窓口担当者へ確認させて頂きます 😭

**Comment by shyouhei** [comment]
現状: きてない…
next action: 槇原さんと状況共有しつつ進める

**Comment by AyakoMakihara** [comment]
@shyouhei 了解しました 😭 情報共有、おねがいします！

**Comment by AyakoMakihara** [comment]
@shyouhei @springaki 振込未の会社さんに確認しました。メールの見落としがあったようです 😭 請求書の再発行をお願いしたいです！！お手数おかけしますが、よろしくお願いします 🐰

**Comment by springaki** [comment]
@AyakoMakihara おぉ連絡ついてよかったです。ありがとうございます。請求書再発行は @takahashim さんかな？

**Comment by takahashim** [comment]
@AyakoMakihara @springaki 了解です、請求書の方はメールで先ほど再発行しました

**Comment by AyakoMakihara** [comment]
@takahashim ありがとうございました 😺

**Comment by takahashim** [comment]
請求書は再発行したので入金されていれば完了
next action: 入金を確認する

**Comment by takahashim** [comment]
入金確認できました！
