### ISSUE TITLE
RailsGirls Osaka 4th のスポンサー費用請求

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#265]
2/17 開催の [RailsGirls Osaka 4th](http://railsgirls.com/osaka) スポンサー費用の請求をお願いしたいです。
(請求先はメールで共有させていただきました)

- [x] 請求する
- [x] 精算する
- [x] 入金確認する

**Comment by takahashim** [comment]
こちらも一通り請求しました。

**Comment by shyouhei** [comment]
現状: 請求書送付済、入金待ち
next action: まつ

**Comment by hsbt** [comment]
:memo: RG の口座にスポンサー収入分を振り込んでもらったが 21600 余分に振り込まれていたので返金します。

**Comment by takahashim** [comment]
お手数おかけします 🙏

**Comment by hsbt** [comment]
本日返金済みです!

**Comment by takahashim** [comment]
@hsbt 入金確認いたしました、ありがとうございます！

**Comment by shyouhei** [comment]
現状: 請求書送付済、入金待ち
next action: まだまつ

**Comment by shyouhei** [comment]
現状: 請求書送付済、入金待ち
next action: そろそろ入金されてきててもいい頃? 要確認

**Comment by shyouhei** [comment]
現状: まだ入金されてないのがありそう
next action: 確認する

**Comment by shyouhei** [comment]
現状: きてない…
next action: 督促へと

**Comment by springaki** [comment]
むむむ...なんでだろ... 必要そうでしたらこちらからも ping できます。
(頻発すると何かオペレーションに問題あるのかと思ってしまいますね)

**Comment by shyouhei** [comment]
現状: きてない…
next action: RGのMLのほうに投げれば良い?

**Comment by springaki** [comment]
うーむ...
はい。railsgirlsjp-invoice _at_ googlegroups.com にて共有いただければ。

**Comment by shyouhei** [comment]
現状: MLに共有済み
next action: MLで進行中

**Comment by takahashim** [comment]
next action: 入金を確認する

**Comment by shyouhei** [comment]
現状: 2回目の入金待ち
next action: 様子見

**Comment by takahashim** [comment]
こちら入金確認できました！

**Comment by hsbt** [comment]
回収ありがとうございます 🙇
