### ISSUE TITLE
RailsGirls Kyoto 7th のスポンサー費用請求

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#266]
3/10 開催の [RailsGirls Kyoto 7th](http://railsgirls.com/kyoto201703) スポンサー費用の請求をお願いしたいです。
(請求先はメールで共有させていただきました)

- [x] 請求する
- [x] 精算する
- [x] 入金確認する

どうぞよろしくお願いします。

**Comment by shyouhei** [comment]
現状: 請求書送付作業中
next action: まつ

**Comment by takahashim** [comment]
こちらも遅くなりましたが請求いたしましたっ

**Comment by springaki** [comment]
ありがとうございます !

**Comment by shyouhei** [comment]
現状: 請求書送付作業中
next action: まつ

**Comment by shyouhei** [comment]
現状: 請求書送付済、入金待ち
next action: そろそろ入金されてきててもいい頃? 要確認

**Comment by shyouhei** [comment]
現状: たぶん来てるんじゃないかな、要確認
next action: 確認する

**Comment by takahashim** [comment]
こちらは入金確認できました
