### ISSUE TITLE
RedDotRubyConfの渡航支援対象を選ぶ

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#267]
#238 の募集第1弾。

https://github.com/ruby-no-kai/official/wiki/OverseasRubyConfTravelGrant2017

CFP deadline: 3/15,会期が 6/22-23 なので、4〜5月で様子をみていくかんじ?
(あまり直前だと航空券や宿が高くなるから余裕をもって決められるとよさそう)

**Comment by kakutani** [comment]
応募がきた!

**Comment by kakutani** [comment]
選んだので連絡します

**Comment by shyouhei** [comment]
選んだ。

next action: @kakutani 当落通知お願いします

**Comment by kakutani** [comment]
メールした。ackが帰ってきたら詳細を先方と相談します。

**Comment by shyouhei** [comment]
現状: @kakutani 進捗してますでしょうか

**Comment by shyouhei** [comment]
うっ。そろそろだ
next action: @takahashim のほうからコンタクトをとってみる

**Comment by takahashim** [comment]
こちらコンタクトをとって対応中です。帰国後に精算予定。

**Comment by takahashim** [comment]
旅費宿泊費を教えていただいたので振り込みました！

**Comment by shyouhei** [comment]
現状: 無事開催された
