### ISSUE TITLE
RailsGirls Kitakyusyu 1st のスポンサー費用請求

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#269]
3/10 開催の [RailsGirls Kitakyusyu 1st](http://railsgirls.com/kitakyushu.html) のスポンサー費用の請求をお願いしたいです。
(請求先はメールで共有させていただきました)

- [x] 請求する
- [x] 精算する
- [x] 入金確認する

**Comment by springaki** [comment]
大変申し訳ないのですが、1社様が早急に請求書を送ってほしいとのことです。ご対応可能でしょうか...
(メールで共有しました)

**Comment by takahashim** [comment]
@springaki メールでもよいでしょうか？

**Comment by springaki** [comment]
(オーガナイザーの方に確認していただきました) 
PDF、郵送のどちらも希望されるようです。取り急ぎPDFをメールで。その後原本も郵送して欲しいとの事です。

お手数お掛けして申し訳ありません...

**Comment by takahashim** [comment]
あ、そうですね、両方の意味でした（今月中に届くのがメールとというつもり）
ではメールの方は本日中で、郵送が届くのはたぶん来週になるかと思います。

**Comment by springaki** [comment]
ありがとうございます。よろしくお願いします !

**Comment by takahashim** [comment]
1社さまのメールは送付しました。残りも今晩中にできれば…。

**Comment by springaki** [comment]
対応ありがとうございます !

**Comment by takahashim** [comment]
郵送分と残りの会社さんの分も処理しておきました。
郵送分はタイムラグがあって、たぶん来週に発送されるはずです。

**Comment by springaki** [comment]
了解しました ! ありがとうございます 😊

**Comment by shyouhei** [comment]
現状: 請求した。入金待ち
next action: 精算を先にやる

**Comment by shyouhei** [comment]
現状: 請求した。入金待ち。未清算。
next action: 東京と合わせて清算する。

**Comment by shyouhei** [comment]
現状: 精算は終わった。入金を確認中。
next action: 引き続き入金を待つ。

**Comment by shyouhei** [comment]
現状: きてない…
next action: 督促へと

**Comment by shyouhei** [comment]
現状: きてない…
next action: RailsGirlsのほうへ情報共有

**Comment by shyouhei** [comment]
現状: MLに共有済み
next action: MLで進行中

**Comment by takahashim** [comment]
next action: 入金を確認する

**Comment by shyouhei** [comment]
現状: 2回目の入金待ち
next action: 様子見

**Comment by takahashim** [comment]
こちらも全件入金確認できました！！

**Comment by hsbt** [comment]
回収ありがとうございます 🙇
