### ISSUE TITLE
Update Ruby FAQ(in Japanese)

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#27]
旧リファレンスマニュアルにあったRuby FAQがメンテナンスされていない状態なので、何とかする。
- http://www.ruby-lang.org/ja/old-man/html/Ruby_FAQ.html

場合によっては、内容を「一般的な質問」と「Rubyの処理系について」くらいとかに整理して、残りの個々の機能的な部分は落としてしまうでもいいかも。

**Comment by snoozer05** [comment]
置く場所はどうとでもなるので、メンテナンスするコストの方が問題

**Comment by kakutani** [comment]
置くなら、ruby-no-kai.org に置くのがいいのかなあ(やっぱり置き場所はどうとでもなる気がするな)

**Comment by kakutani** [comment]
なかなか手が動かんので、

> 場合によっては、内容を「一般的な質問」と「Rubyの処理系について」くらいとかに整理して、残りの個々の機能的な部分> は落としてしまうでもいいかも。

この作戦がいいと思います。機能の話は、いまは良い本がいっぱいあるからそっちに任せたい。

**Comment by takahashim** [comment]
https://github.com/ruby-no-kai/official/wiki/Ruby-FAQ

**Comment by takahashim** [comment]
MLで報告したらcloseでいいかも

**Comment by snoozer05** [comment]
MLで報告するのはどのタイミングですかねぃ

**Comment by kakutani** [comment]
[ruby/www.ruby-lang.org#94](https://github.com/ruby/www.ruby-lang.org/issues/94) とか [ruby/www.ruby-lang.org#234](https://github.com/ruby/www.ruby-lang.org/issues/234) にissueがあるので、あっちでやるのが筋な気がする!

**Comment by shyouhei** [comment]
続きは ruby/www.ruby-lang.org#94 で！
