### ISSUE TITLE
永和システムマネジメントからの RG スポンサーの申し出の対応(2017)

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#271]
永和システムマネジメント様より、 RG 全体の年間スポンサーとして 10 万円を拠出したいとの申し出を受けたため、10 万円の請求書を発行していただきたいです。発行先住所は https://github.com/ruby-no-kai/official/issues/235 と同様でお願いします...!

発行に合わせて 10 万円の資金移動もお願いします 🙏 

- [x] 請求する
- [x] 入金確認する
- [x] 資金移動する

**Comment by takahashim** [comment]
@hsbt 請求と移動まで行いました！

**Comment by hsbt** [comment]
いつもありがとうございます...!

**Comment by shyouhei** [comment]
現状: 請求済み、入金待ち
next action: まつ

**Comment by shyouhei** [comment]
現状: 入金確認済
