### ISSUE TITLE
RailsGirls Tokyo 7th のスポンサー費用請求

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#273]
3/25 開催の RailsGirls Tokyo 7th スポンサー費用の請求をお願いしたいです。
(請求先はメールで共有させていただきました)

* [x] 請求する
* [x]  精算する
* [x]  入金確認する

どうぞよろしくお願いします。

**Comment by hsbt** [comment]
(急ぎませんが資金移動も併せてお願いします... 🙏  )

**Comment by shyouhei** [comment]
現状: 未請求
next action: 請求する/あわせて資金移動

**Comment by emorima** [comment]
こちら、スポンサー申し込みサイト内にて、4/28入金期限と記載があったため、
請求書についてのお問い合わせが、オーガナイザーへあったようです。

今週末からGWに入るので、請求書については、GW明けくらいとお伝えしておいて、問題ないでしょうか？

**Comment by attsumi** [comment]
@hsbt @shyouhei @takahashim 
おつかれさまです。7th オーガナイザーの渥美です。
精算のご対応いただき、ありがとうございます！

江森さんにご共有いただいておりましたように、
4/28を請求期限としていたため、
取り急ぎ、今回のスポンサー様（除く年間スポンサー様）に
「発行がGW連休以降となる見込み」とメールしました。
（請求期限が変わるので、請求書送付の際
　期限について軽く触れていただけると助かります）

共有までとなります。
お忙しい中お手数をおかけいたしますが、どうぞよろしくお願いいたします。

## 下記お送りしたメール
```
【件名：Rails Girls Tokyo 7th ご請求書につきまして】
お世話になります。Rails Girls Tokyo 7th オーガナイザーの渥美です。
Rails Girls Tokyo 7thでは、ご協賛いただき、ありがとうございました。
表題の件につきまして、
現在、請求書発行準備中につき、発行がGW連休以降となる見込みです。
（日本Rubyの会より発行を行います）
大変お待たせしており、申し訳ございません。
入金期限につきましては、請求書と合わせて、
改めて担当者よりご連絡をさせていただきます。

ご連絡が大変遅くなり、
恐縮ですが、何卒よろしくお願いいたします。
```

## お送りしたスポンサー様
- SideCI（株式会社アクトキャット）
- 株式会社キュー
- 株式会社シーキューブ・プランニング(Paypal）
- GMOペパボ株式会社 
- Fablic 
（ケーシーエスキャロット様については、江森さんが窓口・メール送信不要とのことだったのでお送りしませんでした）

**Comment by takahashim** [comment]
ううう、すみません、こちらGW中には発行できると思います

**Comment by attsumi** [comment]
@takahashim 
とんでもございません！ご対応ありがとうございます。
（スポンサー様に一報いれ、ご安心いただくための対応ですので
どうかお気になさらず....!!!）

**Comment by takahashim** [comment]
こちら昨日一通り対応しまして、メールは送付済み、郵送は明日くらいに発送される予定です。

**Comment by attsumi** [comment]
@takahashim ありがとうございます！！！

**Comment by shyouhei** [comment]
現状: 請求済み、入金待ち、未清算
next action: 北九州と合わせてまずは清算

**Comment by shyouhei** [comment]
現状：請求済み、精算済み、未入金
next action: 入金を待つ

**Comment by takahashim** [comment]
こちらも入金確認できました
