### ISSUE TITLE
ぎんざRuby会議01 開催

### ISSUE THREAD

**Issue by y-yagi** [ruby-no-kai/official#274]
お世話になります。Ginzarb の @y-yagiと申します。
初めてのぎんざRuby会議の開催を以下の要領にて計画しております。

名称： ぎんざRuby会議01
開催日： 2017/08/05 (土)
テーマ: Rails 
会場： 株式会社みんなのウェディング様 会議室
参加費： 検討中
配信： なし
定員: 80名程度
実行委員長：工藤研一 (@ken1flan)
会計: @y-yagi
るびまのレポート記事担当： 未定
サイト： http://ginzarb.github.io//kaigi01

開催にあたり、HPの作成の外注、及び、スポンサーを募集する事を検討しております。 
すでに @ken1flanからご相談させて頂いておりますが、請求書の発行についてご相談させて頂けると助かります。
詳細が決まり次第、別途ご連絡させて頂きますので、宜しくお願いいたします。

**Comment by kakutani** [comment]
> 開催にあたり、HPの作成の外注、及び、スポンサーを募集する事を検討しております。
> すでに @ken1flanからご相談させて頂いておりますが、請求書の発行についてご相談させて頂けると助かります。
> 詳細が決まり次第、別途ご連絡させて頂きますので、宜しくお願いいたします。

はーい。 @ken1flan からうかがっておりまーす。状況の進行については適宜issueに書いてもらえると助かります(ここに書かれれば忘れ去られることはない)。公開issueにはそぐわない内容とかは info at ruby-no-kai dot org 宛のメールでご連絡いただければと思います。
(なお、状況の進行や催促はissueでやってもらえるほうが確実です)

**Comment by y-yagi** [comment]
ご確認有難うございます！
諸々了解しました。 状況の進行については、適宜こちらのissueに記載させて頂きます。

**Comment by shyouhei** [comment]
現状: スポンサー請求は他と同じ流れでいいと思われる、サイト受発注は…? 契約主体とか?
next action: サイト発注先とちょっと打ち合わせしないと

**Comment by kakutani** [comment]
行間をissueの文字列で伝えきれるか自信がないので @ken1flan にも相談しにいきますー。

**Comment by shyouhei** [comment]
@kakutani @ken1flan これ決まった内容dumpしてもらえませんでしょうか

**Comment by y-yagi** [comment]
HP公開しましたのでご連絡させて頂きます。
https://ginzarb.github.io//kaigi01/

@kakutani 
状況把握出来ておらず申し訳無いのですが、サイト発注の件についてこちらで何かすべきことはありますでしょうか？ 
なお、サイト作成は、合同会社 esa の赤塚さん(taea)にお願いしております。

**Comment by shyouhei** [comment]
@y-yagi 当然お金かかってますよね。支払いは済んでます? まだです? 当初「請求書の発行についてご相談させて頂けると助かります」とおっしゃっていたため、契約詳細が分からないと請求書とか迂闊に出せないなーという状況です。

**Comment by y-yagi** [comment]
説明足りておらず失礼致しました。
支払いはまだです。サイトの対応がすべて完了した後に、請求書を頂く予定で、その後支払いを行う予定です(サイトの対応完了は7月末ころになる想定です)。

その支払いの対応についてご相談させて下さい。

請求書を作成して頂く際、宛名を日本のRubyの会宛で作成して頂き、その請求書の対応を日本のRubyの会様の方でして頂く、という事は可能でしょうか？ 
(お支払いする金額はこちらで準備しますので、手続き部分だけお願い出来ればと考えております)

お手数ですが、ご確認の程お願い致します。

**Comment by takahashim** [comment]
@y-yagi すみません、ちょっと良く分からなかったのですが、誰から誰宛の請求書になりますか？
（Rubyの会からスポンサー企業さんに請求する＋誰かがRubyの会宛に請求する、みたいな話でしょうか？）

**Comment by takahashim** [comment]
あー、ちょっと話が理解できてなかったのですが、

* サイト制作の件: esa社さんからRubyの会に請求
* スポンサーの件: Rubyの会からスポンサー社さんに請求

という形にしたい、であってますか？

**Comment by y-yagi** [comment]
説明わかりづらくなってしまい申し訳ありません。

はい、まとめて頂いた形に出来ればと考えています。

**Comment by shyouhei** [comment]
@y-yagi 作業発生して恐縮ですが今後の流れで、

1. 予算感をいただけますでしょうか。(Ginzarbからrubyの会にください) 金額に関わる部分の実務が円滑に行えるかの確認調整のためです。サイト制作他、各種の出費の現時点の目算をいただけませんか。ここに公開する性質のものでもないと思いますので、info@ruby-no-kai.orgに直接メールでいただければと思います。
2. esa社様からお見積もりをいただきたいです。すでにお持ちでしたらそれを共有していただければOKかとおもいます。
3. スポンサー様にお見積もりをお送りしたいです。スポンサー様の一覧およびそれぞれの金額など共有していただけますか。

お手数ですが円滑な実務のためによろしくおねがいします。質問など随時ください。

**Comment by y-yagi** [comment]
@shyouhei こちらこそお手数おかけしてしまい申し訳ありません。
上記了解致しました。こちら、整理しご連絡させて頂きます。少々お待ち下さい。

**Comment by takahashim** [comment]
@y-yagi そんなに詳しい情報はいらないのですが、現時点ではどこからいくらスポンサードしてもらって、それをどこにいくら支払うのか等よく分かってなくって、それなのに形としては全部Rubyの会の取引になってしまうので、このままだとちょっとまずいんじゃ…？という気持ちなのでした。

なので、「サイトデザインの金額はこれくらいです」「スポンサーはこれくらいの金額でお願いします」というのを各会社さんとやりとりしておいて、あとで「思ってたのと違ってた」みたいなことがないようにしたいのでした。そのために見積書があるといいかなというわけで、上の2.と3.になってます。

あと、当日や直前にかかる飲食や消耗品のお金もスポンサー費に含まれてるんであれば、それはまとめてざっくりいくらくらいの想定かを教えてもらえればありがたいです（上の1.にあたるやつですね。各明細はなくて構いません。たぶんスポンサー費からデザイン費を引いた分の残り全額がそれに充てられるんじゃないかなーと推測してます。）

**Comment by y-yagi** [comment]
@takahashim 
詳細なご説明ありがとうございます。
諸々承知致しました。情報の共有出来ておらず失礼致しました。 まず全体の予算感について急ぎご連絡させて頂きます。

**Comment by shyouhei** [comment]
現状: スポンサー関連が進行中
next action:
  - [x] スポンサー様への請求書の送付
  - [x] サイト制作費の請求書をまつ
  - [ ] 各種支払い

**Comment by takahashim** [comment]
@y-yagi こちらスポンサーさんへの請求はお送りしました！

**Comment by koic** [comment]
請求書のご送付ありがとうございます。永和システムマネジメントについて届きましたのでこちら処理を進めさせて頂きます。

**Comment by y-yagi** [comment]
@takahashim 
ご対応ありがとうございます！

@koic 
早々にご確認頂きありがとうございます！ お手数ですが、処理の方お願い致します。

**Comment by y-yagi** [comment]
esa社様から頂きましたサイト制作費の請求書をinfo at ruby-no-kai.orgに送付させて頂きました。
お手数ですが、お手隙の際にご確認頂けますと助かります。

**Comment by takahashim** [comment]
@y-yagi ありがとうございます、こちら対応いたしました！

**Comment by y-yagi** [comment]
@takahashim 早々にご対応頂きありがとうございます！ esa社様から入金内容確認出来た旨ご連絡頂けました。

**Comment by y-yagi** [comment]
昨日無事にぎんざRuby会議01が開催出来ました。 諸々のご支援、誠に有難う御座いました。 

あと何か対応が必要な残処理はありますでしょうか? もしありましたら、お手数ですがご指摘頂けますと助かります。 特に無いようでしたら、このチケットはcloseさせて頂ければと思います。

**Comment by shyouhei** [comment]
ごめんなさい、各種支払いなど、こちら側の処理がありそうですので、少々確認した上で閉じさせて下さい。

**Comment by y-yagi** [comment]
ご確認ありがとうございます。承知しました。ではこちらそのままにしておきます。

**Comment by takahashim** [comment]
ぎんざRuby会議01開催おつかれさまでした！　盛況だったようで何よりです。
こちら支払いじゃなくて入金確認作業があったのですが、こちらも完了しまして、esa社さんへのお支払も含めて完了いたしました！　どうもありがとうございました。

**Comment by takahashim** [comment]
というわけでこちらは閉じておきます
