### ISSUE TITLE
福岡Ruby会議02 開催

### ISSUE THREAD

**Issue by udzura** [ruby-no-kai/official#275]
Fukuoka.rb 近藤です。

タイトルの通り、開催を予定して動いております。
つきましては諸々ご協力を仰ぐことになるかと思います。よろしくお願いします。

----

名称：福岡Ruby会議02
開催日：2017年11月25日(土)
会場：大名小跡地 Fukuoka growth next [Site](https://growth-next.com/)
参加費：1,000円 ~ 1,500 円程度
  #=> ペイパルのアカウントをお借りしたいと考えています
配信：なし
定員：100名 ~ 150名
実行委員長(仮)：近藤うちお (@udzura）
会計：TBA
レポート：TBA
サイト：作成依頼中

コンテンツについて、招待講演者2名を予定していますが、スポンサー＋会費でまかなえる可能性があり、諸々固まったらおしらせします。

**Comment by kakutani** [comment]
:tada: 期待してます！

**Comment by shyouhei** [comment]
現状: 見守っている
next action: もろもろ決まってきたら相談してきてください〜

**Comment by shyouhei** [comment]
現状: 見守っている
next action: もろもろ決まってきたら相談してきてください〜

**Comment by udzura** [comment]
サイト作成はデザイナー氏 @horaotoko をアサインしており、鋭意作成中です。公式サイト公開のタイミングで色々Issueを立てさせてください 🙇

**Comment by udzura** [comment]
お疲れ様です。公式サイトを作成中なのですが
http://magazine.rubyist.net/?0042-FukuokaRubyKaigi01Report
上記で使われている前回の写真を素材として利用したい気持ちがあるのですが、 @takahashim さん方面の方でるびまの写真利用のレギュレーションなどについてご確認は可能ですか？
最近のるびまはどなたが関わっているのだろう。。ひとまず @kurotaky @miyohide さんたちにもping

**Comment by kurotaky** [comment]
るびまの写真利用のレギュレーション!
無いような気がしますが、 @takahashim さん @miyohide さんご存知ですか...?

**Comment by miyohide** [comment]
@udzura すみません、分かりません。記事の執筆者に連絡を取られてみてはいかがでしょうか。

**Comment by takahashim** [comment]
@udzura @kurotaky るびま掲載コンテンツの再利用については、特に明記のない場合、写真を含めて著作者（写真の場合は撮影者）が権利を持っている形になっているので、個別に確認する必要があるのでした…

**Comment by udzura** [comment]
https://github.com/ruby-no-kai/official/issues/275#issuecomment-303751398
はい〜この方向で確認を取りつつあります！　ご返答ありがとうございました！ @kurotaky @miyohide @takahashim

**Comment by udzura** [comment]
サイト公開PR https://github.com/ruby-no-kai/regional.rubykaigi.org/pull/53

**Comment by shyouhei** [comment]
現状: 見守っている
next action: 引き続き見守る

**Comment by shyouhei** [comment]
現状: 見守っている
next action: 引き続き見守る

**Comment by shyouhei** [comment]
リンク #281

**Comment by shyouhei** [comment]
現状: 見守っている
next action: 引き続き見守る

**Comment by udzura** [comment]
お世話になります。
チケット価格について確定しましたので、応募開始をしたいと思っております。
つきましては、 https://github.com/ruby-no-kai/official/issues/281 でもご相談したPaypalのアカウントの情報に関して、
udzura@udzura.jp もしくは Facebookメッセンジャー等でご共有お願いできると幸甚です。何卒。

**Comment by takahashim** [comment]
@udzura メールしました！

**Comment by udzura** [comment]
@takahashim 拝受しました！
一緒に、 `fukuoka02@rubykaigi.org` のようなグループの作成を @kakutani さんにお願いできると助かります。 ref: https://github.com/ruby-no-kai/official/issues/245

**Comment by shyouhei** [comment]
現状: fukuoka02@rubykaigi.orq 作成済み CC: @udzura 
next action: 引き続き見守る

**Comment by udzura** [comment]
@shyouhei (@kakutani) ありがとうございます。そちらのグループに参加させていただきたいアドレスをお送りしました。

また、10月中をめどにスポンサー様へのご請求をお願いしたいのですが、可能な感じでしょうか...？

**Comment by takahashim** [comment]
@udzura その場合、請求情報を早めにご連絡いただけるとありがたいです…！

**Comment by udzura** [comment]
@takahashim まとめております。メールの方に詳細をお送りしていますので、ご確認願います 🙏

**Comment by shyouhei** [comment]
> そちらのグループに参加させていただきたいアドレスをお送りしました。

おっと、これ実は自分は入ってないんで見落としというか、気づいてないですね。
@udzura CCに適当にshyouhei at ruby-no-kai.orgあたりを追加して再送していただけると。

**Comment by udzura** [comment]
@shyouhei 再送いたしました！

**Comment by takahashim** [comment]
現状請求済み。
next action: 入金を待つ

**Comment by udzura** [comment]
無事開催いたしました。 🙏 

* [x] 通常価格のご精算 日本Rubyの会
* [x] 松田さんへの渡航支援費お支払い 日本Rubyの会
* [ ] サイトクローズ 我々
* [x] 振り返り 我々
* [x] CFP当選者への支援費の扱いの決定 我々

あたりを残件として認識しております。

**Comment by udzura** [comment]
るびまは、るびま側のIssueで...

**Comment by kakutani** [comment]
> サイトクローズ 我々

このクローズは、どういう意図でしょう?
(Rubyの会としてはアーカイブとして残したい)

**Comment by shyouhei** [comment]
現状: 無事 🎉 
next action: 

- [x] スポンサーフィーの消し込み
    - [x] スポンサーへの請求
    - [x] fukuokarb側への支払
    - [x] スポンサーからの振込確認
- [x] paypal精算
    - [x] early bird
    - [x] 通常価格分
- [x] 松田さんの渡航費支援
    - [x] 金額の確定
    - [x] 振込

他気づいたら追記下さい

**Comment by takahashim** [comment]
松田さん渡航費の領収書はいただきました！

**Comment by udzura** [comment]
> サイトクローズ 

クローズしてる感を出します！（終了しました、という旨を書くなど）

**Comment by kakutani** [comment]
> クローズしてる感を出します！（終了しました、という旨を書くなど）

なるほどなっとくです 😌  (よろしくおねがいします)

**Comment by takahashim** [comment]
@udzura こちら通常価格分のPayPal代金もお振込しました。明日入金される予定です。

**Comment by takahashim** [comment]
松田さんの渡航費も振り込みました。こちらも明日入金予定です。

**Comment by takahashim** [comment]
スポンサーからRubyの会への振り込みも全件確認できました！

**Comment by shyouhei** [comment]
@udzura さん、これって残件ありますでしょうか

**Comment by udzura** [comment]
@shyouhei 
日本Rubyの会としては残件なしと思います！
るびま、サイトの更新などは置いといて、クローズで良さそうです

**Comment by snoozer05** [comment]
了解です！お疲れ様でした！ 🎉
