### ISSUE TITLE
るびま用サーバの乗り換え

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#276]
#263 の続き。
Sqaleが終了するので、さくらのVPS(1G)を使うことにする。

* [x] 契約用アカウント作る
* [x] 支払う
* [x] 作業用アカウント発行する

**Comment by shyouhei** [comment]
現状: サーバは調達した。アカウントも渡した。あとはるびま班でセットアップしていただく
next action: 今月中にはSqaleさんがシャットダウンとなる。費用はそのうち引き落としになる

**Comment by shyouhei** [comment]
現状: Squaleさんは無事終了。さくらは引き落としが始まった。

**Comment by hsbt** [comment]
🙏  ご利用ありがとうございました
