### ISSUE TITLE
るびま会議

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#277]
開催の機運 cf https://github.com/rubima/rubima/issues/422

**Comment by shyouhei** [comment]
@miyohide 移行作業がひと段落したらちょっと集まったりしませんか

**Comment by miyohide** [comment]
@shyouhei わかりました。来月あたりで調整させてください。

**Comment by shyouhei** [comment]
@miyohide 
- 誰呼びたいとかありますか?
- ざっくりの時間はいつがいいですか? 休日か、平日夜か。

**Comment by miyohide** [comment]
@shyouhei 

> 誰呼びたいとかありますか?

編集長である @takahashim さんを呼びたいです。

> ざっくりの時間はいつがいいですか? 休日か、平日夜か。

休日のほうが都合が良いです。平日夜でも調整可能ですが、木曜日は都合悪いです。

**Comment by shyouhei** [comment]
あいだがあいてしまいましたが @takahashim @miyohide ご調整ください

**Comment by miyohide** [comment]
6月ですと、24日（土）、25日（日）、28日（水）が都合良いです。
7月ですと、水曜日と15日（土）、16日（日）、17日（祝・月）ぐらいが都合良いです。

**Comment by takahashim** [comment]
これですが、私の方は6/24でもよいですが、他にもるびま関係者の方々も呼ぶのであればもう少し先の方がよいでしょうか？（ただ7月だと21日以降じゃないと難しそう）

**Comment by takahashim** [comment]
すみません、6/24で準備が間に合わなかったので、7月で仕切り直させてください 🙇

**Comment by miyohide** [comment]
了解しました。

**Comment by shyouhei** [comment]
現状: 流れてしまった
next action: ちょうせいさんとかでしょうか

**Comment by miyohide** [comment]
調整さんを立てました。
https://chouseisan.com/s?h=143aa77383c742818336ef0653a4f6a2

時間は調整可能なので、コメントとかで入れてもらえると嬉しいです。

1週間後(8/3)までで参加者を募ろうかと思っています。後ほどるびま関係者にも連絡しておきます。

集まって話したいテーマとか何か有りますでしょうか。

**Comment by takahashim** [comment]
ありがとうございます！　私の予定も入れておきました。

1点、私の方でテーマとして話してみたいのが「（過去記事も含めた）スマートフォン対応」なのでした。

**Comment by miyohide** [comment]
@takahashim 8/11（金・祝）が全員揃いそうです。リモート参加をznzさんが希望されているので、Hangoutとかで8/11（金・祝）19:00からオンラインでお願いしたいです。

**Comment by takahashim** [comment]
@miyohide こちら了解です！ 8/11の19時からですね。

**Comment by miyohide** [comment]
@takahashim はい、開催近くになりましたら、参加用URLをここに貼り付けます。

なお、テーマとしてあげていたるびまのスマホ対応ですが、現在私の手元では↓のような感じで動いています。

![screen shot 2017-08-09 at 22 01 59](https://user-images.githubusercontent.com/601621/29122818-8ebe19da-7d4e-11e7-91eb-2dee398492eb.png)

**Comment by takahashim** [comment]
すごい、かっこいい！

**Comment by miyohide** [comment]
ハングアウトのリンクです。
https://hangouts.google.com/call/46fwuhntmbfspjeuu2n3swl3na4

**Comment by miyohide** [comment]
仮で立ち上げたスマホ対応のサイトです。
http://tk2-228-23726.vs.sakura.ne.jp/

**Comment by miyohide** [comment]
開催しました。メモを以下に記しました。
https://github.com/rubima/rubima/wiki/20170811_rubima_meetup.md

**Comment by shyouhei** [comment]
おつかれさまでした！
