### ISSUE TITLE
RailsGirls Takasaki 1stのスポンサー費用請求

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#280]
* [x] 請求する
* [x] 精算する
* [x] 入金確認する

スポンサーのリストは受領済み。ちょっとまだ情報が足りてない？（要確認）

**Comment by hsbt** [comment]
👀 

一部情報が抜けている アシラス株式会社様 については @hsbt からオーガナイザーの近藤さんに連絡して、現金として受け取ったスポンサード費用を RG JP の口座に振り込んでいただくことになってます。

@takahashim 

なので 4 件 * 21600 円を請求書発行、RG JP へ資金移動、という流れで認識に相違はなさそうでしょうか...?

**Comment by takahashim** [comment]
あ、はい、アシラス株式会社さんの件はここに書いたあとで気づきました…。
担当者情報もいただいたんで4件発行ということでOKです！

**Comment by takahashim** [comment]
こちら請求と精算の手続きをとりました。どちらも週明けに送付・振込される予定です

**Comment by shyouhei** [comment]
現状: 請求書送付済み、精算済み、入金待ち
next action: 入金を待つ

**Comment by shyouhei** [comment]
現状: 入金待ち
next action: 入金を待つ

**Comment by shyouhei** [comment]
現状: 入金待ち
next action: 入金を待つ

**Comment by takahashim** [comment]
next action: 入金を確認する

**Comment by shyouhei** [comment]
現状: そろそろでは?
next action: 入金確認する

**Comment by shyouhei** [comment]
現状: まだ確認できてない
next action: MLのほうへ状況をシェアする

**Comment by shyouhei** [comment]
現状: まだ確認できてない
next action: 各方面の状況を確認する

**Comment by snoozer05** [comment]
現状: 請求待ちで止まっている
next action: MLのほうへ状況をシェアする

**Comment by springaki** [comment]
Akiが調べて対応します

**Comment by springaki** [comment]
問い合わせ情報が請求シートに載っていなくてそこから各方面に問い合わせていました。
問い合わせ先をGetできそうなので、ようやくコンタクト開始といった状況です。

**Comment by springaki** [comment]
連絡とれました。明日処理予定で振込したとのこと。

**Comment by takahashim** [comment]
こちら入金確認できたので、ついに完了しましたっ！　みなさまご協力ありがとうございました。
