### ISSUE TITLE
[Fukuoka02]キャッシュフロー等のご確認をしたい

### ISSUE THREAD

**Issue by udzura** [ruby-no-kai/official#281]
お世話になります。近藤です。以下、いきなりですが質問に参ります。

## 1) キャッシュフローについて

おおまかに、以下の流れを考えております、ツッコミどころや認識違い等ご指摘願いたいです。

* 7月後半 スポンサーを募集する
* 8月頭 チケット販売を開始する
* 9月中 スポンサーを確定する
* 10月中 アーリーバードとして、一旦閉めきる
* 10月中 Fukuoka.rb の指定する口座に集金できた分を一旦お振込みいただく
* 振込み後 開催に必要な費用等を払う
* 11月25日 開催
* 開催後 スポンサー様へ日本Rubyの会よりご請求をしていただく
* 集金後 Fukuoka.rb の指定する口座にお振込みいただき、清算

また、 Paypal アカウントは https://github.com/ruby-no-kai/official/issues/251 のように日本Rubyの会よりお貸しいただけると助かりますが、同じようにご協力いただけますでしょうか？

## 2) もし予算等が余った場合

今回の会場 Fukuoka growth next は、共催という形で無料でお借りできる見込みなのですが、
そうすると、入場費＋スポンサー費用で、予算が余る可能性が高いです。
そのような場合、例えば、日本Rubyの会への寄付という形を取る等は可能でしょうか？

あるいは、入場費無料なども検討した方が良い感じでしょうか。
（福岡の企業をなるべく巻き込みたい気持ちがあり、スポンサーの枠は削りたくない思いが。）

**Comment by takahashim** [comment]
キャッシュフローについて、上げていただいた流れで問題ないですが、そちらで会場費等支払いのタイミングが早く来そうな場合、Rubyの会の方から早めにお金を渡すことも可能だと思います。
またpaypalアカウントの方も問題ないはず。

予算が余った場合の寄付も可能です。ただし、Rubyの会への寄付は寄附金控除の対象となりませんのでご注意ください。
…という感じでよいでしょうか？　入場費をどうするかはイベント設計に深く関わるので、（足りない場合はともかく）余った場合のことは気にせず考えた方がよいような気もしますね…。

**Comment by udzura** [comment]
ご回答ありがとうございます！

> Rubyの会への寄付は寄附金控除の対象となりません

余りすぎた場合何かしらの申告が発生するかもしれませんね...（ン十万？単位でしょうが）

入場費について持ち帰って考えてみます。

**Comment by udzura** [comment]
> そちらで会場費等支払いのタイミングが早く来そうな場合、Rubyの会の方から早めにお金を渡すことも可能だと思います

こちら助かります。会場の状況を確定させ、場合によってご連絡すると思います。

**Comment by takahashim** [comment]
だいぶ余談ですが…10万円以上余りそうなことが確実で、かつ法人組織に興味がある方がいるのであれば、運営組織として人格のない社団を作って、1年以内に設立から解散まで行って法人税も払いつつ、解散時に残余財産はRubyの会等に寄付するということにしておけば（定款で解散について書いておけば）、udzuraさんやその他個人の方には課税されないような気がします。
法人税7万円＋税理士さんへ数万円の経費に加えて、定款作る等それなりに面倒くさい手間はかかりますけど、登記は不要です。いちど法人ぽい組織を（他人の金で）作ってみたい！というスタートアップ志望者みたいな人がいるならそういうのもよい経験になるかもしれません。
（一般的にはオススメとは言えないのですが、Fukuoka growth next界隈にはそういうのが好きそうな人が山ほどいるのでは…と思ったのでした）

**Comment by shyouhei** [comment]
これは一旦閉じま〜す

何かあったら #275 にて。
