### ISSUE TITLE
[Fukuoka02]FGNとの共催

### ISSUE THREAD

**Issue by udzura** [ruby-no-kai/official#282]
## 概要

Fukuoka Growth Next(以下FGN)内の関連団体であるエンジニアラボとの共催という形を考えており、可能ならば「福岡Ruby会議02 x エンジニアラボ」であったり、「福岡Ruby会議02 by Fukuoka.rb/エンジニアラボ」のような正式名称にして、先方の名前をフィーチャーしたい。
そのような若干変則的な会議名を取ることに問題はないかどうかをお尋ねしたいです。

## 背景

会場として、福岡にはFukuoka Growth Nextという優れたファシリティがあり、可能であればそこを利用したい。
その際の大きなレギュレーションとして、「エンジニアラボ」という名前をイベント名に含めて欲しいという話が出ている。その場合、FGN共「催」という形で会場費用が賄われる。
共催という形でない場合の費用は¥30万〜程度となるそう。

「エンジニアラボ」自体は半官半民で、「エンジニアヒューマンリソースの育成・マッチング」を掲げていてコンセプトは多少ビジネスに寄っていますが、運営に関わる方などの感覚は限りなくコミュニティ的です。

## 関連

https://growth-next.com/about

----

ということで、まずは空気感というか、お聞きしたく思います。

**Comment by snoozer05** [comment]
ぼくは問題ないと思いますが、どうでしょうか > @takahashim

**Comment by shyouhei** [comment]
べつにいいんじゃないですか? というか、Fukuoka02ってべつに日本Rubyの会主催とかいうたてつけではないですよね。お金の処理などで協力していますが、それ以上の話ではないと思うので、名前のようなところで気兼ねしていただく必要はないのでは。

**Comment by udzura** [comment]
なるほど承知しました！
Fukuoka02のメイン主催（？）はFukuoka.rbです（個々のメンバーのボランタリー駆動です）。

**Comment by takahashim** [comment]
出遅れましたが私も特に問題ないかと思いました！

**Comment by shyouhei** [comment]
これは一旦閉じま〜す

何かあったら #275 にて。

**Comment by udzura** [comment]
共催の形で落ち着いております！
