### ISSUE TITLE
個人情報保護規定の必要性の有無について悩むスレ

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#283]
<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr">ふと気になったのだが、Rubykaigiってアンチハラスメントポリシーはあるけど個人情報保護規定ってないんだろうか。ウェブには見当たらなかった。</p>&mdash; Clv024k (@metaforce_) <a href="https://twitter.com/metaforce_/status/898012242871861249">August 17, 2017</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr">問題が起きたら作るようなスタンスなのかな。</p>&mdash; Clv024k (@metaforce_) <a href="https://twitter.com/metaforce_/status/898012495306047488">August 17, 2017</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr">問題が起きるまで放置するというわけでもありませんので必要あれば作成やぶさかでないのですが、RubyKaigiで保護すべき個人情報ってどんなものを想定されていますか</p>&mdash; Urabe, Shyouhei (@shyouhei) <a href="https://twitter.com/shyouhei/status/898026864324759552">August 17, 2017</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr">思い当たるところとしてはチケットの購入情報、購入時のメールアドレス、購入時アンケートの内容と言った情報になると思います。しかし、深くは詰めて考えたわけではないのですが、アンケートの特に託児所の利用についてのフォームを見て疑問が湧いた次第です。</p>&mdash; Clv024k (@metaforce_) <a href="https://twitter.com/metaforce_/status/898037731628007424">August 17, 2017</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr">チケット周りはサイトも運営主体もdoorkeeperさんにお願いしています。なので、プライバシーポリシーもdoorkeeperさん側でご用意されているはずかと存じ上げております。</p>&mdash; Urabe, Shyouhei (@shyouhei) <a href="https://twitter.com/shyouhei/status/898038337474187265">August 17, 2017</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr">とはいえ託児所アンケートはたしかにセンシティブな情報かもしれない。現状が問題とは思いませんが我々の側で規定があるとより安心かもですね、少々検討します。</p>&mdash; Urabe, Shyouhei (@shyouhei) <a href="https://twitter.com/shyouhei/status/898039080067280896">August 17, 2017</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr">ふとした疑問にもかかわらず、お返事ありがとうございます 🙂<br>チケットについても了解しました</p>&mdash; Clv024k (@metaforce_) <a href="https://twitter.com/metaforce_/status/898043341534748672">August 17, 2017</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr">いえ、ご指摘いただきありがとうございました</p>&mdash; Urabe, Shyouhei (@shyouhei) <a href="https://twitter.com/shyouhei/status/898043577808310272">August 17, 2017</a></blockquote>

**Comment by shyouhei** [comment]
上記の通りで現在の自分のフィーリングとしては「現状が問題とは思わないが我々の側で規定があるとより安心かも」という感じ。

**Comment by amatsuda** [comment]
今見えてる範囲では、託児所の申し込み時に集める個人情報の取り扱いに関しては、託児所の申し込みフォームに明記するのが一番キレイでしょうね。
となると、やっぱりとりあえずDoorkeeperの購入ページに個人情報うんぬんを簡潔に書いておくのが良いのかなぁ。

**Comment by shyouhei** [comment]
現状: RubyKaigiうんぬんもそうだが、Rubyの会として個人情報保護方針を定めておいた方がよさそうだ
next action: 文面を作ってプルリクエストするなど?

**Comment by shyouhei** [comment]
現状: 進捗はない。次のRubyKaigiのチケットを売り出すまでになんとかせねば…
next action: 卜部が文面をとりあえず作ってみる

**Comment by takahashim** [comment]
next action: 卜部さんが文面を作ってみる

**Comment by shyouhei** [comment]
現状: 進捗はない。次のRubyKaigiのチケットを売り出すまでになんとかせねば…
next action: 卜部が文面をとりあえず作ってみる

**Comment by shyouhei** [comment]
現状: 進捗はない
next action: 卜部が文面をとりあえず作ってみる

**Comment by shyouhei** [comment]
現状: 文面を作ってみた結果、とりあえず公開せずということに
（規定として無効という意味ではないがコーナーケースの考慮が不十分）。

というわけで閉じます、必要に応じて再開するかもしれない。

**Comment by shyouhei** [comment]
@takahashim @kakutani @snoozer05 @springaki 閉じたスレッドに書きますが…

- GDPR対応が必要になるかもしれない
- 平成29年5月30日の改正個人情報保護法から、いわゆる5,000件制限がなくなり、Rubyの会も晴れて個人情報取扱事業者にカウントされそう
    - http://www.meti.go.jp/policy/it_policy/privacy/downloadfiles/01kaiseikojinjohopamphlet.pdf

といった事情により、これは継続審議かもしれんねという気がしてきています。

**Comment by kakutani** [comment]
小規模取扱事業者にも適用となると安全管理措置とかの運用のことも決めていかねばならないのか…。

GDPRは「日本」Rubyの会としてはどんなんじゃろう…気もしますが、これはどこに相談するのがいいんでしょう(Doorkeeperさんはそのへんどうなんだ…)

**Comment by takahashim** [comment]
とりあえず、

* 持ってる・取ってる情報をリストアップして公開する
* いらないものがあったら処分する
* 新たに取るときのフローを準備する

あたりをやっておくのが良さそうです。

**Comment by shyouhei** [comment]
https://builderscon.io/tokyo/2018 をぐぐっと一番下までスクロールすると"Privacy Policy"と書いてあっておおおという感じですね…

**Comment by shyouhei** [comment]
もうちょっと悩もう。。。

**Comment by shyouhei** [comment]
next action: #309 を参考にしつつどのような個人情報を現状で収集しているかを調査する

**Comment by shyouhei** [comment]
#309の時点で見えていたのは

- RubyKaigiのチケット販売・管理でメールアドレスなどの情報を収集することがある点。
- RubyKaigiでビザが必要な人に対する招聘状の作成事務で、かなり深い個人情報(国籍等)を収集する点。
- 託児所を設置する場合に、利用者の緊急連絡先を収集するが、これが個人情報である点。

が見えていました。これらはどれも委託業者がからむ話ではあります。他に何かあるだろうか。

**Comment by shyouhei** [comment]
近年のRubyKaigiでは宿泊予約システムなどを使う場合がある(2019は使った)が、これはRubyの会の側からとくに個人情報を収集しているわけではなく、契約としては個々人と旅行代理店の間の契約ということになっているので、Rubyの会の側で個人情報を保護してどうこうという話ではない気がする。

**Comment by shyouhei** [comment]
- まず問い合わせ窓口を明示することが必要かもしれない
- 明示する場所としてはRubyKaigiとかではなくてRubyの会のサイトであると思われる

**Comment by shyouhei** [comment]
とりあえず海外の情勢がどうとかは一旦横に置いておいて、国内として問題ない感じにしていきたい。

そうなると、「国内で法的に問題が少ないようなプライバシーポリシーの文面」みたいなのを考えるのは卜部がうだうだするより他の適切な方にお願いしていきたいです。 @takahashim ちょっと探してみていただけますか

**Comment by takahashim** [comment]
今週いったん打ち合わせする予定になりました

**Comment by takahashim** [comment]
とりあえず2パターン（国内法べったりの日英版と、海外法もある程度意識したもの）のお見積りをもらうことになりました。
欧州法の資格を持っている弁護士の方に入ってもらって本気のGDPR対応してもらうオプションは（リスクの割に）無駄に高くつくのでは？　ということで今回はナシになりました。

**Comment by takahashim** [comment]
「GDPRの適用を前提としたプライバシーポリシー」の作成でお願いしてみます。

**Comment by shyouhei** [comment]
引き続き卜部がボールを持っている

**Comment by shyouhei** [comment]
見れてない
next action 見る

**Comment by springaki** [comment]
見れてない
next action 見る

RubyKaigi 現地開催するかどうかでも急ぎかどうか変わりそう。

**Comment by shyouhei** [comment]
現状: RubyKaigi 2020 Takeoutで必要になったので作成した :done:
next action: 一応、これ以降も有効なプライバシーポリシーが出来上がっているが、都度見直しは必要かもしれないのでまた考える
