### ISSUE TITLE
三井住友銀行のネットバンクについて検討する

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#284]
無料で使える売り込みがありました。詳細は後日書きます。

**Comment by shyouhei** [comment]
next action: 高橋さんが銀行に物理的に行ってとりあえず話を聞く。

**Comment by shyouhei** [comment]
現状: 幡ヶ谷支店での法人の取り扱いが終了してしまった…
next action: 新宿支店まで行かねばならぬ。が、逆にいうとだからこそネットバンクになったほうがいいのか…?

**Comment by takahashim** [comment]
現状: まだ行けてない
next action: 新宿支店に行く

**Comment by shyouhei** [comment]
現状: 窓口が遠い
next action: 15時までに窓口に到達する

**Comment by shyouhei** [comment]
現状: ついに窓口に行った。振込先口座の登録が200件までなら無料で開始できるらしい。JNBもあるしまあ200件はいかないのでは
next action: 書類を郵送して申し込む

**Comment by shyouhei** [comment]
現状: あとは申し込むだけ
next action: 申し込む

**Comment by takahashim** [comment]
（さっき）申込書を郵送してきました。

**Comment by takahashim** [comment]
パスワードに英字が使えないと言われてダメ出しを食らってしまった…（書き直して再提出済み）

**Comment by takahashim** [comment]
どうやら受理はされて、もろもろ届いたところです。とりあえずissueは閉じておきますね
