### ISSUE TITLE
トランクルーム契約するか考える(するなら急ぎ)

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#286]
RubyKaigiからの戻しが発生するので(やるなら)すばやく契約。

**Comment by shyouhei** [comment]
とりあえず借りる方向で。
@takahashim 契約関連お願いします。

**Comment by shyouhei** [comment]
@takahashim そろそろ動けそうでしょうか

**Comment by takahashim** [comment]
調べてみたところ、全国どこでも配送可能、というサービスは案外多くないようです。
ヨドコウのヨドクラウド物置 https://www.yodo-cloud-monooki.jp/ が良さそう、ということで条件等調べてます。

* 大きさ・重さ制限は大丈夫か（縦57cm×横44cm×高さ51cm、25kg/箱まで）
* 預け入れは集荷になるけど大丈夫か

**Comment by takahashim** [comment]
ヨドクラウド物置、利用規約では個人しか使えなさそうでした…。
阪神のrisocoだと法人でも使えるようでした。 https://risoco.jp/

**Comment by takahashim** [comment]
risocoのアカウントを作ってみました。
集荷（入庫）が佐川じゃないとダメかも…？

**Comment by takahashim** [comment]
とりあえず4箱注文してみました。たりなさそうであれば会場で追加の申込みを行うことで。

**Comment by shyouhei** [comment]
現状: 契約した。段ボールが来ている。
next action: 段ボールを送付する。

**Comment by takahashim** [comment]
next action: #229 の機材を回収して送る

**Comment by shyouhei** [comment]
続きは #229 で
