### ISSUE TITLE
RubyKaigi下見第二回精算 #2017

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#287]
- [x] 下見実施
- 金額の確定
  - [ ] 旅費
  - [ ] 宿泊費
  - [ ] 会議費
- 領収書を高橋さんに渡す
- [ ] 振り込む

**Comment by shyouhei** [comment]
これそもそも誰と誰が行ったんだっけ…

**Comment by shyouhei** [comment]
- @takahashim 
- @sorah 
- @springaki 
- @amatsuda 
- @nishimotz 
- @takata

**Comment by shyouhei** [comment]
これはRubyKaigiの費用精算プロトコルでやったほうがよさそうかもしれない

**Comment by shyouhei** [comment]
next action: RubyKaigiのほうでやりましょう！このチケットはおわり。

**Comment by sorah** [comment]
清算済
