### ISSUE TITLE
Rubyのテスト環境：スイッチングハブの購入

### ISSUE THREAD

**Issue by ko1** [ruby-no-kai/official#290]
お金の無心です。

現在、芝浦工大におかせてもらっている CI マシン（rubyci.org 用の mac mini x 2、ci.rvm.jp 用のマシン）につないでいるスイッチングハブについて、これまで大学にお借りしていたのですが、事情により使えなくなったので、こちらで用意しようとしています。

今は 8 port でちょうとぴったり使っているのですが、さらなる拡張（raspi 数台）を検討しているので、16ポートを導入しようと思っています。kakaku.com で一番評判がいいこれを検討しています（約7,000円）。
https://www.amazon.co.jp/dp/B01CNHOXJG

本機購入について、ご支援いただくことは可能でしょうか。よろしくお願いします。

**Comment by ko1** [comment]
ちょっと急ぎで持って行く必要があるので、上記　6,980 円のを発注しました。
お認め頂けないようでしたら、私の方で負担します。

**Comment by takahashim** [comment]
これなら消耗品扱いなので問題ないです！　9/28に打ち合わせをやるのでその時に正式に回答しますね。

**Comment by ko1** [comment]
ありがとうございます。よろしくお願いします。

**Comment by shyouhei** [comment]
現状: @ko1 OKです!
next action: @ko1 領収書送ってください!

**Comment by ko1** [comment]
了解です。別件とあわせて高橋さんにお渡しします。

**Comment by takahashim** [comment]
next action: この前領収書をもらいそこねたので後で回収する

**Comment by takahashim** [comment]
領収書回収しました！

**Comment by takahashim** [comment]
振り込んだので閉じます
