### ISSUE TITLE
RailsGirls Kobe 3rdのスポンサー費用請求

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#291]
…ってなんかやることあります? CC @hsbt

**Comment by springaki** [comment]
あります！後ほど情報共有します

**Comment by springaki** [comment]
メールにて共有しました。よろしくお願いします。

**Comment by hsbt** [comment]
おお... 反応できてませんでした。 @springaki お願いします...

**Comment by takahashim** [comment]
請求済み。
next action: 入金を確認する

**Comment by shyouhei** [comment]
現状: まだ振込待ち
next action: まつ

**Comment by shyouhei** [comment]
現状: まだ振込待ち
next action: まつ

**Comment by springaki** [comment]
1社 ping 打ってみました。反応待ち。

**Comment by springaki** [comment]
反応あり。原本ありの請求書再送付お願いをMLに投げました。 🙏

**Comment by takahashim** [comment]
@springaki こちら郵送指示を行いました。今週中に発送される予定なので、届くのは来週になるかと思います。

**Comment by springaki** [comment]
@takahashim ありがとうございます !

**Comment by shyouhei** [comment]
現状: 振り込まれていた
next action: RGの口座に精算

**Comment by hsbt** [comment]
こちら、"12/10/17" に @takahashim さんから精算していただいているので、完了、と思います...!

**Comment by snoozer05** [comment]
完了
