### ISSUE TITLE
RailsGirls Tokyo 8th のスポンサー費用請求

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#292]
進めるためにまずは issue だけ作りました。 /cc @emorima

**Comment by emorima** [comment]
10/6 開催の [Rails Girls Tokyo 8th](http://railsgirls.com/tokyo) スポンサー費用の請求をお願いしたいです。

スポンサー一覧は、メールにて共有させて頂きました。

- [x] 請求する
- [x] 清算する
- [ ] 入金確認する

**Comment by hsbt** [comment]
https://github.com/ruby-no-kai/official/issues/291 と合わせて高橋さんに請求書発行を依頼済み。

@takahashim 適当なタイミングでスポンサー費用の移動もお願いします 🙇

**Comment by emorima** [comment]
ご連絡です。

11月末の振り込み期限と、スポンサーフォームに記載してあったので、
スポンサー様から、請求書発行の確認メールがあったとのことです。
![image](https://user-images.githubusercontent.com/458273/31928010-723d5640-b8d1-11e7-89a9-66b8a0d3032e.png)

請求の時期が、少し後ろにずれそうでしたら、スポンサーの方々にご連絡しようと思いますので、
ご連絡頂けると嬉しいです！

**Comment by takahashim** [comment]
@emorima お待たせしてすみません、今週中に送ります

**Comment by emorima** [comment]
@takahashim ありがとうございます！
お忙しいところお手数おかけしますが、よろしくお願いいたします。 🙇‍♀️

**Comment by shyouhei** [comment]
現状: 請求済み、未精算かも?
next action: 確認して精算

**Comment by shyouhei** [comment]
現状: 入金確認済
next action: 精算も確認したので、おわり
