### ISSUE TITLE
沖縄Ruby会議02 開催

### ISSUE THREAD

**Issue by yasulab** [ruby-no-kai/official#293]
[Okinawa.rb](http://ruby.okinawa/) の安川です。

2017年10月から Okinawa.rb の活動が活発 (那覇市+沖縄市開催) になり、また、[そろそろ200回目](https://okinawarb.doorkeeper.jp/)になりそうなので、沖縄で地域Ruby会議をやろうと思います✨  まだほとんど決まっていませんが、決まっているところだけ書き出してみました! よろしくお願いします 😸 

------------------------------

テーマ：まったりRuby
名称：沖縄Ruby会議02
開催日：2018年3月10日 (土曜)
会場：琉球大学 工学部１号館 大教室 321 (本会場) + 322 (予備会場)
参加費：無料
配信：できればしたい
定員：~~100名~~ 60名 (60名を超えたら、予備で用意している大きな会場に変更)
実行委員長： @yasulab
実行委員： @saboyutaka
会計：@yasulab
レポート：TBA
サイト：http://ruby.okinawa/okrk02/

招待講演者として @kou さんをお呼びする予定です。前回は Matz さんをお呼びしたりサイト制作頑張ったりしたので、今回はもうちょっと楽に開催できる仕組みを整えて、気軽に毎年やるぐらいのペースを掴めたらなと考えています 🤔💭

**Comment by yasulab** [comment]
とりあえず決まっているところだけを抜き出して Web サイトを公開しました 🏗 ✨ 

http://ruby.okinawa/okrk02/
https://github.com/okinawarb/okrk02

**Comment by takahashim** [comment]
next action: 現状急ぎのアクションはなし、様子を見守る

**Comment by snoozer05** [comment]
* Regional RubyKaigiのサイトにリンクしました https://github.com/ruby-no-kai/regional.rubykaigi.org/commit/a350326b3b35c01431795c8796193703f37b9c95
* RubyEventCheckにもリンクしました https://github.com/ruby-no-kai/official/wiki/RubyEventCheck

**Comment by yasulab** [comment]
早速の対応ありがとうございます! 😸 現状のステータスとしては @mrkn さんにもふんわりお声かけしつつ、並行してスポンサーや他の実行委員 (会計担当とレポート担当) を探している状態です 🏃💨 cc/ @saboyutaka

**Comment by shyouhei** [comment]
現状: 見守っている
next action: 費用面などご相談があればおきがるにお願いします

**Comment by yasulab** [comment]
ゲストスピーカーと公募フォーム、および現時点でのスポンサー情報を公開しました! 🎉 
http://ruby.okinawa/okrk02/

費用面についてですが、mrkn さんの旅費交通費は Speee さんが出してくれるとのことだったので、他のお二人をどうしようかなと考えています 🤔💭

**Comment by shyouhei** [comment]
現状: 見守っている
next action: 引き続き、ご相談があればおきがるにお願いします

**Comment by yasulab** [comment]
@shyouhei 招待講演者の @kou さんの交通費を支援していただけたらと考えているのですが、支援していただくことは可能でしょうか? 

レポート係がまだ決まっていないですが、現在 @saboyutaka さんと一緒に手伝ってくれている方を探している状況です。

**Comment by shyouhei** [comment]
@yasulab OKです! がどう精算しますか? (事前・事後どちらでも対応できます)
あと照屋さんはどうするんでしょうか

**Comment by yasulab** [comment]
@shyouhei ２人分の交通費を支援していただけるのであれば、照屋さんの交通費の支援もお願いできると嬉しいです! 😸 もし１人分のみであれば、kou さんの分を支援していただければと考えています 🙏 照屋さんには「もし可能であれば支援したいのですが、交通費を出せなくても大丈夫ですか?」と事前に伺って OK をもらっています ✈️

**Comment by kakutani** [comment]
主催者側で呼びたいスピーカーなんだし、2人なら出しますよ(スピーカー全員の旅費交通費、だとちょっと辛そう)。

**Comment by yasulab** [comment]
@kakutani ありがとうございます! mrkn さんは Speee 社が出してくれるとのことなので、それでは須藤さんと照屋さんの２人分でお願いさせていただけると助かります 🙏 領収書の名義は「一般社団法人 日本Rubyの会」としておくと良いでしょうか? 🤔

**Comment by yasulab** [comment]
@shyouhei 株式会社ミノタケが新たにスポンサーとして加わったのですが、以前の時と日本Rubyの会から請求書を送っていただく形で大丈夫でしょうか? もしそちらで問題なければ、送付先などの情報についてメールでお伝えできればと考えております 📨

**Comment by takahashim** [comment]
領収書の宛名は「一般社団法人日本Rubyの会」にしていただければOKです。
請求書もそれでよいかと。

**Comment by yasulab** [comment]
> 定員：100名 (本会場のみ。サテライト会場を含めると200名まで)

すみません、定員について訂正です 💦 具体的には60名用の会場と162名用の会場の２つがあって、設備としては60名用の方が少し充実していたので、最初は60名で募集を開始し、もしそれ以上に人が集まるようであれば162名用の会場に変更しようと思います 💨

**Comment by yasulab** [comment]
@takahashim 3/10 の開催間近ですが、滑り込みでSansan株式会社もスポンサーになっていただけることになりました! 🎉✨(cc/ @saboyutaka )　「3万円を請求書払い (3月末締め4月末払い) でお願いしたい」とのことです。ご対応のほど、よろしくお願いします! 🙏 

<img width="932" alt="sansan_logo" src="https://user-images.githubusercontent.com/155807/37014054-5580795a-2141-11e8-89d9-2d968ec059c9.png">

http://ruby.okinawa/okrk02/#sponsors

**Comment by yasulab** [comment]
@takahashim 請求書は次の宛先に送ってくださいとのことでした 📨 💨 

> Sansan株式会社 
> 人事部   採用チーム
> 藤田 裕子（Yuko Fujita）
> 
> 〒150-0001
> 東京都渋谷区神宮前5-52-2 青山オーバルビル13F
> TEL : 03-6758-6157 FAX :03-3409-3133

**Comment by yasulab** [comment]
無事に okrk02 が開催されました! 💎✨ 

![okrk02_](https://user-images.githubusercontent.com/155807/37328430-72ffad24-26dd-11e8-999a-0f2b3acb2da6.jpg)

## 残りタスク

- [x] アンケート送付 => https://twitter.com/okinawarb/status/974837082383249408
- [ ] 開催レポートの執筆 ( [@The_Na_Ka](https://twitter.com/The_Na_Ka), [@nankuru_free](https://twitter.com/nankuru_free), [@7kosei](https://twitter.com/7kosei) が執筆中)
- [x] 須藤さんの会計処理 ( @kakutani がやる; 必要な情報はもらったつもり )
- [x] 照屋さんの会計処理 ( ~~@yasulab がやる; 領収書の送付待ち~~ @takahashim に振込先と領収書を共有)
- [x] 動画をウェブサイトから公開 => http://ruby.okinawa/okrk02/

**Comment by yasulab** [comment]
それぞれ状況を更新しました 🔧 💨 

> - [x] アンケート送付 => https://twitter.com/okinawarb/status/974837082383249408
> - [x] 動画をウェブサイトから公開 => http://ruby.okinawa/okrk02/

**Comment by yasulab** [comment]
> 照屋さんの会計処理 ( @yasulab がやる; 領収書の送付待ち @takahashim に振込先と領収書を共有)

こちら、清算が終わったことを確認しました! ご対応ありがとうございます 😸

**Comment by snoozer05** [comment]
@kakutani 須藤さんの会計処理はどうなってますかね ref https://github.com/ruby-no-kai/official/issues/293#issuecomment-372574882

**Comment by snoozer05** [comment]
須藤さんの会計処理がどうなっているか不明

**Comment by kou** [comment]
かくたにさん以外の人に必要な情報を共有した方がよさそうならそうします！

**Comment by snoozer05** [comment]
@kou info@ruby-no-kai.org 宛に必要な情報をお送りいただけますでしょうか 🙏

**Comment by kou** [comment]
@snoozer05 送りました！

**Comment by takahashim** [comment]
@kou これで支払っておきますね

**Comment by kou** [comment]
ありがとうございます！
振り込まれていることを確認しました！
