### ISSUE TITLE
Rails Girls Kyoto 8thのスポンサー費用請求

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#296]
…ってなんかやることあります? CC @hsbt 

---
請求することになったので以下TODO

- [x] 請求する
- [x] 精算する
- [ ] 入金確認する

**Comment by hsbt** [comment]
あ、 issue 建設ありがとうございます。

請求の詳細までは現時点では僕はまだ把握してないので @yada-ITA と @springaki に聞いてみます...!

**Comment by yada-ITA** [comment]
issueありがとうございます。
今回、請求を１社お願いしたいです。
請求先については、先程メールにて送信しておりますので、宜しくお願い致します！

**Comment by takahashim** [comment]
@yada-ITA メール受け取りました！　いただいた内容で請求書を発行しますね

**Comment by shyouhei** [comment]
現状: 請求書発行済み、費用精算済み、入金確認済み。
