### ISSUE TITLE
2018年も海外のRubyカンファレンスへの渡航費支援をやるぞ 💪 

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#297]
基本的には去年と同じ文面です:
https://github.com/ruby-no-kai/official/wiki/OverseasRubyConfTravelGrant2018

TODO:

* [ ] 応募フォームの用意
* [ ] RubyConf 2018の渡航支援をruby-no-kaiがやるのかどうかを決める

**Comment by shyouhei** [comment]
現状: フォームが整備されつつある。台湾のCFPに間に合うように頑張る
next action: アソシエーション方面にサクりと確認して公開

**Comment by takahashim** [comment]
2018はほぼ終わってしまったので、来年から本気出したい
