### ISSUE TITLE
ある地域のRubyistが"他所"の地域Ruby会議に参加する費用を支援できる枠組みを用意したい

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#298]
#297 の準備をしていて、やっぱりあったほうがいいなと思ったのであとで書くつもりでfileしておきます。

目的や選考とかの叩き台は後日かんがえます…。

* * *

issue closeまでの道程をToDoにした:
https://github.com/ruby-no-kai/official/issues/298#issuecomment-1385424277

**Comment by shyouhei** [comment]
現状: 動きなし
next action: たたき台を作成

**Comment by shyouhei** [comment]
現状: 動きなし
next action: たたき台を作成

**Comment by springaki** [comment]
現状: 動きなし
next action: たたき台を作成

**Comment by springaki** [comment]
現状: したかった。動きなし
next action: たたき台を作成

**Comment by snoozer05** [comment]
ちょっと拡散してみて、需要があるか、どんな風にできるかを探る。
[直近の地域Ruby会議](https://github.com/ruby-no-kai/official/wiki/RubyEventCheck#%E4%BB%8A%E5%BE%8C%E3%81%AE-ruby-%E9%96%A2%E9%80%A3%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88)に行けたら行ってみたいな、みたいな人いないかなあ。

**Comment by kakutani** [comment]
2019年に地域Ruby会議やってくれた人たちにちょっと聞いてみましょうか〜

**Comment by kakutani** [comment]
ruby-jpに`#regional_rb`という便利チャンネルができたので、そこで聞いてみた。

**Comment by kakutani** [comment]
ニーズはありそうな雰囲気だったが、今後どうなるかわからん…

**Comment by kakutani** [comment]
引き続きCOVID-19の状況の推移を緊張感をもって見守るしかない

**Comment by springaki** [comment]
引き続き見守っていく

**Comment by springaki** [comment]
具体的な話が出てくるまで、引き続き見守っていく

**Comment by pupupopo88** [comment]
引き続き見守っていく

**Comment by springaki** [comment]
こんなご時世ではありますが、見守っていく

**Comment by kakutani** [comment]
引き続きこんなご時世につき…

**Comment by kakutani** [comment]
変わらず…。

**Comment by springaki** [comment]
変わらず...。引き続き世の中の動向を注視しておく。

**Comment by springaki** [comment]
目的としては、オーガナイザーとか、地域コミュニティ形成している人達が他のコミュニティとももっと交流できるといいなぁ。みたいなお気持ち。

枠組みとしては難しいけど、どこかでオンライン開催=>物理開催に移行していくタイミングとかで、他の地域Ruby会議とかに行って交流したい。みたいな人達がいればお声がけいただく。

- 各コミュニティのオーガナイザーとかが集まってる場とかでお伝えしていければいいかなぁ。
- 気配を察知したら、軽くお話ししてみる。


お問い合わせの方法は
- GitHub Issue からこれる人はそれで。そこから来る人はだいたい知ってる人の気もする
- Google Form 作って、そこから会話スタートできる程度の情報だけ書いてもらう方式
くらいでいいかなー

**Comment by springaki** [comment]
一旦これで。
https://forms.gle/YEEskXqsMftbUHWJA

あとで https://ruby-no-kai.org/contact.html にもリンクしておく。

**Comment by snoozer05** [comment]
あとで https://ruby-no-kai.org/contact.html にもリンクしておく。 -> 島田がやってみます

**Comment by springaki** [comment]
変わらず。見守っている。

**Comment by kakutani** [comment]
2022年の冬を乗り切ればできそうな予感がしてきたが…

**Comment by snoozer05** [comment]
https://ruby-no-kai.org/contact.html こんな感じでつけてみましたー

**Comment by takahashim** [comment]
良さそうです！

**Comment by springaki** [comment]
変わらず。見守っている。

**Comment by springaki** [comment]
そろそろどこかの地域Ruby会議が開催されそう？
見守っている... 👀

**Comment by springaki** [comment]
2023年にはどこか開催されそう。
その際にはオーガナイザー支援などやっていく。
引き続き見守っている... 👀

**Comment by shyouhei** [comment]
そろそろか

**Comment by kakutani** [comment]
福岡03からやりたいな〜

**Comment by snoozer05** [comment]
福岡03でやってみよう！！やり方は別途...

**Comment by kakutani** [comment]
福岡03に向けて…:

* [x] 文面をつくる
* [x] Google Formをつくる
* アナウンスする
* [x] twitter
* [x] ruby-jp

**Comment by kakutani** [comment]
文面をつくってみました: https://github.com/ruby-no-kai/official/wiki/RegionalRubyKaigiTravelGrant

**Comment by kakutani** [comment]
Google Formをつくってみました: https://forms.gle/vdTnxYwXX45gzp127
(所有者や置き場所で混乱して海外カンファレンスのほうを壊してしまった…。scrapboxに移ったら見直したいですが、ひとまずこれで…)

**Comment by kakutani** [comment]
tweeted: https://twitter.com/rubynokai/status/1616388052137693184

**Comment by kakutani** [comment]
#regional_rubykaigi にポストした: https://ruby-jp.slack.com/archives/C04BGJK7C94/p1674212046290429

**Comment by kakutani** [comment]
落ち着いたらscrapboxに移したり、Google Formを作りなおしたりしたいけど、いったんこのIssueとしてはcloseできる状態になったと思う。

**Comment by snoozer05** [comment]
やれたという実績はできた。ので、一旦閉じる。
募集などのスキームは別途整理
