### ISSUE TITLE
Rubyist Hotlinks テープ起こしのアウトソース費用ご支援のお願い

### ISSUE THREAD

**Issue by miyohide** [ruby-no-kai/official#299]
みよひで@るびま編集部です。

現在、Rubyist Hotlinksのテープ起こしを外部の業者（以前 #199 にて利用した業者に依頼予定）にアウトソースすることを考えています。

録音時間と納期から算出された見積金額は、税込み33,534円。より正確な見積もりは、現在依頼中です。

つきましては、アウトソース費用のご支援をお願いしたいと考えております。

よろしくお願いします。

**Comment by takahashim** [comment]
@miyohide はい、問題ないです！　前回と同様に請求書を回していただければ。

**Comment by miyohide** [comment]
@takahashim ありがとうございます。では、作業を進めます。正確な金額やスケジュールが分かりましたらまたご連絡します。

**Comment by kakutani** [comment]
テープ起こしのアウトソース自体はメリットしかない気がするので、基本的にはるびま方面判断で必要だったらお願いしてもらっちゃって、請求を回しますよ的な事後報告 && 我々のリマインダーとしてissueにfileしてもらうのがいいんじゃないかなーと思いました。まる。

**Comment by miyohide** [comment]
@takahashim 見積りを頂けました。金額は33,534円（税込み）、納期は2018年1月9日（火）予定です。

納品され次第、請求書をPDFにて送付いたしますので、振込よろしくお願いします。

**Comment by miyohide** [comment]
@takahashim 本日、業者より納品のお知らせをいただきました。合わせて請求書もいただきましたので、 @takahashim さんにメールにて送付しました。お手数ですが振込をお願いします。
なお、メールでもご連絡しましたが、先方が振込確認を行う関係上、

- 振込日
- 振込人名

の情報も合わせていただけますと助かります。

**Comment by takahashim** [comment]
@miyohide こちら振込予約を行いました。1/10に振り込む予定です。
振込人名は「８７５９５シヤ）ニホンルビ－ノカイ」になっております。

**Comment by miyohide** [comment]
@takahashim 振込、ありがとうございます。先方の振込確認が取れましたら、このIssueを閉じたいと思います。
なお、ざっと文字起こし内容を確認しましたが、専門用語も正しく文字起こしされていました。

**Comment by miyohide** [comment]
先方の振込確認が取れましたので、本Issueは閉じます。
ご協力ありがとうございました。
