### ISSUE TITLE
Wikiを移行する

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#3]
現状のWIkiコンテンツのうち、賞味期限が切れていないものについては移行する。
また、新規のページ作成についてはこちらのWikiに誘導する（Ruby関西には別途相談）。

**Comment by kakutani** [comment]
凍結ボタンを押すにはadminでログインしないといけないっぽい……(パスワード知らない)

**Comment by takahashim** [comment]
どこか表に書いておいた方がいいですか？（kakutaniさんにはDMで伝えましたが）

**Comment by kakutani** [comment]
更新日時の旧いものから(凍結していこうと思います! Ruby関西方面を除いて)

**Comment by takahashim** [comment]
ちょっと現行Wikiのトップページにもコメント書いておきますね

**Comment by takahashim** [comment]
Ruby関西については無量井さんにメールしてみました。どうするかはRuby関西のスタッフ用MLで検討してもらえそうです。

**Comment by takahashim** [comment]
無量井さんから返事が来ました。Ruby関西のWikiについてはこことは別のところに移行予定で、9/15で移行完了の予定だそうです。

**Comment by kakutani** [comment]
関西Ruby会議04でRuby関西の人たちと話をしよう。

**Comment by kakutani** [comment]
凍結してよいと @muryoimpl と話をつけました。あとはやるだけ……。

別件だけど、ruby-no-kai からいまの公式Wikiへのリンクが無いですね。

**Comment by kakutani** [comment]
ひとまず、FrontPage以外はぜんぶfreezeしてみました。一旦閉じちゃっていいですかね? > @takahashim @snoozer05

**Comment by kakutani** [comment]
done
