### ISSUE TITLE
vimeoのアカウントを引き受ける

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#30]
https://twitter.com/#!/iogi/status/177404483221995522

@iogi から引き取らないといけない。

(どういう手続きにすればよいのでしょうか…… @takahashim )

**Comment by takahashim** [comment]
今後も継続的に支払う必要はあるんでしょうか？
なければとりあえずこれまでの金額を聞いて請求書？を回してもらえれば確実でしょうか。あーでも面倒ならRubyKaigiのお金から出したことにする方がきれいなのかなあ。

あと、vimeoのアカウントそのものの引取り作業ってどんなことをすればいいんでしょうか。登録者メールアドレスとクレカ番号みたいなものを変更する？

**Comment by kakutani** [comment]
話が混ざってますね。まずは、これまでの金額を @iogi にお支払いしたいです。
アカウントそのものを引き取るかどうかは別の話にしましょう。

**Comment by kakutani** [comment]
「RubyKaigiのお金から出したことに」できるならそれがいいなあ、と思いました(可能なら)。

**Comment by takahashim** [comment]
年度で区切ってもそれが妥当なんじゃないかという気がしてきました！（料金先払い）

**Comment by kakutani** [comment]
具体的な事務手続きって、あづみさんから引き継がなくていいんですかねえ。一般社団法人の手続きで進めてしまえばよい? > @takahashim

**Comment by takahashim** [comment]
特に引き継ぐ必要がないのであれば（お金周りであづみさんの方から出さないと足りないとかでなければ）、一般社団法人の手続きで問題ないと思います。

**Comment by kakutani** [comment]
#33 のあとで処理する。

**Comment by kakutani** [comment]
@iogi お忙しいところ恐れいりますが、info at ruby-no-kai dot org までメールいただいてもよろしいでしょうか…… vimemo の精算の件で(長らく放置していて申し訳ありません)。

**Comment by kakutani** [comment]
連絡は来たので、金額を確定させる( #33 を倒さないと……)

**Comment by kakutani** [comment]
振り込みました!!
