### ISSUE TITLE
Rails Girls Nagoya 4thのスポンサー費用請求

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#300]
…ってなんかやることあります? CC @yada-ITA @springaki 

---
追記：ふつうに請求する

- [x] 請求する
- [x] 精算する
- [x] 入金確認する

**Comment by springaki** [comment]
Issue立てありがとうございます。
今のところ特にないです。いつもどおりスポンサーさんが付いたら請求関係をお願いします。
また開催後に請求あり/なし含めて共有します

**Comment by yada-ITA** [comment]
issue立てありがとうございます！
スポンサーさま、つくことになりましたので、請求関係お願いすることになります。
また開催後、早めに共有するようにしますので、どうぞよろしくおねがいします！

**Comment by yada-ITA** [comment]
今回、請求を３社お願いしたいです。
請求先については、メールにて先程送信しましたので、宜しくお願い致します！

**Comment by takahashim** [comment]
@yada-ITA こちら了解です！

**Comment by shyouhei** [comment]
現状: 請求書送付待ち
next action: 送付する

**Comment by takahashim** [comment]
@yada-ITA こちら3件請求処理しました！　郵送分は週明け送付の予定です。

**Comment by snoozer05** [comment]
現状: 送付済み
next action: 入金待ち（今月末の予定）

**Comment by takahashim** [comment]
入金確認できました！　ので閉じておきます
