### ISSUE TITLE
RubyKaigiに来る学生の旅費宿泊費を支援するというのはどうだろうか

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#301]
開催地以外に居住している学生が気軽にRubyKaigiに来れるようにする施策を考える。

**Comment by hsbt** [comment]
RG alumna 向けの企画を次回もやろうと思ってるので、足並み揃えられると良さそうって感じてます。

**Comment by kakutani** [comment]
ぜひっ

**Comment by shyouhei** [comment]
現状: やるのはやるということでよいとおもう。諸条件を揉む必要あり。
next action: たたき台を作る

**Comment by snoozer05** [comment]
たたき台を作りたいものの、動けていない

**Comment by springaki** [comment]
- RubyKaigiに来る人たちの間口をひろげたい
- 金銭的に余裕のない学生さんたちを支援する
- 遠い地で開催される事が多いので交通費がかさんでツライ。行けない。という人むけ

**Comment by springaki** [comment]
現状: 動きなし
next action: たたき台を作成

**Comment by amatsuda** [comment]
そうこうしているうちにESMさんがやってくれましたね。この事例はだいぶ参考になるんじゃないでしょうか。 http://blog.agile.esm.co.jp/entry/rubykaigi_tour_2018

**Comment by hsbt** [comment]
YAPC だと学生支援スポンサー(金額に応じて * n 名みたいな奴)と利用用途を明確にした奴がありましたー。

**Comment by springaki** [comment]
現状: 動きなし
next action: 一旦 ESMさんに様子聞いてみる ( @kakutani )

**Comment by shyouhei** [comment]
現状：今年に関してはなにか動きがありそうだ。

**Comment by shyouhei** [comment]
現状: 2019に関してもスポンサー様が実施された
next action: 目配せをしておく
classiさんと振り返りをしたほうがいいのかどうか

**Comment by kakutani** [comment]
RubyKaigi 2020で企業さんがやってくれるならそれでいいかも…

**Comment by springaki** [comment]
前回スポンサーをしてくれた企業さまに、ヒアリングしてみる

**Comment by springaki** [comment]
まだヒアリングできてない
Next Action: 時期をみつつヒアリングする (急ぎではない)

**Comment by springaki** [comment]
またニーズがあれば、再考する。一旦 Close.
