### ISSUE TITLE
Dropbox Business検討

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#303]
RubyKaigiの方で、ファイルの共有（特にスポンサーさんからのファイル送付）用にRubyの会のDropboxがあるといいのでは…という話が出ていたので、検討（下記の非営利団体割引が使えるかどうか問い合わせ）中です。

https://www.dropbox.com/ja/help/business/discounts

**Comment by takahashim** [comment]
お返事いただきました。一般社団法人は非営利団体には該当しないそうです。うーん。

**Comment by kakutani** [comment]
現状の問題としてはフォルダ共有とかのときに、特定個人が出ちゃってビミョウだね…とのことだと思うので、いったん info さんのアカウントをつくってみればいいですかねえ。

**Comment by shyouhei** [comment]
現状: あんまりメリットなさそう…
next action: Dropboxの普通の有料ユーザーを追加すればいいのでは…?

**Comment by snoozer05** [comment]
今年の分は進んじゃったので、来年また思い出したら考える
