### ISSUE TITLE
Ruby インタプリタ開発用の Windows 環境の支援

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#304]
昨年末から内々にはご相談していた Ruby インタプリタの開発のために利用可能な Windows 環境の費用をご支援いただけないかご相談したいです。

現在、Microsoft 様から開発用途のために MSDN ライセンスを提供いただいてますが、このライセンスでは Azure の環境を 1vm しか稼動できません。希望としては

 * @k0kubun さんが進めている mjit 開発など、Windows 環境の対応も必須とされるような開発アイテムで使用可能な共有開発環境(1vm)
 * vc12 以外の CI 環境、vc14(vs2015), vc15(vs2017) の 2vm 

で $300-$400/month くらいを想定しています。

支払いのスキームなどもご相談したいので詳細をここで詰めさせてください〜。

**Comment by k0kubun** [comment]
RubyInstaller2にも使われているMinGW環境のCIが現時点で無いらしいのですが、mjitの最初のWindows対応としてMinGW環境を想定しているため、MinGWでRubyをビルド/CIできる環境があるととても開発が楽になります。

**Comment by takahashim** [comment]
了解です、Rubyの会にはジャパンネット銀行の口座があるのですが、そこのVisaデビットで（普通のクレジットカードのように）支払えれば手っ取り早そうです。

**Comment by kakutani** [comment]
shugo さんにも相談して、まずは会のほうで試してみてください、とのことでした。
実際の金額がどれぐらいなのかがわかると、Rubyアソシエーションで予算化するとかもできるかも(するとはいってない)、とのことでした。

**Comment by shyouhei** [comment]
現状:  やるということでよいとおもう
next action: カードレスVisaデビットというものがある。とりあえず一個カード番号を作ってみる。

**Comment by hsbt** [comment]
手配、お願いします...!

最初に書いた見通しから mingw が追加になっているので、400-500$/month くらいになりそうです。

**Comment by takahashim** [comment]
@hsbt これってazureのアカウントを一個作るのがいいですか？　それともすでに使ってるのがあります？

**Comment by hsbt** [comment]
@takahashim すでに使っているものがあるので、高橋さんをその AD(グループ)に招待して支払い管理者設定 > subscription 作成(支払いアカウント)という順序でどうでしょうか?

**Comment by takahashim** [comment]
@hsbt はい、ではそれでお願いします！
招待、メールアドレスでよければ takahashim@ruby-no-kai.org とか info@ruby-no-kai.org とかで。

**Comment by takahashim** [comment]
ドメインの認証のため、ruby-no-kai.orgのDNSのTXT レコードをいじる必要があるっぽいです…

**Comment by takahashim** [comment]
DNS設定してRubyの会のディレクトリ（？）ができて、そこにサブスクリプションを持ってこれたので、今hsbtさんを招待してます

**Comment by snoozer05** [comment]
できて動いているので、いったん閉じます。
請求も動き始めている。

**Comment by takahashim** [comment]
Azureの請求額ですが、2018/04/06 - 2018/05/05で¥41,471でした。
だいたいこれくらいで安定すると年間50万円くらい予算として積んどく感じでしょうか。
