### ISSUE TITLE
bladeの後継システム

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#306]
@hsbt bladeの件でRubyの会でお手伝いできることがありましたら！という意思表示をとりいそぎ…

**Comment by hsbt** [comment]
原先生とコンタクト取った内容としては、今年は何とか大丈夫そうということでした。ただ、この先5年、10年のスパンで大丈夫かというと、そうではなさそうです。

2018年のうちにコードやデータを頂けないか聞いてみようと思います。

**Comment by hsbt** [comment]
記録: 原先生にメールを出してみました。

**Comment by snoozer05** [comment]
@hsbt その後どうなりましたか？

**Comment by hsbt** [comment]
お返事なしです...!

**Comment by snoozer05** [comment]
はい...!!

**Comment by snoozer05** [comment]
状況に変わりはなさそう。とりあえずは大丈夫そうだけれど

**Comment by hsbt** [comment]
引き続きお返事なしです...!

**Comment by snoozer05** [comment]
はい...!!

**Comment by springaki** [comment]
現状: 動いてる筐体はリプレースされたっぽい？
next action: @hsbt に様子を聞きつつ、やり方考える

**Comment by hsbt** [comment]
いつからかちょっとわからないのですが、現時点で blade は落ちているようです。依然として返事はない状態なのでお伺いをもう一度する感じですかね...

**Comment by springaki** [comment]
おぉ...なるほど... よろしくお願いします 🙏

**Comment by shyouhei** [comment]
現状: 気をもんでいる

**Comment by snoozer05** [comment]
現状: 気をもんでいる

**Comment by kakutani** [comment]
現状: 気をもんでいる

**Comment by springaki** [comment]
現状: 気をもんでいる

**Comment by springaki** [comment]
現状: 気をもんでいる

こんどしばたさんと話す事があれば、かるーく情報共有しとこうかな。くらい

**Comment by springaki** [comment]
現状: 気をもんでいる

**Comment by springaki** [comment]
@hsbt この件ってもうどうやっても連絡取れない感じでしょうかねぇ。他に連絡できるパス等心当たりあれば教えていただきたく。 5年はまだ経ちませんが、もう3年経とうとしてはいる。みたいな感じでした... 急いでいるわけではないのですが、すべてが失われるとつらい...

**Comment by hsbt** [comment]
ちょっと思い出したようにメール出すか連絡をとってみます。

**Comment by springaki** [comment]
いつもお願いしてしまって申し訳ない... よろしくお願いします〜 🙏

**Comment by kakutani** [comment]
@shyouhei says:
> 今日Ruby開発者会議でbladeの話ちょっとできました、それ以上の動きはないが、一応柴田さんとは認識共有できてる感じ (3/17)

**Comment by kakutani** [comment]
原先生と連絡はついた! 引き取るまでには、まだ色々ありそう…。 @hsbt がやりとりをしてくれている!

**Comment by hsbt** [comment]
後継システム、の開発はまだまだこれからなのですが 2021/4/1 時点の全データは取得しました。

**Comment by springaki** [comment]
とりあえず良かった。

**Comment by kakutani** [comment]
* @hsbt の手元にある。まだ`unzip`してない(やっときます〜)とのこと
* ライセンスを処理して `ruby/blade` あたりに置いてみると面白いのでは by @amatsuda 
* ruby-langのMLはMLとして使われている感じはあんまりなくなってきたねえ。redmine購読ツールとしては悪くなさそう(感想)
  * yuguiスペシャル(redmineのメールインターフェイス)は役割を終えてそうだね(余談)

**Comment by hsbt** [comment]
zip のまま手元に眠って半年経とうとしている...という状況なのでまずは中身を眺めて *.rb なツリーは github.com/ruby/blade などにまずは private など何かしら置いていこうと思います。

**Comment by snoozer05** [comment]
blade壊れたらしいという情報あり（ hsbt が取得した以降のデータは失われた可能性があるのこと...

**Comment by hsbt** [comment]
👋  blade は壊れて起動しなくなったそうです。

* 原先生に聞いたところ、Ubuntu を入れ直して復旧しようとはしている
* ただデータのバックアップはなく、 起動しなくなった HDD から吸い出そうとしているが、無理そう。@hsbt が問い合わせたときに取得したものが最新のものになる可能性がある
* @ko1 さんがメールサーバーに購読しているものは残っているかもしれないとのコメント
* @shugo さんと話して Ruby 関係の ML は Google Group に引っ越すついでにアーカイブも Google Group にしようか、と @hsbt が考えているところ

が現状のステータスです。RubyKaigi 2022 が終わった後に @hsbt が本気出していく予定です。

**Comment by snoozer05** [comment]
状況の共有ありがとうございます!!
承知しました 🙏

**Comment by hsbt** [comment]
本気を出していくことにしました。

https://bugs.ruby-lang.org/issues/18976#note-2 に記載した通りですが、txt のみを保持する blade とは異なる仕組みを新たに作ることでなんとかする予定です。

**Comment by snoozer05** [comment]
よろしくお願いします!!

**Comment by kakutani** [comment]
復活した 🎊  https://bugs.ruby-lang.org/issues/18976#note-4 ありがとうございます!
(なので、ここは閉じてもよさそう)

**Comment by hsbt** [comment]
なんとかなったので close でよさそうです! 原先生にも一報を入れておきました。

**Comment by kakutani** [comment]
原先生へのご連絡、よろしくお願いします！おつかれさまでした。
