### ISSUE TITLE
rkoのアカウント整理など

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#308]
rkoのgoogleアカウントを整理していく

**Comment by snoozer05** [comment]
このissueの経緯が失われてしまった....
グループとか個人のアドレスについて整理する？

**Comment by springaki** [comment]
私が整理のたたき台を作ります

**Comment by springaki** [comment]
現状: 動きなし
next action: やります

**Comment by springaki** [comment]
現状: 整理中
next action: 

- グループについては RubyKaigi 2016年以前のグループと 地域Ruby会議関連の終わったものを消す。
(未到達なヤツは info@に届くことを確認)

- 個人アカウントについては @darashi さんのRubyKaigiアカウントが残っている様子。使われてないようなので削除したいのですがいかがでしょうか。 > @darashi

**Comment by darashi** [comment]
@springaki 削除いただいて問題ありません。どうぞよろしくお願いします！

**Comment by springaki** [comment]
@darashi 了解しました。ありがとうございます !!

**Comment by springaki** [comment]
darashiさんアカウント削除した

**Comment by shyouhei** [comment]
棚卸し終わり。@darashi ありがとうございました。
