### ISSUE TITLE
Ruby Kajaを手伝いたい!

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#31]
@nagachika が提案してくれたやつ。
http://d.hatena.ne.jp/nagachika/20120312/ruby_kaja

Yokohama.rb方面が中心でいいと思うので、日本Rubyの会としてなんか後援なりお手伝いなりをしたいです。
http://d.hatena.ne.jp/nagachika/20120312/ruby_kaja
### 追記

Webサイト: http://kaja.rubyist.net/

**Comment by takahashim** [comment]
具体的には何すればいいんですかねえ。
- 投票・公表サイト制作
- 投票呼びかけ
- 集計作業
- その他

**Comment by kakutani** [comment]
- 受賞のときにあげる何かをスポンサード

**Comment by satococoa** [comment]
ドメインがほしいです！
仮）kaja.rubyist.net

**Comment by takahashim** [comment]
kaja.ruby-no-kai.org でも良ければ簡単なんですが……

rubyist.netって今どういう管理になってるんでしたっけ？(名前持ってるのはまつもとさんだけど、ネームサーバの管理とwhois情報の管理的な意味で)

**Comment by satococoa** [comment]
Yokohama.rbのメンバーで案を出したときに ruby-lang.org や rubyist.net 使いたい、ということになり `kaja.rubyist.net`が一番かっこいいねー、という話に今のところなっています。
使用可能なドメインがわかれば、その中から選べれば嬉しいです。

**Comment by dan5** [comment]
まだ具体的には決まってないのですが、みなとRuby会議開催中にRuby Kajaの第一歩となるイベント的なものができたらいいなと考えています。

**Comment by kakutani** [comment]
asakusarbのときは、@shugo が作業してくれました。
リダイレクト先が决まれば、お願いできると思います > @satococoa 

なんかお手伝いできそうなことがありそうなら、ぜひぜひ巻き込んでください! > @dan5

**Comment by dan5** [comment]
ありがとうございます！
特に投票呼びかけはYokohama.rbの力だけでは弱すぎるので
話が具体化してきたらぜひ相談させてもらいたいです>@kakutani

**Comment by satococoa** [comment]
ありがとうございます。
木曜日に みなとRuby会議 系でミーティングをするので、その場でKajaについても話し合います。
進展がありましたら適宜共有したいと思いますのでよろしくおねがいします。

**Comment by kakutani** [comment]
@dan5 @satococoa はいー。なんかここが本スレみたいになって来てますけど、いいんですかね?
(なんか面白いから続けるのを試してみたい)

**Comment by dan5** [comment]
他にいいところが出来るまではここが本スレでー

**Comment by amatsuda** [comment]
(きっと誰か既に指摘してるに違いないと思いつつ)
「冠者」って _男子_ 限定感の強いフレーズのように思うんですが、そのあたりのニュアンスはどうなんでしょう？あっちだってheroなんだからそんなもんなのか？

**Comment by nagachika** [comment]
はい、名前を考えた時に最初に考えた懸念は性別を限定しそうであるということでした。なのではてなダイアリーでは脚注で補足しましたが性別を問わないことは常に強調したいと思います。
冠者は「成人して冠をつけた男子」という定義からして男性を指す言葉だと思います。とはいえ、たとえば「侍」が暗黙のうちに(文化的背景から？)男性を指すであろうのと同様に「冠を戴くのは男子」という文化背景によるものだと思いますので、現代においてその意味を再解釈してみせるのはそれはそれで痛快ではないでしょうか。
とか屁理屈を言いましたが、古くからの言葉を拝借しようと思うと多かれ少なかれ性差の問題はつきまとうのでしょうね。その点現代に産まれた「ジェダイ」などの言葉はその問題から解放されていてうらやましいです。

**Comment by kakutani** [comment]
私は @nagachika のはてダの脚注や↑で仰っている内容で良いと思っていたのですが、それだとナイーブすぎますかねえ。私としては良い名前があればそれに乗りたくて、いまのところkajaがいちばんいいなと思っているのでした。

**Comment by dan5** [comment]
昨日Yokohama.rbのメンバーでkajaについて話し合いました。
そこでYokohama.rbとしての方針は決まりました。

近々 @tyabe から具体的な相談が @kakutani 宛？に行くと思いますー

**Comment by kakutani** [comment]
みなとRuby会議でなんかやる、という件はうかがいました!!(報告まで)

**Comment by kakutani** [comment]
2012.04.24のAsakusa.rbで @tyabe と @dan5 から大枠の話を教えてもらいました。
日本Rubyの会で手伝えることはいろいろとありそうなので、次の理事会(2012.05.09)でしたいです > @takahashim , @snoozer05 

最初のアナウンスが[みなとRuby会議01](http://regional.rubykaigi.org/minato01)であるそうです。

**Comment by kakutani** [comment]
まずは、kajaのqwikに @snoozer05 を追加する(札幌Ruby会議2012で枠をつくってもらえんか、という話は打診しました)

**Comment by kakutani** [comment]
みなとRuby会議01でアナウンスされた。いまは、るびまでのアナウンス準備中。
そこまでやったら一旦閉じていいかな(あとは個別でissuesを起こす)

**Comment by dan5** [comment]
そうですね。るびま公開で閉じていいと思います。

**Comment by kakutani** [comment]
http://jp.rubyist.net/magazine/?AnnounceRubyKaja

http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-list/48795

DONE!
