### ISSUE TITLE
TokyuRuby 会議 12 の開催

### ISSUE THREAD

**Issue by koichiro** [ruby-no-kai/official#310]
こんにちは。Tokyu.rb の 大場 と申します。

第 12 回目となる TokyuRuby 会議の開催を
以下の要領にて計画しております。
日程のみ決まっており、役割等はこれから決める予定です。
おおよそこれまでの TokyuRuby 会議と同規模のものを予定していますが、
取り急ぎ日程を確保致したく、連絡させていただきます。

名称：TokyuRuby 会議 12
開催日：2018年7月29日(日)
会場：株式会社VOYAGE GROUP
参加費：無料
配信：なし
定員: 未定
実行委員長：大場　光一郎
実行副委員長：五十嵐　邦明
　加藤　由佳
　小椋　隆史
　小川　伸一郎
　影山　勝彦
　三浦　美咲樹
　小田切　わか菜
　多田　亜希
　樽家　昌也

**Comment by publichtml** [comment]
TokyuRuby会議12 実行委員の方から来ました。

公式ページを作成しましたのでお知らせいたします。

公式ページ: https://tokyurubykaigi.github.io/tokyu12/

- [RubyEventCheck](https://github.com/ruby-no-kai/official/wiki/RubyEventCheck) からリンクをはりました
- [Regional RubyKaigi](http://regional.rubykaigi.org/) へは追加PR出しており、マージしていただけるの待ちです
  - https://github.com/ruby-no-kai/rko-router/pull/41
  - https://github.com/ruby-no-kai/regional.rubykaigi.org/pull/77

**Comment by publichtml** [comment]
> Regional RubyKaigi へは追加PR出しており、マージしていただけるの待ちです

こちら、マージしていただけて正常に表示されることを確認しました！
ありがとうございますー。

**Comment by snoozer05** [comment]
お疲れ様でした！
