### ISSUE TITLE
大阪Ruby会議の開催

### ISSUE THREAD

**Issue by ogom** [ruby-no-kai/official#311]
Ruby関西の おごもり (@ogom) です。

大阪Ruby会議の開催を計画しております。関西Ruby会議より小規模で開催します。
日程と会場が決まっており、役割などはこれから決める予定です。

名称: 大阪Ruby会議01
開催日: 2018年7月21日(土)
会場: 大阪科学技術センター
参加費: なし
配信: なし
定員: 100名程度

**Comment by ogom** [comment]
名称の年号を連番に変更します。なので `大阪Ruby会議2018` から `大阪Ruby会議01` に変更されます。

**Comment by ogom** [comment]
役割が決まりました。

* 実行委員長 :  @ogom
* るびまのレポート記事担当 :  @yucky39
* 会計 :  @cuzic

**Comment by ogom** [comment]
大阪Ruby会議01が開催されました。

レポート作成の issue はこちらです。
https://github.com/rubima/rubima/issues/469

**Comment by takahashim** [comment]
開催おつかれさまでした！　Twitterで見る限りは盛況だったようで何よりです。

**Comment by snoozer05** [comment]
閉じます！お疲れ様でした！
