### ISSUE TITLE
リモート会議用のマイク・スピーカーがほしい

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#312]
<del>8</del> 10〜15万円くらい？のものがあると捗りそうです。

**Comment by springaki** [comment]
@shyouhei さんが持ってるようなヤツかな

**Comment by takahashim** [comment]
たぶんそんな奴かと思います。

**Comment by asonas** [comment]
高橋さんと色々みていて、ヤマハの会議スピーカーがよいのでは、というお話をしていました。
https://sound-solution.yamaha.com/products/uc/yvc-1000ms
https://www.yodobashi.com/product/100000001003715515/

**Comment by takahashim** [comment]
結局ヤマハのYVC-R1000MSを購入しました
