### ISSUE TITLE
Stripeのアカウントを作る

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#314]
doorkeeperでの決済で、PayPalだとうまくいかない場合があるらしいので、Stripeのアカウントも作っておくとよいのでは…というアドバイスをもらいました。料率も良いそうです。

**Comment by takahashim** [comment]
ちなみにうちの会社で作った時はわりとあっさり作れた記憶があります。

**Comment by takahashim** [comment]
とりあえず法人情報を登録してみました。

**Comment by snoozer05** [comment]
作る

**Comment by snoozer05** [comment]
どこかで時間をとって作業する

**Comment by springaki** [comment]
Doorkeeper PayPalを使ったイベント決済のサポート終了
https://www.doorkeeper.jp/news/2018/10/2/end-of-paypal-support

との事なので次に使うタイミングまでには作ってテストしておきたいですね。

**Comment by takahashim** [comment]
こちらとりあえずアカウントは作って会社情報は登録してみました。
あとはわらわらとアカウントを作ってみればいいのかな？

**Comment by takahashim** [comment]
アカウントは作れたので、このissueは閉じておきます
