### ISSUE TITLE
松江Ruby会議09 開催について

### ISSUE THREAD

**Issue by yoshiokaCB** [ruby-no-kai/official#315]
お世話になります。Matsue.rb の @yoshiokaCB と申します。
第9回目となる 松江Ruby会議の開催を以下の要領にて計画しております。

名称：松江Ruby会議09
開催日：2018/6/30(土) 
会場：松江オープンソースラボ
参加費：なし
配信：あり（URL未定）
定員: 40名程度
実行委員長：吉岡 隆行
実行副委員長：木村 友哉
るびまのレポート記事担当：橋下 将
会計 : 杉原 健司
サイト： （準備中）

詳細が決まりましたらサイトに更新していきたいと思います。
またご相談させていただくこともあるかと思いますので、取り急ぎ開催の宣言をさせていただきました。
何卒よろしくお願いいたします。

**Comment by yoshiokaCB** [comment]
公式サイトを公開しました。
https://matsue.rubyist.net/matrk09/

今回は特にご支援いただくことなく開催ができそうです。
開催後closeしたいと思います。

**Comment by takahashim** [comment]
おお、開催がんばってください！

**Comment by snoozer05** [comment]
お疲れ様でした！
