### ISSUE TITLE
永和システムマネジメントへの RG スポンサー対応(2018)

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#316]
昨年の issue: https://github.com/ruby-no-kai/official/issues/271

永和システムマネジメント様より、 2018 年も RG 全体の年間スポンサーとして 20 万円を拠出したいオファーをもらいました。昨年同様のフローにて 20 万円の請求書を発行していただきたいです。

発行先住所は https://github.com/ruby-no-kai/official/issues/271 と同様でお願いします...! 発行に合わせて 20 万円の資金移動もお願いします 🙏 

- [x] 請求する
- [x] 入金確認する
- [x] 資金移動する

/cc @koic

**Comment by koic** [comment]
請求書が届き次第、入金の方を進めさせて頂きます。請求書の発行よろしくお願いします。

**Comment by takahashim** [comment]
@hsbt @koic これですが、明細としては1口2万x10口と、年間まとめて20万x1口のどっちがよいでしょうか…？

**Comment by hsbt** [comment]
こちらとしては後者ですが、 @koic 特に要望などあります...?

**Comment by koic** [comment]
@takahashim @hsbt ご確認ありがとうございます。特に要望などはありませんので、想定されていた年間まとめて20万x1口にてお願いします。

**Comment by takahashim** [comment]
了解です、では20万x1口でお送りいたします！

**Comment by koic** [comment]
ありがとうございます。よろしくお願いします。

**Comment by takahashim** [comment]
入金確認しました！

**Comment by koic** [comment]
ありがとうございます！
