### ISSUE TITLE
Ruby開発マシン (@nobu 使用)

### ISSUE THREAD

**Issue by shyouhei** [ruby-no-kai/official#317]
@nobu のパソコンが壊れたんですって。
これRuby開発に支障が出るので新しいPCを買ってなかださんに送付あるいはRubyKaigiに持参とかがいいかとおもうんですがどうでしょうか

参照 #150 #207

**Comment by takahashim** [comment]
@shyouhei 普通に購入する場合、10万円を超えるとRubyの会の備品扱いになっちゃいますがいいですかね？
（備品だからといって特になにかするわけではないです）

**Comment by shyouhei** [comment]
いいかどうかは卜部が判断するものではない気が

**Comment by shyouhei** [comment]
@nobu @takahashim 進捗どうでしょう

**Comment by takahashim** [comment]
そういえばRubyKaigiでは話が出なかったのでした…。

@nobu どのマシンがよいとかありますか？

**Comment by takahashim** [comment]
MBP 15inchとのこと

**Comment by takahashim** [comment]
買いました

**Comment by amatsuda** [comment]
中田さんたしかキーボード日本語配列だった気がしますが、そのへんとか大丈夫ですか？

**Comment by takahashim** [comment]
はい、そのあたりについてはささださん経由で確認とったのでした

**Comment by amatsuda** [comment]
ほんとだ、ちゃんと確認してました(ログ読み追いついた)

**Comment by takahashim** [comment]
無事届いたようです
