### ISSUE TITLE
RailsGirls Tokyo 9th のスポンサー費用請求

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#318]
5/18 開催の Rails Girls Tokyo 9th スポンサー費用の請求をお願いしたいです。

スポンサー一覧は、メールにて共有させて頂きました。

- [x] 請求する
- [x] 清算する
- [x] 入金確認する

**Comment by takahashim** [comment]
@emorima RailsGirlsの口座への精算は予約済みなので、朝に振り込まれる予定です。
請求書は準備できたので、問題なければ金曜に発送予定です。

**Comment by emorima** [comment]
@takahashim 
お忙しい中、早急な対応ありがとうございます!

**Comment by takahashim** [comment]
@emorima こちらメールの方は送付済みです。郵送の方は来週送られる予定です（忘れずに送れてよかった）。

**Comment by snoozer05** [comment]
高橋さんが入金確認する

**Comment by snoozer05** [comment]
全部終わったので閉じます。お疲れ様でした
