### ISSUE TITLE
倉庫入出庫

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#319]
RubyKaigi用にRubyの会の倉庫から6箱（全部）出庫して、会議後に入庫する予定です。

* [x] 出庫指定
* [x] 仙台で受け取る
* [x] 入庫準備
* [x] 入庫する

**Comment by takahashim** [comment]
ノートPC以外は入庫済み、それ以外に2箱追加のものが入庫予定になっています。

**Comment by springaki** [comment]
遅れていますがやります !

**Comment by springaki** [comment]
作業中...

**Comment by springaki** [comment]
現状: 荷造りした
next action: 送ります !

**Comment by springaki** [comment]
現状: 変化なし
next action: 送ります !!!

**Comment by shyouhei** [comment]
現状: あと @springaki が送ったらこのissueは閉じれる。

しかしこのタイミングに至っては次の会場に直接送付してもらうのもありなのではないか

next action @springaki どうします？

**Comment by springaki** [comment]
一旦倉庫にいれます ! ごめんなさい...

**Comment by snoozer05** [comment]
あとは集荷手配するだけ。金曜か土曜に集荷手配する予定

**Comment by springaki** [comment]
集荷された。おわり。
