### ISSUE TITLE
アスクルを自動引き落としかクレカ決済にする

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#320]
現状はコンビニ払いなのでめんどくさい。
とはいえ変更は紙じゃないとダメそうなので、とりあえず書類送付を依頼してみました。

**Comment by takahashim** [comment]
書類が来たので返送しました

**Comment by snoozer05** [comment]
その後どうなったかがわかっていない。
次回使ったタイミングでどうなるかを確認する

**Comment by snoozer05** [comment]
ダメだったらまた復活させるとして、これ自体は閉じてしまおう
