### ISSUE TITLE
国税庁法人番号公表サイトに英語表記を追加する

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#321]
なんとなく英語でも見られるようにしたほうが良さげな気がします。
で、英語表記は "Ruby no Kai" でいいんですかね…。

**Comment by snoozer05** [comment]
名刺の英語表記の内容で追加する。
そのうち郵送で提出する。

**Comment by snoozer05** [comment]
時間を見て作業する

**Comment by springaki** [comment]
現状: 動きなし
next action: やります ( @takahashim )

**Comment by shyouhei** [comment]
現状: 動きなし
next action: 折を見て実施する

**Comment by shyouhei** [comment]
現状：このまえちょっと頑張ってデータを登録するところまで実施した
next action: 書類を提出する。

**Comment by shyouhei** [comment]
現状: 動きなし
next action: 書類を提出する。

**Comment by shyouhei** [comment]
現状: 動きなし、書類はある
next action: 書類を提出する。

**Comment by shyouhei** [comment]
現状：ついに郵送した
next action: 表記が載るのを見届けて終わり

**Comment by kakutani** [comment]
載ってそう https://www.houjin-bangou.nta.go.jp/en/henkorireki-johoto.html?selHouzinNo=2011105005022

**Comment by takahashim** [comment]
のりました！
