### ISSUE TITLE
Rails Girls Osaka 5thのスポンサー費用請求

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#323]
6/16 開催の Rails Girls Osaka 5th スポンサー費用の請求をお願いしたいです。

スポンサー一覧は、メールにて共有します。

- [x] スポンサー様に請求する
- [x] Rubyの会からRailsGirlsにお金を振り込む
- [x] スポンサー様からの入金を確認する

**Comment by snoozer05** [comment]
振り込む
