### ISSUE TITLE
Rubyの会総会

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#326]
#325 が終わったら開催する。10月のどこか。

**Comment by snoozer05** [comment]
月火だと島田は調整しやすいです

**Comment by snoozer05** [comment]
来期の活動計画をそれぞれ何となく持ち寄る準備をしましょう

**Comment by springaki** [comment]
10月の予定がはっきり分からないのですが、10/2, 10/9, 10/16 あたりが行けそうです...

**Comment by snoozer05** [comment]
@springaki さんのスケジュールが分かり次第

**Comment by takahashim** [comment]
終わりました
