### ISSUE TITLE
大江戸Ruby会議07 への支援のお願い

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#327]
日本Rubyの会に2018/09/15 に開催される大江戸Ruby会議の開催費用の部分的な支援をお願いしたいです!

https://regional.rubykaigi.org/oedo07/

本編、または懇親会の会場費用について、具体的に支援してほしい金額は後ほどご相談させてください...

**Comment by hsbt** [comment]
@takahashim こちら会場代: 200000円(税込)をご支援いただきたいのですが可能でしょうか? Asakusarb 名義の領収書はあります。

**Comment by takahashim** [comment]
@hsbt はい、問題ないと思いますが、何か収支計画を読み誤ったとかですか？（Asakusa.rb名義の領収書のあたり）
金額が大きいときは確定ではなくても、額も含めて早めに教えていただけるとありがたいです…！

**Comment by hsbt** [comment]
🙇 

会場費用、懇親会会場貸切費用合わせてギリギリいけるかと思いましたが、本編のチケット代を安くしすぎたのと、スケジュールの公開が遅れたなどで思ったより入場者数が伸びなかったので赤字になってしまった、という背景があります。

**Comment by takahashim** [comment]
つらい 😢 
Asakusa.rbだったら詳しい人も多いので、変な科目の赤字は出ないかと思うのですが、他の地域Ruby会議で微妙な科目・金額の出費を救済してほしいと事後に言われると気まずくなってしまうので、あらかじめ連絡してもらう運用フローで統一したいのでした。よろしくお願いします…！
あと、振込先の方もDMその他で教えてください。

**Comment by takahashim** [comment]
こちら支払い完了しました！
