### ISSUE TITLE
Rubyの会のAWSアカウントを作りたい

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#328]
RubyKaigi用に欲しいとのことです。

**Comment by takahashim** [comment]
* RubyKaigi 2019で使いたい
* RubyKaigi 2018のアセットアーカイブ用にすでに使っている分がある（個人アカウントになっている）のをRubyの会に寄せたい

**Comment by sorah** [comment]
- [x] AWS からメールを受け取る Google Groups を用意 (aws@rubykaigi.org とか) (sorahに権限を渡すorだれかやってください)
- [x] `rubykaigi` アカウントを一個つくる (sorah がやる)
- [x]   請求情報を @takahashim に入れてもらう
- [x] iogi なアカウントのバケットからデータをもってくる

**Comment by takahashim** [comment]
@sorah `aws@rubykaigi.org` は作っておきました

**Comment by sorah** [comment]
Ruby-no-kai というよりかは RubyKaigi 用に用意しました。RubyKaigi esaに詳細のっけてあります。次のkaigikaigiで高橋さんに権限わたしつつ請求まわりお手伝い願うというのはどうでしょう。

**Comment by takahashim** [comment]
@sorah はい、それでよいかと思いますー

**Comment by springaki** [comment]
現状: 動きなし
next action: @takahashim さんに請求情報をいれてもらう

**Comment by shyouhei** [comment]
現状: 課金設定がない。このまま4月をむかえるとRubyKaigiが詰む :fearful: 
next action: @takahashim よろしくおねがいします

**Comment by shyouhei** [comment]
現状: 課金設定がない。このまま4月をむかえるとRubyKaigiが詰む :fearful:
next action: @takahashim よろしくおねがいします

**Comment by snoozer05** [comment]
現状: 課金設定がない。このまま4月をむかえるとRubyKaigiが詰む 😨
next action: @takahashim よろしくおねがいします

**Comment by shyouhei** [comment]
@sorah このチケットだいたい終わってるという認識なんですが、

> - [ ] iogi なアカウントのバケットからデータをもってくる

なんだっけこれ。覚えてます？

**Comment by sorah** [comment]
あ、達成できていそう。

"@takahashim さんに請求情報をいれてもらう" これまだ未達成です。

**Comment by sorah** [comment]
振り返り回の時にやってもらいたいところではあるが…

**Comment by shyouhei** [comment]
現状: 高橋さんとそらで作業中

**Comment by springaki** [comment]
@sorah @takahashim 状況いかがでしょうか。

**Comment by takahashim** [comment]
アカウントの作成までできました。クレカの切り替えが必要

**Comment by takahashim** [comment]
クレカ登録しました

**Comment by takahashim** [comment]
デフォルトの支払先をRubyの会のカードにしました。
