### ISSUE TITLE
GitHubとSlackとFront.appについて、non profitプランを検討したい

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#329]
こちらも RubyKaigi の方から出てきたのですが、GitHubとSlackのnon profit向けプランが使えないかどうかを検討してみるのはどうかということでした。

* https://github.com/nonprofit
* https://get.slack.help/hc/ja/articles/204368833-Slack-%E3%81%AE-NPO-%E6%94%AF%E6%8F%B4%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0

- [x] GitHub
- [x] Slack
- [x] Front.app

**Comment by takahashim** [comment]
Front.appも検討したい（ついでにPREMIUMプランにしたい?←なってるはずだけどできない機能がある？）
https://help.frontapp.com/t/q524vz/non-profit-and-education-discounts

**Comment by takahashim** [comment]
それぞれ問い合わせてみます

**Comment by springaki** [comment]
現状: 
- Slack の方は techsoup に登録してみた
- Front.app の方はまだ

next action: 
- techsoup の方は書類送る
- それ以外は順次やっていく

**Comment by shyouhei** [comment]
現状: 動きなし
next action: 書類を送付する

**Comment by shyouhei** [comment]
現状：slackのほうは無事nonprofitになったもよう :tada: 
next action: front appがまだ

**Comment by takahashim** [comment]
GitHubの方もnon profit planになったそうです 🎉 🎉

**Comment by amatsuda** [comment]
めでたい！
……ってことは、private repo無限に作り放題になったってことですか？

**Comment by takahashim** [comment]
はい、そのはずです

**Comment by shyouhei** [comment]
現状: Frontがまだ
next action: Front にコンタクトする。

**Comment by shyouhei** [comment]
現状: 動きなし、Frontにはフォームとかなくてサポートに投げる必要ぽく見受けられる。
next action: Front にコンタクトする。

**Comment by shyouhei** [comment]
現状: Frontにはいっぱつメールを投げた
next action: 返事待ち

**Comment by takahashim** [comment]
Frontはnon profit向けのdiscountで50% offになったみたいです。良かった。
