### ISSUE TITLE
残高を一般社団法人の口座に寄せる

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#33]
あづみさんとコンタクトを取る!

**Comment by kakutani** [comment]
あづみさんと連絡がついた!! 今月中に会う予定(週末から札幌にいくので……)

**Comment by kakutani** [comment]
あづみさんと確認することのメモ:
- PayPalの担当者を変更したいなあ
- 残っている精算はどれだっけ

**Comment by kakutani** [comment]
あづみさんと会えたので、通帳や印鑑をゲットしました。
次は、残高を動かす作業。

**Comment by kakutani** [comment]
やりますぞー(意思表明まで)。

**Comment by kakutani** [comment]
全額移しました。高橋さんの確認をもってCloseとしたい。

**Comment by takahashim** [comment]
どうもです！確認します！

**Comment by takahashim** [comment]
確認しました！　いっぱい入ってました！
