### ISSUE TITLE
リンクアンドモチベーションへの RG スポンサー対応(2018)

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#330]
リンクアンドモチベーション様より、 RG 全体の年間スポンサーとして 10 万円を拠出したいお申し出を頂きました。

発行先住所、宛名は別途ご連絡いたします。

- [x] 請求する
- [x] 入金確認する
- [x] 資金移動する

**Comment by emorima** [comment]
請求書の発行先は以下でお願いいたします。

〒104-0061 東京都中央区銀座6-10-1　GINZA SIX 12階
株式会社リンクアンドモチベーション
組織開発デザイン室 尾上 徹 様 宛

**Comment by takahashim** [comment]
@emorima こちら郵送手続きを行いました！　来週なかごろには着くかと思います。

**Comment by emorima** [comment]
@takahashim 早急な対応ありがとうございます！

**Comment by emorima** [comment]
@takahashim 

先方から年間スポンサーの掲載時期知りたいとのお問い合わせがありまして、
こちらの入金の確認をお願いしたいです！

**Comment by takahashim** [comment]
こちらですが、今日のところはまだ入金がないようでした

**Comment by emorima** [comment]
@takahashim ご確認頂きありがとうございます！ 🙇‍♀️  先方に入金のお願いをしておきます。

**Comment by takahashim** [comment]
@emorima 了解です、こちらの方はあまり頻繁に入金確認を行ってないので、入金後すぐにRails Girls Japan側でアクションが必要なんでしたら、入金したあとリンクアンドモチベーションから一報いただく流れにしてもらえるとありがたいです…！

**Comment by emorima** [comment]
@takahashim 承知しました！先方に入金後にご連絡頂けるようにお願いしておきます！

**Comment by emorima** [comment]
@takahashim 入金は経理処理都合で、今月末に振込予定とのことですので、12/1にご確認お願いします！

**Comment by emorima** [comment]
@takahashim 

リマインドになります。
本日振込処理をしていただけていると思いますので、
週明けにでも、入金の確認をお願いいたします！

**Comment by takahashim** [comment]
@emorima リンクアンドモチベーションさん、入金されてました！ 💰

**Comment by emorima** [comment]
@takahashim ご確認ありがとうございます！

**Comment by springaki** [comment]
現状: 動きなし
next action: 順次やっていく

**Comment by shyouhei** [comment]
現状: 入金確認済、資金移動が未
next action: 移動する

**Comment by shyouhei** [comment]
現状：資金移動も終わり

**Comment by hsbt** [comment]
2/25 に振り込まれているのを確認しました!
