### ISSUE TITLE
RailsGirls Tokyo 10th のスポンサー費用請求

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#331]
10/12, 13開催の Rails Girls Tokyo 10th スポンサー費用の請求をお願いしたいです。

スポンサー一覧は、メールにて共有させて頂きました。

- [x] スポンサー様に請求する
- [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
- [x] スポンサー様からの入金を確認する

**Comment by emorima** [comment]
@takahashim 

すみません。Sansan株式会社様 より、
原本到着が締め日に間に合わない可能性があるため、
データをお送り頂きたいとのご連絡があったのですが、対応お願いできますでしょうか？

**Comment by takahashim** [comment]
@emorima おっとそうなんですね。こちら別途対処しますね

**Comment by emorima** [comment]
@takahashim お手数おかけして申し訳ありませんが、よろしくお願いいたします。 :bowing_woman:

**Comment by emorima** [comment]
@takahashim 

すみません、Sansan株式会社様より、
請求書が届かないとのご連絡が再度ありまして、確認させてください。

Sansan様は、原本必要ということで、郵送での請求書が必要なのですが、
私からの請求のお願いが遅くなってしまったため、
電子版でも先に欲しいとのご依頼がありました。 (☝参照)

Sansan様にお伝えするにあたり、
いつ頃お送りしたかと、再送して頂く場合いつ頃になるか教えて頂けますでしょうか？

**Comment by takahashim** [comment]
@emorima むむ、PDFは江森さんに11/4に別途添付でお送りして、江森さんから送ってもらうつもりだったのですが、受け取られてませんでしたか？

**Comment by takahashim** [comment]
紙の方は11月5日に発送済みになっております。

**Comment by emorima** [comment]
@takahashim 

!!! PDFのメール漏れてました！
明日朝一で、pdfと合わせて、ご確認メールを先方にお送りします！

**Comment by takahashim** [comment]
@emorima ふおお、そうだったんですね。こちらからも念押しが足りなくて失礼しました。
それと紙の方はさすがに先週中には届いているかと思うのですが、こっちも届いてなさそうなのでしょうか？

**Comment by emorima** [comment]
先方に電子版お送りしました。
紙のものは、11/5に郵送済みであることをお伝えしました。
先方に届いていないようでしたら、また再送をお願いするかもしれません。 :bowing_woman:

**Comment by emorima** [comment]
電子版をお送りして、12月末で処理しますとのご連絡を頂きました。

原本はまだ届いていないそうなのですが、電子版で処理できるとのことです。
原本が必要な場合には、ご連絡くださるようにお願いしたので、この件については、
ひとまず完了になります！

@takahashim ありがとうございました！ 🙇‍♀️

**Comment by springaki** [comment]
現状: 12月末らしいので待つ
next action: 来年1月以降に確認する

**Comment by shyouhei** [comment]
現状: 入金確認中
next action: 確認する

**Comment by shyouhei** [comment]
現状：入金確認中
next action: 確認する

**Comment by emorima** [comment]
昨日、高橋さんからご連絡のあった会社の担当者の方にご連絡しましたが、
現時点では返信ありません。

**Comment by emorima** [comment]
お返事まだきておりません...

**Comment by emorima** [comment]
お返事まだありません

**Comment by emorima** [comment]
RubyKaigi にて、 @springaki さんの方で調整して頂いたように、
未入金のスポンサーに対して、5/15までに振込または、ご連絡を頂けるように
メールをお送りいたしました。

**Comment by springaki** [comment]
@emorima 本日時点で入金確認できませんでした。お話した内容で粛々と進めていきましょう。

**Comment by springaki** [comment]
メモ: 先に送金した分、次回送金時マイナスしておく。

**Comment by emorima** [comment]
@springaki 承知しました！

**Comment by springaki** [comment]
現状：入金確認中
next action: 確認する

**Comment by springaki** [comment]
現状：入金確認中
next action: 確認する

**Comment by springaki** [comment]
サイトからは削除したハズ
送金時マイナス計上できたら Closeする。
cc: / @takahashim

**Comment by springaki** [comment]
@takahashim 次回RGに振込する時に 1口 21,600円分差し引いて振込をお願いします。

**Comment by springaki** [comment]
入金確認も送金も完了
