### ISSUE TITLE
RailsGirls Sendai 1st のスポンサー費用請求

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#332]
11/2, 3 開催の Rails Girls Sendai 1stスポンサー費用の請求をお願いしたいです。

スポンサー一覧は、メールにて共有させて頂きました。

- [x] スポンサー様に請求する
- [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
- [x] スポンサー様からの入金を確認する

**Comment by takahashim** [comment]
ご連絡ありがとうございます、先ほど請求手続きを行いました。

**Comment by shyouhei** [comment]
現状: 請求済み、入金待ち。
next action: まつ

**Comment by shyouhei** [comment]
現状: 入金確認済み、振込済み。
