### ISSUE TITLE
RailsGirls Okinawa 1st のスポンサー費用請求

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#333]
11/9, 10 開催の Rails Girls Okinawa 1stスポンサー費用の請求をお願いしたいです。

スポンサー一覧は、メールにて共有させて頂きました。

- [x] スポンサー様に請求する
- [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
- [x] スポンサー様からの入金を確認する

**Comment by springaki** [comment]
現状: 動きなし
next action: 順次やっていく

**Comment by emorima** [comment]
スポンサーお申込み時の内容で、12月末 入金期限として記載してあった関係で、
スポンサー様から請求書が欲しいとのご連絡を頂いたようです。

ご対応よろしくお願いいたします！

**Comment by takahashim** [comment]
@emorima こちらお待たせしてしまっててすみませんでした！　メールの分については今日、郵送については明日発送できるかと思います

**Comment by emorima** [comment]
@takahashim 承知しました！
お忙しい中、ご対応ありがとうございます。　🙇‍♀️

**Comment by shyouhei** [comment]
現状: 請求済み、入金待ち。
next action: まつ

**Comment by shyouhei** [comment]
現状: 入金確認済み、振込済み。
