### ISSUE TITLE
Rubyのテスト環境：設置場所整備費などについて

### ISSUE THREAD

**Issue by ko1** [ruby-no-kai/official#334]
お金の無心です。

Ruby 開発に使うため、実機を数台動かしています。

内訳：
* ミドルタワー x 3
* タワー x 1
* mac mini x 2
* スイッチングハブ
* 下記菅谷研からお借りしているマシン x 2

テストのため：http://ci.rvm.jp/ というテスト環境を用意しており、実機で数台動かしています。mac mini も 2 台動いています。

ベンチマークのため：ベンチマークのために、擾乱の少ない環境が欲しくて、実機を利用しています。ベンチマークは国分さんがこの環境で https://benchmark-driver.github.io/ を計測してもらております。いつもは動かしていませんが、時々評価のために私も使っています。

現在、この実機を芝浦工大・菅谷研にご厚意で置かせてもらっているのですが、トラブル対応が必要なときに気軽に行きづらいので（また、マシンが増えてきてちょっと白い目で見られている）、笹田の家に引き取ろうと思っています。

これにかかるコストを Ruby の会でご支援頂くことは可能でしょうか。

* (1)サーバを置くためのメタルラック 1.5 万円
* (2) 家にサーバを置くための配線工事等 5万円くらい（今工事中）
* (3) ずっとぶん回すために必要になる電気代

1, 2 はお願い出来そう（払いやすそう）だけど、3 は難しそうと思います。
笹田宅に入れるので、どうかなぁ、とも思うのですが、ご検討頂けますと幸いです。

**Comment by ko1** [comment]
費用、忘れていました。

* (4) サーバ類の運搬費 1 万円程度（タクシー利用を想定）

**Comment by takahashim** [comment]
ここのmac miniって #150 #207 のやつですよね。であれば(1)(2)(4)は請求書・レシート等があれば良いんではないでしょうか。

**Comment by ko1** [comment]
ですです。ついでにスイッチングハブは #290 です。
ありがとうございます。

(3) は、まぁ、無理かなあ。

**Comment by takahashim** [comment]
そもそも年間いくらくらいかかりそうですか？＞電気代

**Comment by ko1** [comment]
実際に運用してみないとわかんないんですが、月１～２万円くらいを見込んでいます。

**Comment by ko1** [comment]
ご参考：
200W x 5 台がフルで回るとして、
だいたい 1kWh と考えて、

http://www.tepco.co.jp/ep/private/plan/chargelist01.html
30 円 x 24 x 30 = 2,1600 円。

**Comment by takahashim** [comment]
2,160円なら余裕では…と思ったけどカンマが3桁じゃなかった。
25万円/年くらいでしょうか。

**Comment by ko1** [comment]
はかってみないとわかんないすけどね...。爆音に懲りて止めちゃうかもしれないし。

**Comment by takahashim** [comment]
そうなのか。では移設に係るお金はなんとかするとして、稼働については少し試してみてから、という感じでしょうか。

**Comment by shyouhei** [comment]
とりあえずワットチェッカーを購入するくらいは経費でOKなんじゃないでしょうか。最近はBluetoothでリアルタイム監視できるやつなどもあるようですし。

**Comment by springaki** [comment]
何か適当なワットチェッカーを購入してもらって測り、その結果で概算出して請求してもらえれば良さそう。という話をしました。

@ko1 いかがでしょうか。

**Comment by ko1** [comment]
ご検討ありがとうございます。

https://zigsow.jp/item/274895/review/252378
を持っているので、ちょっと計りだしています。

今計算マシンを

* Linux ミドルタワー x 3（2 台 ci.rvm.jp 用テストマシン、1台ベンチマークマシン、沢山 CPU 使う）
* mac mini x 2（chkbuild マシン）

で計ってるんですが、200W～300W 程度のようです。mac mini は chkbuild マシンなので、タイミングによっては、あまり電力食いません。

今後、もう少し増やす予定です（Linux ミドルタワー x 1、フルタワー x 1、ラズパイ x ?）

もし概算だとすると、毎月、ログをとってご報告する感じでしょうか。ご報告する場合、ちょっと自動化しないとつらいので、上記ワットチェッカーを使って自動化を考えてみます。しかし、ぐぐってみると、公式ページはなくなったのかなぁ。

**Comment by ko1** [comment]
http://www.atdot.net/fp_store/f.q5kcjp/file.copipa-temp-image.png

こういうグラフが出るところまでやりました。

**Comment by ko1** [comment]
(2) 配線工事費、請求が 54,000円で来たんですが、宛名って私の名前とRubyの会、どっちがいいでしょうか。

**Comment by takahashim** [comment]
@ko1 Rubyの会でいいと思います！

**Comment by shyouhei** [comment]
@ko1 月々の電気代をどう払うかは未確定だが、とりあえず１，２を払うのが良いのではないかという気がします。請求書を回していただくことはできますか

**Comment by shyouhei** [comment]
現状：ささださんまち
next action: @ko1 請求書ください

**Comment by ko1** [comment]
こちら、遅くなってすみません。
固定器具をまだ買っていないので、それを含めて請求させて頂きたいと思ってます。
もう少々お待ちください。

**Comment by shyouhei** [comment]
現状：ささださんまち
next action: @ko1 近況どうですか

**Comment by shyouhei** [comment]
現状：うごきなし

**Comment by ko1** [comment]
どーも、忘れちゃって駄目だね。今から発注します。

**Comment by ko1** [comment]
大変遅くなりました。下記、ご支援のほど、どうぞよろしくお願いいたします。

日付 | 用途 | 金額
-- | -- | --
2018/11/30 | 運搬用タクシー代 | 4,340
2018/11/30 | 運搬用資材 | 6,566
2018/11/30 | 運搬用資材 | 708
2018/12/10 | 配線工事費 | 54,000
2019/6/12 | くくり帯 | 956
合計 |   | 66,570

**Comment by ko1** [comment]
すみません、Amazon で注文した資材が入っていなかったので、もう一度。


日付 | 用途 | 金額
-- | -- | --
2018/11/26 | サーバー用ラック | 14,094
2018/11/30 | 運搬用タクシー代 | 4,340
2018/11/30 | 運搬用資材 | 6,566
2018/11/30 | 運搬用資材 | 708
2018/12/9 | ACアダプタ | 982
2018/12/10 | 配線工事費 | 54,000
2019/6/12 | くくり帯 | 956
合計 |   | 81,646

どうぞよろしくお願いします。

**Comment by shyouhei** [comment]
現状: 金額が明らかになった
next action: 

- 振込
- 領収書受領

**Comment by shyouhei** [comment]
@ko1 領収書は以下の住所に送付してください

 〒151-0066 東京都渋谷区西原2丁目33-6-104 一般社団法人日本Rubyの会

**Comment by ko1** [comment]
頑張ります。

**Comment by springaki** [comment]
@ko1 その後、状況いかがでしょうか。

**Comment by snoozer05** [comment]
@ko1 こちら、どんな状況でしょう...??

**Comment by ko1** [comment]
大変遅くなりました！　やっと送りました。

**Comment by takahashim** [comment]
@ko1  届きました！　が、

日付 | 用途 | 金額
-- | -- | --: |
2018/11/30 | 運搬用タクシー代 | 4,340
2018/11/30 | 運搬用資材 | 6,566
2018/11/30 | 運搬用資材 | 708
2018/12/10 | 配線工事費 | 54,000
2019/6/12 | くくり帯 | 956
合計 |   | 66570

しか入ってなかったのですが、他のものは別にもらってましたっけ…？

**Comment by ko1** [comment]
すみません、Amazon のものが入ってませんでした。高橋さんに直接お送りします（住所入ってるんで）

**Comment by takahashim** [comment]
受け取りました！

**Comment by shyouhei** [comment]
next action: 支払う

**Comment by takahashim** [comment]
@ko1 振り込みました！

**Comment by ko1** [comment]
あ、見てなかった。ありがとうございました！

**Comment by takahashim** [comment]
@ko1 こちらこそお手数かけました＆お待たせしました！
