### ISSUE TITLE
TokyuRuby 会議 13 の開催

### ISSUE THREAD

**Issue by kishima** [ruby-no-kai/official#335]
こんにちは。Tokyu.rb の 影山 と申します。

第 13 回目となる TokyuRuby 会議の開催を以下の要領にて計画しております。
これまでと同じようなLT発表を主体としたものを予定しています。
取り急ぎ日程を確保致したく、連絡させていただきます。

名称：TokyuRuby 会議 13
開催日：2019年6月29日(土)
会場：株式会社Speee
参加費：無料
配信：なし
定員：未定
実行委員長：影山　勝彦
会計：河野　誠
るびま記事担当：五十嵐　邦明
他スタッフ：
　大場　光一郎
　小川　伸一郎
　小椋　隆史
　小田切　わか菜
　金山　千夏
　関　学
　多田　亜希
　樽家　昌也
　三浦　美咲樹

**Comment by takahashim** [comment]
ご連絡ありがとうございます！　何か必要なことがあれば追記ください。

**Comment by vestige** [comment]
torubyのよねざわです。
開催がかぶってしまってすいませんです。
お聞きしたいことがありますー。
tokyu13では基調講演などで、この人を呼びたいとか、すでに招待予定の人がいますでしょうか？

**Comment by kishima** [comment]
@vestige ご連絡ありがとうございます。かぶってしまったのは仕方ないので、双方無事楽しく開催できるようにしたいですね。

基本的にこちらからLT登壇を依頼することはないので、特に予定はないです。（サントリーさんは除く🍻）
まだTokyuRuby会議のLT発表者の募集は先ですが、とちぎRuby会議さんの方で登壇を打診される際に、可能であれば、同じ日にTokyuRuby会議も開催予定である旨知らせて頂いて、登壇される方の判断材料にしていただければと思います。
よろしくお願いします。

**Comment by vestige** [comment]
@kishima ありがとうございます。
こちらもこれから登壇者の依頼などを検討していくので、tokyu方面を意識しつつ考えていきますー。

**Comment by publichtml** [comment]
公式ページを公開しました。以後、最新情報などはこちらに随時載せていきます。

http://regional.rubykaigi.org/tokyu13/

**Comment by kakutani** [comment]
おつかれさまでした! るびまのレポートよろしくおねがいしまーす <3
