### ISSUE TITLE
RailsGirls Matsue 4th のスポンサー費用請求

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#336]
@takahashim 

11/10 に開催された RailsGirls Matsue 4th のスポンサー費用の請求をお願いします! 請求先一覧は別途メールにてご連絡します。

---
* [x] スポンサーさんに請求
* [x] RGの口座に振込
* [x] スポンサーさんからの入金を確認

**Comment by takahashim** [comment]
@hsbt おおお、ひょっとして年度内請求（≒今週中）ですか？

**Comment by hsbt** [comment]
続報がありまして、モンスターラボ様だけ年内にお願いしたい、とのことでした...! /cc @IzuO

**Comment by takahashim** [comment]
こちらモンスターサボさんの発送処理を行いました！　他の会社さんも後ほど順次行います（まだ途中）

**Comment by takahashim** [comment]
一通り請求しました

**Comment by shyouhei** [comment]
現状: 請求済み、入金待ち。
next action: まつ

**Comment by shyouhei** [comment]
現状: 入金確認済み、振込済み。
