### ISSUE TITLE
Rails Girls Kyoto 9th のスポンサー費用請求のお願い

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#337]
Rails Girls Kyoto 9th スポンサー費用の請求をお願いしたいです。

スポンサー一覧は、メールにて共有します

- [x] スポンサー様に請求する
- [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
- [x] スポンサー様からの入金を確認する

**Comment by takahashim** [comment]
こちらも一通り請求いたしました！

**Comment by springaki** [comment]
ありがとうございます !!

**Comment by shyouhei** [comment]
現状: 請求済み、入金待ち。
next action: まつ

**Comment by shyouhei** [comment]
現状: 請求済み、入金待ち。
next action: まつ

**Comment by springaki** [comment]
2社ほど未入金っぽい

**Comment by springaki** [comment]
現状: スポンサー様からの入金を確認する
next action: 確認する

**Comment by emorima** [comment]
未入金 2社の担当者様へご連絡しました

**Comment by springaki** [comment]
現状: 確認待ち
next action: 確認する

**Comment by springaki** [comment]
入金確認した
