### ISSUE TITLE
RailsConf 2019 渡航費支援

### ISSUE THREAD

**Issue by yhirano55** [ruby-no-kai/official#338]
[Rails Developers Meetup](https://railsdm.github.io/) を主催している、 @yhirano55 と申します。

2019年4月に開催されるRailsConfへの参加を検討しているのですが、フリーランスのエンジニアのため、渡航費・滞在費等のご支援をお願いしたく、お問い合わせさせていただきました:

* CFPは応募します。不採択時はチケットは購入します。
* 来年開催時にオファーしたところ、2020年ならば参加できるというRails Core Teamのゲストがいらして、その方を招くため、2020年の同イベントの開催を検討しています。
* 2020年以降は規模を更に発展させたく、海外カンファレンスへ参加する機会がこれまで一度もなかったため、RailsConfの視察がしたいです。

フォームが作成された場合は改めてそちらから送信します。ご検討お願いします 🙇

**Comment by takahashim** [comment]
@yhirano55 問い合わせありがとうございます！
そういえば来年の渡航支援については何も準備できてないので、まずはそこから進めてみますね。

**Comment by yhirano55** [comment]
ありがとうございます！よろしくお願い申し上げます。

**Comment by kakutani** [comment]
(何も準備できてないけど進めている)

**Comment by takahashim** [comment]
こちらは受領証をいただいたので精算しました！
