### ISSUE TITLE
TokyoGirls.rbから請求業務のお願い

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#342]
スポンサーからの協賛金の取扱について、メールで相談が来ました。

> TokyoGirls.rbでは3月2日に開催する勉強会で、託児スペースの設置を検討しています。
> 臨時託児サービスの業者に発生する費用は企業スポンサーからの協賛金から充当します。
> 
> 参考: 女性も参加しやすい（でも女性限定ではない）Ruby勉強会を企画中です
> https://blog.jnito.com/entry/2019/01/10/133717

これについて、企業の方から個人だと難しいのでRubyの会の方でなんとかならないか、という相談です。

Rubyの会側での検討内容：

* 作業の切り分け
* こういうのの何かしらのルールや基準は設けておいた方がいいのか

**Comment by shyouhei** [comment]
> こういうのの何かしらのルールや基準は設けておいた方がいいのか

これに関して一般的にどうこういうルール作りみたいなのには前提知識が不足しており、ちょっと理事会のみなさんの側で勉強が必要ぽいのだが、とりいそぎ今回に関しては別段なんの問題もなさそうに感じます。

**Comment by shyouhei** [comment]
現状：請求未
next action: 請求書を出す

**Comment by takahashim** [comment]
請求内容について確認中です

**Comment by shyouhei** [comment]
現状: 請求済み、消込確認中

**Comment by takahashim** [comment]
こちら完了です

**Comment by JunichiIto** [comment]
ご対応どうもありがとうございました！感謝感謝です 🙏
