### ISSUE TITLE
Rails Girls Kobe 4th のスポンサー費用請求のお願い

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#343]
Rails Girls Kobe 4th スポンサー費用の請求をお願いしたいです。

スポンサー一覧は、後ほどメールにて共有します

- [x] スポンサー様に請求する
- [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
- [x] スポンサー様からの入金を確認する

**Comment by takahashim** [comment]
こちら一通り請求しました！（郵送分は明日以降発送処理の予定です）

**Comment by springaki** [comment]
@takahashim 大変申し訳ありません。1社、1 -> 2口 にしてほしいとの事でして、再発行いただけませんでしょうか。該当セルを赤色にしてます。お手数おかけしてすみません。

**Comment by takahashim** [comment]
@springaki こちら了解です、新しい請求書をそのまま担当者の方に再送しておきますね

**Comment by shyouhei** [comment]
現状：請求済み、入金待ち
next action: 入金待ち

**Comment by shyouhei** [comment]
現状：請求済み、入金待ち
next action: 入金待ち

**Comment by springaki** [comment]
すべて入金確認済み
