### ISSUE TITLE
Tama Ruby会議01の開催について

### ISSUE THREAD

**Issue by Shigeyuki-fukuda** [ruby-no-kai/official#344]
こんにちは。Tama.rbの福田と申します。

第1回目となる Tama Ruby会議の開催を以下の要領にて計画しております。
内容は初心者〜中級者を対象としてLT発表を主体としたものを予定しています。
取り急ぎ日程を確保したく、連絡させて頂きます。

名称：Tama Ruby会議01
開催日：2019年7月6日(土)
会場：渋谷セルリアンタワー11F(GMO Yours)
参加費：無料
配信：なし
定員：130名
実行委員長：福田、志村
会計：志村
他スタッフ：大倉、塩井、林、簗瀨、栗原ほか

**Comment by yhirano55** [comment]
Rails Developers Meetup 主催者の 平野 が開催のサポートをしております。スポンサーは募りますが、懇親会でのケータリングやドリンクの現物支給を各所にお願いする次第です。会計処理が手間なので、請求等は特に発生させない方向です。どうぞよろしくお願いいたします。

**Comment by springaki** [comment]
了解です。なにか必要なことがあればお声がけくださいー

**Comment by Shigeyuki-fukuda** [comment]
@yhirano55 
サポートくださり、ありがとうございます！

@springaki 
ありがとうございます！何かありましたら、相談させて頂きます！！

**Comment by Shigeyuki-fukuda** [comment]
@springaki @takahashim 

お世話になっております。Tama Ruby会議01の実行委員長の福田です。

Tama Ruby会議01で基調講演をお願いしている伊藤淳一さんの交通費・宿泊費について相談させて頂きたいです。
こちらをRubyの会様に出して頂くことは可能でしょうか。

また、本来であれば西脇からの往復の新幹線代＋１泊分のホテル代という形でのお願いなるかと思うのですが、7/2から7/8までの6泊分の宿泊費をお願いすることは可能でしょうか。

伊藤さんにお話を伺ったところ、7/2まで仕事で東京に来ており、翌週まで東京に滞在してTama Ruby会議01に登壇をしたいとのことでした。
また7/2までの宿泊費と往復の新幹線代は会社から出るため、7/2から7/8までの6泊分の宿泊費をお願いしたいとのことです。(Tama Ruby会議01の開催日は7/6ですが翌日にも別件で用事があり7/8の朝に西脇へ帰る予定だそうです。)

金額につきましては、
西脇からの往復の新幹線代＋１泊分のホテル代ですと４万円程、
7/2から7/8までの6泊分の宿泊費ですと3.9万円程と、金額としては同じくらいです。

ご検討頂けると大変有難いです。
どうぞよろしくお願いいたします。

**Comment by takahashim** [comment]
@Shigeyuki-fukuda  なるほどです。確かにちょっと変則的ですが、まあざっくり「旅費宿泊費」としてしまえば同じ括りですし、それで困る人はいないんでそれでもいいかな？　という気もします。
いつまでに正式にOK出せると良さそうですか？（今月中くらい？）

**Comment by Shigeyuki-fukuda** [comment]
@takahashim 
ご回答下さりありがとうございます 🙇 
はい！今月だと嬉しいです。
とはいえ、今月は日があまりないので...
厳しいようでしたらまたご相談させてください 🙏

**Comment by takahashim** [comment]
@Shigeyuki-fukuda お待たせしました、こちらOKです！ 🙆

**Comment by Shigeyuki-fukuda** [comment]
@takahashim 
有難うございます 🙇

**Comment by takahashim** [comment]
@Shigeyuki-fukuda ちなみに振り込みタイミングはいつ頃がよいでしょうか？

**Comment by Shigeyuki-fukuda** [comment]
@takahashim 
伊藤さんに領収書を頂けるタイミングを確認します。
確認が取れ次第、折り返しご連絡します 🙏

**Comment by Shigeyuki-fukuda** [comment]
@takahashim 
昨日、無事にTama Ruby会議01、満員御礼で終えることが出来ました。
ありがとうございました。

そして、伊藤さんの宿泊費の件ですが、昨日の時点で `38,700円` で紙の領収書を頂きました。
この後は、Rubyの会のどなたかに伊藤さんから頂いた領収書をお渡しして、伊藤さんの振込先をお伝えする流れでしょうか？

無知で申し訳ありませんが、ご教授頂ければ幸いです。

**Comment by takahashim** [comment]
@Shigeyuki-fukuda 開催おつかれさまでした！
郵送先は〒151-0066東京都渋谷区西原2丁目33-6　一般社団法人日本Rubyの会　高橋宛までお送りください。振込先は info@ruby-no-kai.org 宛までお送りいただければ。

**Comment by Shigeyuki-fukuda** [comment]
@takahashim 
今朝、伊藤淳一さんから頂いた領収書を指定の郵送先に送らせて頂きました。
また、振込先については、先ほどinfo@ruby-no-kai.org 宛にメールさせて頂きました。
お手数お掛けしますが、よろしくお願い致します。

**Comment by takahashim** [comment]
こちら領収書受領しました！　送付ありがとうございました。
そしていただいた口座にお振込みいたしました。

**Comment by kakutani** [comment]
開催おつかれさまでしたー。Rubyの会とのやりとりでまだ必要なものありますか? > @Shigeyuki-fukuda @yhirano55 
なければ、るびま宛にレポート書いてもらって、このissueは閉じちゃおうかな、とおもってます!

**Comment by Shigeyuki-fukuda** [comment]
>こちら領収書受領しました！　送付ありがとうございました。
そしていただいた口座にお振込みいたしました。

@takahashim 
お手数おかけしました。
そして、ありがとうございました 🙇 

>開催おつかれさまでしたー。Rubyの会とのやりとりでまだ必要なものありますか? > @Shigeyuki-fukuda @yhirano55
なければ、るびま宛にレポート書いてもらって、このissueは閉じちゃおうかな、とおもってます!

@kakutani 
登壇者の伊藤淳一さんの宿泊費の件が解決しましたので、
一旦、こちらのissueでのやりとりで必要なことは無さそうです。
また、Asakusa.rbにてお会いさせて頂いた際はアドバイス下さり、ありがとうございました 🙏 
お蔭様で当日トラブルなく終えることが出来ました。

**Comment by yhirano55** [comment]
@Shigeyuki-fukuda おつかれさまでした！

**Comment by Shigeyuki-fukuda** [comment]
@yhirano55 サポート下さりありがとうございました 🙇

**Comment by kakutani** [comment]
るびまにレポートも載ったし、閉じます!l

**Comment by Shigeyuki-fukuda** [comment]
@kakutani @springaki @takahashim @yhirano55 
ありがとうございました ✨
