### ISSUE TITLE
ネットワーク機材調達

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#346]
RubyKaigi用にそれなりの金額のネットワーク機材を調達する話が出ています。
保管方法は未定。

* [x] 見積りを取る
* [x] 発注する
* [x] お支払いする
* [x] 保管先決める

**Comment by takahashim** [comment]
保守契約も必要（1年単位になりそう）。

**Comment by springaki** [comment]
- 調達としてはよさそう。
- 保管方法はどうするのか検討したい。売っちゃうとか、クラウド倉庫に保管するとか。

**Comment by takahashim** [comment]
発注はしました。請求等は今後（しばらく後）になる予定です

**Comment by shyouhei** [comment]
現状: ものはある
next action: 置き場所をどうするか

**Comment by springaki** [comment]
https://unyu.kasegroup.co.jp/storage/service/

**Comment by springaki** [comment]
https://www.sbs-ricohlogistics.co.jp/rlsc/logistics/storage/ 
とか？

RubyKaigi ふりかえりかどこかで @sorah さん含めて検討したい

**Comment by shyouhei** [comment]
@sorah @takahashim ひきつづき揉んでください〜

**Comment by shyouhei** [comment]
現状: 検討中だが結論は出ていない。
next action: 引き続きご検討ください

**Comment by shyouhei** [comment]
@sorah @takahashim 次のRubyKaigiの後にまた今の場所に戻すというのはズルズル行っちゃいそうな気がしますね、時期的にはそこで何らかの新たに確保した保管場所に移動するというのはどうでしょうか

**Comment by snoozer05** [comment]
@sorah が考えるつもりであるとのこと

**Comment by shyouhei** [comment]
8月くらいまでには保管場所の契約に至っていて欲しい気持ちです。

**Comment by springaki** [comment]
@sorah と保管場所について協議する

**Comment by sorah** [comment]
現状クックパッドオフィスに置かれていて、5月くらいにはどかさないと不味い状況だった。が、オフィスクローズの影響でこのへんの作業も着手できない & クックパッドとしての締切(?)も猶予がもたされている状態。

うちのオフィスの本格再開までに着手できないことはない状況だとは思うものの、積極的に出社したいとは思ってないので本格再開後着手でいいかな゙あ、と思っています (2021が近くなっているが…っていう話にはなっちゃう可能性はまぁ、ある…)

**Comment by sorah** [comment]
RubyKaigi 2020 終わった後にほぼほぼ直送できるような状況に持っていくつもりだったけど不可能になったのが痛いですね。

**Comment by shyouhei** [comment]
RubyKaigi 2020 Takeoutではこれらの機材は使用しなかった

**Comment by springaki** [comment]
クックパッドさんに出社するタイミングで倉庫に入れる手続きを粛々とやってもらう

**Comment by sorah** [comment]
まだオフィスでどうこうできるような状況ではなさそう。粛々了解。

**Comment by springaki** [comment]
なるほど了解しましたー。タイミングよろしくお願いしますー
(御社に迷惑かからないのが一番)

**Comment by springaki** [comment]
@sorah また東京の情勢も変わりつつありますが、ご無理のない範囲で考えていただけると嬉しいですー。RubyKaigiKaigi の時に教えていただく。とかでも大丈夫でーす。

**Comment by kakutani** [comment]
@sorah その後いかがでしょうか…?!

**Comment by sorah** [comment]
帯域が売り切れているので今週進捗を出すつもりでした…。

**Comment by kakutani** [comment]
@sorah が進捗させてくれるはず、という認識(まだあわてるような時期ではなさそうだけど、deadlineはある)

**Comment by sorah** [comment]
進捗です。表に出てなそうな金額の話などもあるので続きは RubyKaigi Slack と https://rubykaigi.esa.io/posts/1096 と https://github.com/ruby-no-kai/rubykaigi.org/issues/1452 で進めたい。

**Comment by springaki** [comment]
そらさん、色々とありがとうございました !!

- [x] 契約は交わした
- [x] モノも入庫された様子
- [x] Web管理システムへのログイン
- [x] 自動払い込み申請書送付
