### ISSUE TITLE
RubyKaigi 2019 After Hack by Fukuoka.rb の会場費をご支援いただきたい

### ISSUE THREAD

**Issue by udzura** [ruby-no-kai/official#347]
Fukuoka.rbの @udzura です。
タイトルの件、ご協力いただきたいです！

## 経緯

* RubyKaigi 2019 After Hack（4/21）の会場として [福岡県Rubyコンテンツ産業振興センター](http://frac.jp/) を使いたい。仮押さえ済み
* こちらは県主催イベントでない限り基本的には会場費がかかるため、コミュニティイベントとして日本Rubyの会からご支援いただけないか

見積もりとして、現在、準備撤収含め 9:00 ~ 17:00 で借りるとして

* 12000 * 1.08 * 8 => ¥103,680 程度かかりそう
* 県からコミュニティイベントとして認められれば半額 6000 * 1.08 * 8 = ¥51840 になりそう

という規模感です。

本件、ご検討いただければと思います。

**Comment by springaki** [comment]
@udzura 了解しました。また申請結果で決定金額お教えいただけばと思います。

**Comment by udzura** [comment]
ご担当者様
あれから交渉し、コミュニティイベントとして `6000 * 1.08 * 8 = ¥51840` でお借りできる方向となりました。
つきましては、施設に申し込むに当たって、
請求書送付先を日本Rubyの会のものにしたいのですが、どう入力すればいいかご教示ください！
（物理住所がもし存在しない場合、メールでのご請求ができないか相談します）

<img width="893" alt="2019-03-07 15 30 45" src="https://user-images.githubusercontent.com/91011/53936812-7de40380-40ee-11e9-93f9-163225e7fc41.png">

**Comment by takahashim** [comment]
@udzura 〒151-0066 東京都渋谷区西原2丁目33-6　一般社団法人日本Rubyの会　高橋宛でお願いします！

**Comment by udzura** [comment]
ありがとうございます、書類作成します〜

**Comment by takahashim** [comment]
udzuraさんが近々に利用申請する予定です

**Comment by udzura** [comment]
書類ほぼ作れたので明日申請します。今日、センターの担当者に話を聞いたのですが

* 減免審査の結果は当日会の終了後に判明する
* 今回、コミュニティの名簿や書類のようなものがないのでどうなるかはわからない（一応connpassホームページ等は提示しています）

と言われてしまいました。場合により、請求額が ¥103,680 の方になるかもしれないことをご共有します。

**Comment by takahashim** [comment]
@udzura 51,840円の請求書が来ました！　ので、振り込んでおきますね。

**Comment by udzura** [comment]
本件、doneならクローズのほどを...!!! お世話になりました。

**Comment by takahashim** [comment]
あっとすみません、こちら支払い済みでした！
