### ISSUE TITLE
名古屋Ruby会議04 開催

### ISSUE THREAD

**Issue by eitoball** [ruby-no-kai/official#348]
名古屋Ruby会議04の開催を以下の要領にて計画しております。
日程・場所が決まっていますが、詳細は今後決めていきます。
宜しくお願いします。

名称：名古屋Ruby会議04
開催日：2019年06月08日(土)
会場：大須演芸場
参加費：無料
配信：なし
定員：約100名
実行委員長係：@eitoball
会計：@yadaita @eitoball
他スタッフ：Ruby東海

**Comment by snoozer05** [comment]
@eitoball 必要なことがあればお声がけくださいー

**Comment by shyouhei** [comment]
@eitoball 順調でしょうか。。。

**Comment by eitoball** [comment]
@shyouhei ありがとうございます。何とか開催に進めて準備しています。

**Comment by eitoball** [comment]
無事に終了しました。ありがとうございます。これから、協賛金の請求などしますので宜しくお願いします。

終了したので、close します。
