### ISSUE TITLE
Rails Girls Tokyo 11th のスポンサー費用請求のお願い

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#349]
Rails Girls Tokyo 11th スポンサー費用の請求をお願いしたいです。
スポンサー一覧は、後ほどメールにて共有します。

- [x] スポンサー様に請求する
- [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
- [x] スポンサー様からの入金を確認する

**Comment by emorima** [comment]
@takahashim 

年度末...ということで、Sansan様が今月中に請求書を送って欲しいというご連絡を頂きました。

お忙しいところ申し訳ありませんが、ご対応お願いできますでしょうか。

**Comment by takahashim** [comment]
@emorima お待たせしてすみません、先ほど発送処理を行っておきました！

**Comment by emorima** [comment]
@takahashim 

お忙しいところ対応頂き、ありがとうございます！ :bowing_woman:

**Comment by shyouhei** [comment]
現状: 請求済み、入金待ち
next action: まつ

**Comment by springaki** [comment]
まだ半分くらい入金待ち

**Comment by shyouhei** [comment]
現状: そろそろ入金されててもおかしくない頃
next action: 確認する

**Comment by emorima** [comment]
未入金 2社の担当者様へご連絡しました

**Comment by emorima** [comment]
1社ご連絡を頂き、9月3日付けにて入金して頂けるとのことです。

**Comment by springaki** [comment]
現状: 入金待ち
next action: 待って確認する

**Comment by springaki** [comment]
現状: 入金待ち
1社、11th と 12th を勘違いして振り込んでるかも。
1社、連絡つかず。

next action: 高橋さんと連携して確認する。

**Comment by springaki** [comment]
確認した
