### ISSUE TITLE
みなとRuby会議の支援依頼の精算

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#35]
やるります。

**Comment by kakutani** [comment]
@1syo にまずはメールを出してみた。

**Comment by kakutani** [comment]
@1syo から領収証はもらってるので、精算は可能。原本はまだうけとってない。

**Comment by kakutani** [comment]
振込は高橋さんにやってもうのでassign先変更。

**Comment by takahashim** [comment]
こちらも支払いました！

**Comment by kakutani** [comment]
@1syo から領収証の原本が届きましたので、これを @kakutani が @takahashim に渡したらclose。

**Comment by 1syo** [comment]
入金確認しました。ありがとうございます。

**Comment by kakutani** [comment]
@1syo から原本が届いたので @takahashim に渡す

**Comment by kakutani** [comment]
領収証を @takahashim  に渡したから閉じます
