### ISSUE TITLE
[Nagoya04] スピーカー募集・問い合わせ用のメールアドレスの作成

### ISSUE THREAD

**Issue by eitoball** [ruby-no-kai/official#350]
#250 のように "nagoya04@rubykaigi.org" というメーリングリストの作成をお願いします。

- eitoball at gmail.com

を追加するようお願いします。後ほど、アドレスの追加をお願いするかもしれません。

**Comment by springaki** [comment]
@eitoball 作ってテストメールを送ってみました。いかがでしょうか。
アドレスの追加は随時言っていただければ対応可能です。

**Comment by eitoball** [comment]
@aki メール届いていました。ありがとうございます。

> アドレスの追加は随時言っていただければ対応可能です。

その際は、お手数かけますが、よろしくお願いします。
