### ISSUE TITLE
[Nagoya04] スピーカー募集・問い合わせ用アドレスへのメールアドレス追加

### ISSUE THREAD

**Issue by yada-ITA** [ruby-no-kai/official#351]
#350 にて、作成いただいたメーリングリストアドレスへのメール追加をお願いしたいです。
追加していただきたいアドレスについては @springaki さんに直接連絡します。

お手数おかけいたしますが、よろしくお願い致します。

**Comment by springaki** [comment]
@yada-ITA 了解しました !

**Comment by springaki** [comment]
@yada-ITA 追加しました !

**Comment by yada-ITA** [comment]
@springaki  ありがとうございます！
そして、追加で他の方のアドレス追加が必要になったので、そちらもよろしくお願いします。
アドレスは直接連絡します。
（すみません・・・このissue閉じ忘れてたので、続きで投げちゃいました・・）

**Comment by springaki** [comment]
@yada-ITA 追加しました

**Comment by yada-ITA** [comment]
@springaki ありがとうございます！
また、追加の依頼があるときは、新たなissueを立てるようにして、
このissueはcloseをしておきますー。

**Comment by yada-ITA** [comment]
@springaki 連続でお手数おかけしますが、再びメール追加をお願いしたいです。
（直接アドレスは連絡します・・・！）

**Comment by springaki** [comment]
@yada-ITA 遅くなってすみません。追加しました !
