### ISSUE TITLE
Rails Girls Japan全体の活動に年間通じて協賛できないか

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#352]
具体的には2019年度分としてまとまった金額で支援するなど。

ref. https://github.com/railsgirls-jp/railsgirls.jp/issues/32

**Comment by takahashim** [comment]
はい、良いんではないかと思っております。

**Comment by shyouhei** [comment]
現状: よいのでは
next action: 振り込む

**Comment by shyouhei** [comment]
現状: まだ振り込んでなかった
next action: 振り込む

**Comment by shyouhei** [comment]
現状: まだ振り込んでなかった
next action: 振り込む

**Comment by springaki** [comment]
@takahashim 振り込み状況どうでしょうか。以前、スポンサーキャンセル分1件を差し引きして振り込むというお話だったと思います。

**Comment by takahashim** [comment]
@springaki まだです！　というかその辺の計算をしないと。。というところです

**Comment by takahashim** [comment]
キャンセル分を相殺して振り込みました！
