### ISSUE TITLE
Ruby 開発用 mac mini の更新依頼

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#355]
https://github.com/ruby-no-kai/official/issues/150#issuecomment-485331834 で @ko1 さんから報告してもらいましたが、ruby インタプリタの開発で CI として利用している mac mini が起動しなくなってしまいました、

つきましては新たに mac mini の購入の支援をしていただくことは可能でしょうか?

適当なスペックと価格しては以下を想定しています。

```
3.0GHz 6コア第8世代Intel Core i5（Turbo Boost使用時最大4.1GHz）
16GB 2,666MHz DDR4
Intel UHD Graphics 630
1TB SSDストレージ
￥210,800 (税別)
```

ご検討をよろしくお願いします。

**Comment by shyouhei** [comment]
異議なしです、壊れちゃったってことは、これ結構急ぎですよね。誰かもうひとりapproveしたらgoって感じかと思います。

**Comment by snoozer05** [comment]
良いのではないでしょうか！

**Comment by springaki** [comment]
良いのでは !

**Comment by takahashim** [comment]
では調達するでよいですね。
@ko1 さんか @hsbt さんに購入してもらって、あとで精算するのが手っ取り早いでしょうか？（Rubyの会宛の請求書になってるとうれしい）

**Comment by hsbt** [comment]
Hi~. 以前に対応したようにすすめようと思います。名義を変えることができそうなら、指定いただいた名義にしようと思います。

**Comment by hsbt** [comment]
@takahashim こちら購入&設置完了して無事 macOS のテスト環境が2バージョンに戻りました。別途メールにて立替購入の代金などをお知らせしてますのでご確認お願いします。

**Comment by shyouhei** [comment]
現状: 領収書受領済み
next action: 振込

**Comment by takahashim** [comment]
@hsbt こちら振り込んでおきました！

**Comment by hsbt** [comment]
振込確認しました。ありがとうございます!
