### ISSUE TITLE
合同会社 esa 様のRG年間スポンサー対応(2019年度)

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#357]
合同会社 esa 様に、RubyKaigi2019でRG年間スポンサーをお願いしたところ、
年間スポンサーをして頂けることになりましたので、
請求処理などのお手続きをお願いいたします。

### 発行住所、宛名名
請求書宛名名：合同会社 esa 
〒〒164-0001 東京都中野区中野5-24-18 クロス・スクエアNAKANO 902
合同会社esa 赤塚妙子 様宛

### 口数

1口  10万 JPY

- [x] 請求する
- [x] 入金確認する
- [x] 資金移動する

**Comment by shyouhei** [comment]
現状: 未請求
next action: 請求する

**Comment by shyouhei** [comment]
現状: 請求済、入金待ち
next action: まつ

**Comment by shyouhei** [comment]
現状: 請求済、入金待ち
next action: まつ

**Comment by taea** [comment]
すみません、esaの赤塚です。
こちら、2019/06/07 に、ジャパンネット銀行の口座に "ド）エサ" という名義で ¥108,000 を入金させていただいているのですが、お手すきのときにでもご確認お願いいたします :pray:

**Comment by takahashim** [comment]
こちら入金確認できました！　ありがとうございました。

**Comment by taea** [comment]
ご確認ありがとうございます！ :pray:

**Comment by springaki** [comment]
現状: 入金確認済み
next action: RGに振り込む

**Comment by springaki** [comment]
RGに送金済み
