### ISSUE TITLE
決算報酬改訂のご相談

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#358]
税理士さんとの税務顧問報酬は実は据え置きだったのですが、さすがに年々規模が増えてきているので改訂したいと税理士さんからご相談がありました。

- [x] 改訂して問題ないかどうか決める
- [x] 税理士さんにお返事する

**Comment by takahashim** [comment]
しまったこっちのリポジトリじゃなかった…

**Comment by sorah** [comment]
ミスってそうともおもったし、transfer するとよさそうだなともおもった。  ![image](https://user-images.githubusercontent.com/29440/57597277-bccc8480-7589-11e9-9c48-ba6ed79c0064.png)

**Comment by takahashim** [comment]
@sorah できました！ githubべんりだ

**Comment by amatsuda** [comment]
おー、この新機能が活用されてるとこ初めて見た！

**Comment by shyouhei** [comment]
現状: 問題ないのでは?
next action: 話を進めてください〜

**Comment by takahashim** [comment]
先方に連絡しておきました
