### ISSUE TITLE
名古屋Ruby会議04: レンタル業者対応で日本Rubyの会の名義の利用について

### ISSUE THREAD

**Issue by dot** [ruby-no-kai/official#360]
前回同様名古屋Ruby会議でノボリを立てようと考えています。
そこでノボリの竿と土台をレンタルしようと準備していますが、利用しようと考えているレンタル業者は基本的に法人への対応しかしておらず、日本Rubyの会の名義を利用させていただけないでしょうか。
支払いについては窓口での現金支払いができるので、連絡先などが必要になります。
* 住所
* 電話番号
が必要ということでした。これらの情報を機材レンタルにおいて利用することは可能でしょうか?

**Comment by takahashim** [comment]
@dot たぶん問題ないかと思いますが、契約書とか発注書はありますか？

**Comment by dot** [comment]
契約書はありませんが、レンタルに先だって
[新規取引申請書.xlsx](https://github.com/ruby-no-kai/official/files/3201499/default.xlsx)
こちらの記入が必要との連絡が業者から連絡がありました。
連絡先は必須ですが、年商などの回答ができない箇所は空欄でよいと聞いています。

見積りもあります。必要であればこちらも添付します。

**Comment by takahashim** [comment]
申請書書いておきました！
[default_takahashim.xlsx](https://github.com/ruby-no-kai/official/files/3201611/default_takahashim.xlsx)

見積書はなくてもよいですが、発注は特にハンコとか不要ですか？

**Comment by dot** [comment]
ありがとうございます。
こちらの書類で発注書代わりとなると聞いているので、まずは送ってみます。

**Comment by dot** [comment]
記入いただいた申請書で問題ありませんでした。
ハンコも特に必要なさそうです。
ありがとうございました！
