### ISSUE TITLE
Rails Girls Nagano 1st スポンサー費用請求のお願い

### ISSUE THREAD

**Issue by cobachie** [ruby-no-kai/official#361]
5/24, 25 に開催した Rails Girls Nagano 1st のスポンサーさまへのご請求をお願いいたします。
スポンサーさま一覧は、railsgirlsjp-invoice にメールをお送りいたしました。

- [x] スポンサーさまに請求する
- [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
- [x] スポンサー様からの入金を確認する

**Comment by springaki** [comment]
了解しました！

**Comment by shyouhei** [comment]
現状: 請求済、入金待ち
next action: まつ

**Comment by shyouhei** [comment]
現状: 請求済、入金待ち
next action: まつ

**Comment by springaki** [comment]
現状: 入金確認済み
next action: 預かり金を送金する

**Comment by springaki** [comment]
現状: 1社入金済み、1社入金待ち
next action: 問い合わせ中

**Comment by springaki** [comment]
未入金である事が認識合ったので、請求書再発行済み。今週入金予定。

**Comment by springaki** [comment]
入金確認済み。
