### ISSUE TITLE
富山Ruby会議01 開催

### ISSUE THREAD

**Issue by kunitoo** [ruby-no-kai/official#362]
Toyama.rb の @kunitoo です。
富山Ruby会議01の開催を以下の要領にて計画しております。

* 名称: 富山Ruby会議01
* 開催日: 2019/11/03 (日)
* テーマ: Rubyと富山を楽しみ知ってもらう
  * 富山(北陸)の人には Ruby のおもしろさや最新情報、県外の人には富山にくるきっかけにしてもらいよさを知ってもらえたらと思っています
* 会場: 富山国際会議場
* 参加費: 未定(無料にしたい)
* 配信: なし
* 定員: 約 80 名
* 実行委員長: @kunitoo
* 会計: @mugi-uno, @kunitoo
* スタッフ: @mugi-uno @noboru-i ほかToyama.rbメンバー
* るびまのレポート記事担当: 未定(Toyama.rb のメンバーにお願いする予定です)

関東、関西から招待講演として人を呼びたいと思っているので、支援をお願いするかもしれません。

**Comment by springaki** [comment]
@kunitoo なにか必要な事があればお声がけくださいー

**Comment by kunitoo** [comment]
富山Ruby会議01のWebページを作成したので、[RubyEventCheck の Wiki](https://github.com/ruby-no-kai/official/wiki/RubyEventCheck) も更新しました。
https://toyamarb.github.io/toyama-rubykaigi01/

**Comment by kakutani** [comment]
@kunitoo ありがとうございます。r.rk.org にもPRいただけると助かります! 
https://github.com/ruby-no-kai/regional.rubykaigi.org

https://github.com/ruby-no-kai/regional.rubykaigi.org/blob/gh-pages/_data/events.yml
に足していただけるとありがたいです。

**Comment by kunitoo** [comment]
@kakutani PR作成しました。 https://github.com/ruby-no-kai/regional.rubykaigi.org/pull/105

**Comment by kunitoo** [comment]
@springaki スポンサー費用請求についての相談です。
費用請求を日本Rubyの会から行っていただくことはできますか?
請求を行っていただく場合、必要な情報や手順はありますでしょうか?

また、懇親会スポンサーとしてスポンサー企業様に、懇親会の一部費用を補助していただこうと思っています。この場合、懇親会の領収書などとっておく必要があるものはありますでしょうか?

**Comment by takahashim** [comment]
akiさんではないですが。

> 費用請求を日本Rubyの会から行っていただくことはできますか?

これは問題ないかと思います。詳しくは後ほど…

> また、懇親会スポンサーとしてスポンサー企業様に、懇親会の一部費用を補助していただこうと思っています。この場合、懇親会の領収書などとっておく必要があるものはありますでしょうか?

この辺は富山Ruby会議01の会計としてはとっておいた方がいいかと思いますが、スポンサー企業には普通に請求書だけお送りすればいいんではないかと思います。

**Comment by kunitoo** [comment]
@takahashim ありがとうございます。

> この辺は富山Ruby会議01の会計としてはとっておいた方がいいかと思いますが、スポンサー企業には普通に請求書だけお送りすればいいんではないかと思います。

はい。富山Ruby会議01の会計としてはとっておきます。

スポンサー費用請求するにあたって必要な情報としては、

- 請求先
- 金額

という感じでしょうか?その他必要なことがあれば、教えていただけると助かります。

**Comment by springaki** [comment]
はい。請求に関しては以下のような情報がわかっていれば請求可能です。
`info at ruby-no-kai.org` にお知らせください。

開催後、こちらから請求書を発行します。
企業様の決済上、事前に請求が必要な場合は別途お知らせください。

- 社名    
- ご担当者さまのお名前    
- ご担当者さまのメールアドレス
- 金額
- 請求書に記載する宛名
- 請求品目: [イベント名称] 協賛費用
- 請求書原本送付の必要性の有無
  - 請求書送付先ご住所
  - 請求書送付先担当者さまの所属部署・お名前

**Comment by kunitoo** [comment]
@springaki 必要な情報ありがとうございます。
1点確認なのですが、スポンサー企業様に開催後の請求で問題ないか確認したところ、
「請求日(請求書が届く日)と、入金期限にどのぐらい猶予があるかによって判断したいそうで、入金期限までに１ヶ月程度猶予があるなら事後請求で問題ない」とのことなのですが、入金期限はどのようになるでしょうか?

**Comment by springaki** [comment]
@kunitoo 厳密に記載しておらず、こちらとしては 1ヶ月程度でまったく問題ありません。

**Comment by kunitoo** [comment]
承知しました。先方にお伝えします。ありがとうございます。

**Comment by kunitoo** [comment]
富山Ruby会議01が無事開催できましたので、スポンサー様に費用請求をお願いいたします。
上記の情報はメールにてお知らせします。

また、招待講演の支援については、各個人、会社様が負担してくださったので、支援のお願いはなしとなります。

**Comment by springaki** [comment]
@kunitoo 開催お疲れ様でした !
メールもいただきました。さっそく請求手配しますね。

**Comment by kunitoo** [comment]
@springaki よろしくお願いいたします

**Comment by springaki** [comment]
@kunitoo 本日スポンサー様に請求書送付しました。

**Comment by kunitoo** [comment]
ありがとうございます。

**Comment by springaki** [comment]
@kunitoo さんが立て替えられている費用等、こちらからお支払いするべきものがあれば
info at ruby-no-kai.org
に費用などの情報と振込先口座など教えていただければと思います 😊 

それでこの Issueは閉じることができるハズ

**Comment by kunitoo** [comment]
@springaki さき程、立替ている費用と振込先口座をメールしました

**Comment by springaki** [comment]
スポンサー様支援金をそのまま入金しました。
以上で本件 closeですかね。

またなにかあればお気軽にご連絡ください 😄

**Comment by kunitoo** [comment]
ありがとうございました。
