### ISSUE TITLE
大阪Ruby会議02の開催

### ISSUE THREAD

**Issue by ogom** [ruby-no-kai/official#363]
Ruby関西の おごもり (@ogom) です。

大阪Ruby会議の開催を計画しております。

名称: 大阪Ruby会議02
開催日: 2019年9月15日(日)
会場: 大阪科学技術センター
実行委員長: @ogom
レポーター:  @Islands5
スタッフ: naniwa.rb のメンバー
会計: Ruby関西 のメンバー
参加費: なし
配信: なし
定員: 300名程度

**Comment by springaki** [comment]
`02` ですね。
なにかあればお声がけください

**Comment by ogom** [comment]
@springaki 
遠方からのゲストスピカーの費用の支援をお願いできますでしょうか？
費用は関東からの交通費(3万円)です。
https://regional.rubykaigi.org/osaka02/speakers

登壇者が関西圏以外の方が多く、スポンサー様の協賛金では足りなくなりました。
https://github.com/ruby-no-kai/official/issues/377#issuecomment-525778133

**Comment by springaki** [comment]
@ogom ちなみに支援が必要な総額はどれくらいになる予定でしょうか？

**Comment by ogom** [comment]
@springaki 
支援が必要な総額はゲストスピカーの交通費の3万円です。

**Comment by kakutani** [comment]
#377 の話で今回は大丈夫、っていうことかと思ったら違ったのですね。読み間違えました。

今回の大阪02では基調講演や招待講演での参加費支援の話はなかったので、
慣例的に過去の開催で支援しているぶんを充当するという理屈で支援はできます。
事務的な話は引き続き相談させていただくとして、まずは支援できる/できないのお返事でした! @ogom

**Comment by ogom** [comment]
@kakutani 
#377 の話があるのでおっしゃる通り誤解しやすく申し訳ないです。
ご支援の回答ありがとうございます。よろしくお願いいたします。

**Comment by ogom** [comment]
大阪Ruby会議02 は盛況で、とてもよかったです。https://togetter.com/li/1405373
@kakutani さん、来ていただいてありがとうございます。

レポーターは @Islands5 さんが担当しますので、引き続きよろしくお願いいたします。

**Comment by kakutani** [comment]
01のときは詰んでいていけなかったので、今回うかがえてよかったです。
新しいひと、昔からいるひとの顔を見れたのは収穫でした。

> レポーターは @Islands5 さんが担当しますので、引き続きよろしくお願いいたします

さいきんのるびまの記事を参考にしていただいて、ご無理のない範囲でよろしくお願いします。
(講演内容の詳細な報告とかよりは、開催したことのお知らせみたいな意味合いでのレポートでだいじょぶです)

**Comment by springaki** [comment]
@ogom その後状況いかがでしょうか。支払い情報まとまりましたらご連絡ください。

**Comment by urimaro** [comment]
@springaki 
Ruby関西の松本です。
連絡が遅くなってしまい、申し訳ありません。
口座情報と、ご支援いただきたい金額は以下のとおりです。

項目 | 情報
--- | ---
銀行名 | りそな銀行 (銀行コード: 0010)
支店名 | 京阪京橋支店 (店番: 109)
科目 | 普通
口座番号 | 0209782
口座名義 | ルビーカンサイ (Ruby関西)
金額 | ¥30,000

よろしくお願いいたします 🙇

**Comment by takahashim** [comment]
こちら先ほど振り込みました！

**Comment by urimaro** [comment]
振り込まれていることを確認しました。
ありがとうございました！:angel:

**Comment by springaki** [comment]
@ogom @urimaro この件、他に残件ありましたでしょうか？何事もなければ閉じたいと思います !

**Comment by ogom** [comment]
@springaki 
残件はありません。（レポートも書いてます。）クローズをお願いします。

**Comment by springaki** [comment]
@ogom ありがとうございます。お疲れ様でした !
