### ISSUE TITLE
株式会社アカツキ 様のRG年間スポンサー対応(2019年度)

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#364]
株式会社アカツキ様に、年間スポンサーをして頂けることになりましたので、
請求処理などのお手続きをお願いいたします。

### 発行住所、宛名名
請求書宛名名：株式会社アカツキ
〒141-0021 東京都品川区上大崎2-13-30 oak meguro 8階
島村友造 様宛

### 口数

1口  10万 JPY

- [x] 請求する
- [x] 入金確認する
- [x] 資金移動する

**Comment by shyouhei** [comment]
現状: 請求済、入金待ち
next action: まつ

**Comment by shyouhei** [comment]
現状: 請求済、入金待ち
next action: まつ

**Comment by springaki** [comment]
現状: 入金確認済み

**Comment by springaki** [comment]
next action: RGに振り込む

**Comment by springaki** [comment]
RGに送金済み
