### ISSUE TITLE
名古屋Ruby会議04 株式会社エイチーム様 協賛契約書について

### ISSUE THREAD

**Issue by eitoball** [ruby-no-kai/official#365]
株式会社エイチーム様より、名古屋Ruby会議04の協賛契約書への捺印、および、マイナンバー通知カードのコピーの提出を求められております。

協賛金の請求が日本Rubyの会からとなるため、

1. 協賛契約書の確認
1. 協賛契約書への捺印
1. 社団法人日本Rubyの会のマイナンバー提出

をお願いしたいです。後ほど、協賛契約書を別途メールで送付しますので、確認頂けるとうれしいです。

**Comment by yada-ITA** [comment]
@eitoball さんに補足です。

正確には、請求に関する覚書になるようです。
（原契約は、エイチーム様とRuby東海(代表者個人)間での協賛契約書になります）

原契約が、Ruby東海が直接エイチーム様に請求するという形になっていました。
このままだと、協賛金＝個人の収入に該当してしまうため、
お金の流れをエイチーム様・(今回の請求をお願いする予定の)日本Rubyの会との間の
やりとりとなることを明らかにして、Ruby東海の収入でないことを明らかにするものになります。

なお、上記で書かれている

 > 3. 社団法人日本Rubyの会のマイナンバー提出

については現状特に言われていないので、提出不要かもしれません。

（元々はRuby東海の収入扱いになることから個人の番号通知が求められていました。
　今回の覚書で、協賛金がRuby東海の収入扱いではなくなるため、個人の番号通知は不要となる旨の
　連絡をエイチーム様にいただいています。）

色々とお手数をおかけいたしますが、よろしくお願いいたします。

**Comment by takahashim** [comment]
はい、了解です！
企業の場合はマイナンバーにあたるものは法人番号ですね。ともあれエイチームさんとはRubyKaigiでも契約してるので、こちらの方で問題になることは特にないかと思います。

**Comment by eitoball** [comment]
@takahashim info at ruby-no-kai dot org の方へ覚書を送付しました。ご確認よろしくお願いします。

**Comment by takahashim** [comment]
@eitoball 届きました。あー、なるほど、原契約があるわけですね。これで問題なさそうです。

**Comment by takahashim** [comment]
これは三者の押印が必要なわけですよね。原本の郵送を待っていればよいですか？

**Comment by eitoball** [comment]
> これは三者の押印が必要なわけですよね。原本の郵送を待っていればよいですか？

@takahashim はい。エイチーム様に覚書の内容が問題ない旨をお伝えします。そして、エイチーム様より郵送して頂く流れになります。

**Comment by yada-ITA** [comment]
@takahashim @eitoball 

先程、エイチーム様には覚書の内容が問題ない旨、一報をいれました。

あと、念の為、今後の原本の流れについて補足です。
原本の流れは以下のようになります（と、エイチーム様から連絡いただきました。）

1. エイチーム様が押印した契約書３部を、Ruby東海に送付
1. Ruby東海が送付された原本3部に押印して、日本Rubyの会に3部とも送付
1. 日本Rubyの会が原本3部に押印して、１部を手元に控える
1. 全者押印済の残りの契約書を、エイチーム様とRuby東海へ１部ずつ送付

原本の送付等、色々とお手数おかけしますが、よろしくお願いいたします・・・！

**Comment by eitoball** [comment]
> 2. Ruby東海が送付された原本3部に押印して、日本Rubyの会に3部とも送付

昨日、レターパックにて送付致しました。

**Comment by takahashim** [comment]
こちら届いてたので押印して２通に分けて送付いたしました！

**Comment by eitoball** [comment]
昨日、受け取りました。ありがとうございます。
