### ISSUE TITLE
名古屋Ruby会議04 スポンサー費用請求について

### ISSUE THREAD

**Issue by yada-ITA** [ruby-no-kai/official#366]
名古屋Ruby会議04の協賛各社に対する請求をお願いしたいです。

請求先・請求金額等の詳細については、メール(info atのほう)にて後ほどご連絡いたします。
宜しくお願い致します！

**Comment by shyouhei** [comment]
メール受け取ってます！
next action: しゅくしゅくと請求する

**Comment by springaki** [comment]
請求書発行済み

**Comment by yada-ITA** [comment]
@shyouhei @springaki ありがとうございます！！

**Comment by shyouhei** [comment]
現状: 請求済、入金待ち
next action: まつ

**Comment by snoozer05** [comment]
確認したら閉じる

**Comment by springaki** [comment]
現状: 請求済、入金待ち
next action: 入金確認を改めて行う

**Comment by springaki** [comment]
@takahashim @springaki で調べながらチェックする

**Comment by shyouhei** [comment]
現状: 請求済、入金待ち
next action: 入金確認を改めて行う

**Comment by springaki** [comment]
@takahashim @springaki で調べながらチェックする

現状: 請求済、入金待ち
next action: 入金確認を改めて行う

**Comment by springaki** [comment]
確認メール送信。確認中。

**Comment by springaki** [comment]
返信なし。もう一度 ping する。

**Comment by kakutani** [comment]
もうひとおし…ッ

**Comment by springaki** [comment]
もうひとおししてみました !

**Comment by springaki** [comment]
連絡はついた。7月初旬に入金確認する。

**Comment by takahashim** [comment]
こちら振込確認できました！！ 🎉

**Comment by springaki** [comment]
よかった ! ありがとうございます !!
