### ISSUE TITLE
Rails Girls Ehime 1stのスポンサー費用請求のお願い

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#367]
Rails Girls Ehime 1st スポンサー費用の請求をお願いしたいです。
スポンサー一覧は、後ほどメールにて共有します。

- [x] スポンサー様に請求する
- [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
- [x] スポンサー様からの入金を確認する

**Comment by takahashim** [comment]
ご連絡ありがとうございます！こちら先ほど郵送処理をしたので明後日くらいに発送される予定です。

**Comment by shyouhei** [comment]
現状: 請求済、入金待ち
next action: まつ

**Comment by springaki** [comment]
入金確認済み
