### ISSUE TITLE
RubyKaigi 2006-2008のコンテンツを移行する

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#368]
現状 jp.rubyist.netに置いていあるコンテンツを移行する（jp.rubyist.netサーバ引退のため）。
https://github.com/ruby-no-kai/rubykaigi-static に持っていくのが良さそう？

**Comment by takahashim** [comment]
mp3, oggの音声・動画ファイルがある。動画ファイルはyoutubeに持っていくのが良いかも。

**Comment by kakutani** [comment]
rubykaigi-static にうつそう!(細かい調整はまた別途)

**Comment by snoozer05** [comment]
データを受け取る必要がありそう。
どうやって受け取るか...

**Comment by snoozer05** [comment]
いっかいかずひこさんに聞いてみる？

**Comment by springaki** [comment]
連絡した。データ容量等々、確認してもらってます。

**Comment by springaki** [comment]
一旦データ預かりました。約9GB

**Comment by springaki** [comment]
Next Action: まずはaws s3 に置いておく

**Comment by springaki** [comment]
@sorah に aws s3 にアクセルできるようにしてもらう

**Comment by springaki** [comment]
とりあえずRubyKaigi の S3 に置いておきました。

**Comment by springaki** [comment]
引き続き外部から見れるように、ボチボチ確認します

**Comment by kakutani** [comment]
https://github.com/ruby-no-kai/rubykaigi-static に移すっていうのがよさそうですね

**Comment by shyouhei** [comment]
現状: 
- とりあえずS3には置かれている
- サイトは落ちたまま

next action: 
- サイトを復旧する
- S3のバケットへのアクセス権を整備していく(フルオープンでよいのか)

**Comment by kakutani** [comment]
@sorah このファイルを @springaki が置いた先のファイルを見てみたいなと思ったら、どうすればよいでしょうか?

**Comment by springaki** [comment]
@sorah ping ↑

**Comment by sorah** [comment]
rubykaigi.org で見れたらいい? (2006-2008.rubykaigi.org か、 rubykaigi.org/200{6,7,8} かどっちだろう)

**Comment by amatsuda** [comment]
なるほど、そういえば今まではここだけドメイン違ったんだよな。しかし、今から rubykaigi.org に持ってくるなら断然後者の `rubykaigi.org/200{6,7,8}` がいいです！

**Comment by sorah** [comment]
rk-archive-2006-2008 をじっと覗いてみたら生の hiki データが置かれており、誰かこれを static html にシュッと起こせるひとはおらんかのう………。

**Comment by kakutani** [comment]
先ずは、Akiさんが上げてくれたファイルをわたしもダウンロードしてみたいです！

**Comment by sorah** [comment]
あ～、とりあえず Google Drive 経由でおくります

**Comment by sorah** [comment]
ちっちゃくして info@rk.o に共有しました (.ogg, .pdf, .mp3, .tgz, .pdf は truncate してあります(10GBくらいあったので)) https://drive.google.com/file/d/1qbrfkz9epTG0MnzeuKAhBYLpEutgPaAT/view?usp=sharing

**Comment by kakutani** [comment]
いただきました。ひとまず御礼まで!  展開したら`CVS`とか`hiki.conf`とかがあって、日本Ruby遺産だな…という思いをあらたにしている。やっていかねば… 💪

**Comment by sorah** [comment]
では歴史を知っている人々にアーカイブ化を任せます… (でかいバイナリを含めた公開作業はやります)。

**Comment by kakutani** [comment]
はい、アーカイブにする作業そのものは @sorah ｾﾝﾊﾟｲのお手をわずらわせるわけにはいかない…(2021の準備とかもっと大事なやつがあるらかね 🙄 )。でっかいファイルとかそういうのは、またいずれ作業ができあがったら助けてくださいませ 😇

**Comment by springaki** [comment]
高橋さんがスクレイピングしたヤツを発掘したがそちらは大容量ファイルがtuncateされていたようなので、上記の大容量ファイルとマージしたりするとうまくいくのかも。
という話をした

高橋さんのスクレイピングファイルはとりあえずリポジトリにpushしてくれるとのこと。

**Comment by kakutani** [comment]
ちっちゃくしたやつは受けとりました! ありがたや 🙏

**Comment by pupupopo88** [comment]
2006分はマージされました！
https://github.com/ruby-no-kai/rubykaigi-static/pull/7

2007, 2008も粛々とやる。

**Comment by kakutani** [comment]
2007はスクレイピングしたやつがあった。2008はhikiのソースはあるけど、htmlファイルがない…という感じ。

**Comment by kakutani** [comment]
2008のをやらないとな…という認識はあります。

**Comment by springaki** [comment]
2007, 2008も粛々とやる。

**Comment by koic** [comment]
RubyKaigi 2008 へのリンクが切れていることに気がつきました。ご報告まで。
https://rubykaigi.org/2021-takeout/past_kaigis

**Comment by amatsuda** [comment]
@koic はい。こちらのスレにコメントくださるのはさすがですね。
2008はリンクが切れているというよりはサイトが地上から消滅してしまっているのが現状、という認識で、わかっていつつも敢えてそのままにしてある感じなんですが、確かにクリックして404を見せらせるよりは、ひとまずリンクしないようにしておく、とかのほうがベターですかねぇ……。

とは思わないでもないですが、それを完全に直そうと思ったら過去の全Kaigiのサイト上のリンクを直さないといけなくなりそうで( https://rubykaigi.org/2020/past_kaigis/, https://rubykaigi.org/2019/past_kaigis/, https://rubykaigi.org/2018/past_kaigis/, etc.)、なんかやっぱりめんどくさそうなのであんまりやりたくない気がしてきました！

**Comment by shyouhei** [comment]
- データは保全してある
  - MySQL dump?
  - Wayback machineからツモしてきたほうが早い可能性は感じなくもない
- どうにかしてサルベージする必要あり

**Comment by kakutani** [comment]
進捗は無です!

**Comment by springaki** [comment]
インターネットアーカイブから取った方がなんとかなりそうという @takahashim のお言葉がありました。

**Comment by takahashim** [comment]
https://github.com/ruby-no-kai/rubykaigi-static/pull/15

**Comment by springaki** [comment]
https://github.com/ruby-no-kai/official/issues/368#issuecomment-882330225
一旦マージして確認することにした

**Comment by snoozer05** [comment]
現行のサイトで古いサイトにリンクを貼っている箇所を直す必要がありそう

**Comment by snoozer05** [comment]
https://rubykaigi.org/2021-takeout/past_kaigis の 2008 のリンクが http://jp.rubyist.net/RubyKaigi2008/ となっているのをなおす

**Comment by springaki** [comment]
PRありがとうございます !
@takahashim さん、確認のもとマージしていってもらう

**Comment by amatsuda** [comment]
いろいろ頑張った結果、2006と2007の全録画のサルベージに成功して、YouTubeのRubyKaigiチャンネルへのアップロードも完了しました。現時点ではまだ非公開、というか「限定公開」状態なんですが、近いうちに全部publicにしてrk.oからのリンクも張り直して、このissueもクローズできる予定です :soon:

**Comment by amatsuda** [comment]
皆さまのご協力のおかげを持ちまして、大江戸Ruby会議09出前Editionも無事終了いたしました。
会期中にこちらのPRをデプロイして、現在では2006-2008の各年のサイトからYouTubeのそれぞれの講演動画へのリンクが貼られている状態になっています。 https://github.com/ruby-no-kai/rubykaigi-static/pull/56

あわせて、YouTube上でも全動画を公開状態に設定して、年ごとのplaylistも公開状態にしています。
2006 https://www.youtube.com/playlist?list=PLbFmgWm555yYV96o5mCVU9mXqgW8r11YU
2007 https://www.youtube.com/playlist?list=PLbFmgWm555yYta-4eFdivOfc_aIRdRDT3
2008 https://www.youtube.com/playlist?list=PLbFmgWm555ybVPGKLjv1XQATX1Q4WuQcm

以上でこのissueはやっとクローズできるようになった気がします！

**Comment by fdiary** [comment]
みなさま本当におつかれさまでした！

**Comment by kakutani** [comment]
偉業!!!!!! ⛏️ 🪓 💍 🛤️
