### ISSUE TITLE
名古屋Ruby会議04 費用の振り込みについて

### ISSUE THREAD

**Issue by eitoball** [ruby-no-kai/official#371]
7月26日（金）までに @eitoball より info _at_ rubykaigi _dot_ org の方に振り込み口座と金額をお知らせします。

**Comment by eitoball** [comment]
先ほど、メールしました。ご確認ください。

**Comment by takahashim** [comment]
@eitoball おまたせしました、こちらメールでいただいた金額を先ほどお振込いたしました！

**Comment by eitoball** [comment]
@takahashim 確認しました。ありがとうございます！
