### ISSUE TITLE
Rails Girls Sendai 2ndのスポンサー費用請求のお願い

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#372]
Rails Girls Sendai 2nd スポンサー費用の請求をお願いしたいです。
スポンサー一覧は、後ほどメールにて共有します。

 - [x] スポンサー様に請求する
 - [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
 - [x] スポンサー様からの入金を確認する

**Comment by takahashim** [comment]
とりいそぎ一通り請求いたしました！

**Comment by emorima** [comment]
ありがとうございます！

**Comment by springaki** [comment]
入金確認済み
