### ISSUE TITLE
鹿児島Ruby会議01の開催

### ISSUE THREAD

**Issue by kurotaky** [ruby-no-kai/official#374]
鹿児島RubyコミュニティのK-Ruby方面からやってきました @kurotaky です。
鹿児島Ruby会議01の開催を以下の要領にて計画しております!

名称: 鹿児島Ruby会議01
開催日: 2019/11/30 (土)
テーマ: プログラミング言語Rubyを通して越境する
会場: [mark MEIZAN](https://mark-meizan.io/about) に決定
参加費: 0円
配信: なし
定員: 約 90 名
実行委員長: @kurotaky 
会計: 未定
スタッフ: K-Rubyメンバー
るびまのレポート記事担当: 未定

イベントサイト
https://k-ruby.github.io/kagoshima-rubykaigi01/

**Comment by kakutani** [comment]
るびまへの開催レポートを何卒お願いしたく…ッ

**Comment by kurotaky** [comment]
開催レポート書きます!!! 💪

**Comment by kurotaky** [comment]
イベントサイトオープンしております 🎉 発表者も絶賛募集中なので是非ご応募下さい〜
https://k-ruby.github.io/kagoshima-rubykaigi01/

**Comment by kakutani** [comment]
行動規範が掲げてあるのは良いですね。せっかくなので、インシンデントと思しき事象に遭遇した、見かけた場合の連絡先が明示してあるとさらに良いのではと思いました。

**Comment by kurotaky** [comment]
スタッフにお声がけ下さい〜という文言を追加しました 🙆‍♂
メールでの連絡先などはこれから考えます!

**Comment by kurotaky** [comment]
@kakutani 
スポンサー費用を受け取る口座を `鹿児島Ruby会議01`で作ろうとしたのですが、任意団体となってしまい、口座開設に時間がかかる&審査も結構大変と銀行窓口で聞きました。

各スポンサー企業に日本Rubyの会の口座をご案内して、そこに一度お金を振り込んでもらって、
招待講演の方への渡航費支払い・飲食物の準備代金支払い・会場費支払い等を行なうことはできますか..？

**Comment by springaki** [comment]
@kurotaky kakutaniさんではありませんが、一旦お答えしますー。

日本Rubyの会から各スポンサー様に請求させていただき、各種支払いをする事もできます。
そちらで開催の障壁が少なくなるように、色々と相談可能です。
まずは速報的なご連絡でした。

**Comment by kakutani** [comment]
口座をつくるのに手間がかかるようになってる、っていうのはなんとかしたいなあと思いました。

協賛費用の入金先は日本Rubyの会にして、請求書つくるとか支払いとかは鹿児島チームにお任せするようなかたちの運用ってできたりしますかねえ(細々した支払などのハンドリングの手間が増えそう)。 @takahashim 

railsgirl-jpでやっているような、預り金っぽい運用をイメージして発言しています（お金の振込先が鹿児島チームの誰か個人の口座になる）

**Comment by kurotaky** [comment]
@springaki 速報ありがとうございます!

**Comment by takahashim** [comment]
そうですね、支払いはお任せした方が良さそうです。
請求はどっちがいいんでしょうね…手間としては請求書発行までしてもらった方がよいかもですが、良く分からない入金があると悩ましいのでそこは密に連携する、とかでしょうか？
というか、そもそもスポンサーさん側の都合として、請求主体が鹿児島Ruby会議チームで振込先口座がRubyの会、という請求を受け付けてもらえるかどうかの問題もあるので、その辺をスポンサーさんと詰めておいた方がよさそうです（場合によっては取引先の登録が必要になったりするんで、それならRubyの会で請求業務までやった方が良さそう）。

**Comment by takahashim** [comment]
あと、支払いについても、法人じゃないとちょっと…みたいな場合があれば、そこもRubyの会でやるのは問題ないです。
ただ、過去その辺が問題になったのは会場との契約くらいかと思うので、会場がとれたんであれば大丈夫じゃないでしょうか。

**Comment by kurotaky** [comment]
@takahashim 
ありがとうございます。

> そもそもスポンサーさん側の都合として、請求主体が鹿児島Ruby会議チームで振込先口座がRubyの会、という請求を受け付けてもらえるかどうかの問題もあるので、その辺をスポンサーさんと詰めておいた方がよさそうです（場合によっては取引先の登録が必要になったりするんで、それならRubyの会で請求業務までやった方が良さそう）。

スポンサー企業の方にRubyの会で請求を受け付けてもらえるか確認してみます。

請求書発行については鹿児島Ruby会議実行委員の中でする予定でした。
良く分からない入金が無いように、スポンサーと振り込まれる金額リストを事前に共有するようにすれば良いですかね？ 🤔

**Comment by kurotaky** [comment]
参加者募集開始しました 🎉
https://k-ruby.connpass.com/event/152423/

**Comment by kurotaky** [comment]
@takahashim @kakutani @springaki 
最初は、請求書発行については鹿児島Ruby会議実行委員でする予定でしたが、
日本Rubyの会に請求書を出していただく形で調整させてほしいと思っています 🙏 
(RailsGirls方面でもこのような感じでやり取りをしているとお聞きしました。)

### スポンサー費用の流れイメージ
1. スポンサー企業と費用のリストを 日本Rubyの会に共有
2. 日本Rubyの会からお金を振り込んでもらう (K-Rubyメンバーの使っていない口座とか?)
3. 日本Rubyの会が請求書出してスポンサー企業からお金を集める

現在、日本Rubyの会が請求書発行してOKかどうか、スポンサー企業の方々に確認中というステータスです。

**Comment by kakutani** [comment]
@kurotaky もう確認取り始めちゃってますかね…確認を取るというよりは、後援の日本Rubyの会から請求します、と説明したほうがやりとりは減ると思います。

事前に請求先リストを共有してもらう流れでokです。

**Comment by kurotaky** [comment]
@kakutani ありがとうございます。

> 確認を取るというよりは、後援の日本Rubyの会から請求します、と説明したほうがやりとりは減ると思います。

なるほど...なるほどな...となりました 😇 確認連絡をスポンサー窓口となっていただいているK-Rubyメンバーまでしたところで、このissueを見たので、

追加で状況説明して、"後援の日本Rubyの会から請求させていただきます" 的な情報をお伝えしました 🙏 請求主体は `鹿児島Ruby会議実行委員会` で 振込先口座が `日本Rubyの会` という感じで。

**Comment by kurotaky** [comment]
進めないと..

@takahashim @kakutani @springaki
鹿児島Ruby会議01のスポンサー企業へ請求書発行をお願いしたいです 🙏
請求書は私がスポンサーの方に送ります。
企業のリストは `info at ruby-no-kai dot org` に送ります！

**Comment by kurotaky** [comment]
メールを送りました 📬

**Comment by kurotaky** [comment]
@takahashim @kakutani @springaki
スポンサー企業から日本Rubyの会の口座に振込してもらって、
K-Rubyの誰かの口座に30万円を振込みする流れを想定していましたが、当日(11月30日)に会場で支払いが発生するお金に関しては間に合わなそうだな..と思っています...。

日本Rubyの会から先に30万円をK-Rubyメンバーの口座に振り込んでもらって、
スポンサー企業から日本のRubyの会にお金を振り込んでもらうという流れで対応を進めたいです。
ご確認よろしくお願いいたします 🙏

**Comment by takahashim** [comment]
@kurotaky 振り込みタイミング、了解です！
今週は（RubyConf週なので）あんまり動きがないかもしれませんが、月末より前には振り込めそうです

**Comment by kurotaky** [comment]
@takahashim 
ありがとうございます 🙏 RubyConf良いですね!
11/27,28くらいで振込確認できると助かります 🙇 
`info at ruby-no-kai dot org` に口座情報を送るようにします!

**Comment by kurotaky** [comment]
@takahashim メールを送りました 📬🙏

**Comment by takahashim** [comment]
@kurotaky お待たせしました、こちら先ほどお振込みましました！　請求書の方も後ほどお送りしますね。

**Comment by kurotaky** [comment]
@takahashim ありがとうございます😊振り込み確認しました。イベント終了後に収支報告します🙋‍♂️

**Comment by shyouhei** [comment]
現状: スポンサー入金待ち

**Comment by kurotaky** [comment]
スポンサー企業1社から、「すみません、本日中(2020/1/17)に振り込みます。」と連絡が来ました  🙏

**Comment by snoozer05** [comment]
@kurotaky 入金はありましたか？

**Comment by snoozer05** [comment]
@kurotaky 失礼しました...レス違いでした。こちらで、入金を確認したら閉じる

**Comment by snoozer05** [comment]
確認したので、閉じる

**Comment by kurotaky** [comment]
ありがとうございました！
