### ISSUE TITLE
平成Ruby会議01の開催

### ISSUE THREAD

**Issue by yhirano55** [ruby-no-kai/official#375]
Railsdm方面からやってきました @yhirano55 です。
平成Ruby会議01の開催を以下の要領にて計画しております。

名称: 平成Ruby会議01
開催日: 2019/12/14 (土) 10:30〜19:00（懇親会 19:30〜21:30）
テーマ: 界隈で登壇経験の浅い若手の方を中心としたトーク + CFP（2トラック）+ 基調講演
会場: 株式会社ドリコム（カフェとセミナールーム）
参加費: 無料
配信: なし
定員: 約 220 名
実行委員長: @tashirosota
会計: なし（現物支給形式）
スタッフ: 平成.rb メンバー (サポート: @yhirano55)
るびまのレポート記事担当: @yuriko1211

**Comment by kakutani** [comment]
> るびまのレポート記事担当: 未定

こちらよろしくお願いします!

**Comment by yhirano55** [comment]
承知しました〜

**Comment by takahashim** [comment]
三鷹の中高生国際Rubyプログラミングコンテストの最終審査会とかぶってた… https://www.ruby-procon.net/shinsa-docs/2019072300015/ (まあ中高生向けなんでターゲット違いますが)

**Comment by yhirano55** [comment]
確定後に恐縮ですが、12/7（土）だと平成.rbのコアメンバーの参加が難しいらしく、翌週の12/14（土）に変更になりそうです。また決まったらお知らせします。

**Comment by yhirano55** [comment]
👆会場確認し、12/14（土）にリスケいたしました。失礼しました。

**Comment by yhirano55** [comment]
ざっくりとした方向性共有:

| 時期 | 予定 |
|--:|:--|
| 9月上旬 | タイムテーブル仮決定・基調講演のスピーカー2名の依頼開始 |
| 9月中旬〜下旬 | 基調講演のスピーカー決定 |
| 10月上旬 | LP公開・CFP募集開始（10月下旬） |
| 11月上旬 | スピーカー公開・参加者募集開始（connpass）・スポンサー募集開始 |
| 12月14日 | イベント当日 |

- 開始時間は13:00〜19:00（19:00〜21:00懇親会予定）
- 基調講演 2枠（平成.rbメンバーが候補者リストアップ中）
- トーク 1本 15min（Ruby, Rails, それ以外可）
- 平成.rbメンバーとプロポーザルを受け付けて複数セッション 2トラックで
- モブプロや飛び込みLT枠を設けるかも
- コーヒー・懇親会のフード・ドリンクなどをスポンサー募集する予定
- クリエイティブ制作（LP・名札）のスポンサーも募集する予定（交渉中）

**Comment by yhirano55** [comment]
タイムテーブルができました。微調整は入りますがこの方向で進めます。共有まで。

![image](https://user-images.githubusercontent.com/15371677/64135336-50201300-ce22-11e9-8f66-38a19b7f18c3.png)

**Comment by tashirosota** [comment]
Ruby関係者各位

ご挨拶遅くなってしまい申し訳有りません。

平成.rb発起人でtaskey株式会社でエンジニアをしております。
田代 創大です。よろしくお願い致します。

運営やら立ち回り等のノウハウを平野さんから頂きつつ、平成Ruby会議の実行委員長をやらせて頂きます。

Rubyのコミュニティ文化がとても良イモノだとおもっており、それを世代世代で途切れさせたくなく、少しでもRubyへの貢献が出来たら良いなという思いから平成.rbはスタートさせました。

未熟者ですが、見守って頂けましたら幸いです。
何卒よろしくお願い致します。

**Comment by tashirosota** [comment]
下記tweetにてLPの公開とCfP、スポンサー募集開始いたしました。
https://twitter.com/tashiro_rb/status/1181820741525757953

こちらLPになります。
https://heiseirb.github.io/kaigi01/

**Comment by kakutani** [comment]
@tashirosota サイト公開おつかれさまです 🚀
ひとつ質問です。サイトを見たのですが、Code of Conductを見つけられませんでした(見落した?)。
特に用意する予定はない or あとで掲載するのいずれなのかが知りたいです。

ruby-no-kai/regional.rubykaigi.org#110 でregional.rubykaigi.orgにも載せました(typoしてしまった…)。

**Comment by yhirano55** [comment]
@kakutani 代理回答となっちゃいますが以下にリンクがありまして、内容的にCode of Conductとなります。

![image](https://user-images.githubusercontent.com/15371677/66474964-4e0a3d80-eacd-11e9-8987-98f42bba55c5.png)

**Comment by yhirano55** [comment]
るびまのレポート記事担当も決まりました。

**Comment by kakutani** [comment]
> るびまのレポート記事担当も決まりました。

issueのDescriptionを「未定」から更新していただけるとありがたいです。

**Comment by kakutani** [comment]
> 代理回答となっちゃいますが以下にリンクがありまして、内容的にCode of Conductとなります。

なるほど〜。かんぜんに見落していました 👀 
ブラウザの幅が広いと最初はリンクが出ていない状態になっていて気づきませんでした。
(スマホで見たらリンクとお知らせは最初から出ていた)

手元ではSafari,Chromeともこんな感じになってました(hoverしている間はリンクが出る)
<img width="379" alt="平成Ruby会議_01___平成_rb_and_平成Ruby会議_01___平成_rb" src="https://user-images.githubusercontent.com/2160/66532940-28704900-eb4c-11e9-8950-8bc75127b27e.png">

せっかくアンチハラスメントポリシーを掲げているのだから、
常に表示されているほうが良いと思います。ご検討くださいませ。 @tashirosota @yhirano55

**Comment by yhirano55** [comment]
@kakutani 常時表示できるようデザイナーさんに依頼しました

**Comment by yhirano55** [comment]
@kakutani 常時表示になりました :pray:

**Comment by kakutani** [comment]
確認しましたー。さっそくの対応ありがとうございます 🐬

**Comment by springaki** [comment]
@yhirano55 @tashirosota 私は参加できませんでしたが、無事開催されまでしょうか。特に残件なければ Closeしようと思います。

**Comment by yhirano55** [comment]
@springaki おかげさまで無事開催できました。たいへんお世話になりました。

**Comment by springaki** [comment]
@yhirano55 お疲れ様でした !!
