### ISSUE TITLE
地域Ruby会議登壇者への支援制度検討のお願い

### ISSUE THREAD

**Issue by urimaro** [ruby-no-kai/official#377]
Ruby関西のスタッフをしている松本です。

現在、招待講演者に対する支援をしていただいていますが、招待講演かどうかにかかわらず、登壇者の交通費と宿泊費を支援する制度を検討していただけないでしょうか？

Ruby関西が関係する地域Ruby会議では、スポンサーを募って登壇者の交通費に充てたりしています。
しかし、以下の理由から遠方からいらっしゃる登壇者の交通費、宿泊費を用意するのが難しくなっています。

- 十分なスポンサーを集められるかわからない
- RFPを募集することが多いので、登壇者がどこから来るのかわかる時期とスポンサー募集の時期が合わない

そこで海外Rubyカンファレンス渡航費支援のように、登壇者の交通費と宿泊費を支援する制度を検討していただけないでしょうか？

**Comment by kakutani** [comment]
提案ありがとうございます！
* 今回の大阪02でどう支援するか
* 地域Ruby会議の枠組みとして公募による発表者の支援をどう考えるか
を分けて話せるといいなと思ってます。

まずは会期が近くて具体的な大阪02の話をしたいです。
状況としては支援が必要な感じなのかが知りたいです。

**Comment by urimaro** [comment]
@kakutani 
回答が遅くなってすみません:bow:

大阪Ruby会議02では、登壇者にお車代をお渡しする予定です。
計22万円必要なのですが、スポンサーさんの協賛金などでまかなえる見通しが立っています。

登壇者 | お車代 | 人数
--- | --- | ---
関西圏の方 | 3千円 | 3名
上記以外 | 3万円 | 7名

このため当初から大阪Ruby会議02が予定していた分については、日本Rubyの会にご支援いただく必要はないと考えています。

とは言え、以下についてはお渡しすることができない状況ですので、必要に応じて登壇者の方々を支援していただけたらなぁと思っています。

- 宿泊費
- お車代で不足する交通費

**Comment by kakutani** [comment]
> このため当初から大阪Ruby会議02が予定していた分については、日本Rubyの会にご支援いただく必要はないと考えています。

状況の共有ありがとうございます。大阪02についてはまず大丈夫そうということで承知しました。

地域Ruby会議への支援制度、という観点では話を整理したほうがいいかな…と思うので少しお時間ください。

**Comment by urimaro** [comment]
#363 の件。
大阪Ruby会議02では、RFPで発表者を募集する以外に招待講演を予定しており、以下のように想定しておりました。

- 招待講演者の交通費は日本Rubyの会に支援していただく
- 招待講演者以外の登壇者の交通費はスポンサーさんの協賛金でまかなう

招待講演者以外の話だと勝手に解釈してしまった結果、混乱を招く回答をしてしまい、申し訳ありませんでした:bow:

**Comment by shyouhei** [comment]
大阪Ruby会議02に関しては個別に対応した、今後も同様の話があった場合は再度検討する。
