### ISSUE TITLE
TokyuRuby 会議 14 の開催

### ISSUE THREAD

**Issue by rust** [ruby-no-kai/official#378]
こんにちは。Tokyu.rb の 小川 です。

かなり先になるのですが、第14回目の TokyuRuby 会議の開催を以下のように計画しています。
取り急ぎ、日程の連絡のために issue を立てさせていただきます。

名称：TokyuRuby 会議 14
開催日：2020年11月29日(日)
会場： 未定
参加費： 無料
配信：なし
定員： 未定
実行委員長： 小川 伸一郎
会計： 未定
るびま記事担当： 未定
他スタッフ： 未定

上記スタッフについては来年開催予定のキックオフにて決定予定です :pray:

**Comment by rust** [comment]
今年の11月開催予定だった TokyuRuby 会議 14 は時期未定の延期とします。

TokyuRuby 会議は省力運営を心がけているため、新コロナウイルス情勢がどのように変化するかがわからない状況では運営コスト増が避けられず、またあの空気感をオンラインで再現することは不可能でもあるので、スタッフと協議の結果、延期することにしました。

開催時期は未定になりましたが、開催を諦めたわけではないので、日々情勢を見守りつつ、好機を待ちたいと思っています。

**Comment by takahashim** [comment]
連絡ありがとうございます、確かにオンラインでは難しいですよね…。延期で承知しました。

**Comment by kakutani** [comment]
#476 で復活の狼煙 👀
