### ISSUE TITLE
PayPalの担当者をあづみさんから変更する

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#38]
あづみさんがフロントで色々やるのは大変そうなので、巻き取りたいと思います。
PayPalの設定画面で「事業名の変更(担当者名の変更)」をしようとすると、下記を求められました。

よく理解できていないのですが、「日本Rubyの会」が担当者をあづみさんから(たとえば)かくたにに変更する、みたいな手続きを取ればいいんですかね……PayPalに電話して相談しようかなあと思ったのですが、まずはここで相談してみます。

PayPalアカウントでの取り引きをメインにおこなうアカウント担当者名の変更には、以下の書類をすべてアップロードまたはファックスにてご提出いただく必要があります。

下記はPayPalの画面からコピーしたものをちょっとmd風にしたものです:
### 1.新しい担当者の有効な写真付き身分証明書:

運転免許証、パスポート、住民基本台帳カードいずれかのコピー
日本国籍をお持ちでない場合は、外国人登録証明書のコピー
### 2. 委任状:

ご提出いただく委任状では、新しいアカウント担当者が、PayPalビジネスアカウントの管理者としてPayPalアカウントにおけるすべての取り引きをおこなうことを、お客様が承認している旨を明記してください。また、委任状には、以下の情報も必ず記載してください。
- PayPalアカウントに登録したメールアドレス
- 事業名
- 住所
- 電話番号
- 新しい担当者名
- アカウント担当者の変更理由

なお、代理人は、新しい担当者として、委任状に捺印をお願い致します。また、委任者であるお客様は委任状に、PayPalアカウントに登録した事業名を所有する事業の代表者として、個人事業主の場合は個人の実印、法人事業の場合は法人の代表印（会社実印）を捺印してください。委任者は、委任状に捺印された印鑑について、過去6ヶ月以内に発行された印鑑登録証明書を提出しなければなりません。
### 4. PayPalアカウントに登録したクレジットカードまたは銀行口座の取引明細書:

過去6ヶ月以内に発行されたクレジットカードまたは銀行口座の取引明細書（利用明細書又は通帳）のコピー ただし、アカウントにクレジットカードおよび銀行口座を登録していない場合は、不要です。

以下のリンクから書類を提出される前に、画像が鮮明かつ記載事項が判読できることを必ずご確認ください。ご送付された書類に不備がある場合は、再度送信をお願いすることがあります。ご注意ください。
書類をアップロードされる場合は、デジタルカメラで撮影またはスキャナーで読み取った画像をご利用ください。PayPalへのファイルのアップロードに関する詳細は、下の[ファイルのアップロード]クリックしてください。
### 個人情報の保護

PayPalがお客様から収集した情報は安全に保管されます。PayPalは、ユーザー規約に特に規定されている以外にお客様の個人情報を第三者に開示することはありません。

**Comment by takahashim** [comment]
なんかこれはPayPalに電話で相談した方がいいですかね…。個人（あづみさん）の実印を要求されそう。

**Comment by kakutani** [comment]
なんとなく試してわかってきたことは、登録するドメインもrubykaigi.orgからruby-no-kai.orgに変更するのは画面上からはできなさそうでした。全部まとめて電話で相談ですかねえ。

**Comment by takahashim** [comment]
メールにも書きましたが、新しくアカウント作ってしまうのはどうでしょう。

**Comment by kakutani** [comment]
それが早いと思います!

**Comment by kakutani** [comment]
続きは #44 で。
