### ISSUE TITLE
kakutaniもMFで経費精算できるようにする

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#380]
@springaki ってやり方はあくしてるんでしたっけ

**Comment by springaki** [comment]
はあくしてるので、今度色々共有しましょうかー。
どのみちサービス連携どこまでできるか高橋さんと最終詰めしないといけないのでした。

**Comment by kakutani** [comment]
#379 のこともあるし、いっぺんやっときましょうか

**Comment by takahashim** [comment]
@kakutani 3/30にinviteメールが飛んでるはずなんですが、見つからないですか？

**Comment by kakutani** [comment]
ログインはできました!!1

**Comment by kakutani** [comment]
過去の領収書を発掘したいきもちを高めようとしている

**Comment by shyouhei** [comment]
何か一つやってみたら閉じる

**Comment by shyouhei** [comment]
#403 のためにこのチケットが早く終わると嬉しい。

**Comment by kakutani** [comment]
ばたり…。

**Comment by kakutani** [comment]
確定の季節がやってきたので次回までには…

**Comment by kakutani** [comment]
申請してみたつもり… 😇

**Comment by takahashim** [comment]
承認してみました！

**Comment by kakutani** [comment]
この流れでよさそうなら、よさそう! 領収書を発掘次第順次入れていきます…

**Comment by takahashim** [comment]
やった、とりあえず「未払金」として仕訳帳に載るところまでは自動化できてるぽいです！
