### ISSUE TITLE
株式会社 クラッソーネ様のRG年間スポンサー対応(2019年度)

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#381]
株式会社 クラッソーネ様に、年間スポンサーをして頂けることになりましたので、
請求処理などのお手続きをお願いいたします。

### 発行住所、宛名名
請求書宛名名：株式会社 クラッソーネ
〒450-0002 愛知県名古屋市中村区名駅5-7-30　名駅東ビル4F
人事広報部
宮田ゆかり様宛
yukari_miyata@crassone.jp

### 口数

年間スポンサーが増えたため、
Rails Girls JPのメンバーで話し合い、会見年度を 4/1〜翌年3/31までとして、
年度途中で年間スポンサーをお申込み頂いた場合には、
支払い月の1日から～3/31までをスポンサー対象月とし、
スポンサー費用は月割した金額でのご請求とさせて頂く形としました。

クラッソーネ様にも、この点については了承を頂いております。

クラッソーネ様は、9/1〜翌年 3/31までとして、
以下の金額のご請求をお願いいたします。
10万円 / 12ヶ月 * 7ヶ月(9/1〜翌年3/31) = 58,333円

- [x] 請求する
- [x] 入金確認する
- [x] 資金移動する

**Comment by takahashim** [comment]
了解です！
金額については単価58,333円、数量1にして、備考欄に計算式を書くのがよいでしょうか。

**Comment by takahashim** [comment]
@emorima  請求書ですが、

* 品目名: `Rails Girls 年間スポンサー協賛金 (2019年9月〜2020年3月)`
* 備考欄: `対象期間が9/1〜翌年3/31の７ヶ月間となりますため、費用は10万円 × (7/12) = 58,333円となります。`

みたいな書き方でどうでしょうか…？

**Comment by emorima** [comment]
@takahashim 

品目名、備考欄に上記の記載があると、とてもわかりやすいので、お願いしたいです！

**Comment by takahashim** [comment]
@emorima 承りました！

**Comment by springaki** [comment]
入金確認済み
