### ISSUE TITLE
Rubyist Hotlinks テープ起こしのアウトソース費用ご支援のお願い

### ISSUE THREAD

**Issue by miyohide** [ruby-no-kai/official#383]
みよひで@るびま編集部です。

現在、Rubyist Hotlinksのテープ起こしを外部の業者（以前 #299 , #199 にて利用した業者に依頼予定）にアウトソースすることを考えています。

録音時間と納期から算出された見積金額は、税込み25,000円。より正確な見積もりは、現在依頼中です。

つきましては、アウトソース費用のご支援をお願いしたいです。

よろしくお願いします。

**Comment by kakutani** [comment]
もんだいないとおもいます~

**Comment by miyohide** [comment]
ありがとうございます。では、作業進めます。

**Comment by miyohide** [comment]
見積もりの結果、9/30納品予定、24,094円となりました。
請求書が届きましたら前回と同じようにお送りします。

**Comment by miyohide** [comment]
@takahashim 納品が早まりまして、昨日納品いただきました。
高橋さんあてにメールにて請求書を送付しましたので、ご確認の上振り込みをお願いします。

**Comment by takahashim** [comment]
@miyohide メール受領しました！　先ほど振り込んでおきました。

**Comment by takahashim** [comment]
ちなみに振り込み人名は `118629シャ）ニホンルビーノカイ` にしてあります（先に番号つけるとのことだったので）。

**Comment by miyohide** [comment]
振込手続きありがとうございます。先方の確認が取れましたら、本件はCloseします。

**Comment by miyohide** [comment]
先方の確認が取れましたので、Closeします。ご協力ありがとうございます。
