### ISSUE TITLE
Rails Girls Fukuoka 2nd スポンサー費用請求について

### ISSUE THREAD

**Issue by mochi5o** [ruby-no-kai/official#384]
11月1日と2日に開催される、Rails Girls Fukuoka 2nd スポンサー費用の請求をお願いしたいです。

スポンサー様が確定しましたらメールにてご連絡させていただいてよろしいでしょうか。

**Comment by springaki** [comment]
@makimoch はい。了解しました !

**Comment by springaki** [comment]
`railsgirlsjp-invoice at googlegroups.com` にご連絡いただければ、Rails Girls Japanオーガナイザと日本Rubyの会メンバと共有できるようになってますので、開催後そちらで共有していただければOKです。

**Comment by springaki** [comment]
@mochi5o スポンサー様に請求しました !

**Comment by springaki** [comment]
続きは #389 で。
