### ISSUE TITLE
RHC に講師を呼びたいのだけど、講演謝金を援助いただくことは可能でしょうか

### ISSUE THREAD

**Issue by ko1** [ruby-no-kai/official#386]
https://rhc.connpass.com というイベントを恵比寿にて笹田と遠藤さんで毎月くらいに開催しているんですが、外部講師をお一人、呼べないか検討しています。この講演謝金をRubyの会にお願いすることは可能でしょうか。

RHC は、Ruby インタプリタの開発をしたい人、興味ある人に、最初のステップをご案内するイベントで、Ruby インタプリタ開発者を増やすことを目的としています。ご講演も、Ruby 3 に関する開発についてのご講演をお願いする予定です。実際に参加者の方に貢献しやすいテーマをご紹介頂く予定ですので、RHC のテーマに合致するご講演になる予定です。

決まりましたら、上記 connpass にて開催案内をする予定です。

（具体的な講演者名をここで明らかにしていないのは、今依頼中だからです）

この講演の講演謝金をRubyの会さんにご支援頂くことは可能でしょうか。1時間程度のご講演の依頼を検討しておりまして、交通費は多分不用で、講演者金2万円程度を想定しています。

Regional RubyKaigi ではこういう実績があるのは存じていますが、他は知らないため、微妙かと思います。あるイベントに支援すると、じゃあ別のイベントでも、とキリが無くなるので、線引き難しいなぁ、やっぱり難しいかなぁと思います。が、とりあえず伺ってみました。

なお、クックパッドの名前は冠していないので、現状会社のイベントにはしておりません。会場は借りております。

ご検討のほど、よろしくお願いします。

**Comment by ko1** [comment]
あ、講演者から OK が来てました。松本宗太郎さんに、Ruby type signature についてのご講演をお願いしようと思います。まだまだ signature を充実する必要があり、RHC 参加者の方に手伝ってもらえないかと思って企画しております。

**Comment by takahashim** [comment]
改めて考えてみると、Rubyの会でお金を出すパターンとしては、

* a) 非営利目的で活動しているユーザグループ的な集まりが、
* b) 不特定多数の人（とりわけ上記グループ外の人）が参加できるイベントを開催するために、
* c) 実費の負担をRubyの会にお願いしてくる

といったような場合がわかりやすいですよね。これらを全部満たす必要があるわけではないですが、条件が違う場合だとどうしたもんかなと思いました。

> まだまだ signature を充実する必要があり、RHC 参加者の方に手伝ってもらえないかと思って企画しております

そういうことであれば、本当に求めるものは講演謝礼ともまたちょっと違ったりします？

**Comment by ko1** [comment]
> そういうことであれば、本当に求めるものは講演謝礼ともまたちょっと違ったりします？

座学レクチャー1時間＋実習のメンターみたいなイメージです。講演というか講師謝礼ですかね。

(b), (c) については合致すると思いますが、(a) についてはどうなんだろうなあ。

**Comment by takahashim** [comment]
例えばsignatureの整備のためにまとまった予算を用意して、座学の講師謝礼はそこから出す、みたいなのはどうですか？

**Comment by takahashim** [comment]
そういった背景を考慮しないと、単に「あらゆる勉強会の講師に謝礼が欲しい」みたいな話になってきりがないのではと思いました

**Comment by ko1** [comment]
仰る通りかと思います。
RA Grant みたいに、Rubyの会で何か審査する仕組みがあるといいんですかね？
Rubyの会の負担（金銭的ではなく、審査負担）になってしまうので、こういうのには手を出さない、というのは、それはそれで手だと思いますが。

**Comment by ko1** [comment]
なお、regional のほうも交通費等実費に限る、ということを知らなかった（講演謝金もOKだと思ってた）ので起票した次第でした。実現するにはハードル高そう。

**Comment by takahashim** [comment]
> RA Grant みたいに、Rubyの会で何か審査する仕組みがあるといいんですかね？

RAみたいに毎年公募して審査して…というのだと大変ですが、ざっくり「Ruby 3開発支援」くらいの粒度のテーマで単発にやるんであれば実現できそうな気がしてきました。

**Comment by ko1** [comment]
Ruby3に資するテーマで都度提案を受けて、可否は高橋さんの目利きに期待、みたいな感じでしょうか。

**Comment by kakutani** [comment]
書いてたら長くなってしまった。「Ruby 3開発支援」の枠を用意してそこから出す、っていうのに賛成です!

> なお、regional のほうも交通費等実費に限る、ということを知らなかった（講演謝金もOKだと思ってた）

ちょっと混乱しちゃったところもあるのですが、いまのところ会からの支援の方針としては、招待講演者(基調講演, 招待講演など)交通費等実費に限る感じのつもりです。
謝金を払いたいなら、各開催の運営側でスポンサーを探してほしいと思ってます
(「あらゆる地域Ruby会議の講師に謝礼が欲しい」になるとしんどいな、という気持ち)。

> 「Ruby 3開発支援」くらいの粒度のテーマで単発にやる

これは良さそう。金額とかどうしよう…というのは悩ましいですが、
こういうのを支援できると日本Rubyの会っぽい感じがします!
試しにやってみて、いいかたちができそうならRAとも仲良くなんかやれるとよさそう。

> Ruby3に資するテーマで都度提案を受けて

「提案」としてまとまる前とかでも相談できるといいのかなあ。

**Comment by takahashim** [comment]
@ko1 本件ですが、Ruby 3開発支援目的でまとまった予算を用意することは合意がとれたので、当初の目的は実現できそうです。
詳しい手順や今後は別途相談させて下さい！

**Comment by ko1** [comment]
ありがとうございます。手続き等決まりましたらご連絡ください。
このチケットでやります？

**Comment by takahashim** [comment]
今度のRHCの件についてはこのチケットでやりましょうか

**Comment by ko1** [comment]
了解です。詳細お待ちしております。

**Comment by takahashim** [comment]
先日のRHCの件、支払いまで完了しました

**Comment by ko1** [comment]
ありがとうございます！　私が閉じちゃっていいのかな？
