### ISSUE TITLE
RailsGirls Okinawa 2nd のスポンサー費用請求

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#388]
10/4,5 開催の Rails Girls Okinawa 2ndスポンサー費用の請求をお願いします。

スポンサー一覧は、メールにて共有させて頂きました。

- [x] スポンサー様に請求する
- [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
- [x] スポンサー様からの入金を確認する

**Comment by takahashim** [comment]
こちらお送りいたしました！

**Comment by emorima** [comment]
ありがとうございます！

**Comment by springaki** [comment]
入金確認済み
