### ISSUE TITLE
Rails Girls Nagoya 5th スポンサー費用請求にかかる協賛契約書に関するお願い

### ISSUE THREAD

**Issue by yada-ITA** [ruby-no-kai/official#391]
Rails Girls Nagoya 5th(2020/1/31-2/1) の開催にあたって、スポンサー費用請求を
お願いする予定なのですが、この中で、スポンサーをしていただく株式会社エイチーム様より、
お金の流れを明確化するための、請求に関する覚書のやりとりをお願いされております。

（#365 (名古屋Ruby会議04の件)と同じものになります。
協賛金＝Rails Girls Nagoya Team代表個人の収入でないことを明らかにするため、
お金の流れをエイチーム様・(今回の請求をお願いする予定の)日本Rubyの会との間の
やりとりとなることを明らかにするものです。）

今後の流れについては以下のようになる予定です。

1. エイチーム様が押印した契約書３部を、RailsGirl Nagoya Team代表宛に送付
1. 1.で送付された原本3部に押印して、日本Rubyの会に3部とも送付
1. 日本Rubyの会が原本3部に押印して、１部を手元に控える
1. 全者押印済の残りの契約書を、エイチーム様とRails GIrls Nagoya Team 代表宛へ１部ずつ送付

また原本を日本Rubyの会宛に送付しましたらご連絡いたします。
原本の送付等、色々とお手数おかけしますが、よろしくお願いいたします・・・！

**Comment by takahashim** [comment]
名古屋Ruby会議04のときと同様ですね。了解です！

**Comment by ta8co** [comment]
Ruby日本の会　高橋様
Rails Grils nagoya 竹上と申します。
昨日、契約書を高橋様宛てに送付しました。（レターパック）
到着しましたら捺印をお願いいたします。
お忙しいところお手数おかけしますが、よろしくお願いいたします。

**Comment by takahashim** [comment]
こちら書類は受け取りました！　押印して2通それぞれ返送するので、少々お待ちください。

**Comment by snoozer05** [comment]
返送済みとのことでcloseします。問題があればお知らせください
