### ISSUE TITLE
松江Ruby会議10 開催 

### ISSUE THREAD

**Issue by tomo-k** [ruby-no-kai/official#392]
Matsue.rb の @tomo-kと申します。
第10回目となる 松江Ruby会議の開催を以下の要領にて計画しております。

名称：松江Ruby会議10
開催日：2020/06/06(土)
会場：松江オープンソースラボ
参加費：なし
配信：あり（URL未定）
定員: 60名程度
実行委員長：木村 友哉
るびまのレポート記事担当：佐田 明宏
会計 : 杉原 健司
サイト： http://matsue.rubyist.net/matrk10/ （準備中）

イベントにてお招きするゲストスピーカーへの交通費と宿泊費のご支援をお願いできないでしょうか。
昨年までの実績を元にした概算ですが、費用は以下ように考えております。

### 概算費用詳細
交通費：￥40,000 程度
宿泊費：￥16,000 程度（前泊が必要なため2泊分計上）
合計：￥56,000 程度

詳細が決まり次第、改めてご連絡させていただきます。
何卒よろしくお願いいたします。

**Comment by takahashim** [comment]
ゲストスピーカーの旅費交通費は問題ないです、詳細お待ちしております！

**Comment by tomo-k** [comment]
@takahashim 
イベントサイトは4月公開予定ですので、公開され次第更新させていただきます。

交通費に関して、ゲストが確定し、見積もり直したところ少し変更がありましたので改めてご確認いただけますでしょうか。

交通費：￥40,000 程度 → ￥60,000 程度

少しバッファを見た金額にはなっているため、実際の精算額はこれより少ない可能性が高いです。
よろしくお願いします。

**Comment by takahashim** [comment]
@tomo-k ご連絡ありがとうございます、問題ないです！

**Comment by tomo-k** [comment]
@takahashim 
こちらで開催宣言をさせていただいた、松江Ruby会議10について、
昨今のコロナウィルスの感染拡大を受け、安全のためにイベントの開催を延期することとしました。
状況が落ち着いてから改めて、日程を再設定しようと思います。

**Comment by takahashim** [comment]
@tomo-k それは残念ですがこの状況だと仕方ないですね…。改めて無事に開催できることを祈ってます。

**Comment by sada** [comment]
Matsue.rbの @sada です。

新型コロナの影響で中止になった松江Ruby会議10ですが、本年での開催を目指しています。
ただ、あらためて一から準備し直すことになり、以下のissueを新しく作成しました。

https://github.com/ruby-no-kai/official/issues/471

お手数をお掛けしますが、こちらのissueは閉じていただけないでしょうか。

**Comment by snoozer05** [comment]
@sada 間違って #471 閉じてしまいました...こちら閉じますね！
開催応援いたします！

**Comment by kakutani** [comment]
@tomo-k 折悪しく当初のかたちが実らなかったのは残念ですが、準備を進めていただいてありがとうございました!

2023年版の松江Ruby会議10にも期待しています 🙌
