### ISSUE TITLE
Rubyの会の銀行口座へのアクセスを改善する

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#393]
Rubyの会の口座にアクセスできる人を増やす。
ジャパンネット銀行のBA-PLUSに契約すればできそう？

**Comment by snoozer05** [comment]
まだ調べられていない

**Comment by hsbt** [comment]
Rails Girls だと MUFG の bizstation にして必要な数だけバンバンカードを作成してます(今から銀行変えるのもだるいかと思いますが...)

**Comment by takahashim** [comment]
MUFGほどではないかもですが、JNBもBA-PLUSにしたところ利用者IDばんばん発行できそうです！

**Comment by snoozer05** [comment]
akiさんが振り込み依頼ができる状態であることが確認できたらdone

**Comment by springaki** [comment]
振込依頼かけられるようになったのでDone.
