### ISSUE TITLE
大江戸Ruby会議08 開催 & ご支援のお願い

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#394]
地域 Rubyist 集団の Asakusa.rb のメンバーが中心となって開催する大江戸Ruby会議の8回目を開催します。以下が開催概要です。

名称: 大江戸Ruby会議08
日時: 2020年2/11(火) 9:00-17:00
場所: 浅草5656会館
オーガナイザー & スタッフ: Asakusa.rb メンバー
サイト: https://regional.rubykaigi.org/oedo08/

なお、今回招待公演として関西地方から二名スピーカーを招待しています。二名分の往復交通費と1泊の宿泊費のご支援を日本Rubyの会からお願いすることは可能でしょうか? ご検討をお願いします。

**Comment by springaki** [comment]
ゲストスピーカーの旅費交通費は問題ありません。詳細お待ちしております！

**Comment by snoozer05** [comment]
@hsbt 開催おつかれさまでした！こちら支援についてその後の状況教えていただけますでしょうか。

**Comment by hsbt** [comment]
招待公演 2 名の交通費、宿泊費は確認できているのでご連絡します!

**Comment by hsbt** [comment]
@takahashim へメールを送りましたー

**Comment by takahashim** [comment]
メールもらいました！　って、2名じゃなくて3名になったんですね…。
まあ金額的には11万ちょっとということでいいんではないでしょうか。

**Comment by takahashim** [comment]
@hsbt 先ほど振り込みました！

**Comment by hsbt** [comment]
@takahashim 振り込み確認しました。ありがとうございます。
