### ISSUE TITLE
Rails Girls Nagoya 5thの スポンサー費用請求

### ISSUE THREAD

**Issue by yada-ITA** [ruby-no-kai/official#396]
Rails Girls Nagoya 5thの スポンサー費用の請求をお願いしたいです。
スポンサー一覧は、メールにて共有します。
(invoiceのほうに送付しています)

* [x] スポンサー様に請求する
* [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
* [x] スポンサー様からの入金を確認する

**Comment by springaki** [comment]
8/17 にRailsGirls-JPに立替請求分を送金済み
