### ISSUE TITLE
kaigionrails.orgのネームサーバをなんとかする

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#397]
現状はvalue domainでAレコードのみ設定している状態なので、どこで・どう設定運用するか決めて移す必要があります。

* どこに置くか(luadns or cloudflare or その他)
* MX周りの設定追加（G Suiteを使う？）

**Comment by takahashim** [comment]
ちなみにネームサーバの先についてはKaigi on Railsのチームにお任せなので、Rubyの会の方でどうこうする必要はなさそう。

**Comment by okuramasafumi** [comment]
https://support.google.com/a/answer/80610

今起こっている問題である、G Suiteに登録できない問題のヘルプです。

**Comment by okuramasafumi** [comment]
G Suiteについてですが、一旦サポートに問い合わせてみました。

**Comment by snoozer05** [comment]
G Suiteに関しては解決済みとのこと

**Comment by snoozer05** [comment]
DNSはluadnsですかねぃ

**Comment by takahashim** [comment]
#400 でMX周りの修正が入るかもしれないので、それが一段落したらこちらも対応したいところです…。

**Comment by takahashim** [comment]
こちら対応しました https://github.com/ruby-no-kai/dns/pull/11
