### ISSUE TITLE
日本Rubyの会とKaigi on Railsの関係性を整理する

### ISSUE THREAD

**Issue by okuramasafumi** [ruby-no-kai/official#398]

**Comment by takahashim** [comment]
イベントへの関わり方の一般的な分類としては、

* 主催（共催）: 開催の責任を(共同で)持つ
* 協賛: 主にお金か人を出す
* 後援: 主に名前貸しだけど、人を出すこともある
* 協力: 何か部分的に手伝う

みたいな使い分けが多いのですが、Kaigi on Railsの場合、

* Rubyの会の中で出た企画でもないし、RubyKaigiほどRubyの会の理事がOrganizerにいたりするわけでもなく、方向付け等は大倉さんその他によるチームで決めていきつつ、Rubyの会はあくまでスーパーバイザー的な関わりになりそう
* その一方で、施設やスポンサー等に対してはRubyの会の名前で契約したり請求したりされたりすることになりそう

という形を考えています。そのため、上記4つとも少し異なっているかなと思っています。

それよりは、主催組織から一部の運営業務（契約周り含む）を委託されて別組織として動く、みたいなのが実態に合うのかなと思いました。
強いて言うなら上の4番目の「協力」の一種で、「運営協力」みたいな形がよいかもしれません。

**Comment by snoozer05** [comment]
運営協力で良さそうに思います

**Comment by okuramasafumi** [comment]
遅くなってすみません、運営協力で良さそうに思います！

**Comment by takahashim** [comment]
ではこの形でよろしくお願いいたします！
