### ISSUE TITLE
Rails Girls Ehime 2nd のスポンサー費用請求

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#399]
2/7, 8 開催の Rails Girls Ehime 2ndスポンサー費用の請求をお願いします。

スポンサー一覧は、メールにて共有させて頂きました。

- [x] スポンサー様に請求する
- [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
- [x] スポンサー様からの入金を確認する

**Comment by takahashim** [comment]
@emorima 連絡ありがとうございます、こちら一通りお送りいたしました。
メール送付分のうち、紙の請求書が必要というところがあれば念の為ご一報いただけるとありがたいです。

**Comment by emorima** [comment]
@takahashim 早急な対応ありがとうございます！
紙の請求書が別途必要になった場合は、こちらに追記させて頂きます！

**Comment by springaki** [comment]
8/17 にRailsGirls-JPに立替請求分を送金済み
