### ISSUE TITLE
サイト作る

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#4]
http://ruby-no-kai.org/ のサイトを作る。

**Comment by takahashim** [comment]
コンテンツの一部は設置済み、内容が古いので更新しておく。
デザインについては別途（別チケットを用意した方がいいですか？）

**Comment by kakutani** [comment]
これの完了条件を「新デザインをあててそれっぽくなってること」にしておけば、このままでも良いと思います。
内容とデザインが最低限揃ったら完了にして、取りこぼしは別チケットで。

**Comment by takahashim** [comment]
じゃあそうしましょうか。今月中にデザインも合わせて作る、ということで。
でもassignは二人にはできないのか…

**Comment by kakutani** [comment]
とりあえずしまださんにしてみた!

**Comment by snoozer05** [comment]
デザインをあてたものを design ブランチに push しました。
「新デザインをあててそれっぽくなってること」が完了かどうか確認をお願いいたします！

**Comment by snoozer05** [comment]
問題なければ master に merge します。会則と入会案内の内容のはデザインを master に merge した後で master でやりますかねい。それとも、design ブランチでそれらも作業してから master に merge しますか？

**Comment by takahashim** [comment]
ええと、ローカルで確認できる環境はないんですが、とりあえずマージしちゃっていいんじゃないでしょうか！

**Comment by snoozer05** [comment]
マージしましたので、http://ruby-no-kai.org/ にデザインがあたりました！ご確認をお願いします！

**Comment by takahashim** [comment]
おおお！　かっこいい！　いいと思います！
あー、ちょっとブラウザの横幅が短いとスクロールバーが二つになってしまうのはアレかも…（13インチでは生活しづらい世の中になりつつある気がする今日このごろ）。

**Comment by snoozer05** [comment]
確認ありがとうございます。スクロールバーの件は別チケットを起こしました。ちょっとmayucoさんと相談してみます。
このチケット自体は close してしまっても良い感じでしょうか！

**Comment by takahashim** [comment]
内容がまだちょっと…。というわけで担当を私に変えておきます！

**Comment by snoozer05** [comment]
はい！おねがいします！

**Comment by kakutani** [comment]
規約を載せる作業はやるぞー

**Comment by kakutani** [comment]
LOCALとかlinuxfoundation.orgは定款はbylawsっていうpermalinkになってからそれに倣おう

**Comment by takahashim** [comment]
ありがとうございます！　とりあえず住所はなくていいです！
詳しくはあとで読みます

**Comment by kakutani** [comment]
あとは何をやれば閉じれるんでしたっけ……

**Comment by kakutani** [comment]
いったん閉じます。あとは、個別でissueを運用しましょう。
