### ISSUE TITLE
超エンジニアミーティングの交通費の精算をする

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#40]
@takahashim, @ko1, @tatsuo, @kakutani の4名ぶん。

**Comment by takahashim** [comment]
岡山の川野さんの交通費もお願いします！（というか要金額確認）

**Comment by kakutani** [comment]
おお……そうなると @miyohide のぶんも?

**Comment by kakutani** [comment]
@takahashim, @ko1, @tatsuo, @miyohide は交通費を教えてくれたら払います!! (川野さんにmentionできない……)

**Comment by kakutani** [comment]
反応ないからこれはもう日本Rubyの会がおいしくいただきました、でいいのかな?

**Comment by ko1** [comment]
(2012/09/19 19:01), Kakutani Shintaro wrote:

> 反応ないからこれはもう日本Rubyの会がおいしくいただきました、でいいのかな?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ruby-no-kai/official/issues/40#issuecomment-8714703.

おー，
本所吾妻橋から往復の代金をもらえると．
幕張だっけ？

## 

// SASADA Koichi at atdot dot net

**Comment by miyohide** [comment]
@miyohide $B$G$9!#$9$_$^$;$s!"8+Mn$H$7$F$^$7$?!#(B

$B;d$NJ,$O@:;;$J$7$G(BOK$B$G$9!#(B

**Comment by takahashim** [comment]
@miyohide さんのが文字化けしていますが、ESCを補完して解読したところ、

```
@miyohide です。すみません、見落としてました。
私の分は精算なしでOKです。
```

となりそうです。これでよかったでしょうか。

**Comment by takahashim** [comment]
@ko1 さんももちろん交通費を申請してもらって構いません。ので、かかった交通費の領収書か、なければどこからどこまで何を使って何円だったかを教えて下さいませ。

**Comment by miyohide** [comment]
$B$O$$!#LdBj$"$j$^$;$s!#(B

2012$BG/(B9$B7n(B20$BF|(B 23:23 Masayoshi Takahashi notifications@github.com:

**Comment by ko1** [comment]
(2012/09/20 7:25), Masayoshi Takahashi wrote:

> @ko1 https://github.com/ko1 さんももちろん交通費を申請してもらって構い
> ません。ので、かかった交通費の領収書か、なければどこからどこまで何を使っ
> て何円だったかを教えて下さいませ。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ruby-no-kai/official/issues/40#issuecomment-8729778.
> 
> from: 本所吾妻橋 to: 海浜幕張
> で調べると片道800円でした！

## 

// SASADA Koichi at atdot dot net

**Comment by kakutani** [comment]
海浜幕張からバスに乗りませんでしたか？

**Comment by tatsuosakurai** [comment]
すみません、忘れていました！
精算なしとさせてください〜。

**Comment by snoozer05** [comment]
おわってた
