### ISSUE TITLE
Google for Nonprofitsを使ってみる

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#400]
* Kaigi on Rails方面でG Suiteを使うことを検討中
* 現状は無料プランはなさそう
* [G Suite for Nonprofits](https://www.google.com/intl/ja/nonprofits/offerings/apps-for-nonprofits/)というのがあるらしい
* そのためには[Google for Nonprofits](https://www.google.com/nonprofits/)に登録する必要があるらしい→登録してみる

**Comment by takahashim** [comment]
TechSoupと連携していれば申し込めるみたいです

**Comment by takahashim** [comment]
複数のドメインごとにそれぞれG Suiteを使えるかが気になる…

**Comment by springaki** [comment]
気になる... 試してみましょう 👍

**Comment by okuramasafumi** [comment]
参考までに、TechSoupと連携しているとSlackも無料で使える可能性がありそうです。
https://slack.com/intl/ja-jp/help/articles/204368833-Slack-%E3%81%AE-NPO-%E6%94%AF%E6%8F%B4%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0

**Comment by takahashim** [comment]
とりあえずアカウントは作れたぽいです。

> G Suite で複数のドメインを管理できますか？
> 組織で複数のドメインを所有している場合も、新たにドメイン名を取得した場合も、追加費用なしですべてのドメインをアカウントに追加できます。ユーザーは、ID を 1 つのドメインのみで利用することも複数のドメインで利用することもでき、いずれの場合も 1 つの組織の一員としてサービスを共有できます。管理者は組織内のドメインを同じ管理コンソールで管理できます。ドメインは、使用方法に応じて、個別のドメインまたはドメイン エイリアスとして追加します。

ということなので、とりあえずkaigionrails.orgの方を登録してみます。
ruby-no-kai.org とかを移行するかどうかは後で考えよう…

**Comment by takahashim** [comment]
@okuramasafumi kaigionrails.orgを登録しようとすると「このドメイン名はすでに使用されています」になるんですけど（それはそう）、どうするのが正しいんですかね…？

**Comment by okuramasafumi** [comment]
@takahashim すみません、気づいてませんでした💦

うーん、一旦既存のG Suiteを削除というか紐付けを解除してそこからやり直すべきなんでしょうか…？

**Comment by takahashim** [comment]
@okuramasafumi そんな感じでしょうか。もう結構メール等に使ってますか？

**Comment by okuramasafumi** [comment]
いいえ、これから使おうというタイミングですので、今なら削除しても大丈夫です。

**Comment by takahashim** [comment]
じゃあいったん消すか別の何かに置き換えてもらうかしてもらうのが良さそうです

**Comment by okuramasafumi** [comment]
サポートに連絡したら削除は不要と言われました。
https://support.google.com/nonprofits/answer/3367223
この手順に従えばできるはずとのことです。

> I think that the error was caused by the user not skipping steps one and two in the article. And the error was received because the user tried to create another G Suite, not sign up for the G Suite for Nonprofits.

ステップ1,2を飛ばすのが重要とのこと。

**Comment by takahashim** [comment]
@okuramasafumi とりあえず「有効化リクエスト受領済み」になりました！（審査は数日かかるそうです）

**Comment by takahashim** [comment]
@okuramasafumi 

> G Suite for Nonprofits に関心をお寄せいただきありがとうございます。 G Suite アカウントが正しいエディションに設定されていないため、G Suite for Nonprofits にドメインをアップグレードできませんでした。現時点では、G Suite for Nonprofits にアップグレードできるのは G Suite Basic アカウントのみです。

とのことなんですが、kaigionrails.orgのエディションは何になってるかわかりますか?

**Comment by okuramasafumi** [comment]
@takahashim たしか、デフォルトがBusinessエディションだったと思います。
試しにBasicに変更してみますね。

**Comment by takahashim** [comment]
再度アクティベートを試みて、 ` Status: Activation request received ` になりました。

**Comment by takahashim** [comment]
@okuramasafumi 
```
おめでとうございます
の G Suite for Nonprofits が有効になりました kaigionrails.org
```
という謎のメッセージが来たのですが、そちらの設定は何か変わりました？

**Comment by okuramasafumi** [comment]
<img width="809" alt="スクリーンショット 2020-03-19 14 12 26" src="https://user-images.githubusercontent.com/1012014/77037248-3c21b480-69f4-11ea-93c8-2a8d232fd17e.png">

Nonprofits有効化されたようです、ありがとうございます！

**Comment by snoozer05** [comment]
他のやつはこまったときに引っ越すことにして、ひとまずこのissueは閉じてしまいます
