### ISSUE TITLE
Ruby開発支援のお願い（CIのサーバ代）

### ISSUE THREAD

**Issue by mame** [ruby-no-kai/official#404]
Ruby開発でWSL2のCIをAzureで構築したいと思っています。
月2万円ほどかかりそうなのですが、
これを日本Rubyの会にご支援いただくことは可能でしょうか。

内訳は、WSL2が動かせるインスタンスで一番安いもの（D2_v3/D2s_v3）が
推定で月額 \18,069（税別）です。
無料枠で試験的に構築し、動作確認しています。
https://twitter.com/mametter/status/1266789374588366848

よろしくお願いいたします！

**Comment by mame** [comment]
柴田さんに権限をもらいました！ありがとうございます！移設していきます。

**Comment by takahashim** [comment]
@mame こちらの件、もろもろ了解です！
一応今月の理事のミーティングで承認を取る予定ですが、作業の方は進めてもらって大丈夫です。

あと、この機会に（これまでのインスタンスも含めて）Reserved Instanceを導入しようかと思うんですが、これって1年以上継続的に使う予定ですか？

**Comment by mame** [comment]
ありがとうございます！すでに移設完了してしまいました。

WSL2のCIは、WSL2が廃止などにならない限り止めることはないと思っています。

**Comment by takahashim** [comment]
了解です、では試しにwsl2ciをReserverd Instanceにするところからやってみますね。
インスタンスの価格は4割引くらいになりそうです。

**Comment by hsbt** [comment]
@takahashim Reserved ですが、今利用している Windows Server については AWS(OSS 支援プランに申し込みしているので無料枠で使用できる) でも使うことができるので折を見て移設しようかと思っています。

**Comment by hsbt** [comment]
@takahashim 今どういうステータスでしょうか?( @shyouhei から止まってるという話を聞きました )

wsl2ci を Reserved インスタンスにする、は進めていただいて良いと思います!

**Comment by takahashim** [comment]
こちらですが、

* タイミングを決める
* いついつやりますと宣言する
* RIにする

というところです！

**Comment by takahashim** [comment]
こちら止まっていてすみません！　こちらは「リソースを再デプロイする必要はありません」ということなので、これから適応させてみます
