### ISSUE TITLE
Ruby開発支援のお願い（CI用のApple silicon）

### ISSUE THREAD

**Issue by mame** [ruby-no-kai/official#412]
Rubyのデバッグ・テスト用にApple siliconなmac miniが欲しいと思っています。
購入費用を日本Rubyの会にご支援いただけないでしょうか。

[16 GB の構成で 92,800円（税別）](https://www.apple.com/jp/shop/buy-mac/mac-mini )のやつと考えています。

いただけたら、#355 でご支援いただいた mac mini と同様にコミッタ間で共用し、https://rubyci.org/ にも掲載したいと思っています。

よろしくお願いいたします！

cc/ @ko1 @hsbt

**Comment by kakutani** [comment]
@takahashim ｽｯと進められるとよさそうですが(異議なし!)、進めてもらってよいでしょうか?

**Comment by takahashim** [comment]
良いかと思います！

**Comment by kakutani** [comment]
@mame 購入してください!!!q

**Comment by mame** [comment]
ありがとうございます！柴田さんたちと相談していい感じにやりますー。

**Comment by takahashim** [comment]
こちら領収書をいただいて、振り込み精算しました（納期の都合で金額変わったそう）。

**Comment by hsbt** [comment]
今、柴田の手元にあるのでCIのセットアップを終えたのちに sasadake DC に輸送予定です。

**Comment by springaki** [comment]
輸送予定とのことで、こちらとしては一旦見守っておわり。という状況なので一旦 Closeしちゃいます
またそのMac でダメだったりしたら改めてご連絡ください〜

**Comment by mame** [comment]
無事に運用開始されましたので、ご報告です。ご支援ありがとうございます！ セットアップや運用の柴田さんやささださんもありがとうございますー。

http://rubyci.s3.amazonaws.com/osx1100arm/ruby-master/recent.html RubyCIにちゃんと入った様子
https://twitter.com/mametter/status/1332192908468883456 いろいろ実験できてます
