### ISSUE TITLE
株式会社LegalForce様のRG年間スポンサー対応(2020年度, 2021年度)

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#415]
株式会社LegalForce様に、年間スポンサーをして頂けることになりましたので、
請求処理などのお手続きをお願いいたします。

請求書宛名：株式会社LegalForce
以下にpdfをお送りくださいとのことです。
  To:accountant@legalforce.co.jp
  Cc:kumiko.kondo@legalforce.co.jp

2020年度(3月)、2021年度
以下の金額のご請求をお願いいたします。
108,333円
内訳：
　2020年度スポンサー費　100,000円 / 12ヶ月 * 1ヶ月 = 8,333円
　2021年度スポンサー費　100,000円

請求書は、高橋さんに既に作成して頂いたものでOKです！
- [x] 請求する
- [x] 入金確認する
- [x] 資金移動する

**Comment by kakutani** [comment]
ボールがお見合いになっていそうなので @springaki が確認する~

**Comment by springaki** [comment]
@emorima が送ってくれるとのことでした !

**Comment by springaki** [comment]
江森さんから請求書送付して先方に受け取ってもらえたところまでは確認しました。

Next Action: 入金待ち

**Comment by springaki** [comment]
入金確認完了
