### ISSUE TITLE
cfp-appのpostgresがraw limitに達しそうなので課金したい

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#417]
いまは無課金のHobby Devで1万行まで。
Hobby Basicにupgradeすると1,000万行で9USD/mo. 

cfpのデータは資産だと思うし、まずはこれで払うのでよさそう…
そのプランは 50USD/mo. になので、ここまで増えちゃうと、悩みどころですね。
まあだいぶ先になるのでは(毎月cfp-appを使ってもらえるならいいけど…)。

**Comment by kakutani** [comment]
いいんじゃない、という話になった!

**Comment by springaki** [comment]
@amatsuda あたり、ポチッとアップグレードしていただければ。

**Comment by kakutani** [comment]
ひとまず大丈夫になったみたいなので、必要になったらポチっといきましょう
