### ISSUE TITLE
rko-routerのライセンス

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#423]
https://github.com/ruby-no-kai/rko-router のライセンスを教えて欲しい、と聞かれたのですが、どういう構想でしたっけ…？

**Comment by kakutani** [comment]
なにも考えていなかった…。original autorは @darashi なのですが、彼の意向を確認して決めてもらえばよいんでしょうか(自由なライセンスを選んでもらえるとうれしい)。

**Comment by darashi** [comment]
同じく何も考えてなかったです。自分としてはRubyの会が扱い易いようになっていればそれがうれしいです。

**Comment by springaki** [comment]
日本Rubyの会より
今まではライセンス決まってなかったけど、今年からMITにします !! とか宣言してもらえれば、その時点からそのライセンスが適用されるとのことでした。

@darashi 参考にしたライブラリとかなんとかあったりしますかねぇ？そういうのが特になければ MIT とかでどうでしょう？みたいな話になっておりました。

**Comment by darashi** [comment]
> @darashi 参考にしたライブラリとかなんとかあったりしますかねぇ？そういうのが特になければ MIT とかでどうでしょう？みたいな話になっておりました。

だいぶ前のことなのであまり定かではないのですが、特になかったんじゃないかと思います。MIT でよいとおもいます。

**Comment by kakutani** [comment]
遅まきながらで恐縮ですが、MITでLICENSEを追加しました!
