### ISSUE TITLE
Kaigi on Railsの2021年分サイトをpublicしても大丈夫かどうか

### ISSUE THREAD

**Issue by okuramasafumi** [ruby-no-kai/official#424]
## 背景

https://github.com/ruby-no-kai/kaigi-on-rails-2021 のビルドとデプロイを自動化するためにGitHub Actionsを利用しようとしたところ、

```
GitHub Actions workflows can't be executed on this repository.
The billing plan for ruby-no-kai does not include access to GitHub Actions. Please contact the organization owner or billing manager for questions about the current billing plan
```

と出てきました。レガシープランのためGitHub Actionsはプライベートレポジトリでは利用できないようです。
publicレポジトリでは利用できそうなので、レポジトリをpublicにできないかと考えました。

## メリット

メリットはなんといってもGitHub Actionsが使えることです。

## デメリット

デメリットはいくつか考えられます。サイトのコンテンツ自体はクリエイティブ・コモンズでライセンスされているため、レポジトリがpublicでも問題はないと思われますが、利用しているgemやプルリクエストなどまで全部丸見えになるため、例えばセキュリティの問題が生じた際に危険となる可能性はあります。

## 確認したいこと

レポジトリをpublicにしても大丈夫でしょうか。
なお、もしruby-no-kaiがレガシープランから移行すればレポジトリをpublicにする必要はなくなりますが、現時点ではあまり現実的ではないという予測があります。

**Comment by amatsuda** [comment]
んんんー、RubyKaigiのほうをやってる経験から言わせてもらうと、publicにするのはあまりおすすめできなそうですね。

confidential、っていうほど深刻な話ではないかもしれないけど、いちおうアナウンス前の何かを世に出す形になっちゃうので、スポンサーやスピーカーのような当事者に変な形で情報が届いちゃう可能性があります。出されたPRが毎回一瞬でマージされるならあまり気にしなくてもいいのかもしれないけど、実際は数日間とかタイムラグが出たりしますよね？
というのと、GHのissueやPRが議論の場になったりした際に、オープンにしちゃダメかもしれない内容かどうかとかいちいち気をつかいながら発言するのはけっこう面倒なんじゃないかと思われます。し、うっかり何かをお漏らししちゃう可能性も怖いです。

参考までにRubyKaigiで最近あった事例を挙げると、コロナ対応で、中止か延期か強行か、みたいな判断の難しいやつを、告知文言を調整しながら適切なタイミングを見計らって出す、みたいなことがあったりしました。そういうのはやっぱりpublicだと困っちゃいますねー。

もちろん、GHでぷるりをマージしたら勝手にサイトにデプロイされるといいよね、っていう気持ちはよくわかるし、そこでGH Actionsですよ、っていう発想もまあ順当ではあると思うし、そうじゃなかったらじゃあどうすんの？っていうと、いやー、なかなか難しいですよね。
確かに、大江戸Ruby会議とかでも結局毎回手でデプロイコマンド叩いてたもんなー。

**Comment by okuramasafumi** [comment]
> オープンにしちゃダメかもしれない内容かどうかとかいちいち気をつかいながら発言するのはけっこう面倒なんじゃないかと思われます

ありがとうございます、確かに、Issueとかが事実上使いづらくなってしまうのはありますよねえ…

**Comment by takahashim** [comment]
将来的にレガシープランから移行することは要検討ではありますが、それを待たずにすぐに対応できる方法としては、

* プライベートのままCircieCI等を導入する
* デプロイ用に別途公開リポジトリを作ってなんかうまいこと運用する

というところでしょうか（プライベート一切不要、ということはさすがになさそうなので）。
とはいえ後者は面倒な割にうれしいことが少なさそうなので前者ですかね…。

**Comment by okuramasafumi** [comment]
> プライベートのままCircieCI等を導入する

この方法がよい気がしてきました、無料で使える範囲ならそちらでやろうと思います。

**Comment by kakutani** [comment]
CircleCIのプランは無料じゃなくても、常識の範囲内なら大丈夫ですよー(念のため)。

**Comment by okuramasafumi** [comment]
遅くなってしまってすみません、CircleCIで自動デプロイできるようになりました！
目的は達成できたので、このissueはクローズしたいと思います。
