### ISSUE TITLE
2020年度分までの登記書類提出

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#426]
2020年度分までの登記書類提出を促されたので、議事録を揃えてもっていく 🚶

**Comment by snoozer05** [comment]
まだ

**Comment by takahashim** [comment]
催促されたので「こ、今月中には…！」とお返事してあります（まだやってない）

**Comment by kakutani** [comment]
takahashim 「出しなおしになってしまったよ」
??? 「これはどうすれば?」
takahashim 「ひたすら物理で紙をまわします」

**Comment by kakutani** [comment]
takahashim 「そろそろ本気だす」

**Comment by kakutani** [comment]
@kakutani のところにまず届くらしい

**Comment by kakutani** [comment]
捺印をしました! 💮 並び順的につぎは @snoozer05 だったので、そちらへ送付します!

**Comment by springaki** [comment]
本日 @pupupopo88 に向けて送ります ! 🚀

**Comment by springaki** [comment]
議事録は一通り揃ったとのこと。
その他の書類は部分的に足りない可能性があるので、順次 @takahashim に確認・補完していってもらう。

また提出状況で必要なものがあったら教えてください 🙏

**Comment by takahashim** [comment]
実はまだ足りてないところが判明したのでもう少々お待ち下さい。。。

**Comment by springaki** [comment]
一旦そのまま出していいのでは。ということなので代理提出してもらった。
結果はまだわからない。様子を見守っている...

**Comment by takahashim** [comment]
無事提出して更新されました！！
