### ISSUE TITLE
ChromebookがEOL

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#428]
RubyKaigi用に年に1回使っていたChromebookが昨年の時点でEOLだったようで、

> 来年以降使うなら買い直しで、そろそろ廃棄してもよいかもしれないです

とのことでした。

* [x] 廃棄する？
* [x] 来年必要であれば買い換える？

**Comment by takahashim** [comment]
まずは方針が決めておいて、あとは来年必要になったら改めて検討ということでも良さそう（来年の開催形態もなかなか固まらないと思うので…）

**Comment by springaki** [comment]
https://support.google.com/chrome/a/answer/6220366?hl=ja

なるほどこういうのが出てきちゃうんですね。ツラい...
![82e8d5a8-s](https://user-images.githubusercontent.com/534628/133051037-ee1801d7-9831-4b10-8351-833c32293574.png)

**Comment by springaki** [comment]
廃棄したらこのissueはcloseして、新規に必要な場合は新しくissue立てましょう。

廃棄方法については iogi さんと @takahashim で話合ってもらう。

**Comment by takahashim** [comment]
こちらについてはRubyKaigi 2022で新しいChromebookに買い換え済みです。
