### ISSUE TITLE
捺印をやめて「電子契約サービス」にDXしたい!

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#429]
したい!

**Comment by kakutani** [comment]
[議事録の電子化に関する法的規制と電子署名 \- サインのリ・デザイン](https://www.cloudsign.jp/media/20180215-gijirokudenshika/)
一般社団法人で↑こういうのに対応しているところはあるのかな、というところから…。
ぱっと思いつくのはクラウドサインだが、対応しているのかなあ(問い合わせるのがよさそう)。

他のサービスもどんなのがあるかなあ、というのを調べる必要がありそう。

**Comment by kakutani** [comment]
* 代表印については、適切な電子署名(証明書とか使うやつ)でやれる必要がある
* 理事の認印はクラウドサイン的なやつでもよさそう
* "再来年"までに体制を整えれば脱ハンコできそう

**Comment by kakutani** [comment]
サービスの選定をするとよいかも。法務局?にリストがあるから国内ベンダーのどれかを選ぶのが無難そう。

**Comment by takahashim** [comment]
これの（６）その他でした https://www.moj.go.jp/MINJI/minji41-1.html

**Comment by springaki** [comment]
クラウドサイン、NINJA SIGN とかは使った事があって、使い勝手なんとなくわかりそう。電子印鑑ＧＭＯサインさんあたりを試してみて選定してみる。

- 使い勝手よさそうで
- 複数人署名ができて
- そこそこの値段の安いヤツ (そんなに使わないとおもうので)

を選んでみる

**Comment by springaki** [comment]
https://biz.moneyforward.com/contract/ を試そうとしているところ

**Comment by snoozer05** [comment]
使えそうということがわかった

**Comment by kakutani** [comment]
社員総会の書類で電子化できたら完了〜

**Comment by snoozer05** [comment]
DX化した！
