### ISSUE TITLE
RubyのCI用 raspi 4 の購入

### ISSUE THREAD

**Issue by ko1** [ruby-no-kai/official#432]
CI で利用するために、下記を 4 台購入していただくことはできるでしょうか

https://jp.rs-online.com/web/p/raspberry-pi/1822098
（今調べたら、在庫12台、次回1月後半とのこと）

用途: 32 bit で動かす CI がほとんどないので、作っておきたい。ついでに 64 bit RasPi OS も試しておきたい。多分壊れるだろうから、ちょっと多めに確保しておきたい（その場合、どれか用途を潰す）
* 32bit: rubyci 用、ci.rvm 用各1台
* 64bit: rubyci 用、ci.rvm 用各1台

9,735円 * 4 = 38,940 円（税込み）

32bitOSで 8GB は、無駄になりそうな気もしますが、1 process が 3GB という制限があるだけで、使いきれはするようです（LPAE）。あと、4GB の在庫がない（あっても高くて 8GB との差額が 1500 円くらい）。

設置は笹田自宅になるかと思います（ssh でつながるならどこでも良い）。
安くないので、懐事情とのご相談となるかと思いますが、ご検討のほど、よろしくお願いします。

**Comment by ko1** [comment]
なぜ今か：
前から買わないとなと思っていて、さぼっていたら昨今の半導体不足で、「やべ」と思って在庫見たら（ちょっと高いけど）あった、という次第です。今後何もわからないんですが、半年くらいたったら落ち着いてるかもしれず、その場合は高い買い物になりますね。逆に、ずっと手に入らない、、、みたいなことは、さすがにないかなぁ。

**Comment by takahashim** [comment]
む、もう在庫1個だけかも？

**Comment by ko1** [comment]
残念！　凄いタイミングではけちゃいましたね。

**Comment by ko1** [comment]
というわけで、気長にご検討いただけますと幸いです。

**Comment by takahashim** [comment]
では来年1月に向けてということで。

**Comment by shyouhei** [comment]
購入すること自体に異議ございませんので入手性の問題が解決できれば、と思いました

**Comment by ko1** [comment]
何もわからないけど、今みたら在庫ありますね...。
注文するならどういうプロセスがいいでしょうか。

**Comment by takahashim** [comment]
@ko1  購入自体は問題ないかと思うので、送付先を教えてもらってこちらで買うでもいいですし、買ってもらってあとで領収書を渡してもらうでも良いです。

**Comment by ko1** [comment]
またダメになってるな。そちらで購入いただくのが私が一番楽なのですが、どうでしょうか。あとで送付先お送りします。

**Comment by takahashim** [comment]
はい、それでも大丈夫です 🙆

**Comment by ko1** [comment]
じゃあ会計的に問題なければ、ご注文いただいて1月を待つ...とかでいいでしょうか（送付先 Fb で送りました）
お手数をおかけします。

**Comment by takahashim** [comment]
こちら発注はしました！　発送はしばらく先になりそうです。

**Comment by kakutani** [comment]
笹田家DCで着弾を確認したら閉じてもらってokです! @ko1

**Comment by springaki** [comment]
着弾待ち

**Comment by takahashim** [comment]
「【重要】配送遅延のお知らせ」という連絡が来ておりまして、新しいお届け予定日は「2022/02/03」となっておりました…。むむむ。

**Comment by springaki** [comment]
一旦待つ 👀

**Comment by takahashim** [comment]
続報です。
「新しいお届け予定日」は「2022/03/17」になったそうです…。

**Comment by takahashim** [comment]
さらなる続報です。
「変更後の見込みお届け日：納期確認中でございます。」だそうです…。

**Comment by takahashim** [comment]
連絡が来ました。キャンセルだそうです… 😢 

```
平素は格別のご高配を賜り、厚くお礼申し上げます。

ご注文いただいておりますRaspberry Pi製品につきましてご案内申し上げます。
Raspberry Piを供給するRaspberry Pi Trading Ltd は、深刻な供給不足問題の根本的な解決に向けて、
製品の製造体制を見直す決断を行いました。これに伴い、弊社を含む全ての既存製造ベンダーとの
製造ライセンス契約を 2022年7月1日をもって終了する旨の決定がなされました。
当該契約終了と同時に、Raspberry Pi Trading Ltdより発注分も含め、Raspberry Pi製品の供給はないと
通達があり、供給交渉の甲斐なく決裂し、残念ながらお客様にご用意することができなくなりました。
誠に勝手ながら、下記のご注文分に関しましてはキャンセルとさせていただきます。

ご注文をいただいておりましたお客様、およびお取引様には多大なご迷惑をおかけしますこと、
心よりお詫び申し上げます。


※　弊社事務処理の都合により、お客様WEBサイト上において注文履歴が残っている場合がございますが、
本メールを持ちましてキャンセルのご連絡とさせていただきます。
※　キャンセルについてのFAQはこちら
https://jp.rs-online.com/web/content/m/raspberrypi-faq

また、Raspberry Pi製品（PI 3B+、PI 3B、PI 3A+、Pi zero、CM3、CM3+、CM4等）につきましては、
ラズベリーパイ財団にお問合せ下さいますようお願い申し上げます。

◆問い合わせ先
　https://www.raspberrypi.com/contact/
◆製品ページ及び購入先情報
　https://www.raspberrypi.com/for-industry/
　→「Buy now」→「More info」→「Buy Raspberry Pi xxx」→「Industry」・「Model」・「Country」を選択

大変恐縮ではございますが、事情をご賢察いただき、ご了承いただきますようお願い申し上げます。
```

**Comment by ko1** [comment]
ご連絡ありがとうございます。
Twitter でも話題になってましたね。
また、なんか見つけたらどうぞよろしくお願いします。

**Comment by ko1** [comment]
https://www.switch-science.com/catalog/6370/?src=raspberrypi
13,090円 x 4 = 52,360
だいぶ高いけど、こっちだと買える？

**Comment by takahashim** [comment]
スイッチサイエンスの方はずっと入荷待ちになってるようですが、とりあえず会員になって待ち行列に並ぶ？のがいいんでしょうか？

**Comment by ko1** [comment]
twitter だと時々入ってるみたいな話も聞きますが、現状だといつになるかわかんないですね（10日前に見た tweet だと11月には、みたいなことが書いてありました）。もし、余裕があれば、並んでおいていただけると助かります。

（RasPi3 のうわさも出てきてるようですが、こっちはいつになるのかな）

**Comment by shyouhei** [comment]
- https://www.jeffgeerling.com/blog/2022/you-cant-buy-raspberry-pi-right-now
    - https://news.ycombinator.com/item?id=33071408

今だと海外なら入手できるとかそういうものでもないぽいですね

**Comment by ko1** [comment]
https://gadgetrip.jp/2022/10/friendlyelec_nanopi_r6s/
目的は ARM でのテスト構築なので、この辺、価格がちょっと高いんですが、試すのは可能でしょうか。
円安がなければなぁ。

**Comment by takahashim** [comment]
元々がそんなに高いわけではないので、円安かどうかを気にする必要はなさそうかと。

**Comment by takahashim** [comment]
https://www.friendlyelec.com/index.php?route=product/product&product_id=289
ケースつきだと$139ですね。

**Comment by snoozer05** [comment]
@ko1 上なら買えそうなのですが、こちらで大丈夫でしょうか...?? 大丈夫そうなら、送り先とか教えていただけると！

**Comment by ko1** [comment]
ありがとうございます（＆お返事が遅れてすみません）。
年末に Oracle cloud で OCI Ampere A1 Compute の無料インスタンスが作れたので、ARM で回すマシンが欲しい、という希望は叶えられました（ http://ci.rvm.jp/results/master@oci-aarch64 ）。

が、若干遅いのと、いつ使えなくなるかさっぱりわからないのと（https://zenn.dev/shinshin86/scraps/022e44712274fd）、もともとの 32 bit 環境というニーズが叶えられていないため、お言葉に甘えてご注文いただいてもよろしいでしょうか。高橋さんが私の住所ご存じかと思いますが、島田さんのほうにお送りした方が良ければ、別途お送りさせていただきます 🙏

**Comment by snoozer05** [comment]
@ko1 お返事ありがとうございます！

> 高橋さんが私の住所ご存じかと思いますが、島田さんのほうにお送りした方が良ければ、別途お送りさせていただきます 🙏

や、大丈夫だと思います！
@takahashim 購入とささださんのところへの発送お願いできそうでしょうか...??

**Comment by snoozer05** [comment]
https://www.friendlyelec.com/index.php?route=product/product&product_id=28
をとりあえず2台買ってささださんのお家に送る。高橋さんに購入していただく

**Comment by takahashim** [comment]
購入しました、こちらも発送は時間がかかるようで1ヶ月くらいかかるかも？　みたいな状況だそうです。

**Comment by takahashim** [comment]
なぜかうちに送られてきてしまったので転送しますね…

**Comment by takahashim** [comment]
（ついでに関税手数料とられたので良かったのか悪かったのか）

**Comment by ko1** [comment]
🙏

**Comment by ko1** [comment]
届きました！
![img_2387_720](https://user-images.githubusercontent.com/9558/222610459-09b793ba-2109-4ebc-a311-11db238917d5.jpg)

（ケースなかったので、段ボールでカバーつくるかな

**Comment by snoozer05** [comment]
よかったです！
