### ISSUE TITLE
GitHub organizationを新プランにする

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#434]
このGitHub organizationは #329 で無事non-profitプランになっているのですが、現状はLegacyプラン(Silver)のままなので、新プランにするのを検討します（以前どこかで検討してた気がしたんだけどどこだったっけ…）。

とりあえずサポートに問い合わせしてみています（memberがいっぱいいるけど問題ないのかどうか）。

**Comment by amatsuda** [comment]
もしmemberがいっぱいが問題って言われたら、いま稼働してない人たちはkick outしてもいいんじゃねえかとは思います。まあそういう理由があるなら誰も文句は言わんでしょう。

**Comment by hsbt** [comment]
コスト爆上げになると思うので、主要メンバーだけ残して、メンバーではないけどアクティブですという人はリポジトリのコラボレータって感じと思います。

**Comment by kakutani** [comment]
> いま稼働してない人たちはkick outしてもいいんじゃねえかとは思います。まあそういう理由があるなら誰も文句は言わんでしょう。

ですねえ。何かあればまたお願いすればよさそう

**Comment by takahashim** [comment]
これですが、GitHubのsupportからはnon-profitプランなのでdiscount効くので問題ないとのことだったので、あとでupgradeしてみます

**Comment by amatsuda** [comment]
おっ

**Comment by takahashim** [comment]
upgradeしました

**Comment by springaki** [comment]
新プランに移行された

#435 につづく
