### ISSUE TITLE
GitHub リポジトリのメンバを一旦整理する

### ISSUE THREAD

**Issue by springaki** [ruby-no-kai/official#435]
GitHub organizationを新プランに伴い、正規の請求だとこんな感じになる。
GitHubさんの支援により Non Profit Planを受けているが、いつまで有効かわからず突然 $10,000越えの請求が来ても怖いので、徐々にメンバも整理していこうという話になった。

https://github.com/orgs/ruby-no-kai/people

![ruby-no-kai-upgraded-1](https://user-images.githubusercontent.com/534628/145775350-e79eb11c-e628-44ec-b9b3-6ade60eaa5bd.png)

![2021-12-13_17 05 14-1](https://user-images.githubusercontent.com/534628/145775371-a443b14e-2bfe-4326-8729-85c688885c5d.png)

まずは 終わっているイベントの Team は解散してもいいかもしれない
https://github.com/orgs/ruby-no-kai/teams

- Ruby Kaigi
- Kaigi on Rails

くらいしかなさそうなので、rubykaigi.org への移行も含めて整理していけそう

**Comment by kakutani** [comment]
課金対象になるのはプライベートrepoへのアクセス権限なので、野放図にやっていたのを整理していく。

1. 動いていないチームを減らす
1. チームに属していないメンバーはいったんorgのメンバーからは外す
1. 必要な人は外部コラボレーターとして足していけばよさそう (やってみたいとわからない)

outside collaborator であっても。private repoへのアクセス権限があると課金対象にカウントされる。必要なぶんは追加すればよい。

現状は、GitHubのプランや変遷の歴史とともに結局どうなってんだか把握できていないのが問題なので、まずはこれを整理していく。

**Comment by amatsuda** [comment]
> rubykaigi.org への移行も含めて整理していけそう

ここはちょっと認識が違いまして、ruby-no-kaiオーガニゼーションがupgradeできたんだったら、この「rubykaigi.org への移行」という作業はなくなりそうです。

あらためていきさつを整理しますと、以下のような流れで今回のupgradeが行われたのでした。

1. 今までの毎年のRubyKaigiのサイトは [ruby-no-kai/rubykaigi.org](https://github.com/rubykaigi/rubykaigi.org) リポジトリ上で、Middlemanを使ってstatic siteを生成したやつをHerokuに送りつけて配信、という構成になっていた
2. まあこれでも動いてたからいいんだけど、無駄にデプロイが複雑なので、どうせstaticなサイトなんだったらGH Pagesに置けばいいのでは？ていう気がしてきた
3. しかし、ruby-no-kaiオーガニゼーションはlegacyプランのorganizationだったため、GH Pagesが公開できない！
4. そんなこともあろうかと、`rubykaigi` というニュータイプorganizationも取ってあるのですよ、と高橋さんに言われた(プランはGitHub Free)
5. なるほど、じゃあ既存の`rubykaigi.org`リポジトリを`rubykaigi`オーガニゼーションにtransferしてみよう
6. transferをやってみて、GH Pagesの公開を試してみたけど、GitHub Free for organizationsのprivateリポジトリではGH Pagesを公開できない、とのこと
> GitHub Pages is available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. For more information, see "GitHub's products."
 (https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages より)
7. つまり、ruby-no-kaiオーガニゼーションをGitHub Teamにアップグレードしてそっちにrubykaigi.orgリポジトリを再度戻したら、今度こそGH Pagesが公開できるようになっているはず

で、このたびruby-no-kaiオーガニゼーションをGitHub Teamにアップグレードしていただいたとのことなので、次は僕のほうでrubykaigi.orgリポジトリのtransfer backとGH Pagesの公開を試してみます。これでうまく行くようなら、rubykaigiオーガニゼーションは全く使わない感じになりそうです。

**Comment by springaki** [comment]
あーなるほど。わかりやすい。理解しました。

> 僕のほうでrubykaigi.orgリポジトリのtransfer backとGH Pagesの公開を試してみます。これでうまく行くようなら、rubykaigiオーガニゼーションは全く使わない感じになりそうです。

了解です。よろしくお願いします !

**Comment by amatsuda** [comment]
では手始めに、いま稼働してない rk??-team は僕のほうで全部消しちゃいますよ。

**Comment by amatsuda** [comment]
過去のRubyKaigiっぽいteamをざっくり削除完了しました。
まだteamを消しただけで、peopleはいっぱい残ってるので、Billing的なやつに変化はありません。

**Comment by springaki** [comment]
今見たら表示が $0 になってました。

![スクリーンショット 2022-03-28 17 18 09](https://user-images.githubusercontent.com/534628/160356095-e0daf205-4f37-44d7-b120-5d972e966d40.png)

**Comment by pupupopo88** [comment]
Kaigi on Rails org の non-profit 申請が通ったらKaigi on Rails のメンバーを整理してcloseします！

**Comment by pupupopo88** [comment]
やっと申請通ってKaigi on Railsメンバーの整理完了したのでcloseします！！
