### ISSUE TITLE
テスト環境用のPCの購入

### ISSUE THREAD

**Issue by ko1** [ruby-no-kai/official#436]
（間違って途中で投稿しちゃった）

http://ci.rvm.jp/ に使ってる物理マシンが5年くらいたつので大分しんどい状況になっており、もし余裕があればご支援いただけないでしょうか。

https://store.minisforum.jp/products/minisforum-elitemini-hx90?variant=40590285865126
16GB RAM+256GB SSD つき、\86,980 ＋送料

が小さくて速い（し、10万切ってる）と教えてもらったので、こちらを希望します。

具体的には、
https://twitter.com/_ko1/status/1379584297020006401
にある、ruby/sky1~3 とラベルのある 3台の大きいマシンのうちの1台のリプレースで、主にテストをドンドン繰り返すものです。希望があれば、Rubyコミッタにログインしてもらえるようにする予定です。

残りの2台のうち、1台はベンチマークをずっと回しているので変更できないのですが（環境の安定性）、もう1台も余裕があれば replace したいと思っています（こちらは雑多なテスト・評価用）。ので、もし余裕があれば、さらに1台ご検討ください。

RasPi に続いてクレクレ言ってますが、どうぞよろしくお願いします。

**Comment by ko1** [comment]
（主に）AWS 上のリソースを使った rubyci.org があるのになんでわざわざ実機要るの？　というための説明資料です：[cirvm.pdf](https://github.com/ruby-no-kai/official/files/8114904/cirvm.pdf)
（どこかで発表できないかなぁと思って資料だけ作っていた）

**Comment by takahashim** [comment]
購入は問題ないかと思いますが、クラウドじゃなくて物理マシンの方がよいのはなにか理由があるんでしょうか？
（資料読んでも「rubyci.org以外で好きに使えるクラウドのインスタンスがあればいいんでは…？」と思ったのでした）

**Comment by ko1** [comment]
ci.rvm.jp のマシンについて、まったくクラウドで問題ないです（できればそうしたい）。
金額は、多分物理マシンのほうが安いと思っています。また、料金の計算が面倒そう。

評価マシン用は、物理マシンじゃないと厳しいかなと思っています（が、これは optional）。

**Comment by takahashim** [comment]
@ko1 こちら遅くなってすみません、購入OKです 🙆‍♀️ 
どういう手順で進めればいいですか？

**Comment by ko1** [comment]
ありがとうございます。
RasPi の時みたいに、お手数ですが、そちらで購入し送付先を我が家にしておいていただけますと、領収書のやり取りがなくて助かります。

**Comment by shyouhei** [comment]
@ko1 ああ、いえ、クラウドでいいのではという話をしました。そうなってくると購入して送付というが慣れとはちょっと違ってきますよね。なのでどういう手順にしようかというご相談でした。

**Comment by takahashim** [comment]
あれ、実機とクラウドの両方あるとよい（評価用は実機が必要）、ということじゃなかったでしたっけ。

**Comment by shyouhei** [comment]
それならそれでだと思います。何を買うかから調整でしょうか

**Comment by ko1** [comment]
クラウド（AWS？）の場合、どんな処理になるでしょうか。例えば、私が使った分を毎月請求する？（のは面倒かなぁ）。
実機については、最初に書いてあるのでどうでしょうか。

**Comment by shyouhei** [comment]
請求書の手書きは面倒じゃないでしょうか…利用料が毎月変動しそうですし。
rubyciはどうしてるんですかね。多分それ用のクレジットカードをRAが発行してAWSに登録してるとかかな。

**Comment by hsbt** [comment]
rubyci は

* 昔は @hsbt がクレカを AWS などに登録して立替、請求書を JPY に変換して misoca で合計の請求書を作成して RA から精算してもらう
* 今は RA がクレカを AWS に登録して、直接処理をしてもらう

ってなってます。

**Comment by shyouhei** [comment]
たぶん同じ感じが双方楽でいいと思うので実現可能かもんでみますー

**Comment by ko1** [comment]
> 金額は、多分物理マシンのほうが安いと思っています。また、料金の計算が面倒そう。

（計算というか清算でしたね）

* (1) 高そう
* (2) 清算が面倒そう

というのが、物理マシンどうでしょうか、って理由だったんですが、(1) の金額については実際どれくらいのコストかかるのかやってみないとわからないところがあるので、1か月くらいやってみます（これについて、費用負担は不要です）（実機との比較をしてみます）。
(2) については、今回のことに限らず機会があるかもしれないので、(https://github.com/ruby-no-kai/official/issues/436#issuecomment-1088428375 にある通り)Rubyの会でご検討いただけると幸いです。

**Comment by takahashim** [comment]
クラウドの場合、基本的には、

> 今は RA がクレカを AWS に登録して、直接処理をしてもらう

みたいな形になるかと思います。なので精算の手間は特にないはず。

とはいえ、AWSじゃなくてそれこそherokuとかの方が、構築・運用の手間等では便利なのでは？　という気もするんですが、DBの容量が大きいと高くつきすぎますかね…（Rubyの会で使ってるPaaSとしてはherokuが多いです。最近のサービスとしてrenderとかにもちょっと興味ありますが、そんなにメリットがあるわけではなさそう。）

**Comment by shyouhei** [comment]
あ、まあ、テスト用の計算機資源という意味だと、回しっぱなしなので、Herokuはなじまない感じです(dynoがすぐ死んでしまう、年単位で動かし続けたい)

**Comment by takahashim** [comment]
あー、http://ci.rvm.jp/ は集計・表示するだけのサーバではなくて、テストの実行もするんですね…。
（とはいえDBが大きそうだとherokuならHobbyではなくStandardあたりになるのかと思っていたので、dynoを動かしっぱなしにするのは特に問題ないという想定でした）

**Comment by takahashim** [comment]
@ko1 それはさておき実機（Minisforum EliteMini HX90）の方はraspiと同じ住所宛に送りますね

**Comment by ko1** [comment]
> あー、http://ci.rvm.jp/ は集計・表示するだけのサーバではなくて、テストの実行もするんですね…。

ci.rvm は集計だけしています。heroku にしてもいいんだけど、自分でメンテしてる sakura VPS で十分賄えているんで（なんと sqlite3）、とくに困っていません。

> それはさておき実機

🙏

**Comment by ko1** [comment]
実機届きました！　やっぱり速いですね（家の中で一番速い）
