### ISSUE TITLE
一般社団法人日本Rubyの会のPayPalアカウントを作成する

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#44]
paypal@ruby-no-kai.org で作成していただけると助かります。
(paypal@ruby-no-kai.org は"All users within Ruby-no-Kai"のgorupとして作成済です)
- rubykaigi.orgのほうのアカウントを閉じたい
- メールアドレスの確認とか、UserなりOwnerなりの整理をする

**Comment by takahashim** [comment]
とりあえず作ってみましたが、これってメールアドレスは個人のアドレス以外に登録するところはないんでしたっけ？（takahashim@ruby-no-kai.orgしか入力してない。確認のメールは届いていない模様）

**Comment by takahashim** [comment]
paypal@ruby-no-kai.org を追加しようとしたら、

> 送信されたメールアドレスは、すでに別のPayPalアカウントに登録されています。そのアカウントの保有者である場合は、ログインして取引をおこなってください。そうでない場合は、異なるメールアドレスを入力してください。

と言われました！

**Comment by kakutani** [comment]
paypal@rubykaigi.org のアカウントに追加しようとしてunconfirmedのままになってたので、
そちらからremoveしました。もう一度ためしていただいてよいでしょうか? > @takahashim

**Comment by takahashim** [comment]
追加してみました！

**Comment by takahashim** [comment]
やっぱりメールが届かない、ような…

**Comment by kakutani** [comment]
うーん。詰んでしまったのでしょうか……(電話で聞くしかない?)。
高橋さんの出したtest メール自体は届いてました。

**Comment by takahashim** [comment]
pay@とかpayment@とかいう新しいアドレスを作ってみるとか？

**Comment by takahashim** [comment]
相変わらずpaypal@もpayment@も届かないんですけど、とりあえずkakutani@を追加してみました。こっちはどうでしょう？

**Comment by takahashim** [comment]
ひょっとして認証しないとだめとか？

**Comment by kakutani** [comment]
"新しいメールアドレスの確認" のメールがpaypalから来てましたが、このときに入れるパスワードって教えてもらってましたっけ……(高橋さんが認証したなら良いんですが)

**Comment by takahashim** [comment]
あれ、私の方では自分のアカウントのパスワードしか登録してないので、新規に登録するとかでは？

**Comment by kakutani** [comment]
rubykaigiのアカウントのほうで社団法人の口座を紐付けてしまったので、行き止まり。
rubykaigiアカウントのほうをあづみさんに本人確認してもらって、銀行口座をremoveの上、アカウント自体をcloseするのがよさそう。

いまはあづみさんからの本人確認資料到着まち。

**Comment by kakutani** [comment]
あづみさんの本人確認を開始しました。

**Comment by kakutani** [comment]
あづみさんのところに「アカウント取引責任者用暗証番号」が郵送されたらしい(ソースはPayPal)

**Comment by kakutani** [comment]
本人確認が終わったので、一般社団法人の銀行口座をrubykaigi.orgのアカウントから削除しました。
一般社団法人の口座を ruby-no-kai.org のPayPalアカウントに紐付けてください > @takahashim

**Comment by kakutani** [comment]
@takahashim ping

**Comment by takahashim** [comment]
紐付けてみました！

**Comment by kakutani** [comment]
メールアドレスの問題はいまだに残っていそうな気がしますが、アカウントとしてはこれで成立したってことですかねえ。
メールアドレスの件とかは別issueにして一旦これは閉じちゃいましょうか。

**Comment by kakutani** [comment]
……と思ったら、google groupsのメールアドレスにはpaypalから届かないという問題が1年ぐらい前から出ていて直っていないっぽい。

"どうも8月24日以来 PayPal の通知メールが Google Apps のグループメールアドレス宛に限って届かないという問題が発生しているらしい。http://goo.gl/UEstQ "
https://twitter.com/takayukister/status/114960943083028480

別件で同様の問題にハマったのですが、groupsじゃなくてuserにしたらシレっとメールが届きました。
user から group に forward したらできるかなあ。ちょっと試してみます。

**Comment by kakutani** [comment]
payment@ruby-no-kai.org を新規にuserとして追加しました。
で、↑ここからruby-no-kai.org内のgroupにメールをforwardするようにして、
groupにruby-no-kai.orgの理事を追加しました。

メールが流れていくのは確認したので(まずは単独で確認してから他の理事をgroupに追加しました)、
paypal側でpayment@ruby-no-kai.org をメールに追加していただけますか? > @takahashim

**Comment by takahashim** [comment]
先週末に追加してみたんですが…

**Comment by kakutani** [comment]
ぐぬぬ……どっか機会のあるときに一緒にやってみるのがいいですかねえ。とほほ。

**Comment by kakutani** [comment]
payment@ruby-no-kai.org で疎通確認ができたと思うので、一旦閉じます!
