### ISSUE TITLE
テスト環境用のRISC-Vボードの購入

### ISSUE THREAD

**Issue by mame** [ruby-no-kai/official#440]
RubyのCI用にRISC-Vのボードがほしいと思っているのですが、買ってもらうことはできますでしょうか。

https://www.amazon.co.jp/dp/B0975B1GSF

RISC-Vの話題は徐々に増えていると感じているので、CIは置いておきたいと思ってます。
今はAWSでRISC-VのQEmuを構築してRubyCIに登録していますが、一周5時間ほどかかっています。
Linuxが動くRISC-Vボードも大分安くなってきた（3万円弱）ので、そろそろ実機も試してみていいのかなと思いました。

ただ、本当に動かせるのか？QEmuより十分速いのか？（上のボードの性能は raspberry pi の半分くらいみたいです）など読めないところもあります。
やってみたら全然ダメだった、となってもよければ、試してみたいです。

もしうまく動くようなら、ささだ家データセンタに置いてコミッタが自由にログインしてデバッグ等できるようにする予定です（ささださんの了承は得てます）。

**Comment by takahashim** [comment]
なるほど、いいんではないかと思います！
SipeedならaliexpressのSipeed storeで買ったほうが良いかも。
https://www.aliexpress.com/item/1005002856721588.html

送付先はどこにするのがよいですか？（先日のMinisforumと同じでよいでしょうか）

**Comment by mame** [comment]
ありがとうございます！ 送付先はTwitter DMで連絡しました

**Comment by takahashim** [comment]
こちら購入しました。発送はだいぶ先になりそうです（「13 days 以内に発送されます」とのことでした）。

**Comment by takahashim** [comment]
こちらは発送はされているようですが、「仕出地の物流ハブに到着済み」で止まっているようです…

**Comment by springaki** [comment]
まだ止まっている様子。引き続き様子を見守っている。
60日到着されないと、自動キャンセルされてしまうかもしれない。様子見。

**Comment by takahashim** [comment]
ストアに確認してみたところもうちょっと細かい情報を教えてもらい、5/21に航空会社に移ったところまでは確認できました。その後どうなったかをロジの会社に確認してもらっています。

**Comment by takahashim** [comment]
先ほど出国したとの連絡がありました

**Comment by mame** [comment]
ご連絡が遅れましたが、1週間ちょっと前に無事に到着しました！

CI用にセットアップするのにだいぶ手間取っていたのですが、ついに昨日chkbuildがおおよそ完走してくれました（まだ一部のテストがタイムアウトしているので要調整）。

ただ、残念ながらQEmuよりも1.5倍～2倍くらい遅そうです……。当初にも懸念していたことですが、CI用に購入するには時期尚早すぎたかも。実機でもちゃんと動作することが確認できたのはよかったですが、CI用よりは手元でのデバッグ用として活用できないか考えてみたいと思います。

**Comment by takahashim** [comment]
報告ありがとうございます、まずは無事に動作したということで良かったです！
