### ISSUE TITLE
RailsGirls 年間スポンサー費用請求(株式会社タイミー様)

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#442]
株式会社タイミー様より、年間スポンサーのお申し込みがありましたので、
請求処理をお願いいたします。

株式会社タイミー様の情報は、メールにて共有させて頂きました。

 - [x] 請求書を作成する
 - [x] 請求書を送付する( @emorima )
 - [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
 - [x] スポンサー様からの入金を確認する

**Comment by springaki** [comment]
Next Action: 8月頭に入金確認する

**Comment by snoozer05** [comment]
全て終了。対応お疲れ様でした
