### ISSUE TITLE
福岡 Rubyist 会議 03 の開催について

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#443]
Fukuoka.rb の尾田です。
掲題の通り、開催を予定して準備を進めています。
つきましては諸々ご協力を仰ぐことになると思いますので、よろしくお願いします。

--

名称：福岡 Rubyist 会議 03
開催日：2023 年 2 月 18 日（土）
会場：リファレンス駅東ビル
参加費：1,000円
配信：なし
定員：80 名程度
実行委員長：尾田（@jinroq）
会計：TBA
レポート：TBA
サイト：https://regional.rubykaigi.org/fukuoka03/

**Comment by jinroq** [comment]
https://github.com/ruby-no-kai/regional.rubykaigi.org/pull/124
公式サイトの PR を作成しました。

**Comment by snoozer05** [comment]
ありがとうございます！内容確認してマージさせていただきました！

**Comment by jinroq** [comment]
https://twitter.com/devchick99/status/1564141288756088833?s=21&t=ynW93ej32aQs9Iq6KnwSzA
このようなご意見をいただいたのですが、対応していただくことは可能でしょうか？（最初に http なリンク貼ったのがよろしくなかったのですが）

**Comment by takahashim** [comment]
https://docs.github.com/ja/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#%E3%81%82%E3%81%AA%E3%81%9F%E3%81%AE-github-pages-%E3%82%B5%E3%82%A4%E3%83%88%E3%81%AB-https-%E3%82%92%E5%BC%B7%E5%88%B6%E3%81%99%E3%82%8B
↑これですよね。
何か設定して問題あることありましたっけ？

**Comment by snoozer05** [comment]
全く記憶にないので、多分問題ない（単に設定していない）だけじゃないかなあと思います...!!

**Comment by takahashim** [comment]
では設定しておきます…！

**Comment by takahashim** [comment]
設定しました

**Comment by jinroq** [comment]
https://github.com/ruby-no-kai/regional.rubykaigi.org/pull/125
キーノートスピーカーと会場情報を記載しました。

**Comment by jinroq** [comment]
@takahashim @snoozer05 

http から https へのリダイレクトの対応をしていただいたかと思いますが、有効になっていないようです。

http://regional.rubykaigi.org/fukuoka03/

お手漉きの時にご確認をお願いします。

**Comment by snoozer05** [comment]
うーん、GitHub pagesの設定的には、次のように有効にしているつもりなのでした....何だろ

<img width="815" alt="スクリーンショット 2022-09-30 19 44 58" src="https://user-images.githubusercontent.com/3954/193253603-869103e4-80b3-48b6-a995-90a8a915e4b2.png">

**Comment by jinroq** [comment]
公式サイトに日本 Ruby の会を後援として記載したいのですが、ロゴ画像とかあったりしますか？

**Comment by jinroq** [comment]
そろそろ、スポンサー募集および CFP オープンを検討しています。
その際スタッフ（実質わたし一人ですが…）と外部との連絡手段として `fukuoka03@rubykaigi.org` を作成していただきたいです。
jinroq+fukuokark03 at gmail で登録いただければ、と思います。 ref: #275

**Comment by jinroq** [comment]
（独り言ですが、カンファレンス名を[変更したいな](https://github.com/ruby-no-kai/official/issues/448#issuecomment-1308067560)という気持ちが若干あります…。ただ、慣例のない名称になるので変えて良いのかどうかがよく分からないです）

**Comment by snoozer05** [comment]
> 公式サイトに日本 Ruby の会を後援として記載したいのですが、ロゴ画像とかあったりしますか？

https://github.com/ruby-no-kai/official/tree/gh-pages/images/logos この辺りから拾ってもらうことで用は足りそうでしょうか...??

> そろそろ、スポンサー募集および CFP オープンを検討しています。

お疲れ様です!!

> その際スタッフ（実質わたし一人ですが…）と外部との連絡手段として fukuoka03@rubykaigi.org を作成していただきたいです。

@takahashim or @kakutani ruby-no-kai.org （こっちなら島田でもできた）でなく rubykaigi.org なので、どちらかに対応をお願いできるでしょうか 🙏

**Comment by takahashim** [comment]
@jinroq メールアドレス（グループ）は作ってみたんですが、メンバーが追加できなさそう…？

**Comment by takahashim** [comment]
`+fukuokark03` を省いたgmailアドレスであれば追加できたんですが、これでも問題ないでしょうか？

**Comment by kakutani** [comment]
> （独り言ですが、カンファレンス名を[変更したいな](https://github.com/ruby-no-kai/official/issues/448#issuecomment-1308067560)という気持ちが若干あります…。ただ、慣例のない名称になるので変えて良いのかどうかがよく分からないです）

#448 で「命名規約」を緩くしたい、という話をしているので、変えることそのものには @jinroq の意向を優先してもらってよいと思います。「慣例にない」ことがどうコミュニティで受容されるのかはやってみないとわからないですしねえ。

スポンサーやCFPを募集するのであれば、その前に決定しておけるとよさそうですね。

**Comment by jinroq** [comment]
@snoozer05 
ありがとうございます！そちらを使わせていただきます。

@takahashim 
省いたやつで問題ありません。

**Comment by jinroq** [comment]
@kakutani 
https://github.com/ruby-no-kai/official/issues/448#issuecomment-1311261745

おっしゃる通りやってみないと分からないので、やってみます。

**Comment by snoozer05** [comment]
> http から https へのリダイレクトの対応をしていただいたかと思いますが、有効になっていないようです。

rko router周りっぽい...??
https://github.com/ruby-no-kai/rko-router/blob/master/config/force_https.conf

**Comment by jinroq** [comment]
[情報共有]
スポンサーさんは公募ではなく、jinroq から直接お声がけさせていただいています。請求書関連でサポートをしていただきたいです。

**Comment by kakutani** [comment]
regional.rubykaigi.org のインデックスにもリストしておこうと思います: 
https://github.com/ruby-no-kai/regional.rubykaigi.org/commit/c45f711b902afaebfce35b782eabd47532e61e2f

**Comment by kakutani** [comment]
> > http から https へのリダイレクトの対応をしていただいたかと思いますが、有効になっていないようです。
> 
> rko router周りっぽい...?? https://github.com/ruby-no-kai/rko-router/blob/master/config/force_https.conf

できたと思います! (https://github.com/ruby-no-kai/rko-router/pull/89)
http://regional.rubykaigi.org/fukuoka03 ← リダイレクトされるはず

**Comment by jinroq** [comment]
@kakutani 
リダイレクトされることを確認しました！対応ありがとうございます！！

**Comment by jinroq** [comment]
そろそろ開催間近になってきたので、残タスク整理。

- 12月下旬： スポンサー企業様を公式サイトに掲載
- 12月下旬： スピーカー決定
- 1月上旬： タイムテーブルを公式サイトに掲載
- 1月上旬： チケット販売開始
- 2/18： カンファレンス開催
- 2月下旬 or 3月下旬： 開催後、スポンサー企業様に請求書の郵送

確認事項

- [ ] チケット販売時にアカウントを借りる #251 
- [ ] スポンサー費用を前借り（開催後に請求するので、その時に返金）
- [ ] Keynote Speaker の交通費・宿泊費の援助（もしかしたら不要かも）
- [x] ~~請求書ではなく領収書の発行が可能か確認~~ 必要なくなった

**Comment by jinroq** [comment]
@takahashim （であってます？）

以下の 2 つをお願いしたいのですが、別途 issue を立てた方がいいでしょうか？
- チケット販売時にアカウントを借りる（paypal アカウントを借りる）
  →Doorkeeper を[想定](https://fukuokarb.doorkeeper.jp/)していますが、管理者を探しているところです…
- スポンサー費用を前借りする
  →会場の拡張費として使わせていただきたいです

**Comment by kakutani** [comment]
仮に、Doorkeeperだとすると現在はPayPalではなくてStripeになってます。
https://www.doorkeeper.jp/pricing
> 料金は主催者の [Stripe](https://support.doorkeeper.jp/article/95-stripe)アカウントへ直接入金され、イベント開始前に集金状況を確認することができます

Doorkeeprの支払いの設定のページをみてみると、

> ここで記入する情報は、特定商取引法に基づく表記のページならびに参加者に対して発行される領収データに表示されます。

…となっているので、Rubyの会のStripeアカウントをつかって、チケットの販売事業者は日本Rubyの会になっているほうが気は楽そうですね(後援しているしな)。
会のStripeのアカウントはいまは @takahashim が管理なので、相談ですねえ(会のアカウントを使うのがよさそう)。

ただ、Doorkeeperっていまは月額利用料金がかかるんですよねえ。こんかいみたいな単発イベント用だといまは用途に合わないかもしれませんね。

テキトウにいまググったら「STORESで電子チケットがカンタンに販売できる！」そうです。
https://stores.jp/ticket
こういうもののほうが使いやすいかもしれない…?

スポンサー費用については、請求も日本Rubyの会でやるようにすれば、福岡Rubyist会議03側からの「返金」は不要になると思います。請求よりも支払いが先に来るのはカンファレンスあるあるなので、必要な情報を info at ruby-no-kai dot org にメールしてください〜(振込先、金額、いつまでに必要、など)。

**Comment by jinroq** [comment]
@kakutani 
> ただ、Doorkeeperっていまは月額利用料金がかかるんですよねえ。こんかいみたいな単発イベント用だといまは用途に合わないかもしれませんね。

前回の福岡 Ruby会議 02 では connpass を使っていたようですね。connpass には払い戻し機能がないので Doorkeeper を候補にあげましたが、今回も connpass で販売しようかと思います。
つきまして、やっぱり PayPal のビジネスアカウントをお借りしたいです（こちらも @takahashim 管理？）

> スポンサー費用については、請求も日本Rubyの会でやるようにすれば、福岡Rubyist会議03側からの「返金」は不要になると思います。請求よりも支払いが先に来るのはカンファレンスあるあるなので、必要な情報を info at ruby-no-kai dot org にメールしてください〜(振込先、金額、いつまでに必要、など)。

こちら承知しました。後ほどメールします。

**Comment by kakutani** [comment]
> 前回の福岡 Ruby会議 02 では connpass を使っていたようですね。connpass には払い戻し機能がないので Doorkeeper を候補にあげましたが、今回も connpass で販売しようかと思います。

PayPalもStripeもアカウントはあるので、決めたら教えてもらえるとよさそうです。

> こちら承知しました。後ほどメールします。

請求関連の情報も共有してもらうことになると思います! (開催後の請求とのことなので、急ぎませんが念のため)

**Comment by takahashim** [comment]
@jinroq どちらも問題ないですが、別issueにしたほうがいいかもです！（何度か往復のやりとりがありそうなので）

**Comment by jinroq** [comment]
@takahashim 
相談ですが、謝礼金の振り込み作業の代行を Ruby の会に代行していただくことは可能でしょうか？
一旦 Fukuoka.rb の口座に集めてやろうかと思っていましたが、二度手間だなと思いまして。

**Comment by takahashim** [comment]
@jinroq はい、それでも大丈夫です 🙆‍♀️

**Comment by kakutani** [comment]
> 一旦 Fukuoka.rb の口座に集めてやろうかと思っていましたが、二度手間だなと思いまして。

@jinroq そういえば、たとえば会場費とかの振り込みも、Rubyの会のほうに請求書をまわしてもらえれば対応できると思いますが、これはもう払っていたりしますかねえ。謝礼や会場費用以外でも、立て替え的なやつがあるなら対応できるとおもいます(お知らせまで)。

**Comment by jinroq** [comment]
@takahashim 
ありがとうございます！

@kakutani 
承知しました。会場費は支払ってありますが、少し拡張したので追加費用が発生しています。その支払いの方をお願いしようかと思います。

**Comment by jinroq** [comment]
支払い関連（各 Issue を別途たてる）

- [x] 会場費追加費用支払い代行 #458 
- [x] キーノートスピーカー旅費支払い代行
  - [x] そらはさん #459
  - [x] ぺんさん #460
- [x] 謝礼金支払い代行
  - [x] デザイナー #461
  - [x] 八女茶 #462
- [x] ノベルティー代
  - [x] jinroq（代わりに支払っている） #464 
- [x] 現金振り込み（雑費とかで必要になりそうなやつ） #466

**Comment by jinroq** [comment]
請求関連（別途 Issue をたてる）

- [x] スポンサー費用請求代行 #463

**Comment by jinroq** [comment]
~~福岡 Rubyist会議 03 に東京から参加する友人を私の家に泊める予定でしたが、諸事情により難しくなりました。
この方の宿泊費のみを支援していただくことは可能でしょうか？~~

この方の宿泊費の支援は、福岡 Rubyist会議 03 の収益からさせていただきたいです。

- [x] 宿泊費支援（やんちゃさん） #467

**Comment by jinroq** [comment]
https://github.com/ruby-no-kai/official/issues/443#issuecomment-1386226490
こちらが完了したら、本 Issue はクローズする予定です。
他に残タスクはないですよね？（わかる方へ）

**Comment by jinroq** [comment]
#443 がクローズになったので、本 Issue もクローズします。
皆さま、ご協力感謝します🙏
