### ISSUE TITLE
Ruby 開発用 Mac mini の購入依頼

### ISSUE THREAD

**Issue by hsbt** [ruby-no-kai/official#444]
https://github.com/ruby-no-kai/official/issues/207 か https://github.com/ruby-no-kai/official/issues/355 で購入した Intel Mac mini の片方がハードウェア的にダメになったようで、再起動してもすぐに止まるようになってしまいました。またもう片方の Intel Mac mini も HDD が故障しているらしく High Sierra のまま稼働はしてますが OS のアップデートができない状態です。

つきましては、macOS の開発環境として M1 の Mac mini の購入費用を日本 Ruby の会から拠出していただけないでしょうか?

可能と言うことであれば、スペックを見積もろうと思います。

**Comment by takahashim** [comment]
はい、問題ないかと！ 🙆

**Comment by hsbt** [comment]
ありがとうございます!

M1 8core, 8GB RAM, SSD 512GB で 120,800円でした。こちらで立て替えて注文して、後ほど精算いただくと言う感じで行きます。

**Comment by hsbt** [comment]
@takahashim @springaki 宛に領収書を送付しました!

**Comment by takahashim** [comment]
@hsbt ありがとうございます、振り込みました！

**Comment by snoozer05** [comment]
状況終了。対応お疲れ様でした
