### ISSUE TITLE
地域Ruby会議名の命名規約を変更(緩和)したい

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#448]
### 🎯  やりたいこと

* "Regional RubyKaigiの命名規約"を現状よりも「緩くしたい」
* 具体的には、イベント名の `#{RegionName(地域名)}` を「規約」とはしない(参考、とする)
* 規約を緩くして「原則」や「ガイドライン」を充実させていくのがよさそう

#### "RubyKaigi #{YYYY}"と地域Ruby会議での名前の混乱を減らしたい

あわてて補足すると、混乱を「**無くしたい**」ではない(その達成には「Ruby会議」と名乗らない、が一番簡単だけど、それは抵抗がある( 「地域Rubyコミュニティにとっての自分たちの"ﾙﾋﾞｰｶｲｷﾞ"」が地域Ruby会議だと思うので)

* 2016年以降RubyKaigi は東京以外でやる(し、やり続けるだろう)ので、地域Ruby会議と混乱しやすい状況は続く
* 地域Ruby会議プロジェクトは「日本Ruby会議2008」からのフォークで、当時は"RubyKaigi" == 東京の前提だった
* オフラインのイベントもだんだん戻ってきそうだし、2023年で地域Ruby会議も15年、RubyKaigiも再始動して10年というのもタイミング的に丁度よさそう
* なので、2022年のうちに大枠はお知らせしておきたい

これは余談(とはいえ動機のひとつ)ですが、きっかけは [ファインディエンジニアラボのインタビュー記事](https://engineer-lab.findy-code.io/history-of-rubykaigi) 収録の際に、と地域Ruby会議の話題になったとき、@amatsuda  から混同・混乱についての話題になって「たしかにRubyKaigiが東京から出ていってからはそうスよね…」という気持ちになったのでした(記事本編ではDropされてしまった)。

### 🕵️‍♀️ 現状

[Regionalrubykaigi · ruby\-no\-kai/official Wiki](https://github.com/ruby-no-kai/official/wiki/Regionalrubykaigi#regionalrubykaigi%E3%81%AE%E5%91%BD%E5%90%8D%E8%A6%8F%E7%B4%84)

> 「RegionalRubyKaigi(地域Ruby会議)」は総称表現です。個別の開催には基本的に下記の命名規約にしたがって名前をつけてください。
> 
> 日本語表記は、「開催都市または地域名」 + 「Ruby会議」(例:東京Ruby会議)
> 英語表記は、「RegionName」 + 「RubyKaigi) (例:TokyoRubyKaigi)
> 開催回数は、"%02d" % count (例:01)。countは1オリジン
> 公式タグは、"RegionName" + "RubyKaigi" + count の lowcase。例: tokyorubykaigi01
> 公式ハッシュタグは公式タグよりも短いものがよいでしょう。例: tkrk01

### ❓ Issueでなにをしたいの

* オフィシャルなアナウンスメントをバーンと出そうとすると(kakutaniの)手が止まりそう(なので、早めに共有しておきたい)
* 「ガイドライン」的なもののについてのご意見などをうかがえるといいなと思ってます

### ☑️  Issueを閉じる条件

* 「オフィシャルなアナウンスができたな」と思えたら完成
  * 具体的には、Issueではない文書をオフィシャルっぽい場所に置く
* (Issue Closedじゃなくても「緩くする」方針そのものはEffective Immidiatelyでよいと思ってます。どう緩くするかはまあIssueとかで議論できるとよさそう

* * *
ここからは kakutani のまとまってない考えです。

###  前提: 目的はあくまでRubyKaigiとの混同を「減らす」であって「無くす」ではない

* 「日本Ruby会議」と「RubyKaigi」の違いとかは(個人的には大事なのですが)伝わりづらいのは「それはそう…」(ﾙﾋﾞｰｶｲｷﾞという名前が「強い」ので…)
* 上の繰り返しになりますが「「地域Rubyコミュニティにとっての自分たちの"ﾙﾋﾞｰｶｲｷﾞ"」が地域Ruby会議」というスタンスは変わらない「Ruby会議」という名前を避ければ、混同は消滅するが、それは本意ではない
* といいつつ、「`#{Prefix}`Ruby会議」ではない名前でも「地域Ruby会議」としてもよさそう。良い例は思い浮かびませんが、たとえば"Ruby on Ales"みたいな「Ruby会議」という文字列が含まれていない地域Ruby会議があってもよい
* **既存の地域Ruby会議や、次回開催については、ホストする地域コミュニティの判断にお任せします**
* とうぜん愛着もあると思うので、**変えなくてもいいし、変えてもいい**

###  `#{Prefix}Ruby会議#{YYYY}` は気が進まない

* RubyKaigiとの混同を「減らす」が目的なので、 "[日本のRubyコミュニティについて一定の知識と経験が無い参加者が、RubyKaigi(開催に西暦年が振られる)と地域Ruby会議とを混同しないように配慮をお願いします](https://github.com/ruby-no-kai/official/wiki/Regionalrubykaigi#%E6%9C%AD%E5%B9%8Cruby%E4%BC%9A%E8%AD%B02012%E3%81%A8%E3%81%8B%E9%96%A2%E8%A5%BFruby%E4%BC%9A%E8%AD%B02017%E3%81%A3%E3%81%A6%E3%81%84%E3%81%86%E3%81%AE%E3%81%8C%E3%81%82%E3%82%8B%E3%81%91%E3%81%A9)" という認識から変わっていません(目的はRubyKaigiとの混同を避ける、なので)
* prefix-`#{YYYY}`は避けてほしいが、いっぽうで"01", "02"といった現在の規約(`"%02d" % count`)に **こだわらなくてもよい**
* 複数回、開催することになったときに `#{YYYY}` 以外でどうするのかな…というのは気になるけど、そこもホストコミュニティにお任せでよさそう

###  `"#{Prefix}地域Ruby会議"` の `Prefix` どうする問題(本丸)

* **`#{純粋地名}Ruby会議` じゃなくてもいいですよ、を基本としたい**
* が、`#{純粋地名}Ruby会議` でもいいですよ、という気持ちもあるので、命名規約よりはガイドラインを整備するほうがいいかなあという気持ち
* 東京は、TokyuRuby会議、大江戸Ruby会議、ぎんざRuby会議、TamaRuby会議、渋谷Ruby会議 といった「ユニーク」な名前がある
  * これは北米のRegional Ruby Conference っぽくてよい(北米は都市の愛称などを使った、Gotham、Lone Star、Mountain West、Nickel City、Windy City...みたいなのが多い(多かった))
  * https://rubyconferences.org/past/ このへんのバラエティは参考になるかも
  * いまとなっては「東京」にRubyKaigiは返ってこなさそうなので、むしろ「東京Ruby会議」はわかりやすいのだけれど「東京ぜんぶ」を引き受ける地域コミュニティが存在していなさそうなので(東京砂漠だ)、たまに「やりたい人がやる」かたちになってて、これはこれで興味ぶかい
 * 逆に「松江Ruby会議」は、松江にはRubyKaigiは行かなそう(RubyWorld Conferenceがおこなわれる"サンクチュアリ")なので、純粋都市名Ruby会議が「ユニーク」になっている(これはこれで興味ぶかい)

* 関西Ruby会議・九州Ruby会議(広域感がある)、札幌市中央区Ruby会議(ニッチな感じがよい)

 * 「地名」「地域名」じゃなくてもいいかも。ホストする地域Rubyコミュニティが愛着を持てるならいいんじゃない?
   * 「みなとRuby会議」はそういう観点からはいい感じだったかも
   * 地名じゃんくても、といって、**"#{企業名}Ruby会議"は悩ましい。絶対にだめ! とはいわないけれど…直接料金を徴収していないとしてもどうしても採用・広報の一環になるだろうし、実質商用利用では…という気持ちがある(紛争に類する話とかをしたいわけではない…くわしくないし…)**
  * 地名を使うといつかRubyKaigiとカブる可能性があるから「地名を使わないで」とは言いたくない
  * もちろん「カブるかもしれないから避けよう」という判断は尊重します

#### 😓  地域名に囚われていて見落していた(追記)

* 平成Ruby会議: 「元号」という切り口というか「平成.rb」が開催したやつだから、「地域Rubyコミュニティがホストするのが地域Ruby会議」という観点に照らすと、ネーミングとしては王道だな
* ここから「べつに『地域Ruby会議』は概念なんだから「suffix Ruby会議」じゃなくてもよくね?」まであと一歩だなあ

### (おまけ) RubyKaigi, Ruby会議, Ruby Kaigi 問題

* 混同を「減らす」という意味だと、だいたい国内で日本語話者向けの開催だろうし`#{Prefix}Ruby会議`という表記を推奨したい(ﾙﾋﾞｰｶｲｷﾞと言いたいなら)
* デザインとかで使うぶんには`#{Prefix}RubyKaigi`はよいと思います
* ちゃんとした文書とかでなければ、 (地域Ruby会議じゃない)The「RubyKaigi」のことを「Ruby会議」「Ruby Kaigi」と書かれていても、あんまりﾙﾋﾞｰｶｲｷﾞ警察はしなくていいか…という気持ち(機会があったらお伝えしていくのは良い心がけではある)

### (本筋ではないけど)るびまレポートの件

*「るびまにレポートを出してください」は、最近あんまりるびまも元気がないので、必須じゃなくしてもいいけど、そうするとたとえば講演者の交通費や、会場費用などの支援をRubyの会からおこなうときに、どういう基準で支援するかを考え直したりしないといけないなあ…と思ったり(るびまの話はまた別途、という感じですが)
  * 「レポートを書かせる」みたいな感じになるのも、うまくいったりいかなかったりなので、必須にするのは微妙だなあとも思ってます

### (さらに本筋ではないけど)他、開催まわりのいろいろ情報も古くなっている件

GitHubのWikiはurlはかっこいい https://github.com/ruby-no-kai/official/wiki/ んだけど、あんまり活用できてないので、
別の手段にしようかな〜と思ってます。

ただ、これから地域Ruby会議を開催するにあたっては、https://github.com/ruby-no-kai/official/issues/new で「シャウト」(やります!)と宣言する、という運用そのものは変えずにやっていきたいと思っています。

…やはりまとまりませんでした。いったんここで Submit new issue!

**Comment by kakutani** [comment]
* 福岡03の前にこのIssueをopenできれば良かったのですが…でも、Fukuoka.rbがホストするなら「福岡Ruby会議」でよさそう、と思ってます @jinroq 
* [てくてくラジオ ep.51](https://anchor.fm/tektek-radio/episodes/51--1-e1om4mc)で鹿児島02のウワサを聞いたので、ご参考まで(鹿児島02という名称に私は異論ありません) @kurotaky

**Comment by kurotaky** [comment]
ありがとうございます☺️

**Comment by kakutani** [comment]
### 🥇  現状のまとめ

**"原則: RubyKaigi #{YYYY}" と混同を避けられれば、何でもよい**

とはいえ、地域Rubyコミュニティとしては地域Ruby会議をホストするなら"#{prefix}Ruby会議"って言いたいよね。それを止めるものではありません(つまり、現状からあまり変わらないかも)。

kakutaniの気持ちとしては、地域Ruby会議は「日本Ruby会議2008」からforkしたものだから、正式名称のsuffixに"RubyKaigi"を使われることには気乗りがしないのだけれど、時は移ろうし、まあ個人の感想です…。

### 💭  気づいたこと

* 名前のこと: ["Fukuoka mruby Kaigi 2022"](https://www.digitalfukuoka.jp/topics/218)や"mruby/c kaigi"はあんまり混同しちゃう感がないのは、処理系の名前がついているからか。"#{runtime} kaigi"と2wrodになっているからか。そしてこれらは「地域Ruby会議」ではない、といいう認識(日本Rubyの会が支援するプロジェクトではない)
* 「地域Ruby会議」とは何なのか…となるけれど、https://github.com/ruby-no-kai/official/issues で開催をシャウトしてくれたら地域Ruby会議、という感じになるのかなあ
  * かつては「るびまにレポートを寄稿してもらう」ことで日本のRubyコミュニティとのつながりを記録する、というのを想定していたけれど、るびまも元気がないから、これも制約からは外す必要がありそう
  * 「地域のRubyコミュニティがホストしている」も実際のところは条件に含まれそうだけれど、「地域のRubyコミュニティ」の定義がふわっとしている(し、ふわっとしていてよさそう)
* 昔は「企業やよくわからない団体が『Ruby会議』を名乗って変なイベントをやられたらどうしよう」と心配していたことも背景にあったけれど、運よくいまのところ穏当に済んでいるので、「問題」は先送りになっている

**Comment by jinroq** [comment]
なんとなく「福岡 Rubyist 会議 03」にしたいな、という気持ちが湧いてきました。
字面は違えど発音は同じなので、RubyKaigi と Ruby 会議の違いを説明するのが面倒になってきたのと、PHPerKaigi の響きがいいなぁ、と思ったり。

**Comment by snoozer05** [comment]
> なんとなく「福岡 Rubyist 会議 03」にしたいな、という気持ちが湧いてきました。

Rubyist会議!! 素敵な響きだと思いました :-) 変える分には全然良さそうに感じましたが、そうするとナンバリングは01になるかな...?? （同名のイベントの01,02はまだ無いので）と思いましたが、その辺りをどうするか、ですかねぃ。01,02から名称を変えての03です、というのが説明されれば良いのかも？

**Comment by kakutani** [comment]
名前を変えることについては @jinroq の意向を優先でよいと思っています。
https://github.com/ruby-no-kai/official/issues/443#issuecomment-1309871322

> そうするとナンバリングは01になるかな...?? （同名のイベントの01,02はまだ無いので）と思いましたが、その辺りをどうするか、ですかねぃ。01,02から名称を変えての03です、というのが説明されれば良いのかも？

福岡のRubyコミュニティ(fukuoka.rbという理解でよいのかな)がホストするイベントとしての連続性はあるよ、ということであれば`03`が残してあっても良さそうとは思いました。

**Comment by udzura** [comment]
> Rubyist会議!! 素敵な響きだと思いました 

とてもagreeです。ナンバリングは私も03で行っちゃって良さそうと思いました。

**Comment by jinroq** [comment]
sudo mv `福岡 Ruby 会議 03` `福岡 Rubyist 会議 03`

実行します！

**Comment by kakutani** [comment]
https://scrapbox.io/ruby-no-kai/Regional_RubyKaigi を改訂したらclose可能…ッ

**Comment by kakutani** [comment]
(左手骨折の固定がとれたらやります…やる気はあるんだ本当なんだ信じてくれ〜)

**Comment by kakutani** [comment]
[Regional RubyKaigi/命名規約 \- ruby\-no\-kai](https://scrapbox.io/ruby-no-kai/Regional_RubyKaigi%2F%E5%91%BD%E5%90%8D%E8%A6%8F%E7%B4%84) ここを編集していこうと思います

**Comment by kakutani** [comment]
いったん書きました。closeできます

**Comment by kakutani** [comment]
@ruby-no-kai/directors というチームメンションをつかえるようにしたつもり…。有効になったかな??
