### ISSUE TITLE
rubykaigi.orgをホストしているlinode.comの料金を精算したい

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#45]
@kakutani が立て替えてます。1年ぶん。

**Comment by takahashim** [comment]
Invoiceとかと、あとできれば円建ての金額がわかる明細があるとよいのですが。

**Comment by kakutani** [comment]
318.94USDについて、交換レートが81.561で、実際に支払った額は、26,013JPY でした!

下記は @kakutani のクレジットカードの利用明細のキャプチャです。

 ![receipt](https://img.skitch.com/20120612-n6e5ifrhuxkju2dc9qbib564gu.png)

**Comment by kakutani** [comment]
振込先情報はお伝えしたつもり!

**Comment by takahashim** [comment]
振り込みました！

**Comment by kakutani** [comment]
ありがとうございます!
