### ISSUE TITLE
2013年開催 東京Ruby会議10 ウェブサイト移転に伴うDNS変更のお願い

### ISSUE THREAD

**Issue by bash0C7** [ruby-no-kai/official#450]
ご無沙汰いたしております。

[東京Ruby会議10ウェブサイト](http://tokyo10.rubykaigi.info/)はHeroku上で動かしていたのですが、プラン改定に伴って[Googleサイト]( https://sites.google.com/view/tokyo10-rubykaigi-info/)に移設して情報を引き続き残そうと思います。

これにあたってtokyo10.rubykaigi.infoの向け先をGoogleサイトに降ってもらうステップがあるので、対応にお付き合いいただけますでしょうか。

# 経緯

このrubykaigi.infoというドメインは、 かつて `http://qwik.jp/RegionalRubyKaigi/209.html` にて @kakutani の方でとっていただいたものでした。

```
[tokyo10.rubykaigi.info](http://tokyo10.rubykaigi.info/)

というドメインなら違和感が(私のなかでは)消失したので
[rubykaigi.info](http://rubykaigi.info/) というドメインを取るだけとりました。

ここから転送するというのはいかがでしょう?
```

# ステップ

Googleサイトのサイトに[カスタム ドメインを使用するヘルプ記事](https://support.google.com/sites/answer/9068867)にそって、DNS側、当Googleサイト側の双方で交代交代で操作が必要になると思います。

## 1. ドメインの所有権を証明する

rubykaigi.infoのDNSに、Googleサイトから指定のベリファイ用TXTレコードもしくはベリファイ用CNAMEを登録する必要があります。
登録内容は個別に受け渡しをさせてください。

## 2. 別の登録事業者で登録して自分が所有しているドメインを使用する

ドメイン所有権の証明を行わないと手段の確認からできないのですが、おそらく、このステップで何らかDNS側、Googleサイト側双方に指定する内容が出てくるものと考えています。

**Comment by kakutani** [comment]
おへんじ遅れました。現状、ドメインレジストラはvalue-domainなので、このDNS設定を変更すればよさそうですね。
いま見たら、「GOOGLE APPSで運用する設定」みたいなテンプレ設定もありました。
私宛におしえてもらえれば設定します〜。

**Comment by bash0C7** [comment]
ありがとうございます。少々お待ち下さい！

**Comment by bash0C7** [comment]
いましばしお待ち下さい。すいません

**Comment by bash0C7** [comment]
@kakutani 大変おまたせしてます。先程メールにて所有権確認のために設定いただきたいレコード情報をお送りしました。
よろしくお願いします。

**Comment by snoozer05** [comment]
@bash0C7 お手数ですが、再度こちらお送りいただいても良いでしょうか 🙇  info@ruby-no-kai.org 宛でお願いします...!!

**Comment by bash0C7** [comment]
すいませんリマインドいれそこなってました＆お返事おそくなりました。

@snoozer05 ありがとうございます。少々おまちくださいませ

**Comment by bash0C7** [comment]
@snoozer05 お待たせしてます。ご指定のメール宛に情報お送りしました。

**Comment by takahashim** [comment]
@bash0C7 連絡ありがとうございます、TXTレコードを追加してみました！

**Comment by bash0C7** [comment]
ありがとうございます。
現時点ではいきわたってないようなので、明日あたりに改めて確認します。

>ドメインの TXT レコードで確認トークンが見つかりませんでした。DNS の変更が反映されるまでに時間がかかる場合があります。しばらく時間をおいてから、Search Console でプロパティを再度開いてください。確認に再度失敗した場合は、別の DNS TXT レコードを追加してみてください。

**Comment by takahashim** [comment]
@bash0C7 あっとすみません、ミスっていたので修正してみました。これでどうでしょうか？

**Comment by bash0C7** [comment]
@takahashim ありがとうございます

>ドメインの TXT レコードで確認トークンが見つかりませんでした。DNS の変更が反映されるまでに時間がかかる場合があります。しばらく時間をおいてから、Search Console でプロパティを再度開いてください。確認に再度失敗した場合は、別の DNS TXT レコードを追加してみてください。

がでました。

dig打ってみるとこういうこたえが帰ってきたので、今一度ご確認いただけませんか

```sh
dig +noall +answer TXT tokyo10.rubykaigi.info 
```
>tokyo10.rubykaigi.info.	3315	IN	CNAME	tkrk10.herokuapp.com.
>tkrk10.herokuapp.com.	40	IN	CNAME	va02.ingress.herokuapp.com.

**Comment by takahashim** [comment]
むむ、ドメインじゃなくてホスト名で設定するんですね…（rubykaigi.infoの方にTXTレコードを追加してました）。すみません。ではいったんCNAMEレコードを消してTXTレコードを設定してみます！

**Comment by takahashim** [comment]
@bash0C7 `dig +noall +answer TXT tokyo10.rubykaigi.info` で返ってくるようになったはず…！

**Comment by bash0C7** [comment]
お待たせいたしております。

@takahashim ありがとうございます！これで所有権確認のステップが完了したので、続いて名前解決できるようにCNAME設定をお願いしたいです。

rubykaigi.info のDNS設定にて以下を願えますでしょうか。

![image](https://github.com/ruby-no-kai/official/assets/137741/213765a7-e6d1-4015-8be2-273576f5f955)

```
別のタブで、ドメイン登録事業者のウェブサイトにログインします
DNS 設定に移動します
新しい CNAME エントリを作成します
CNAME の値またはエイリアスの欄に「tokyo10」を入力します
CNAME の宛先の欄に「ghs.googlehosted.com.」（末尾のピリオドを含む）を入力します
変更を保存
```

**Comment by takahashim** [comment]
@bash0C7 設定してみました、（サイトは表示されないようですが）これでいいんでしょうか…？

```console
$ dig +noall +answer CNAME tokyo10.rubykaigi.info
tokyo10.rubykaigi.info.	3215	IN	CNAME	ghs.googlehosted.com.
```

**Comment by bash0C7** [comment]
設定ありがとうございます！

サイト側設定上はつながってる...はずなんですが、カスタムドメインでの表示されなかったので再確認してみます
![image](https://github.com/ruby-no-kai/official/assets/137741/e71e3d4b-be9c-4564-91e3-b2a4d5d5244d)
![image](https://github.com/ruby-no-kai/official/assets/137741/b9fc2580-bbd4-475b-80f8-e71382bf77ab)

**Comment by takahashim** [comment]
おっ、今見たら見れました！
<img width="703" alt="スクリーンショット 2024-02-26 22 43 59" src="https://github.com/ruby-no-kai/official/assets/10401/e194b2f0-21b1-4e40-a3dd-3395a054943f">

**Comment by bash0C7** [comment]
おおお、ありがとうございます！ https://tokyo10.rubykaigi.info/ 
おかげで過去情報をアーカイブとして残すことができました。
