### ISSUE TITLE
鹿児島Ruby会議02の開催

### ISSUE THREAD

**Issue by kurotaky** [ruby-no-kai/official#451]
鹿児島RubyコミュニティのK-Ruby方面からやってきました @kurotaky です。

https://twitter.com/kurotaky/status/1595704664795713536 でシャウトしましたが、
鹿児島Ruby会議02の開催を以下の要領にて計画しております!

名称に関しては 〇〇Ruby会議02のように変わる可能性があります。
https://github.com/ruby-no-kai/official/issues/448 の流れも読みながら考え中です💭 
(〇〇は薩摩とか唐芋とか良いかなあとか考えています)

名称: 鹿児島Ruby会議02
開催日: 2023/03/04 (土)
テーマ: Rubyに関係する何か (仮)
会場: [mark MEIZAN](https://mark-meizan.io/about) の予定
参加費: 0円
配信: なし
定員: 約 90 名
実行委員長: @kurotaky 
会計: 未定
スタッフ: K-Rubyメンバー + 色々調整中
るびまのレポート記事担当: 未定

前回のイベントサイトとissue👇 
- https://k-ruby.github.io/kagoshima-rubykaigi01/
- https://github.com/ruby-no-kai/official/issues/374

**Comment by kakutani** [comment]
お待ちしておりました!

> 名称に関しては 〇〇Ruby会議02のように変わる可能性があります。
> #448 の流れも読みながら考え中です💭
> (〇〇は薩摩とか唐芋とか良いかなあとか考えています)

変えてもいいし、変えなくても大丈夫です 😄 

どこかのタイミングで`events.yml`にも追加していただけると助かります
https://github.com/ruby-no-kai/regional.rubykaigi.org/blob/gh-pages/_data/events.yml

**Comment by kurotaky** [comment]
今回は `鹿児島Ruby会議02` でいきます！

**Comment by kakutani** [comment]
As you like! 異論ございません!

**Comment by kakutani** [comment]
* [ ] https://github.com/ruby-no-kai/regional.rubykaigi.org/blob/gh-pages/_data/events.yml#L449 にサイトへのリンクを `external_url` で追加する

まったく急ぎませんが、備忘のためコメントしておきます〜。

**Comment by kurotaky** [comment]
@kakutani @takahashim 
鹿児島Ruby会議02の準備を進めているのですが、2点ご相談があります 。

## 鹿児島Ruby会議02のスポンサー費用の振込みについて

スポンサー企業と金額が確定したらリストを共有しますので、
- 日本Rubyの会からK-Rubyメンバーの口座に振り込んでいただく (2月下旬)
- スポンサー企業から日本のRubyの会に振り込みをしていただく  (2月末または3月末期限)

という流れを、今回もお願いしたいです..! 🙏
前回 https://github.com/ruby-no-kai/official/issues/374#issuecomment-545214730 あたりでやり取りしていました。

## 招待講演について

Yuguiさんに招待講演をお願いしているのですが、メールでまだお返事頂けていない状況でして、
どなたか繋がりのある方がいましたらお声がけお願いしたいです..!!! 🙏 
https://gist.github.com/kurotaky/aae9a963805ececf92fb338f8a5d0a26 の内容をお伝えいただけると嬉しいです 📬

**Comment by amatsuda** [comment]
はー、Yuguiさんにはちょうどその1週間前のRuby 30周年で講演をお願いしてしまったところなので、翌週に基調講演ていうのが帯域的にちょっとどうか、というのはあるのかもしれないですねぇ https://30.ruby.or.jp/

**Comment by kurotaky** [comment]
なるほど... そうですね!
ちょうど今Yuguiさんから返信がありまして、参加が難しそうでしたので、別のプランを考えて動いてみます!

**Comment by snoozer05** [comment]
運営お疲れ様でした！

**Comment by kurotaky** [comment]
ありがとうございました！
