### ISSUE TITLE
RailsGirls 年間スポンサー費用請求(TokyoDev株式会社様) 

### ISSUE THREAD

**Issue by emorima** [ruby-no-kai/official#453]
TokyoDev株式会社様より、年間スポンサーのお申し込みがありましたので、
請求処理をお願いいたします。(2022年度、2023年度分のお申込みを頂きました)

TokyoDev株式会社様の情報は、メールにて共有させて頂きました。

 - [x] 請求書を作成する
 - [x] 請求書を送付する( @emorima )
 - [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
 - [x] スポンサー様からの入金を確認する

**Comment by takahashim** [comment]
こちらは今日中に請求書作りますね！（というかすでに準備しております）

**Comment by hsbt** [comment]
請求書を先方に送付した、入金してもらった、Ruby の会で確認した というステータス

next action: Ruby の会から RG 口座へ送金する

**Comment by snoozer05** [comment]
#469 のなかで対応済み
