### ISSUE TITLE
[Fukuoka03] PayPal ビジネスアカウントについて

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#454]
別 Issue で[共有](https://github.com/ruby-no-kai/official/issues/443#issuecomment-1379776740)した通り、connpass にて福岡 Rubyist会議 03 のチケット販売を考えています。
つきまして、connpass でチケット販売時に必要な PayPal ビジネスアカウントをお借りしたいです。
ご連絡は fukuoka03 at rubykaigi.org になりますか？

**Comment by takahashim** [comment]
@jinroq 了解です、fukuoka03 at rubykaigi.orgの方に投げておきますね

**Comment by takahashim** [comment]
これってアカウントを教えるだけで、パスワードとかトークンとかの認証っぽいやつはいらないんですよね…。
https://help.connpass.com/organizers/paid-event-edit.html
一回試してみないと正常に動作したかどうか分からなさそう？

**Comment by jinroq** [comment]
@takahashim 
不要そうに思えましたが、試してみます。共有ありがとうございます。

**Comment by jinroq** [comment]
https://fukuokarb.connpass.com/event/271949/
チケット販売を開始できました。ありがとうございます。

特に問題なければ本 Issue はクローズしていただいて問題ありません。

**Comment by takahashim** [comment]
@jinroq  PayPalのダッシュボードでも決済が行われていることを確認しました！
最初の1件か2件はテスト用のものですか？　であれば返金しますが、どうしましょうか。

**Comment by jinroq** [comment]
テストはしていません！ぶっつけ本番をぶちこみました。なので、返金は大丈夫です👌

**Comment by takahashim** [comment]
了解です！　では無事完了ということでissue閉じますね
