### ISSUE TITLE
Rails Girls 年間スポンサー費用請求(ピクシブ株式会社様)

### ISSUE THREAD

**Issue by thatblue** [ruby-no-kai/official#455]
@takahashim @springaki 

昨年よりRails Girls Japanのメンバーとなりました @thatblue と申します、よろしくお願いいたします。

ピクシブ株式会社様より2023年度分の年間スポンサーのお申込みを頂きましたので、請求処理をお願いいたします。
請求に必要な情報は別途メールにて共有させていただきます。

* [x] 請求書を作成する
* [x] PDFの請求書を送付する( @thatblue )
* [x] 請求書を郵送する
* [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
* [x] スポンサー様からの入金を確認する

**Comment by thatblue** [comment]
先ほどメールをお送りしました、よろしくお願いいたします。

**Comment by hsbt** [comment]
請求書を送った、というステータス

next action: 入金を確認する

**Comment by thatblue** [comment]
@takahashim @springaki

入金確認のリマインドです、お支払い期限が2月末だったのでそろそろ確認出来そうかな？と思っていました。
お手数ですがよろしくお願いいたします:bow:

**Comment by takahashim** [comment]
@thatblue 連絡ありがとうございます、入金確認できました。

**Comment by thatblue** [comment]
ご確認とご入金ありがとうございます！ Rails Girls Japan側の口座でも入金が確認できましたので、こちらはクローズします。
