### ISSUE TITLE
[Fukuoka03] 会場費追加費用支払い代行依頼

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#458]
会場リファレンス駅東ビル4階 会議室Q の追加費用支払いの代行を依頼させていただきたいです。
金額： ￥55,000 円
振込先はメールにて連絡させていただきます。

**Comment by takahashim** [comment]
了解です、こちらそれぞれ支払っていきます！

**Comment by takahashim** [comment]
会場費振り込みました

**Comment by takahashim** [comment]
@jinroq この辺のissueはお支払いしたら閉じていっていいでしょうか。それともそちらで確認されたら閉じる流れの方がよいでしょうか。

**Comment by jinroq** [comment]
@takahashim 振り込まれたことを先方に確認して、私の方でクローズにします。諸々ありがとうございます！

**Comment by takahashim** [comment]
ではそれでお願いします :pray:

**Comment by jinroq** [comment]
先方から振り込みの確認ができたとのことで、クローズします。
