### ISSUE TITLE
[Fukuoka03] キーノートスピーカー旅費支払い代行（そらはさん）

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#459]
そらはさんの福岡 Rubyist会議 03 の交通費・宿泊費の支払い代行を依頼したいです。
振込先は別途メールにて共有させていただきます。

**Comment by jinroq** [comment]
そらはさんがまだ振込先を教えてくれない…。

**Comment by sorah** [comment]
すみません… https://rubykaigi.esa.io/posts/1253 に乗っている内容でなんとか…………。

**Comment by kakutani** [comment]
@jinroq …というわけで、こちらで把握できるので金額がわかれば教えてください 😎

**Comment by sorah** [comment]
(いまから宿を取ります)

**Comment by sorah** [comment]
15-18滞在で確定させました。18日ちょっと早めに離脱しないといけなくて、Rubyist 交流機会をねらってちょっと前から福岡ふらつくつもりです。

- 振込先: RubyKaigi esa でも jinroq さんに DMした内容でも(同一)
- やど: 36,500円
- 飛行機:
  - 往路32,580円
  - 復路22,080円

領収書は全部PDFなんですがどうしよう? RubyKaigi の経費もたまってるし RubyKaigi Esa に通常通り記載してしまってもいいし、jinroq さん経由でも、Rubyの会がやりやすい方法で対応します。

**Comment by kakutani** [comment]
> 領収書は全部PDFなんですがどうしよう? RubyKaigi の経費もたまってるし RubyKaigi Esa に通常通り記載してしまってもいいし

このルートにして、会のほうでいい感じにやっておくのがスムーズそう!! (なので、RubyKaigiのほうのesaにいつもの感じでお願いします)

…というわけで、sorahのぶんはいい感じにやっておきます @jinroq

**Comment by sorah** [comment]
ではそうします。2023費用にいれとく

**Comment by sorah** [comment]
のせました https://rubykaigi.esa.io/posts/1253/revisions/11

**Comment by jinroq** [comment]
@sorah 振り込みが済んでいたら、本 Issue をクローズしてください。

**Comment by sorah** [comment]
うけとってます。起票者じゃなくて write access もないからとじれない…

**Comment by sorah** [comment]
あー、宿泊税が現金現地精算なんだった…それをあとでおねがいしなくてはいけない
