### ISSUE TITLE
[Fukuoka03] キーノートスピーカー旅費支払い代行（ぺんさん）

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#460]
ぺんさんの福岡 Rubyist会議 03 の交通費・宿泊費の振り込みをお願いしたいです。
振込先は別途メールにて共有させていただきます。

**Comment by takahashim** [comment]
旅費振り込みました

**Comment by jinroq** [comment]
振り込みを確認していただいたので、クローズします。
