### ISSUE TITLE
[Fukuoka03] スポンサー費用請求代行依頼

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#463]
福岡 Rubyist会議 03 のスポンサー費用請求の代行を依頼させていただきたいです。
請求先については別途メールにて共有させていただきます。

**Comment by jinroq** [comment]
@takahashim 
先ほど各スポンサー企業に請求書に関するメールを送信しました。
請求書の発行をお願いします。

**Comment by takahashim** [comment]
@jinroq 開催おつかれさまでした！

そして請求書についてですが、

* 金額は以前見せてもらったシートの金額
* 送付方法は（紙の郵送ではなく）メールにあるメールアドレスに送付

で良いでしょうか？

**Comment by jinroq** [comment]
@takahashim 

> 金額は以前見せてもらったシートの金額

金額を共有していなかったので、改めてメールにて共有させてもらいました。
ご確認のほど、よろしくお願いします。

> 送付方法は（紙の郵送ではなく）メールにあるメールアドレスに送付

こちらでよろしくお願いします。

また、請求が完了しましたら、高橋さんに本 Issue をクローズしてもらってもいいでしょうか？

**Comment by takahashim** [comment]
了解です、ではこちらの方は発送次第クローズしておきます！

**Comment by takahashim** [comment]
発送済みなので閉じておきます
