### ISSUE TITLE
[Fukuoka03] 宿泊費支援振り込み依頼（やんちゃさん）

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#467]
やんちゃさんの宿泊費の支援をしたいです。
宿泊費の振り込みの代行を依頼したいです。
詳細は別途メールにて共有させていただきます。

**Comment by jinroq** [comment]
@takahashim 
こちら 2/8 にメールを出していますが、ご確認いただけますでしょうか？

**Comment by takahashim** [comment]
すみません、確認できてませんでした！　こちら振り込みますね

**Comment by takahashim** [comment]
@jinroq 遅くなりましたが振り込みました 🙏

**Comment by jinroq** [comment]
振り込みを確認できましたので、本 Issue はクローズします。
