### ISSUE TITLE
Rails Girls 年間スポンサー費用請求(STORES 株式会社様)

### ISSUE THREAD

**Issue by thatblue** [ruby-no-kai/official#469]
@takahashim @springaki 

STORES 株式会社様より2023年度分の年間スポンサーのお申込みを頂きましたので、請求処理をお願いいたします。
請求に必要な情報は別途メールにて共有させていただきます。

* [x] 請求書を作成する
* [x] PDFの請求書を送付する( @thatblue )
* [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
* [x] スポンサー様からの入金を確認する

**Comment by thatblue** [comment]
請求書発行のご対応ありがとうございます、請求書PDFをSTORES様へお送りしました。
お忙しい中恐縮ですが、引き続き入金確認をよろしくお願いいたします。

**Comment by takahashim** [comment]
こちらも入金確認できました。
そして #453  #455 #456 と本件の分を合わせて振り込みました。ご確認ください。

**Comment by thatblue** [comment]
ご確認とご入金ありがとうございます！ Rails Girls Japan側の口座でも入金が確認できましたので、こちらはクローズします。
