### ISSUE TITLE
地域Ruby会議のレポートを送るための手順をofficial wikiに書く

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#47]
https://github.com/ruby-no-kai/official/wiki/Regionalrubykaigi に書くか、独立したページを用意する。

**Comment by kakutani** [comment]
実作業的には @sunaot が書いてくれてもぜんっぜん構わないんだけれど :)、
いちおう @kakutani にassignしておきます。

**Comment by kakutani** [comment]
とにかく書いた。https://github.com/ruby-no-kai/official/wiki/Regionalrubykaigi/_compare/a76e985b000c1ea71acfdc3bfd7c4844df6c19c9...262f9b6316770e40f4a1f3d7fbf09388aebce137

**Comment by sunaot** [comment]
こんなのあった！！！と思いつつ、追記しました。すみません、ありがとうございました！

**Comment by kakutani** [comment]
丁寧な追記、かたじけなし！ :whale:
