### ISSUE TITLE
Rails Girls 年間スポンサー費用請求(株式会社フィヨルド様)

### ISSUE THREAD

**Issue by thatblue** [ruby-no-kai/official#472]
@takahashim @springaki 

株式会社フィヨルド様より2023年度分の年間スポンサーのお申込みを頂きましたので、請求処理をお願いいたします。
請求に必要な情報は別途メールにて共有させていただきます。

* [x] 請求書を作成する
* [x] PDFの請求書を送付する( @thatblue )
* [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
* [x] スポンサー様からの入金を確認する

**Comment by thatblue** [comment]
@takahashim @springaki 

フィヨルド様より入金のご連絡を頂きましたので、お手すきの時にご確認いただけますと幸いです 🙇

**Comment by takahashim** [comment]
こちら入金が確認できました 🙆

**Comment by takahashim** [comment]
そして送金も行いました

**Comment by thatblue** [comment]
@takahashim 
早速のご確認と送金ありがとうございます！確認が取れましたらissueクローズさせていただきます 🙇

**Comment by hsbt** [comment]
RG 口座への振り込み確認しましたー

**Comment by thatblue** [comment]
ご対応ありがとうございました！全タスクが完了しましたのでこちらクローズします。
