### ISSUE TITLE
KeebKaigi後援のお願い

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#473]
RubyKaigi 2023の前日に、KeebKaigiというスピンオフ的なキーボード関係のミートアップを松本で開催したいと考えていま す。

* 名称: KeebKaigi 2023 ( https://keebkaigi.org/2023 )
* 日時: 2023/05/10 17:00 - 18:00 (tentative)
* 場所: 松本市内コワーキングスペース
* 規模: 30名程度
* 費用: 500円とか1,000円とかそんな感じ
* 内容: 著名キーボード設計者やRubyistによるキーボードとRubyにまつわるトークと、参加者同士の交流
* 目的: Rubyとキーボードのシナジ〜で、両方のコミュニティの可能性を押し広げたい! RubyKaigi参加者どうしが事前に交流できることで、会期の体験の質を高められると期待しています(RubyKaigiが捗る!)

準備は、RubyKaigi Teamとは若干重なりつつも別チーム( @swanmatch, @hasumikin, @takkanm, @kakutani )で進めています。以下のようなことが必要になるので日本Rubyの会の後援というかたちにさせてもらえると助かります!

* 会場の予約、費用の請求/支払
* 事前払いの参加費用の徴収になんらかのチケットシステムを利用したい
* スポンサー費用の請求/支払
* 他にもイベント準備に必要なことがあれば…

枠組みは地域Ruby会議の後援と同じような感じで大丈夫だと思います(ｷｰﾎﾞｰﾄﾞちほーの地域Ruby会議と考えることも可能…ッ??)。よろしくお願いします。

**Comment by kakutani** [comment]
Maciejが松本でKafkaとRubyのワークショップをやりたいそうなので(たぶん[Karafka](https://github.com/karafka/karafka) とかを扱うと思います。KeebKaigiが始まるまでの時間、同じ会場でKafkaとRubyについての小規模な集まりもできるといいんじゃないかという話をしています(会場は終日借りても価格は大きな差がないのと、半端に営業するよりはまるっと借りてしまったほうが先方としても都合がよさそうです)。

**Comment by takahashim** [comment]
これって企画としては2つ別々のものだけど、運営は1つでまとめてやるような理解で合ってますか…？

**Comment by kakutani** [comment]
> 運営は1つでまとめてやるような理解で合ってますか…？

* 本人から「Kafkaのワークショップやりたいんだが」みたいな相談が羽角さん(と松田さんもかな)に来た
* 場所のアテが特にない… → KeebKaigiの場所をつかえばいいんじゃね? 💡 

みたいな状況です。「運営を1つでやる」とまでやれるかどうかはわかんないですが、会場まわりのことは @swanmatch と連携して進めていくことになりそうです。@hasumikin は当日は午後到着予定だし、 @swanmatch はRubyKaigiの会場準備もいくらかはあるので、私が当日は松本でなんとかするか…みたいなのが現状決まっていることのすべてです…。Asakusa.rb の花見あたりで 🌸 で協力を仰げるといいかもしれない…。

**Comment by kakutani** [comment]
モンスターラボさんのロゴ利用申請が会から必要だったので(メールで申請)、 ruby-no-kai の私のメルアドから申請しました(infoにccするのを忘れていたので、事後報告)。

**Comment by kakutani** [comment]
請求/精算が発生しそうなので、適宜Issueにしていく。
このIssueは、開催がつつがなく終われば閉じる。他、なんか相談ごとがあればコメントします〜

**Comment by kakutani** [comment]
📝 継続(する?できる?)なら https://github.com/keebkaigi/keebkaigi.github.io/issues/28 という課題はある(ので、メモ)。

**Comment by kakutani** [comment]
(お知らせです) Peatixのチケット販売の受け取りが直接銀行口座に入金可能だったので、Rubyの会の口座を登録しました! @takahashim

**Comment by kakutani** [comment]
口座に謎のお金が入金されるかもという情報は高橋さん以外にもまとめてメンションしたほうがいいのでは? と思ったので @ruby-no-kai/directors というチームをつくってみました

**Comment by kakutani** [comment]
@takahashim 「KeebKaigi2023収支予算」というｽﾌﾟｼを共有させていただきました。
「振込依頼」というシート(左から2枚目)に、金額が確定して請求書が届いている(または精算が可能な)ものをリストしています。

振込先口座と金額、振込期限を記載しているので、振込いただいたら、「済」のところにチェックしていただけると助かります!
「請求書未着」のものについては、届き次第更新していきます。
よろしくお願いします。 /cc @swanmatch

**Comment by swanmatch** [comment]
@takahashim 
ノベルティキーキャップの請求書が届いたので共有のスプシに追記しました。
PDFの原本はSlackでお送りしました。

お手すきの際に振込をお願い致します:pray:

**Comment by takahashim** [comment]
こちらも振り込みました！

**Comment by hasumikin** [comment]
（こっちに書くのでいいのかな？）
ITOCしまねソフト開発センターさんのスポンサー費は5/31振り込み予定、との連絡をもらいましたので、ここに共有しておきます
ref https://github.com/keebkaigi/2023-team/issues/52

**Comment by swanmatch** [comment]
[情報共有]
ラムダノートさんの請求書はRubyの会に直接届いたようで、すでに高橋さんが支払い対応頂いたとのこと。
請求書のコピーは例のスプシに貼り付けて更新してあります。

**Comment by snoozer05** [comment]
ステータス: まだ請求の情報が一件きていないので、それを待っている状況

**Comment by kakutani** [comment]
@takahashim  KeebKaigiのスプシの「振込依頼」のシートに判明している振り込み先をすべて記入しました!!

そうだおもいだした。KeebKaigiの支援の件で、振込までやれたら負荷分散になるよな…というのが動機でした。 @pupupopo88 (お知らせまで)

**Comment by takahashim** [comment]
一通り振り込みました！

**Comment by springaki** [comment]
@kakutani が関係各位から諸々請求書をもらう

**Comment by kakutani** [comment]
最終残金の処理をやってないので、やるます

**Comment by kakutani** [comment]
請求書をつくってもらうように依頼しました。いただいたら会でvalidateしてもらおうとおもいます…!

**Comment by taea** [comment]
@takahashim ( cc @kakutani ) 

"KeebKaigi 2023 追加デザイン費用一式" として、合同会社esaよりメールで請求書お送りさせていただきました🙏
お手すきのときにご確認お願いします〜

**Comment by takahashim** [comment]
@taea ありがとうございます、先ほど振り込みました！

**Comment by kakutani** [comment]
は、早い…!! ありがとうございます！

**Comment by taea** [comment]
@takahashim @kakutani ありがとうございます！振込確認いたしました！確かにいただきました！ 🙏🏼

**Comment by kakutani** [comment]
さつそくの確認ありがとうございます！
