### ISSUE TITLE
大阪Ruby会議03の開催

### ISSUE THREAD

**Issue by honeniq** [ruby-no-kai/official#474]
Ruby関西 & Ruby Tuesday の宇佐美（@honeniq）と申します。
大阪Ruby会議03の開催を計画しています。

名称: 大阪Ruby会議03
開催日: 2023年9月9日(土)
会場: ハートンホテル心斎橋 松風ホール
実行委員長: @honeniq
レポーター: 未定
スタッフ: 未定
会計: @ogom Ruby関西
参加費: 未定
配信: 未定
定員: 150名程度 ※01・02の実績より

上記のとおり、まだ日程くらいしか決まっていません。 🌸 
01・02の実行委員長だった おごもりさん（@ogom）にサポートいただきつつ、準備を進めていきたいと思います。

こちらでも諸々ご支援頂くことになるかと思いますので、よろしくお願いいたします。

**Comment by kakutani** [comment]
@honeniq シャウトありがとうございますー。 経験者のサポートがあるのは心強いですね。
 Issueでも相談してもらって構わないのですが、もっと雑に相談したいときは日本Rubyの会のDiscordサーバーのチャットでお気軽にお声かけください〜  👾 
https://discord.gg/ygbBBKuzuH
( #regional-rubykaigi-orgz のチャンネルです)

**Comment by ogom** [comment]
@honeniq 
[大阪Ruby会議03](https://rubykansai.github.io/osaka03/) URLの転送設定の追加をお願いします。

大阪Ruby会議02 の PR を参考に PR を作成してください。
https://github.com/ruby-no-kai/rko-router/pull/53

**Comment by kakutani** [comment]
> 大阪Ruby会議02 の PR を参考に PR を作成してください。

こちら ruby-no-kai/rko-router#94 でdeploy済です(おしらせ)

**Comment by kakutani** [comment]
請求業務は @takahashim がやってくれた

**Comment by ogom** [comment]
@takahashim @kakutani 
ありがとうございます。

おかげさまで申し込みサイトがオープンできました。そして、たくさんの申し込みがあって嬉しいです。
https://rubykansai.doorkeeper.jp/events/158794

**Comment by takahashim** [comment]
お金周りについて経過報告:

- 1件請求書をもらったので先ほど振り込みました
- 9月にもう2件ほど対応する予定です

**Comment by honeniq** [comment]
おかげさまで、大阪Ruby会議03が無事開催できました。
参加申込み175名中141名にご来場いただき、大盛況でした。
反省点は色々ありますが、ひとまずホッとしています。

後日、実行委員で集まって振り返り兼打ち上げを行い、レポートも作成する予定です。

@kakutani 
会場でもお声掛けいただきありがとうございました！

**Comment by takahashim** [comment]
開催おつかれさまでした！

会場費が追加で発生したとのことなので、その分の請求はRubyの会の方で開催支援として支払います。

**Comment by snoozer05** [comment]
状況がわからなくなってしまったので、残しつつ、状況を掘り起こすところから

**Comment by snoozer05** [comment]
まだ

**Comment by ogom** [comment]
@snoozer05 
連絡が遅くなり申し訳ございません。
大阪Ruby会議03 のメンバーに確認したところ、会場費が追加で発生した件については対応して頂いております。
その他も残のタスクは無い状況の認識です。

なに確認されたい状況はありますか？
もしかして、issues がクローズされていないことで、確認されているのでしょうか？

**Comment by snoozer05** [comment]
@ogom まだ入金が確認できていないスポンサーさんがおりまして...そのためにまだ開いている状況でございます...!!

**Comment by ogom** [comment]
@snoozer05 スポンサー様から未入金の状態があるのでしょうか？

**Comment by snoozer05** [comment]
@ogom お返事できておらず申し訳ないです。はい、1社スポンサーさんからの入金が確認できておらず確認している状態なのでした...継続的に確認していますので、進捗あればこちらで共有させていただきます...!!

**Comment by kakutani** [comment]
(請求書を再送付した)

**Comment by pupupopo88** [comment]
@honeniq @ogom 
お待たせしました(?)、入金確認できましたのでcloseします 🙌
