### ISSUE TITLE
`kaigionrails.org`のDNSを自分達で管理したい

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#475]
kaigionrails.orgのDNS管理について相談があったのでこちらに転記しておきます。

----

## なぜやるのか

現在、 kaigionrails.org のDNS recordは https://github.com/ruby-no-kai/dns で管理されています。ここで管理することによるデメリットとして、ruby-no-kai側の誰かによるapproveが必要であるという問題があります。

この一手間は、 `[WIP] rfc/Herokuから別のPaaSに移行したい` にも関連してきますが、新しいWebアプリ、Webページを公開する際にKaigi on Rails teamにコミュニケーションが閉じないので若干の時間がかかってしまいます。

## なにをするのか
複数人で管理できるDNSに移行します。第一候補はCloudflareです。

### Cloudflareに移行する理由

* 50ユーザーまで無料
    * DNSに関しても無料(制限に関しては不明)
* 今後、公式サイトをCloudflare Pagesに移行するとなったとき都合が良い
    * managed DNSを提供しているIaaSで静的サイトホスティングを提供しているのは、他にはAWSとGCPくらいしかない(と思っている)

### やらないこと
Domainそのものの移管は行わず、NSをCloudflare DNSに向けるのみとする。

### デメリット
IaCでなくなる(GitHubを見ればどのようなDNS recordが設定されているのかがわかる状態になっていたが、そうでなくなる)

**Comment by kakutani** [comment]
* 提案どおりCloudflareに移行してもいいです
* ruby-no-kai/dns でマージできるように kor.org チームの人を加えてもよいです

お好きな方法でどうぞ!

**Comment by unasuke** [comment]
> 提案どおりCloudflareに移行してもいいです

ではCloudflareに移行する方向で作業を進めようと思います！

**Comment by kakutani** [comment]
必要なことがあれば、このIssueかDiscordでお気軽に〜
👾  https://scrapbox.io/ruby-no-kai/Discord

**Comment by snoozer05** [comment]
📝 このissueはCloudflareに移ったことを確認して閉じる

**Comment by unasuke** [comment]
Cloudflare側から移行完了の通知が来たので、クローズできる状態になりました。手助けいただきありがとうございました。

**Comment by kakutani** [comment]
こちらこそお手間取らせてしまいました(遅くなってすみません)。引き続きよろしくお願いします!
