### ISSUE TITLE
TokyuRuby会議14の開催(retry)

### ISSUE THREAD

**Issue by ginkouno** [ruby-no-kai/official#476]
こんばんは、Tokyu.rbの河野 です。

2020年に延期とさせて頂いたTokyuRuby会議14ですが、
以下のように開催を計画しています。

名称：TokyuRuby会議14
開催日：2023年7月29日(土)
会場： 株式会社Speee 会議室
参加費： 未定
配信：なし
定員： 未定(100人程度を想定)
実行委員長： 河野　誠
司会：小川 伸一郎
会計： 未定
るびま記事担当： 未定
他スタッフ： 
大場光一郎
小椋隆史
小田切わか菜
関学
多田亜希
三浦美咲樹

会場は未定でして、もし決まらなかった場合は10月29日(土)へのスライドなども考えております。
まずは日程確保のため、Issueを立てさせて頂きました。
どうぞよろしくお願いいたします。

**Comment by kakutani** [comment]
@ginkouno 🥳🍻 前スレである #378 は閉じてもよいでしょうか?

**Comment by ginkouno** [comment]
はい、閉じて頂ければ :pray:
お手数をおかけいたします。

**Comment by kakutani** [comment]
> 会場は未定

企業さんからの会場提供を受けるのは悩ましそうですよね…(提供する側が)。
うまく会場が見つかるよう応援しています!!

**Comment by kurotaky** [comment]
@ginkouno @kakutani 
もし渋谷(東急の渋谷駅近く)で良ければ会場提供出来るかもです。確認しておきましょうか❓飲食オッケーだと思います。

**Comment by kakutani** [comment]
(私は特に意見はないので、お任せします! @ginkouno )

**Comment by kurotaky** [comment]
ruby-jpのtokyurbチャンネルにも参加したので、気軽にお声掛け下さい〜 🙋

**Comment by ginkouno** [comment]
おお、ありがとうございます！
ruby-jpの方でご相談させて頂きます 🙏

**Comment by ginkouno** [comment]
会場ですが、最初に交渉中だったSpeee社様の会場をお借りすることになりました。
ご協力ありがとうございました！

**Comment by ginkouno** [comment]
TokyuRuby会議14でスポンサーを募ろうと思っております。

声をかけるのはこれからなのですが、もしご支援頂ける会社さんが現れた場合、
お金のやりとり周りをご支援頂きたく。

以下 @kakutani さんに相談させて頂いた内容ベースなのですが、

- Rubyの会に請求書を発行頂き、スポンサーさんからの入金先をRubyの会にしてもらう
- TokyuRuby会議でかかった経費をレシートとかで取っておき、それをRubyの会に提出して、実費でRubyの会から頂く

といった流れでよろしかったでしょうか？

また2023/07末実施なので、2023/08末を入金期限とし、その後精算させて頂ければと考えております。

ご支援頂けるかどうかおよび、
可能であった場合は必要な手続きや情報、どなたに窓口をお願いすればよいか等、教えていただけましたら幸いです :pray:

**Comment by kakutani** [comment]
> といった流れでよろしかったでしょうか？

はい、基本的にはそんな感じです!

**Comment by ginkouno** [comment]
ご確認ありがとうございます！

早速ですが、スポンサー様2社が確定しました。
2023/08末付発行、2023/09末期限の請求書の発行をお願い致したく思いますが、
そのために必要な情報と、その情報の投げ先(このIssueにぶら下げていいのか、あるいは誰かにmailするのかなど)を教えて下さい！

**Comment by takahashim** [comment]
https://scrapbox.io/ruby-no-kai/Regional_RubyKaigi%2F%E8%AB%8B%E6%B1%82%E6%83%85%E5%A0%B1 この辺の情報を `info [atmark] ruby-no-kai.org` あたりに投げていただければ…！（請求書送付先の具体的な情報は非公開の方がよいかと思うので）

**Comment by ginkouno** [comment]
承知しました！後ほど送らせて頂きます 🙏

**Comment by takahashim** [comment]
スポンサー請求についてのRubyの会でのTODO:

* [x] スポンサー費用を請求する(8月末付)
* [ ] 入金を確認する
* [x] 請求額を振り込む

**Comment by publichtml** [comment]
@takahashim
スポンサーさまからの入金確認できていますでしょうか？
Tokyu 側の振込先は 10/24 にメールでお知らせしていますが、再度情報必要ならばお知らせください。

**Comment by snoozer05** [comment]
TODO @takahashim が後で入金確認をする

**Comment by takahashim** [comment]
@publichtml 遅くなってしまって失礼しました、入金はまだ一部確認できていないものがあるようなのですが、それはさておき請求額については先ほどお振込みしました。お待たせしてしまってすみませんでした。

**Comment by publichtml** [comment]
@takahashim 指定通りの額が無事振り込まれていることを確認しました。ありがとうございます。
入金確認などの残作業、お手数ですがよろしくお願いいたします 🙏 
もし Tokyu 実行委員側で対応した方がいいことがあれば (スポンサー様への確認など)、お知らせください。

**Comment by snoozer05** [comment]
閉じます！お疲れ様でした！
