### ISSUE TITLE
Rails Girls 年間スポンサー費用請求(GMOペパボ株式会社様)

### ISSUE THREAD

**Issue by thatblue** [ruby-no-kai/official#477]
@takahashim @springaki 

GMOペパボ株式会社様より2023年度分の年間スポンサーのお申込みを頂きましたので、請求処理をお願いいたします。
請求に必要な情報は別途メールにて共有させていただきます。

* [x] 請求書を作成する
* [x] PDFの請求書を送付する( @thatblue )
* [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
* [x] スポンサー様からの入金を確認する

**Comment by thatblue** [comment]
@takahashim @springaki

こちらの件ですが、お支払い期限が5月末だったのでそろそろ確認出来そうかな？と思い、リマインドでした。
お手数ですがよろしくお願いいたします🙇

**Comment by takahashim** [comment]
@thatblue 入金を確認しました！

**Comment by thatblue** [comment]
@takahashim ご確認ありがとうございます、承知しました！
