### ISSUE TITLE
Rails Girls 年間スポンサー費用請求(株式会社えにしテック様)

### ISSUE THREAD

**Issue by thatblue** [ruby-no-kai/official#481]
@takahashim @springaki

株式会社えにしテック様より2023年度分の年間スポンサーのお申込みを頂きましたので、請求処理をお願いいたします。
請求に必要な情報は別途メールにて共有させていただきます。

- [x] 請求書を作成する
- [x] PDFの請求書を送付する(@thatblue)
- [x]  Rubyの会からRailsGirls-JPに立替請求分を送金する
- [x] スポンサー様からの入金を確認する

**Comment by thatblue** [comment]
@snoozer05 @takahashim @springaki 
こちら、えにしテック様から明日(6/13)付で入金手続き済みとのご連絡をいただいております。
お手すきのタイミングで入金をご確認いただければと思います。

**Comment by takahashim** [comment]
@thatblue 入金を確認できましたので送金しました！
