### ISSUE TITLE
Ruby Hack Challenge Holiday in 福岡 の支援についてのご相談

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#483]
## 概要

[Ruby Hack Challenge](https://rhc.connpass.com/) を福岡で開催するにあたり、笹田さんと遠藤さんをお招きしたいと考えています。
その際のおふた方交通費をご支援していただけないか相談させていただきたいです。

## Ruby Hack Challenge Holiday in 福岡 について

* 日時： 2023/08/05（土） 13:00〜17:00
* 場所：株式会社 Ruby 開発福岡オフィス 5F
* 募集予定人数： 10 名程度（参加者が多い場合は別途会場を探します）

![connpass イベントページ下書き 1](https://github.com/ruby-no-kai/official/assets/2787780/d7e9f12c-1924-439d-92d9-fc37e4ad929f)

![connpass イベントページ下書き 2](https://github.com/ruby-no-kai/official/assets/2787780/4d9e396c-2ed0-494a-8764-4f40337f890a)

### なぜやるのか？

私は Fukuoka.rb というコミュニティの運営に 2018 年から携わっていますが、「コミュニティ活動だけではなく、もっと実用的な Ruby への貢献はないだろうか？」と常々考えていました。
そんな中、Ruby Hack Challenge の存在を知り、「福岡から ruby 本体にコントリビュートできる人材を育成する場が欲しい」と思い 2020 年頃から[構想は練っていた](https://speakerdeck.com/jinroq/fu-gang-falsefang-karacan-rimasita-fukuoka-dot-rb-desu?slide=37)ものの、コロナ禍で開催を見送っていました。
また、Fukuoka.rb はプログラミング初学者でも歓迎する場としていますが、本イベントでは中級者から脱却したいプログラマーの足がかりになるようにする予定です。

### ご支援いただきたい理由

当初、私が所属する企業に交通費・宿泊費を依頼する想定でした。が、弊社決算期は 6 月と思っていたところ 8 月であったため、予算が確保できませんでした。
また、笹田さん遠藤さんが所属されている企業から交通費・宿泊費を出していただくのが大変難しい状況であるため、ご支援していただけないか相談させていただきたいです。

**Comment by takahashim** [comment]
はい、良いかと思います！！

**Comment by kakutani** [comment]
> * 募集予定人数： 10 名程度（参加者が多い場合は別途会場を探します）

せっかくだからもうちょっと参加者が増えるといいですね! (8/5はとちぎに行くから行けないな…)

**Comment by jinroq** [comment]
@takahashim 
ありがとうございます。笹田さんと遠藤さんには旅費が確定次第、共有していただけるよう連絡しておきます。

@kakutani 
どの程度の人が集まるのか全然読めない && 弊社オフィスのキャパがそのくらい、という事情があったりします。
人数が増えるようでしたら、広めの会場を探します。

**Comment by kakutani** [comment]
🙌  https://connpass.com/event/286145/

**Comment by jinroq** [comment]
@takahashim 
笹田さんの領収書についてメールにて連絡しましたので、ご確認のほどよろしくお願いします。
※遠藤さんは急用ができてしまったため、今回は不参加となりました。

**Comment by jinroq** [comment]
@takahashim 

https://github.com/ruby-no-kai/official/issues/483#issuecomment-1666539128
こちらのメールはご確認いただけたでしょうか？

**Comment by takahashim** [comment]
@jinroq はい、確認しましたがまだ対応しておりません（すみません！）。もう少しお待ち下さい

**Comment by takahashim** [comment]
@jinroq 先ほど振込対応いたしました！

**Comment by ko1** [comment]
振込確認しました。ありがとうございます。

**Comment by jinroq** [comment]
@takahashim
対応ありがとうございました。本 Issue はクローズします。
