### ISSUE TITLE
Rails Girls 年間スポンサー費用請求(株式会社スタメン様)

### ISSUE THREAD

**Issue by thatblue** [ruby-no-kai/official#488]
株式会社スタメン様より2023年度分の年間スポンサーのお申込みを頂きましたので、請求処理をお願いいたします。
請求に必要な情報については、別途メールにて共有させていただきます。

- [x] 請求書を作成する
- [x] PDFの請求書を送付する(@thatblue)
- [x]  Rubyの会からRailsGirls-JPに立替請求分を送金する
- [x] スポンサー様からの入金を確認する

**Comment by takahashim** [comment]
@thatblue こちらの件、先ほど入金確認できましたので送金しました！

**Comment by thatblue** [comment]
ご連絡ありがとうございます、承知しました！
