### ISSUE TITLE
Rails Girls Matsue 5thのスポンサー費用請求

### ISSUE THREAD

**Issue by thatblue** [ruby-no-kai/official#489]
11/11に開催されたRails Girls Matsue 5thのイベントスポンサー様への協賛費用請求処理をお願いいたします。  
請求に必要な情報は、別途メールにて共有させていただきます。

- [x] スポンサー様に請求する(PDF送付: @thatblue)
- [x] Rubyの会からRailsGirls-JPに立替請求分を送金する
- [x] スポンサー様からの入金を確認する

**Comment by thatblue** [comment]
@takahashim 
ご連絡が遅くなり申し訳ありません、イベントスポンサー様のうち、株式会社トラストソフトウェア様につきまして12/13付けでご入金頂いたとのことで、お手すきの際に入金のご確認をお願いいたします。

**Comment by snoozer05** [comment]
TODO @takahashim 送金処理と入金の確認をする

**Comment by takahashim** [comment]
確認が遅くなりました、トラストソフトウェアさんの入金は確認できました。残りの会社さんの分はまだ入金されていないようでした。

**Comment by thatblue** [comment]
@takahashim 
ありがとうございます、私の方も確認が遅くなってしまい申し訳ありません。
トラストソフトウェア様の入金確認が出来た件、承知しました :bow:

**Comment by takahashim** [comment]
@thatblue お待たせいたしました、残りの会社さんについても入金が確認できました！

**Comment by thatblue** [comment]
@takahashim 承知しました、ご確認ありがとうございます！
