### ISSUE TITLE
福岡 Rubyist会議 04 の開催について

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#490]
Fukuoka.rb の尾田です。
掲題の通り、開催を予定して準備を進めています。
つきましては諸々ご協力を仰ぐことになると思いますので、よろしくお願いします。

--

名称：福岡 Rubyist会議 04
開催日：2024 年 9 月 7 日（土）
会場：リファレンス駅東ビル
参加費：2,000円〜3,000円
配信：なし
定員：120 名程度
実行委員長：尾田（@jinroq）
会計：ta
レポート：nagachika

**Comment by jinroq** [comment]
@snoozer05 

https://github.com/ruby-no-kai/regional.rubykaigi.org/pull/140
この PR をマージしたのですが、画像素材と CSS が[上手く読み込めていません](https://regional.rubykaigi.org/fukuoka04/)。
時間を置いたらいい感じに適用されるものでしょうか？

**Comment by jinroq** [comment]
@snoozer05 

https://github.com/ruby-no-kai/official/issues/490#issuecomment-1938644595
こちら単純に参照のパスがミスってそうなので、こちらの方で対応します。失礼しました。

**Comment by jinroq** [comment]
開催まで約二ヶ月前となったのでそろそろ残タスク整理。

- 7 月上旬〜中旬：チケット販売開始
- 7 月中旬〜下旬：タイムテーブル公開
- 7 月のどこか：パネルディスカッションのトークテーマをパネラー達と揉む
    - @jinroq が草案を作って各パネラーに相談する
- 09/07 カンファレンス開催

**Comment by jinroq** [comment]
支払い関連（各 Issue を立てる）

- [x] 会場費支払い代行（ #503 ）
- [x] 主催企業からの会場費の振り込み（ #504 ）
- [x] チケット販売サイトオープン
    - [x] チケット販売用 ~~Stripe~~ PayPal アカウントを借りる（  ~~#506~~ #507 ）
- [x] 懇親会用サイトオープン（ #509 ）
    - [x] 懇親会用 PayPal アカウントを借りる
- [x] キーノートスピーカ旅費支払い代行
    - [x] かねこさん
- [x] 謝礼金支払い代行
    - [x] デザイナー
    - [x] 八女茶
- [x] ノベルティー代（ #510 ）

**Comment by jinroq** [comment]
非常に今さらなのですが、外部との連絡手段として fukuoka04 at rubykaigi.org を作成していただきたいです。
jinroq at gmail のみ登録をお願いします。

**Comment by kakutani** [comment]
@jinroq 
> 非常に今さらなのですが、外部との連絡手段として fukuoka04 at rubykaigi.org を作成していただきたいです。

テストメールをおくってみました。届きました??

**Comment by jinroq** [comment]
@kakutani 
はい、届きました！ありがとうございます！

**Comment by jinroq** [comment]
残タスクすべて終わりましたので本 Issue をクローズします。
今回もご助力ありがとうございました。
るびまは別途出します。
