### ISSUE TITLE
Rails Girls 年間スポンサー費用請求(ピクシブ株式会社様: 2024年度分)

### ISSUE THREAD

**Issue by thatblue** [ruby-no-kai/official#492]
@takahashim @springaki 

ピクシブ株式会社様より2024年分の年間スポンサーのお申込みを頂きましたので、請求処理をお願いいたします。
請求に必要な情報は別途メールにて共有させていただきます。

- [x]  請求書を作成する
- [x]  PDFの請求書を送付する(@thatblue)
- [x]  Rubyの会からRailsGirls-JPに立替請求分を送金する
- [x]  スポンサー様からの入金を確認する

**Comment by thatblue** [comment]
@takahashim @springaki 
入金確認のリマインドです 🙇 
こちら、お支払い期限が3月末だったのでそろそろ入金確認が出来そうかなと思っておりました。
年度初めのお忙しい頃に恐縮ですが、お手すきの際にご確認いただければと思います！

**Comment by takahashim** [comment]
@thatblue お待たせしました、各社さんからの入金を確認できました！

**Comment by thatblue** [comment]
@takahashim 
ご確認ありがとうございます、承知いたしました！
