### ISSUE TITLE
一般社団法人の銀行口座を開設する

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#5]
今まで使っていた口座は任意団体用なので、新しく法人としての口座を用意する（銀行印は購入済）。

**Comment by kakutani** [comment]
三井住友で高橋さんが口座を開いてくれることになった。

**Comment by takahashim** [comment]
三井住友銀行に申し込みに行きました。現在審査中です。

**Comment by takahashim** [comment]
どうも妙に時間がかかったようですが、銀行から連絡があり口座は作れそうとのことです。要資料提出（活動実体を表すものということでサイトのコピーとかが必要そう）。

**Comment by kakutani** [comment]
すすんでる!

**Comment by takahashim** [comment]
超遅くなりましたが開設されました！
ちなみにカードが受け取れるのは来週になります。
