### ISSUE TITLE
TokyuRuby会議15の開催

### ISSUE THREAD

**Issue by kishima** [ruby-no-kai/official#500]
こんにちは、Tokyu.rbの影山です。
昨年に続きTokyuRuby会議15の開催を以下のように現在計画しております。

名称：TokyuRuby会議15
開催日：2024年9月29日(日)
会場：GMO Yours フクラス
参加費： 無料
配信：なし
定員： 未定(100人未満程度を想定)
実行委員長： 影山　勝彦
司会：小川 伸一郎
会計： @u1tnk
るびま記事担当： @shokola
他スタッフ：
@smallmonkey117
@akmhmgc
関学
大場光一郎
多田亜希

まず日程確保のためにIssueを立てさせていただきました。
会場やスタッフ等はアップデートありましたが、随時ご連絡したいと思います。
よろしくお願いいたします。

**Comment by kurotaky** [comment]
会場の下見のタイミングが決まったら、教えて下さい〜 🙋

**Comment by kishima** [comment]
@kurotaky 遅くなってすみません。６月中旬以降でお願いできればと考えています。詳細はまたDM致します！

**Comment by kishima** [comment]
会場をGMOペパボ様から貸して頂けることなりましたので、スタッフと合わせて概要更新しました。

**Comment by kishima** [comment]
今回も前回 #476 と同様にスポンサー様を募りたいと考えております。
2024/9末発行、2024/10末入金期限の請求書をRubyの会から発行していただく形をとれればと思いますが、前回同様にフォームからご依頼させていただく形で問題ないでしょうか？
https://scrapbox.io/ruby-no-kai/Regional_RubyKaigi%2F%E8%AB%8B%E6%B1%82%E6%83%85%E5%A0%B1

**Comment by takahashim** [comment]
@kishima はい、それでお願いします！

**Comment by kishima** [comment]
@takahashim 承知しました！

**Comment by kakutani** [comment]
TokyuRuby会議運営の皆さまへ。サイトの準備できたタイミングでregional.rubykaigi.orgのevents.ymlにpull-reqしてもらえるとうれしいです〜(やっておきました):

https://github.com/ruby-no-kai/regional.rubykaigi.org/blob/8b88a8b9422b1f86208ea54a91a56a8d06e53ff4/_data/events.yml

**Comment by u1tnk** [comment]
さきほど  info[atmark]ruby-no-kai.org のメールアドレスに
https://github.com/ruby-no-kai/official/issues/500#issuecomment-2161971286

の内容を送付させて頂きました。
期限が明日になってしまい、ギリギリで申し訳無いのですがご対応宜しくお願いします 🙏

**Comment by u1tnk** [comment]
@takahashim 
上記の請求書の件ですが、どうでしょうか？
こちらの依頼が遅くて申し訳無いのですが、先方に連絡する必要があるので、いつ頃になるのかだけでも分かると助かります 🙏

**Comment by takahashim** [comment]
@u1tnk こちら対応済みのはずです！　詳しくは後ほど。

**Comment by u1tnk** [comment]
@takahashim 
良かったです！ ご対応ありがとうございました。

**Comment by takahashim** [comment]
遅くなりましたが先ほど領収書類を受け取りました！

**Comment by pupupopo88** [comment]
スポンサーさんからの振り込みも全て完了しているのを確認しました！
これで残作業ないと思うのでcloseしますね 🙋‍♀️ 

お疲れ様でした 🎉

**Comment by u1tnk** [comment]
@takahashim @pupupopo88 
了解しました。
完了までご対応頂きありがとうございました！ 🙏

**Comment by kishima** [comment]
ご協力いただいた皆様、本当にありがとうございました！
無事楽しく終えることができてよかったです。
実行委員長はまた変わっていくかと思いますが、今後ともよろしくお願いいたします！
