### ISSUE TITLE
[Fukuoka04] 会場費支払い代行依頼

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#503]
会場リファレンス駅東ビル4階 会議室Q の会場費支払いの代行を依頼させていただきたいです。
金額： ￥215,380 円
振込先はメールにて連絡させていただきます。

**Comment by jinroq** [comment]
@takahashim 

先ほどメールをお送りしましたので、ご確認ください。

**Comment by takahashim** [comment]
こちらは了解です、振り込んでおきます！

**Comment by takahashim** [comment]
@jinroq 振込完了しました（西日本シティ銀行の方の口座です）

**Comment by jinroq** [comment]
@takahashim 
ありがとうございます！会場側からも振り込みの確認の連絡がきましたので、本 Issue はクローズします。
