### ISSUE TITLE
[Fukuoka04] 主催企業からの会場費の振り込み

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#504]
主催企業である株式会社Ruby開発から会場費の一部を日本 Ruby の会宛に振り込みます。
振り込み予定金額： 100,000 円
日本 Ruby の会の振り込み先の確認は別途メールにて行います。

**Comment by jinroq** [comment]
リマインダ：早く稟議書を書く

**Comment by jinroq** [comment]
@takahashim 

メールをお送りしましたのでご確認をお願いします。
（稟議は通りました！）

**Comment by takahashim** [comment]
こちらも確認しました、このやりとりについては書面もあった方が良さそうなので、詳細はメールしますね

**Comment by jinroq** [comment]
@takahashim 
ご連絡ありがとうございます！
社用メールから必要な情報はお送りしましたのでご確認をお願いします。

**Comment by jinroq** [comment]
@takahashim こちら弊社から振り込まれていますでしょうか？振り込まれているのであれば本チケットはクローズします。

**Comment by pupupopo88** [comment]
@jinroq 入金確認できました💰 のでcloseします！
