### ISSUE TITLE
[Fukuoka04] チケット販売に関するご相談

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#505]
福岡 Rubyist会議 04 の参加は有料にする（販売価格 4,000 円を予定）予定ですが、チケット販売をするにあたり以下の相談をさせていただきたいです。

- チケットはどこから販売する？
    - RubyKaigi 2024 で高橋さんに相談させてもらった際は「全部日本 Ruby の会に寄せてもらえれば大丈夫」と教えていただきましたが、運営側は具体的に何をしたら良いでしょうか？
    - チケットを販売するサイトは固定で決まっていたりするのでしょうか？
        - 福岡 Rubyist会議 03 の時は PayPal ビジネスアカウントをお借りして connpass から販売しました（#454)
- インボイス制度の対応はどのようにしたら良いでしょうか？
    - こちらも RubyKaigi 2024 で高橋さんに相談させてもらい「日本 Ruby の会に寄せる」というお話になりましたが、運営側は何をしたら良いでしょうか？

これはまた別件かもしれませんが、懇親会参加用の参加フォーム（有料）も用意しようかと考えています。こちらもどのような形式でやると良いか相談させてもらいたいです。

- 福岡 Rubyist会議 04 のチケット販売経路と同じ経路で参加費を募る？
- 懇親会だけ PayPal ビジネスアカウントをお借りして connpass で参加を募る？
    - この場合、インボイス制度の対応は必要？

**Comment by takahashim** [comment]
「（会計を）全部日本 Ruby の会に寄せる」というのは、基本的に以下の2点になります:

- お金を払うときはRubyの会が払うことにする
    - そのため、領収書や請求書はRubyの会に対して発行してもらう
- お金をもらうときはRubyの会がもらうことにする
    - そのため、送金先はRubyの会の銀行口座か、PayPal or StripeのRubyの会のアカウントにしてもらう
    - 最後にお金が余ったときには余剰金を誰かに送金することも可能ですが、その場合は源泉徴収等が必要になるかもです

こうすると、全部Rubyの会の会計で処理することになって、誰か個人が負担したりインボイスで問題になったりはしないはずです。

### チケット販売サイトについて

そしてチケットの販売ですが、販売サイトはどこでもいいのですがお金のやりとり（「チケット売上代金-手数料」の送金先）として以下のどれかが使えるサイトがよいです:

* PayPalに対応（Rubyの会のPayPalアカウントを登録して使う）
* Stripeに対応（Rubyの会のStripeアカウントを登録して使う）
* あとでまとめて（？）銀行口座に振込（Rubyの会の銀行口座を登録して使う）

### インボイス制度の対応について

また、インボイス制度への対応については、大きく以下の2点について対応が必要かと思います:

- (Rubyの会がお金を払う場合について)請求書・領収書の宛名が「一般社団法人日本Rubyの会」にしてもらう
  - 消耗品等を買う場合も同様です
- (Rubyの会が参加者からお金をもらう場合について)販売サイトに領収書発行機能がある場合で、領収書の発行者が販売サイト事業者ではなくイベント主催側になる場合、領収書の発行者を「一般社団法人日本Rubyの会」に、適格請求書発行事業者登録番号としてRubyの会の登録番号を設定する
  - 実際connpassとかってどうなってましたっけ…？

なお懇親会についても同様ですが、サイトやチケットは本編と同じでも別々でも特に問題はないはずです。

ちなみに会場費以外で10万円以上の支払いが必要なものってありますか？　細かい出費は最後にまとめて精算でもよいかと思いますが、大きめのものがあれば事前に教えていただければ。

**Comment by jinroq** [comment]
@takahashim 

> * お金を払うときはRubyの会が払うことにする
>     * そのため、領収書や請求書はRubyの会に対して発行してもらう
> * お金をもらうときはRubyの会がもらうことにする
>     * そのため、送金先はRubyの会の銀行口座か、PayPal or StripeのRubyの会のアカウントにしてもらう
>     * 最後にお金が余ったときには余剰金を誰かに送金することも可能ですが、その場合は源泉徴収等が必要になるかもです

共有ありがとうございます。

> (Rubyの会が参加者からお金をもらう場合について)販売サイトに領収書発行機能がある場合で、領収書の発行者が販売サイト事業者ではなくイベント主催側になる場合、領収書の発行者を「一般社団法人日本Rubyの会」に、適格請求書発行事業者登録番号としてRubyの会の登録番号を設定する

前回のチケット販売は PayPal アカウントをお借りして connpass 上で販売しました。その際の請求書・領収書の宛名は弊社名としていました。
前回はインボイス制度導入前だったので適格請求書発行事業者登録番号は登録していません。現在どのようになっているか調べてみます。

> ちなみに会場費以外で10万円以上の支払いが必要なものってありますか？　細かい出費は最後にまとめて精算でもよいかと思いますが、大きめのものがあれば事前に教えていただければ。

今回は以下のものが 10 万円以上と見積もっています。

- ノベルティ（T シャツ）代： 10 万円前後
    - スピーカー
    - スタッフ
- 懇親会費用： 30〜40 万円

**Comment by jinroq** [comment]
## イベントの集金について

### connpass

https://help.connpass.com/organizers/paid-event-edit

* PayPal で前払い
    * 福岡 Rubyist会議 03 で使った実績あり
    * connpass への手数料なし
    * PayPal の手数料あり
* インボイス制度に対応している
* 払い戻し機能がない
    * 福岡 Rubyist会議 03 ではキャンセルしても払い戻しはしなかった

### Doorkeeper

https://support.doorkeeper.jp/article/95-stripe

* Stripe で前払い
    * 以前 RubyKaigi でも使っていた
    * 複数コミュニティでも使えそう
        * https://support.doorkeeper.jp/article/147-community-legal-page
    * Doorkeeper への手数料あり（3.60%）
    * Stripe の手数料あり
* インボイス制度に対応している
* 払い戻し機能あり
    * https://support.doorkeeper.jp/article/4-refund-payment
    * Doorkeeper の手数料は返金されるが、Stripe 手数料は返金されない

### で、結局どっちを使う？

可能であれば以下のようにしたい。

* カンファレンスは Doorkeeper を使いたい
    * キャンセルで返金できるようにしたい
    * 前日締め切りで当日キャンセルは無しとする
* 懇親会は connpass を使いたい
    * 飲み会キャンセルによる予算不足は困るので「connpass の仕様で払い戻しはできません」としたい
    * Doorkeeper で払い戻し不可にしてもいいかも

**Comment by snoozer05** [comment]
@jinroq こちら、もうcloseできる感じでしょうか？（何か未解決事項とかありますか？

**Comment by jinroq** [comment]
@snoozer05 クローズしました！ありがとうございます！
