### ISSUE TITLE
[Fukuoka04] Stripe アカウントの借用について

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#506]
別 Issue で[共有](https://github.com/ruby-no-kai/official/issues/505#issuecomment-2191726466)しました通り、Doorkeeper にて福岡 Rubyist会議 04 のチケット販売を考えています。
つきまして、Doorkeeper でチケット販売時に必要な Stripe アカウントをお借りしたいです。
別途メールにて連絡します。

**Comment by jinroq** [comment]
@takahashim 

![Screenshot from 2024-07-17 22-12-25](https://github.com/user-attachments/assets/80bc54d8-bd8d-487e-8396-2c5b0731d057)

Doorkeeper/Stripe と格闘したのですが既存の日本Rubyの会の Stripe アカウントと紐付けられず…（動線が新規 Stripe アカウント作成しか見つからない）。Stripe に問い合わせましたが返事がないので Doorkeeper でのイベント作成は断念し connpass で募集します。
よって、本チケットはクローズします。

**Comment by takahashim** [comment]
@jinroq  む、そうだったんですね…。おつかれさまです。
connpass+PayPalで行う場合でも、Rubyの会側のオペレーションでPayPal支払いの返金(refund)を行うこともできるかと思うので、キャンセル時の対応が必要な場合は相談していただければ。

**Comment by jinroq** [comment]
@takahashim 

> connpass+PayPalで行う場合でも、Rubyの会側のオペレーションでPayPal支払いの返金(refund)を行うこともできるかと思うので、キャンセル時の対応が必要な場合は相談していただければ。

承知しました、ありがとうございます。

**Comment by jinroq** [comment]
https://support.doorkeeper.jp/article/160-stripe-setting-multi-communities

非常に今さらですが Strip から回答があり、このヘルプページのリンクだけが貼られていました。できるのかどうかは未確認です（誰かやってください）。
