### ISSUE TITLE
[Fukuoka04] PayPal ビジネスアカウントの借用について

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#507]
@takahashim 

#506 で共有しました通り、Doorkeeper/Stripe の連携が上手くできず開催時期も近くなってきましたので、前回同様 connpass にてチケット販売をします。
必要な情報については別途メールにて連絡します。

**Comment by jinroq** [comment]
https://fukuokarb.connpass.com/event/325792/
カンファレンスのチケット販売は開始しました！

**Comment by snoozer05** [comment]
こちらは状況終了と思うので、閉じます
