### ISSUE TITLE
[Fukuoka04] 懇親会の予算についてのご相談

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#509]
@takahashim 

福岡 Rubyist会議 04 の懇親会についてご相談です。

## 相談したいこと

まだ金額が決まっていないが、先に概算見積の金額を振り込んでいただき残金を後日返金するという形でご支援いただくことは可能でしょうか？

### 相談内容詳細

[懇親会会場](https://hakata-manryobako.com/)を 60 名で予約していますが、9 月のコースメニューの内容が 9 月にならないと分からないため金額も現時点では確定できない状況です。
一方で店側から人数の確定を一週間前まで（08/31 まで）とされているため、早急に懇親会用募集ページをオープンにしたい状況です。

概算見積もり（最大金額）： 8,000 円 * 60 名 = 480,000 円
※参加費は 5,000 円で募集する予定です。

参考までに懇親会用募集ページは以下のような内容となります。

![Screenshot from 2024-08-17 13-40-33](https://github.com/user-attachments/assets/ed792bb9-af58-453e-87fd-1bfbaabd781e)

![Screenshot from 2024-08-17 13-41-01](https://github.com/user-attachments/assets/afb45404-e88b-48f3-a803-4bbe0c108c8d)

**Comment by takahashim** [comment]
@jinroq なるほどです、これっていったん8,000 円 * 60 名とかの請求書をRubyの会宛でお店に発行してもらえたりできるでしょうか。であれば何も問題ないです。
あるいは請求書じゃなくても何かしらの書面を出してもらえればそれで対応できるかと思います。

**Comment by jinroq** [comment]
@takahashim 
最終的に支払時に XXXX 円 * n 名の領収書を発行してもらうことになると思います。
なので 09/01 〜 09/05 までに Fukuoka.rb の口座に確定した金額をお振り込みいただければと考えています。
（8,000 円 * 60 名はあくまで考えられる最大の予算で 10 万円以上であることを共有する意図でした）

一応請求書が発行可能かも確認しておきます。

**Comment by takahashim** [comment]
@jinroq Fukuoka.rbの口座じゃなくてお店の口座に振り込めないでしょうか

**Comment by jinroq** [comment]
@takahashim 
> Fukuoka.rbの口座じゃなくてお店の口座に振り込めないでしょうか

承知しました。請求書の件と併せて確認します。

**Comment by jinroq** [comment]
@takahashim 
本日電話確認したところ担当者が変更になり、かつ、不在のためちゃんと確認できませんでした。
一旦確認できたことは以下のとおりです。

- 請求書払いは可能
    - ただし、請求先の名刺が必要（本当に必要かは担当者に確認させる）

日本 Ruby の会の名刺だけもらえたりしますか？（もしくは @kakutani が持ってたりしますか？）

**Comment by jinroq** [comment]
（懇親会場の人数確定締め切り（08/31）がせまっているので connpass のイベントページはオープンしてしまいたいお気持ち）

**Comment by takahashim** [comment]
@jinroq あんまり状態のよい名刺ではないですが、あるにはありました。
どこかに郵送するのがよいでしょうか？

それとconnpassは先にオープンしてもよいかと思いますが、何かブロッカーになりそうですか？

**Comment by jinroq** [comment]
@takahashim 
> どこかに郵送するのがよいでしょうか？

https://www.ruby-dev.jp/company/access
福岡オフィス（部屋番号は 501）の尾田宛までお願いいたします。

> それとconnpassは先にオープンしてもよいかと思いますが、何かブロッカーになりそうですか？

支払い方法が未確定のままオープンしてよいものかと思っていました。オープンします。

**Comment by pupupopo88** [comment]
@takahashim @jinroq 
もし当日でよければ自分が名刺持っていきますよ〜(どのみち持っていくので)
懇親会はわからないですけど、本編であれば @kakutani も @snoozer05 も @springaki も参加する…はずなので、誰かしらからは渡せるはず

**Comment by jinroq** [comment]
@takahashim @pupupopo88 
先ほど店側に連絡しまして「メールにて pdf 添付でも構わない」とのことでした。
teambbss2 at gmail dot com に「9月7日予約（尾田）」と記載していただき、メールを出していただければと思います。

店名： 萬漁箱
担当者名： タナカ様
予約日時： 9 月 7 日 19:00

**Comment by pupupopo88** [comment]
@jinroq @takahashim 
先ほど Cc: ruby-no-kai の info、(念のため)尾田さん個人メール Bcc で送りました ✉️

**Comment by jinroq** [comment]
@pupupopo88 
ありがとうございます！

**Comment by jinroq** [comment]
@pupupopo88 
参加予定人数： 52 名
一人予算： 8,000 円
別途店が用意する日本酒代： 50,000 円

計： 466,000 円

の予定です。

**Comment by pupupopo88** [comment]
@jinroq はい！ご連絡ありがとうございます。

**Comment by jinroq** [comment]
@pupupopo88 

https://x.com/jimlock/status/1830442127077367935

経緯はこちらですが、参加予定人数が 53 名に変更となりました。
よって合計 474,000 円の予定となります。

**Comment by jinroq** [comment]
@takahashim @pupupopo88 
請求書払いが完了しましたら本 Issue のクローズをお願いします。

**Comment by jinroq** [comment]
@takahashim
こちら支払いは済みましたでしょうか？

**Comment by pupupopo88** [comment]
@jinroq 先ほど自分宛に請求書がきていることを確認しました。これから手続きします、といったステータスです！ 🙏 
※ 当日伺っていた通り、追加1万円UPの 484,000 円 での請求でした！

> 請求書払いが完了しましたら本 Issue のクローズをお願いします。

かしこまりました！

**Comment by takahashim** [comment]
@jinroq @pupupopo88 こちらの484,000円ですが、今日付で振り込まれたようでしたのでこのissueも閉じておきます

**Comment by jinroq** [comment]
@takahashim ありがとうございます！
