### ISSUE TITLE
RubyWorld Conference 2012 のあとに温泉ミーティングをやる?

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#51]
RAとうまいこと分担できるといいな(人をあつめたりするのはruby-no-kai、かな)。

**Comment by mrkn** [comment]
これやるんですか？

**Comment by takahashim** [comment]
やる予定です！（松江市方面とはすでに話をしていますが、詳細未定）

**Comment by mrkn** [comment]
参加するには、何日まで滞在する必要がありそうですか？

**Comment by takahashim** [comment]
土曜日に昼は松江駅前、夜は松江市の温泉に泊まって、日曜に解散の予定です

**Comment by mrkn** [comment]
ありがとうございます！

**Comment by snoozer05** [comment]
告知がでたから終了ですかねぃ

**Comment by kakutani** [comment]
土曜日のオープンソースラボのハッカソンの告知まち。

**Comment by takahashim** [comment]
宿泊費の振り込みも終わりました

**Comment by mrkn** [comment]
楽しい企画をありがとうございました :star2: :star2: :star2:

**Comment by snoozer05** [comment]
これはあと何が終わったらcloseなんでしたっけ？

**Comment by takahashim** [comment]
参加者からの集金→完了、集金したお金の振り込み→未完、ですが、issueとしては閉じておきます！
