### ISSUE TITLE
[Fukuoka04] キーノートスピーカー旅費支払い代行

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#513]
@yui-knk の福岡 Rubyist会議 04 の交通費・宿泊費の振り込みをお願いしたいです。
振込先は別途メールにて共有させていただきます。

**Comment by jinroq** [comment]
@takahashim 
こちらメールを出しましたのでご確認ください。

**Comment by takahashim** [comment]
@jinroq メールが届いたので振り込んでおきました。

ところで宿泊費の方は紙の領収書が原本であれば紙を送ってほしいです！
* [領収書の送付方法](https://scrapbox.io/ruby-no-kai/%E9%A0%98%E5%8F%8E%E6%9B%B8%E3%81%AE%E9%80%81%E4%BB%98%E6%96%B9%E6%B3%95)

なお交通費（タクシー代）の方は領収書がなくてもいいのですが、差し支えなければ一緒に送っていただけた方がありがたいです。よろしくお願いします。

**Comment by yui-knk** [comment]
@takahashim
申請した金額が振り込まれていること確かに確認いたしました。素早い対応ありがとうございます。
宿泊費、交通費（タクシー代）ともに紙の領収書(画像でお送りしたもの)を送付可能です。簡易書留などではなくて、通常の封筒での送付で問題ないでしょうか?

**Comment by takahashim** [comment]
@yui-knk ありがとうございます、精算が不要であれば通常の封筒でも大丈夫です

**Comment by jinroq** [comment]
@takahashim 
原本が届きましたら本 Issue のクローズをお願いします。

**Comment by yui-knk** [comment]
本日の夕方に投函いたしました。

**Comment by takahashim** [comment]
@yui-knk 遅くなりましたが受領しました！　ありがとうございました
