### ISSUE TITLE
[Fukuoka04] 福岡 Rubyist会議 04 キャンセルの返金について

### ISSUE THREAD

**Issue by jinroq** [ruby-no-kai/official#515]
@takahashim 

福岡 Rubyist会議 04 をキャンセルされた方が 2 名います。この方たちに返金をしたいと考えています。
どのような方法が返金のベストエフォートでしょうか？

**Comment by takahashim** [comment]
@jinroq 決済に使ったメールアドレスを教えてもらうのが確実そうです！

**Comment by jinroq** [comment]
@takahashim 
connpass ではなく PayPal のメールアドレスですよね？

**Comment by takahashim** [comment]
@jinroq はい、PayPalのメールアドレスになります。これが普通にユーザーから見えるユーザーの識別子になります。

もうちょっと詳しく説明すると、決済単位の識別子もあるにはあるのですが、いろいろ種類がある上に販売者側からは使えない（？）識別子もあるようなので混乱しやすいのでした。そのため分かりやすく確実な情報としてメールアドレスで教えていただければ、というところです。

**Comment by jinroq** [comment]
@takahashim 
承知しました。メールを出しましたのでご確認ください。

**Comment by jinroq** [comment]
@takahashim 
対応ありがとうございます。両名から返金された旨の連絡がありましたので、本 Issue はクローズします。
