### ISSUE TITLE
RegionalRubyKaigiKaigiを単独開催するのはどうか

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#52]
- 10月後半ぐらいに、ちょっと今後の話を考えたりできるといいなあ。
- 交通費を補助できたりするといいかも
- 岡山、みなととか、新しい01が出てきたので、話ができるとなあ。

**Comment by kakutani** [comment]
RegionalのMLに投げた。 まず、 @eitoball から反応があった。

**Comment by kakutani** [comment]
他、いくつか反応をもらっている。参加したいと言っている人の地域と時期を調整して、KRPも会場候補として視野に入れる。そんなに人数いないから、東京でやるなら永和でよさそう……。

**Comment by kakutani** [comment]
(その後、進展しておりません。札幌が終わったあとかなあ)

**Comment by kakutani** [comment]
札幌がおわったけど……。RailsGirls Kyotoのついでにやるとか(京都で)。

**Comment by kakutani** [comment]
(特に進展ない)

**Comment by snoozer05** [comment]
やりたいなあ

**Comment by kakutani** [comment]
Rubyの20周年とかにみんなが来てくれるならいいえど、そこまでの引きはないかなあ…

**Comment by kakutani** [comment]
RubyKaigiでかな……

**Comment by snoozer05** [comment]
RubyKaigi 2013 でやれるといいな

**Comment by snoozer05** [comment]
RubyKaigi2013かRubyHirobaでやることにしましょう！ cc @kakutani

**Comment by shyouhei** [comment]
これやるん? そういえばですが。

**Comment by shyouhei** [comment]
むむむ、こぼれてしまった…

**Comment by kakutani** [comment]
だいぶ突発的にではありますが、github drinkupが終わったあとに名古屋と関西と横浜と福岡の人たちと2時間ぐらい立ち話をしました。RubyKaigiもrebootしちゃったし、一旦閉じてしまってよいと思います。
