### ISSUE TITLE
rubykaigi.info ドメインを日本Rubyの会で引き取ってもらえるといいな

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#54]
東京Ruby会議10の公式URL用というのと、今後もエイリアス用に使えるかなーと思い、kakutaniが取るだけ取った。

**Comment by takahashim** [comment]
具体的には何をすればいいんでしたっけ？

**Comment by kakutani** [comment]
ruby-no-kai.org と同じ管理にして、費用を会のほうで負担してもらえればいいかなあ、と。~1,000JPY/yr です。
初年度は value-domainのセールで買ったので 280JPY/yr. なのでこれは別にいいです、というのと、
処理するのも来年でいいかなあ、と。

**Comment by kakutani** [comment]
日本Rubyの会アカウントへドメインを移しました。
