### ISSUE TITLE
地域Ruby会議への支援のかたち

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#55]
メモ:
- 会場代(多くの場合は前払い)の資金が個人の立て替えになるのが怖いなー、という話に対して支援できるのか。
- するとしたら、どういうかたちでやればいいのか(形式とか手続きがヘビーになるとお互いしんどいしなー)

**Comment by takahashim** [comment]
これって問題は、まとまった金額を立て替えるのが個人にとってしんどい、という話ですよね？

これに関してはあんまり形式的な手続きを決めたくないところですね…。基本的にRubyの会が支援する活動については、立替えられるようにできた方がいいと思います。
それでもルールくらいはあった方がいいんですかね？　たとえば、１万円以上の支出についてはメール等で事前に共有、とか？

**Comment by kakutani** [comment]
新しいガイドラインとして、
- 10万円程度 または
- 予算の10%程度
  というのを支援枠としてはどうか、という話が @takahashim から出た。賛成。

**Comment by kakutani** [comment]
よし、これでいこう。
