### ISSUE TITLE
登記の登録住所の変更をする

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#60]
高橋さんとあづみさんが引っ越すので、実印スタンプラリーが必要。

2012年9月というか札幌Ruby会議2012に合わせてスケジューリングする感じ。
あづみさんのぶんのハンコは、平日夜にもらいにいけばよさそう。

**Comment by snoozer05** [comment]
これってもう終わりでしょうか。

**Comment by takahashim** [comment]
こちらは火曜日づけで事務所住所は変更になったはずですが、税務署への提出と理事の住所変更が残ってます…

**Comment by snoozer05** [comment]
こちらは道のりは遠い感じでしょうか... ><

**Comment by takahashim** [comment]
ちょっと税務署が物理的に遠い…orz
あと、あづみさんの住所変更はそれはそれで進める変更があります

**Comment by snoozer05** [comment]
やっと進められそう

**Comment by kakutani** [comment]
@takahashim がまだ税務署にいってない

**Comment by snoozer05** [comment]
これはまだ税務署に行っていない感じでしょうか？

**Comment by takahashim** [comment]
税務署行って紙をもらってきたところで止まっております…orz
（そして昨日大江戸03から帰ってきたら申告書が投函されていたというorz）

**Comment by shyouhei** [comment]
このチケットの現状がしりたいです…

**Comment by takahashim** [comment]
書面を提出して、問題がなければそのまま（特に連絡もなく）終了になる予定です

**Comment by kakutani** [comment]
何かあればreopenするということで
