### ISSUE TITLE
misocaに印影画像を登録する

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#62]
おためし。

**Comment by kakutani** [comment]
「80 x 80pxのpng jpeg gifに対応」だそうです。

misocaのアカウント情報はメールしてあるので、よろしくお願いします。

**Comment by kakutani** [comment]
印影を @snoozer05 にスキャンしてもらったら、@kakutani が作業する(ので、しまださんにアサイン)

**Comment by snoozer05** [comment]
やりました

**Comment by kakutani** [comment]
@snoozer05 なんかうまく出なかったので、画像ファイルそのものを送ってもらえますか?!

![](https://img.skitch.com/20120919-f24tc938496gjfhrwfd32fx2cw.png)

**Comment by kakutani** [comment]
できt!!1
