### ISSUE TITLE
Rails Girlsの原田さん立替ぶんを精算する

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#65]
よろしくお願いします。

**Comment by takahashim** [comment]
振り込みました！

**Comment by kakutani** [comment]
@yokolet に確認してもらうように伝えました。ackが来たら閉じます。

**Comment by kakutani** [comment]
https://github.com/railsgirls-jp/tokyo-management/issues/10#issuecomment-8446894 きた。
(@railsgirls-jp/tokyo-management#10 とか書けるのかな)
