### ISSUE TITLE
セールスフォース・ドットコム様の新規サプライヤー・支払先登録申請書の処理

### ISSUE THREAD

**Issue by snoozer05** [ruby-no-kai/official#67]
おねがいできますでしょうか...

**Comment by takahashim** [comment]
とりあえず履歴事項全部証明書は入手しました

**Comment by snoozer05** [comment]
ありがとうございます！支払先登録申請書の作成はどのようにすすめましょうか...

**Comment by takahashim** [comment]
MacのLibreOfficeではまともに編集できなさそうなので、あとでWindowsマシンを引っ張りだしておきます…

**Comment by snoozer05** [comment]
宜しくお願いします...!!

**Comment by snoozer05** [comment]
こちら状況どんな感じでしょうか

**Comment by takahashim** [comment]
LibreOfficeでは開けなさそうです＞＜
とりあえず項目だけは用意しておいて、島田さんかだれかでWord持ってる人に編集してもらった方がいいでしょうか？

**Comment by snoozer05** [comment]
oo... 了解しました。
とりあえず、その作戦でお願いします(ぼくの方でいただいた内容をもとに入力を試みてみます)。

**Comment by takahashim** [comment]
送りました！！

**Comment by snoozer05** [comment]
いただいた内容をもとに申請書を作成し、ひとまずメールにてセールスフォース様にお送りしました。

先方で内容の確認がとれましたら、登記簿謄本のコピーと申請書に押印いただいたものをセールスフォース様に郵送にてお送りいただけますでしょうか(送付先は現在確認中)。

**Comment by snoozer05** [comment]
送付先の連絡がきたので、郵送をおねがいできますでしょうか。
(送付先は先ほどメールしました)

**Comment by takahashim** [comment]
郵送しました！

**Comment by snoozer05** [comment]
ありがとうございます！
