### ISSUE TITLE
sprk2012 のスポンサー代の入金を確認する

### ISSUE THREAD

**Issue by snoozer05** [ruby-no-kai/official#68]
Rubyの会の口座に入金予定となっている分について確認をお願いします

**Comment by takahashim** [comment]
確認しました！　これってどこで管理してますか？
ちなみに9月は2社のみでした。

**Comment by snoozer05** [comment]
sprk2012の Pivotal Tracker のカレントでaccept待ちになっているもののうち、「Rubyの会に入金のあるもの」となっているものがそれにあたります。入金のあった2社についてはacceptを押していただけますでしょうか！

**Comment by takahashim** [comment]
acceptしておきましたー

**Comment by snoozer05** [comment]
ありがとうございます！

**Comment by kakutani** [comment]
支払期日は11末になっているらしい。

**Comment by snoozer05** [comment]
@takahashim  12月になったので、いまいちど入金確認をおねがいできますでしょうか！

**Comment by takahashim** [comment]
入金確認しました！

**Comment by takahashim** [comment]
E和さんの10月の入金ってひょっとして何かと抱き合わせ金額なのかしら…？（SPRK2012の金額とは違う額になってる）

**Comment by kakutani** [comment]
5まん多いならrailsgirlsとまとめて？

**Comment by takahashim** [comment]
そんな気がしてきました！

**Comment by kakutani** [comment]
じゃあ、そういうことだと思います!

**Comment by takahashim** [comment]
ではそういうことで！　問題なければこちらも閉じておいて下さい＞しまださん

**Comment by snoozer05** [comment]
はい！確認ありがとうございました！
