### ISSUE TITLE
githubのorganizationアカウントにruby-no-kaiのロゴを設定してほしい

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#7]
しまださんにお願いすればいいですか?

**Comment by snoozer05** [comment]
今、ruby-no-kai のメールアドレスが info@rubykaigi.org で設定されているので、これは info@ruby-no-kai.org とかにすべきかなと思います。
info@ruby-no-kai.org にする場合はメールアドレス(グループですかねぃ）を作成願います > 角谷さん
メールアドレスが決定、準備ができたら gravatar に設定するようにします。

**Comment by kakutani** [comment]
あ、そっか。すんません……あとでやっときます。

2011/9/6 snoozer05
reply@reply.github.com:

> 今、ruby-no-kai のメールアドレスが info@rubykaigi.org で設定されているので、これは info@ruby-no-kai.org とかにすべきかなと思います。
> info@ruby-no-kai.org にする場合はメールアドレス(グループですかねぃ）を作成願います > 角谷さん
> メールアドレスが決定、準備ができたら gravatar に設定するようにします。

## 

Kakutani Shintaro

**Comment by snoozer05** [comment]
設定ありがとうございます！このissueはcloseして大丈夫でしょうか！
