### ISSUE TITLE
Ruby Kaja のTシャツ発送費用の支援

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#70]
誰が立て替えてるんだろ。@tyabe ?

**Comment by snoozer05** [comment]
これはどういう状態なんでしたっけ

**Comment by kakutani** [comment]
@tyabe 側で領収証をもっていることを把握しました。向こうも認識はしているので、いつか・どこかでランデブーできたら精算できそうです。

**Comment by kakutani** [comment]
東京Ruby会議10 で @tyabe から受けとる――予定。

**Comment by kakutani** [comment]
@tyabe の振込先をおしえてもらう。

**Comment by tyabe** [comment]
@kakutani 振込先、メールで送りましたー

**Comment by kakutani** [comment]
いただきました! ちょっと整理して(ごめんなさい、時間をください……)、入金処理を進めます。

**Comment by kakutani** [comment]
@takahashim が振り込んだと言っているので、@tyabe からACKが返ってきたらclose.

**Comment by tyabe** [comment]
@kakutani 確認しましたー。ありがとうございました:sushi:

**Comment by kakutani** [comment]
:money_with_wings:
