### ISSUE TITLE
paypalアカウントに理事もアクセスしたい

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#74]
#44 の続き。複数アカウントからのアクセスの設定をすれば、アクセスできるようになるはず。ぼちぼち進めていきたい。

https://www.paypal.com/jp/cgi-bin/webscr?cmd=p/mer/logins-outside

**Comment by kakutani** [comment]
@kakutaniは終わったので、次は @snoozer05 のやつ。

**Comment by kakutani** [comment]
挑戦しようとして、ぼくの権限だと無理だったので、 @takahashim おねがいします!

**Comment by shyouhei** [comment]
RubyKaigiのときに！

**Comment by snoozer05** [comment]
おわりました！ありがとうございました！
