### ISSUE TITLE
paypalアカウントの送金制限を解除したい

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#75]
100K JPYの送金制限を解除したほうが海外の人とのやりとりがスムーズにいくはず。
RubyKaigiの前には、送金を解除しておきたい。
(法人としての「本人確認」を済ませればいいのかな?)

**Comment by takahashim** [comment]
paypalアカウントが「ステータス：認証済み」になりました！！
で、これでいいんでしたっけ？

**Comment by kakutani** [comment]
「支払/引出限度額: 限度額を表示」の先の、

> 支払い
> お客さまのアカウントには、累積支払限度額¥100,000 JPYが設定されています。現時点で支払いが可能な金額は
> ¥100,000 JPY支払限度額¥0 JPY¥100,000 JPY適用法令にしたがい、PayPalは日本のすべてのPayPalアカウントに
> 対して累積支払限度額¥100,000 JPYを設定しています。本人確認は、なりすまし、マネーロンダリング、テロへの
> 資金供与を防止するために行います。この限度額を解除するには、法人としての本人確認に必要な書類を提出して、
> 法人としての本人確認手続きを完了する必要があります。
> 
> 支払限度額を解除するには、本人確認書類を提出して、法人としての本人確認手続きを行ってください。
> [本人確認]をクリックすると、お手続きを開始できます。

からの「本人確認」のお手続きをおこなって、支払限度額を解除したいです!!!
(本人確認ってアカウントをつくるときに済ませたんじゃねーの、と思うのですが……)

**Comment by takahashim** [comment]
![ 2013-01-23 21 07 26](https://f.cloud.github.com/assets/10401/89830/f82c1112-6555-11e2-84e1-d817bebb657c.png)
…ック、ここから「以下のステップ」に従うにはどうすれば…

**Comment by kakutani** [comment]
これは、アカウント責任者がサポートから「本人確認」から

> 「法人・その他組織の本人確認手続きページ」から、「以下のステップにしたがう」にも
> 何もボタンが表示されていないのでアクションの取りようがない

という旨の問い合せをおこなうと、謎の運用対応によって、しばらくたつと「ボタンつけました」という連絡がきます。

数営業日のうちにサポートから返信がこない場合は、同じ内容を何度も何度も問い合わせます。
近頃は一度問い合わせるだけでボタンがつくようになりました!!

**Comment by takahashim** [comment]
電話したら10分でボタンつきました！！１

**Comment by kakutani** [comment]
:+1:

**Comment by takahashim** [comment]
手元にあった履歴事項全部証明書がちょっと古かった…というわけで続きは来週の予定です

**Comment by takahashim** [comment]
履歴事項全部証明書のスキャンをアップしてもエラーになった問題は、ファイル名の日本語が原因だったようなので修正して返事待ちです…

**Comment by takahashim** [comment]
本人確認完了しました！！（たぶん

**Comment by kakutani** [comment]
うおー、おつかれさまです！

**Comment by snoozer05** [comment]
done?

**Comment by takahashim** [comment]
支払/引出限度額のページで支払い・引き出し両方とも「お客さまの限度額は解除されました」と表示されております。
これでいいんでしょうか？

**Comment by kakutani** [comment]
オワタ!!
