### ISSUE TITLE
ネットバンクの口座を作る

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#76]
ネットバンクの口座だと、入金があるとメールが飛ぶので便利かなあ、と思いました。あと複数人での確認もいちおうはできるぽいです（振り込みするにはジャパンネット銀行の場合、USBトークンが必要）

具体的な使い方はあまり考えてないのですが、とりいそぎチケット切っておきます。

**Comment by kakutani** [comment]
おー。入金通知メールべんりそう!

**Comment by snoozer05** [comment]
どこか決めましょう！

**Comment by takahashim** [comment]
ジャパンネット銀行にしようかと思っているのですが、USBトークンについて確認する（自分用メモ）

**Comment by kakutani** [comment]
お金を払えばドングルは増やせるらしい。

**Comment by xibbar** [comment]
今ってUSBトークンなんですか。口座を持って10年以上経つのですが、
私のトークンはUSBじゃないなぁ。

**Comment by xibbar** [comment]
やっぱりUSBじゃないですよね。
https://www.japannetbank.co.jp/card/index.html
些細なことでしたが。

**Comment by xibbar** [comment]
http://www.japannetbank.co.jp/token/tokens/
を見ると1050円で追加できますね。

だいたいネット銀行で法人口座といったら
ジャパンネット銀行か楽天銀行になりますね。

**Comment by shyouhei** [comment]
継続して作成

**Comment by shyouhei** [comment]
進行中とのこと。

**Comment by takahashim** [comment]
ようやく書類（履歴事項全部証明書）を入手したので作業します…

**Comment by shyouhei** [comment]
実績
- 申し込んだけどvalidation error

next action
- 代表理事の住所変更(定款の変更)が必要

**Comment by shyouhei** [comment]
定款の変更手続きは申請済み。承認待ち。

**Comment by shyouhei** [comment]
謄本は取れた。next action: 印鑑証明を取りに行く必要がある。

**Comment by shyouhei** [comment]
印鑑証明が入手できた
next action: 書類送付

**Comment by shyouhei** [comment]
書類は送付された

next action: 結果待ち

**Comment by takahashim** [comment]
前回提出した書類には不備があり、再提出を求められたので再度送って結果待ちです…

**Comment by takahashim** [comment]
とか言っていたら開設されたらしいです。

> シャ）ニホンルビーノカイ 様
> 普通預金の口座開設をお申し込みいただき、ありがとうございました。
> 口座開設の手続きが完了しましたのでお知らせいたします。
> 
> 口座開設日: 2015年12月03日

**Comment by kakutani** [comment]
:tada: :dollar:

**Comment by takahashim** [comment]
口座できました。書類受領しました。
使い分けは考えないと、というところです。

**Comment by shyouhei** [comment]
とりあえずこのチケットは終了。使い方を考えるのは別チケットで
