### ISSUE TITLE
Rails Girls(RG) Kyotoの立替金の精算をする

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#78]
RG Kyotoのオーガナイザーの @chnstz と相談して、会期中のお金周りは日本Rubyの会が面倒をみることにしました。具体的には、私が小口現金とか準備で買った消耗品とかの精算を現地で立て替えてしまおうと思います。

領収証を集めて整理するので、あとで私の口座に入金いただくかたちでこの立替金を精算してもらいたいたいです > @takahashim

**Comment by takahashim** [comment]
了解です！

**Comment by snoozer05** [comment]
明細がきていたので、@takahasim さんの精算待ち状態

**Comment by kakutani** [comment]
かくたにの精算してもらいたいぶんは、129,689 JPY でした! よろしくお願いします。

**Comment by kakutani** [comment]
金額のupdate: 134,489

see #81

**Comment by kakutani** [comment]
私が金額を間違えて伝えちゃったけど、これ自体はおわり。続きは #89 で。
