### ISSUE TITLE
githubのruby-no-kai organizationにprivate repoがほしい

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#85]
るびまの進行をgithubでやろうかという話が出ていて、現状はfreeのrubima orgアカウントができています。

るびまの記事執筆にあたっては、特にインタビュー原稿の起こしと編集については、
履歴も含めて公開したくない、というニーズがあります(言っちゃいけない話とかもあるので)。

なので、記事によってはprivate repoが欲しくなることもあるだろうから、
そのための退避先として、ruby-no-kai orgのprivate repoがあるといいな、と思うにいたりました。

また、RubyKaigiの進行もやれるといいかな、と思っているのですが、タスク管理としてはオープンに書きづらいこともあったり、rubykaigiの準備のことでorganizersのpublic activityが活発になりすぎるのもいかがなものかと思ってます。

ruby-no-kai/official やrailsgirls-jpでgh issuesをタスク管理として使うことには
だいぶ慣れてきたので、使わせてほしい!!! と提案します。

よろしくお願いいたします。
(@takahashim がOK/NGの判断をしてくれたらclose)

**Comment by takahashim** [comment]
- るびまの進行はpublicでいいような？
- るびまの執筆はもうちょっと議論の様子見な気がしますね……るびま編集部としての判断が必要だと思うので、その結論を待ってからでいいと思います（必要に応じてRubyの会でリソースを用意する、というのは議論の前提にしてもらって大丈夫ではあります）。
- RubyKaigiの進行はprivate reposを作っていいと思いました！　（pivotalとの使い分けが気になりますが、そこはこれから運用しながら決めていけばいいかと）

一点確認ですが、終わった後で１〜２年後に溜まったissuesごとレポジトリを破棄しても大丈夫だと思います？（レポジトリの使い回しはちょっと微妙かなあ＆定額出費が単調増加必須な仕組みを導入するのは慎重になりたい）

**Comment by kakutani** [comment]
- るびまについて、進行そのものはpublicでよいです。
- 執筆についても「様子見」でよいと思います。
- RubyKaigiの進行には使いたい!!!

private repoのライフサイクルですが、プロジェクトの性格にもよるとは思いますけれども、
リソースとして提供するときに「プロジェクトが終わったら消すぞ!!」という前提で提供するのはいかがでしょうか。

プロジェクトが「終わった」あとにも引き取りたい人がいれば、
その人のアカウントにownershipを転送することは可能です(ちょう簡単)。
そうすれば、すくなくともruby-no-kaiのorgからは追い出すことができます)。

ちなみにRubyKaigiの運営については、2013年以降もリポジトリは1つで良いです。
「年」をマイルストーンとして運用しようと思ってます。

**Comment by takahashim** [comment]
あ、いや、RubyKaigiの話で、
- 「年」できれいにタスクが終わらない
- reposを分けないとメンバーの入れ替えができない

ので、そこは分けれないといまいち幸せになれなささそうかと思うんですが、どうなんでしょう？

**Comment by takahashim** [comment]
まあ、そこは先送りしてとりあえず導入しちゃってもいいかと思いました！

**Comment by kakutani** [comment]
ありがとうございます!! ではまずは、@kakutani のカードで立て替えちゃいますねッ。
RubyKaigiの進行の運用については、また別途お話させてください!!
