### ISSUE TITLE
rubykaigi.bizを日本Rubyの会の持ち物へと移す

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#87]

**Comment by shyouhei** [comment]
かくたにさんが持っている。
rubykaigi.info はいかん済み。これはまだ。

**Comment by shyouhei** [comment]
- rubykaigi.info は使われている。ただのスクワッティングではない
- bizはスクワッティングだけだし今となってはべつにいっかなーという気がしている @kakutani さん

**Comment by shyouhei** [comment]
まあ放置?
