### ISSUE TITLE
RG Kyotoの入金確認(入金期日:1/31ぶん)

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#93]
misocaのほうの入金ステータスを変更していただけると助かります(金額もあちらに書いてありますゆえ)。
- [x] paperboy&co. 様
- [x] クランディム 様
- [x] Happy Elements 様

**Comment by kakutani** [comment]
@takahashim お手すきのときに確認をお願いします!

**Comment by takahashim** [comment]
31日に入金がありました！

**Comment by kakutani** [comment]
お。すべてですか?

**Comment by takahashim** [comment]
3件並んでました！　misoca更新済みです
