### ISSUE TITLE
開発者会議の交通費のガイドラインを用意する

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#97]
- 開発者会議には開発者を呼びたいけど遠い人は交通費が辛い
- とはいえ結構各地に散らばっているので全員分持つことになると大変そう
- なので加減を考える
  - 1万円以上で希望者のみ、とか

**Comment by kakutani** [comment]
さしあたってはこれで良さそう。

**Comment by kakutani** [comment]
wikiのどっかに転記したらcloseとする。

**Comment by shyouhei** [comment]
まだない

**Comment by takahashim** [comment]
Wikiにはこの内容＋茶菓子代（これは全額、1万円以内）を載せることにしましょう

**Comment by ko1** [comment]
どっかに載ってる？

**Comment by snoozer05** [comment]
作ってみました https://github.com/ruby-no-kai/official/wiki/RubyDevelopersMeetingSupportGuideline

@takahashim 足りないところ、おかしなところがあれば手を入れていただけますでしょうか..??

**Comment by takahashim** [comment]
@snoozer05 こちらで問題ないと思います！

**Comment by snoozer05** [comment]
確認ありがとうございます！それではこれは閉じてしまいます！
