### ISSUE TITLE
申告の発注を検討

### ISSUE THREAD

**Issue by takahashim** [ruby-no-kai/official#98]
今年はプロに頼むかもなので、まずは検討する

**Comment by shyouhei** [comment]
これの検討を始めたいです！

**Comment by shyouhei** [comment]
検討を開始している。

**Comment by takahashim** [comment]
税理士紹介サービスみたいなところに申し込み→電話かかってくる→メールでクレと返事→メール待ち、という状態です

**Comment by takahashim** [comment]
こちらですが、もろもろ事情を伝えて、予算として10万円くらいとお伝えしたところ、「20万円くらいになりそう」と言われたので、別のところをあたっております…

**Comment by takahashim** [comment]
いずみ会計事務所の人と打ち合わせてきました。こちらでは記帳済みであれば決算書作成は10万円内でやってもらえそう、とのことです。
あと、カンファレンスやセミナーとかなら営利事業にはならない（法人税の対象にはならない）けど、カンファレンスの入場料収入やスポンサーからの協賛金の合計が1000万円超えると翌々年度から消費税の納税義務が発生する（！）、とのことでした。ううむ。

**Comment by kakutani** [comment]
うおおこれは海外の人からは消費税を取らない対応とかそーゆうにが必要になったりするのでしょうか……。

**Comment by takahashim** [comment]
そんな感じですかね…

**Comment by xibbar** [comment]
受け取った消費税から払った分の消費税を除外して支払うので、
利益がいっぱい出てたり、人件費をどっさり払っていたりしない限りは
本則課税で申告してもそんなに大きな金額にならないと思いますよ。

海外の人から消費税を取らない対応って出来るんですか？
ただの値引きと指摘されて、残りに課税されてオシマイな気がする。

**Comment by takahashim** [comment]
あーでも国際取引ではなく、国内でのカンファレンス等の開催＝国内での役務の提供と考えるとふつうに消費税が課税される取引になりそうです。

**Comment by takahashim** [comment]
こちらお願いしました！
