### ISSUE TITLE
日本Rubyの会MLの位置づけについて訊かれた

### ISSUE THREAD

**Issue by kakutani** [ruby-no-kai/official#99]
定款的にクリアしたのはいいんだけど、実運用としてどうなってるんでしたっけ、ということを「日本Rubyのチュートリアル」のアナウンスにあわせて聞かれたので、認識をあわせておきたいなあ、とdump。

**Comment by takahashim** [comment]
いわゆる賛助会員的なもの、という説明がいいのかなあ。会費はなくて情報取得のみ。

**Comment by kakutani** [comment]
もうちょっと活用したほうがいいな、と思います(なんか他人事っぽいけど……)。

**Comment by shyouhei** [comment]
今まで通りのゆるい運用でいいのかなあ。

運用はよさそうだが位置づけ…？

**Comment by shyouhei** [comment]
位置づけはさておき運用はこれまでどおりということでこのチケットはおわり。
